### ISSUE TITLE
Python-docx: Structure problem. One Paragraph contains two objects.

### ISSUE THREAD

**Issue by Huiicat** [python-openxml/python-docx#1003]
Hi, the situation is I want to print the text from the paragraph.
When I code
`doc.paragraphs[i].text`
It comes two lines. Like:
`ABC`
`DEFG`

Than I think it contains two lists, So code as blow to get the first list only:
`doc.paragraphs[i].text[0]`
 However, the result is not like what I think, it becomes:
`A`
`D`

I have no idea why it could be that?
How can I do to get the first list "ABC" ??

btw. [i] is one of paragraphs from document

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag.

**Comment by Huiicat** [comment]
@scanny hello, I have already posted my questions on StackOverflow.
But still no one know how to do.
The link is: https://stackoverflow.com/q/69039644/10870868

**Comment by scanny** [comment]
@Huiicat you're not providing the minimal reproducible code example and so you're not giving us enough to go on to help you. What we need is something like this:

```python
>>> doc = Document("my-doc.docx")
>>> paragraph = doc.paragraphs[17]  # --- the problematic one ---
>>> paragraph.text
'ABC
DEFG'
... etc.
```
