### ISSUE TITLE
Can't get row.cells from table object

### ISSUE THREAD

**Issue by u84six** [python-openxml/python-docx#1005]
I'm trying to iterate over tables to get the text from each of the cells, but after getting the rows of the table and iterating over each row, row.cells is throwing an exception:

docx.oxml.exceptions.InvalidXmlError: required ``<w:tblGrid>`` child element not present

I've looked in document.xml file and noticed that it doesn't have w:tblGrid. Is this incompatible? Or is there another way I can get to the values of each cell? The hierarchy is: w:tbl -> w:tr -> w:tc -> w:p -> w:r -> w:t <- this is where the value is in the first cell of the first row

I'm just trying to figure out if this file I'm parsing is compatible or not.

**Comment by scanny** [comment]
Well, according to the ISO 29500 spec/schema the `w:tblGrid` element must appear exactly once under the `w:tbl` element of each table. So your XML appears to be invalid according to the schema. Whether or not Word will load it or not is another question. But `python-docx` depends on that element for reading the column-width, so that exception isn't going away.

Where did the `.docx` document come from? Was it produced by Word or something else?

**Comment by u84six** [comment]
> Well, according to the ISO 29500 spec/schema the `w:tblGrid` element must appear exactly once under the `w:tbl` element of each table. So your XML appears to be invalid according to the schema. Whether or not Word will load it or not is another question. But `python-docx` depends on that element for reading the column-width, so that exception isn't going away.
> 
> Where did the `.docx` document come from? Was it produced by Word or something else?

I think the docx file is generated by code. But surprisingly, it opens fine in the latest version of Word, so that's why I was confused.

**Comment by u84six** [comment]
The sad thing is now I'll have to learn Powershell scripting to do what I want, versus Python, a language I actually know. Ugh

**Comment by u84six** [comment]
What I did was open with Word and select "Open and Repair". Then saved as new file and fix the issues. Thanks for the tip. I diffed the original file and new file (document.xml) and there are tons of differences. So I'll have to take a look at the doc gen code we use and see how to apply the latest schema. Thanks for the help

**Comment by scanny** [comment]
Glad you got it working :)

**Comment by nadermx** [comment]
I feel this might be helpful, as I think its a duplicate, https://github.com/python-openxml/python-docx/issues/548#issuecomment-1447553270

**Comment by dijkstra-mose** [comment]
Since you know the cause of the problem, why do not solve it? There are so many in-valid documents in reality. If python-docx is not robust enough,  it's basically useless in practice.
