### ISSUE TITLE
How i can get figure text

### ISSUE THREAD

**Issue by artemasd** [python-openxml/python-docx#1008]
I need to get the text of a shape in a document and then change it.

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag.

**Comment by artemasd** [comment]
StackOverflow write - "python-docx does not support the arbitrary drawing at this moment."

**Comment by scanny** [comment]
Oh, right, I see. That's correct. There is no current support for floating shapes.

**Comment by artemasd** [comment]
@scanny I do it ♥ (without your packet)
`def docx_replace_shape(old_file, new_file, replace, replaced):
    zin = zipfile.ZipFile(old_file, 'r')
    zout = zipfile.ZipFile(new_file, 'w')
    for item in zin.infolist():
        buffer = zin.read(item.filename)
        if item.filename == 'word/document.xml':
            res = buffer.decode("utf-8")
            for it in range(len(replace)):
                res = str(res).replace(replace[it], replaced[it])
            buffer = res.encode("utf-8")
        zout.writestr(item, buffer)
    zout.close()
    zin.close()`

**Comment by scanny** [comment]
Glad you got it working :)
