### ISSUE TITLE
Multiple Table in same Row

### ISSUE THREAD

**Issue by israrhussainrao** [python-openxml/python-docx#1026]
There is no support for adding two table in same row. Direction and alignment works only for different row. 
i am unable to align two table in one row by left and right direction

**Comment by scanny** [comment]
A table is a block-level item, like a paragraph, and so cannot directly appear side-by-side with another table or paragraph.

However, a table can appear _inside a cell_ of another table. So you can create a one-row, two-column table and place a table in each of its two cells. This would result in them appearing to be "on the same line".

**Comment by israrhussainrao** [comment]
Thank you very much, Steve, I solved the issue, I was trying the same logic but was doing the mistake, but it worked in the end.
I am sharing the code for others may it help.

`
table  = document.add_table(rows=1, cols=2)
table.allow_autofit = False
table._cells[0].width = Inches(4.0)
table._cells[1].width = Inches(4.0) 
column_first = table._cells[0].add_table(rows=2, cols=2)
column_second = table._cells[1].add_table(rows=2, cols=2)
column_first.style = 'TableGrid'
column_second.style = 'TableGrid'
`
