### ISSUE TITLE
Question regarding how python-docx works under the hood.

### ISSUE THREAD

**Issue by awa5114** [python-openxml/python-docx#1028]
This is more of a question than an issue, but I would like to ask whether `python-docx` uses `pywin32` to interact with Microsoft Word COM objects under the hood. If not, how does it interact with Microsoft Word through python?

**Comment by scanny** [comment]
`python-docx` doesn't interact with Microsoft Word. `python-docx` is essentially a friendly and knowledgeable XML editor. Friendly means you can tell it what you want to do in user-space terms, like "add paragraph", and knowledgeable meaning it knows all the details about how to modify the XML of the .docx file to accomplish that.

Among other benefits, this lets you generate Word documents on a Linux server without Microsoft Word anywhere in sight. It also generally performs substantially better than the "remote-control" approach used by COM32 types of interfaces.

**Comment by awa5114** [comment]
@scanny that's awesome. I had no idea Office apps used an XML standard under the hood. I can definitely see how that allows for better performance than a COM-based API like `pywin32`. Mind blown.

**Comment by fleek** [comment]
> @scanny that's awesome. I had no idea Office apps used an XML standard under the hood. I can definitely see how that allows for better performance than a COM-based API like `pywin32`. Mind blown.

Rename the docx file to zip and you can extract all the xml files contained inside.

**Comment by qwertynik** [comment]
Yes, directly unzipping also works 🌟
