### ISSUE TITLE
Finding the location of paragraphs and other elements

### ISSUE THREAD

**Issue by qwertynik** [python-openxml/python-docx#1032]
Hello,

Thanks for building this library, makes programmatic access of MS documents much easier.

Wanted to understand how can the following details be extracted from Word documents.

- Finding the dimensions (width and height) of the document in pixels
- Identifying the location of paragraph elements (top and left) in pixels

The use-case is to generate HTML from Word documents containing only specific elements.

Looking forward to your responses.

Thanks!

**Comment by scanny** [comment]
What do you mean by document dimensions? The entire document or just each individual page (like paper-size setting is A4 or letter)? The former (in particular the overall document length or "height") is not available without rendering the document. The latter is determined separately by each section on its `.page_height` and `.page_width` properties.  
https://python-docx.readthedocs.io/en/latest/api/section.html

Margins are also defined in the section (and so can vary from section to section). This will determine the text extents of each page. If you're looking for the actual position of each paragraph, that cannot be determined without rendering the text of the document and may vary noticeably between renderers. In any case, `python-docx` is not a renderer so can't help you with that. A renderer like Microsoft Word or LibreOffice could theoretically and _may_ in fact provide access to position of a specific paragraph but I don't know about those details.

**Comment by qwertynik** [comment]
> The latter is determined separately by each section on its `.page_height` and `.page_width` properties.
> https://python-docx.readthedocs.io/en/latest/api/section.html

Yes, I meant the latter. Thanks for answering @scanny. In one of the documents of dimension 7.81 x 20.66 (height), the value returned for one of the sections is 7143750 x 18891250 (height). Wondering which coordinates are being used.

Is there a way using which the position can be computed for paragraphs? At least approximate. One way could to be assess the height of all elements that are added before by paragraph - using the font size, line-height, white-space, etc.

Looking forward to your response.

Thanks!

**Comment by scanny** [comment]
I believe the return type is `docx.share.Twips` ("twentieth of a point") 1/1440 inch. You can use the convenience converters on any of the `Length` subtypes to get that in whatever units you need, so for example `page_height_in_mm = section.page_height.mm`.  
https://python-docx.readthedocs.io/en/latest/api/shared.html

**Comment by scanny** [comment]
On the second question, theoretically yes. The trickiest part is probably judging where Word breaks the lines because that can put you off by a full line height. I haven't had much luck with it.

**Comment by qwertynik** [comment]
> I believe the return type is `docx.shared.Twips` ("twentieth of a point") 1/1440 inch. You can use the convenience converters on any of the `Length` subtypes to get that in whatever units you need, so for example `page_height_in_mm = section.page_height.mm`. https://python-docx.readthedocs.io/en/latest/api/shared.html

That would be helpful.

> On the second question, theoretically yes. The trickiest part is probably judging where Word breaks the lines because that can put you off by a full line height. I haven't had much luck with it.

Hmm, ok. Isn't the fact that there is a line break at point Y discernable from the underlying XML document?

**Comment by scanny** [comment]
@qwertynik No. The document just records what text is in each paragraph. It's the renderer's job to wrap that text between the margins. This is as it should be because there are a lot of render-time particulars that will vary from rendering to rendering and that the document cannot know, like which fonts are available, the actual text-metrics used by that font on that output device, what size paper is in the printer, etc.

The document _does_ store paragraph breaks and "hard" line breaks, but the problem with trying to locate any given piece of rendered text is the _soft line breaks_ inserted by the renderer when _flowing_ the text into a text container.

**Comment by qwertynik** [comment]
Interesting to know about the underlying functioning. While at the outset this behavior might appear to be inefficient implementation. But with the context you provided its importance and use are clear - rendering in different environments, different font styling, etc. 

> It never has been for mine so I stopped undertaking those purposes
Yes, its understandable that for higher precision these approaches might not be well-suited. While precision is preferable, if measurements are off by a few mm's the output should still be usable

From my limited exposure to Qt, it is a UI rendering engine. Can you point to related open-source rendering engine libraries, without a UI, to programmatically render and guess the location?

Thanks!

**Comment by scanny** [comment]
I don't really keep up with that, Google will know better than me, here's one list: https://towardsdatascience.com/top-10-python-gui-frameworks-for-developers-adca32fbe6fc

**Comment by qwertynik** [comment]
Ok, thanks @scanny will check.
