### ISSUE TITLE
Automerging tables

### ISSUE THREAD

**Issue by HallerPatrick** [python-openxml/python-docx#1072]
Hello,

when adding two tables into a document object, like following: 

```python

doc = docx.Document()
records = (
    (3, '101', 'Spam'),
    (7, '422', 'Eggs'),
    (4, '631', 'Spam, spam, eggs, and spam')
)
section = doc.sections[-1]
table = doc.add_table(rows=1, cols=3)
table.style = 'Colorful Grid'

hdr_cells = table.rows[0].cells
hdr_cells[0].text = 'Qty'
hdr_cells[1].text = 'Id'
hdr_cells[2].text = 'Desc'
for qty, id, desc in records:
    row_cells = table.add_row().cells
    row_cells[0].text = str(qty)
    row_cells[1].text = id
    row_cells[2].text = desc

# doc.add_paragraph('')
table1 = doc.add_table(rows=1, cols=3)
table1.style = 'Colorful Grid'

hdr_cells = table1.rows[0].cells
hdr_cells[0].text = 'Qty'
hdr_cells[1].text = 'Id'
hdr_cells[2].text = 'Desc'
for qty, id, desc in records:
    row_cells = table1.add_row().cells
    row_cells[0].text = str(qty)
    row_cells[1].text = id
    row_cells[2].text = desc
doc.save("test.docx")
```

and open the docx afterwards. I am getting one merged table instead of two. See image:
![image](https://user-images.githubusercontent.com/22773355/162453277-ad186e75-0939-48aa-91af-ea4d0055344e.png)

Is this the expected behaviour, and if yes, is there a workaround to have two seperate tables?

Greetings,
Patrick

**Comment by keithbriggs** [comment]
What does "yest" mean?

**Comment by funes79** [comment]
typo

**Comment by HallerPatrick** [comment]
Yeah, its kind of a not-expected behaviour, but probably the fault of the docx editor (Word), and not `python-docx`. I also used a paragraph with 0 font size in the `run`, to reduce spacing.

It seems this is not a bug, and can therefore be closed :)

**Comment by unicodeee** [comment]
To reduce the gap in between, make sure to set line_spacing to 0 or a small number
`def split_table(document): 
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.line_spacing = 0
    run = paragraph.add_run()
    font = run.font
    font.size = Pt(0)`
    
`
# create table1
split_table(document)
# create table2
`

**Comment by AnotherPointofYou** [comment]
Good afternoon, I tried your way but the "add.paragraph" gives an additional line that I don't want and it doesn't bring close enough the two tables. Does anyone know how to stop auto-merging with non-space consuming way?
