### ISSUE TITLE
extracting images from a document

### ISSUE THREAD

**Issue by alexander-pecheny** [python-openxml/python-docx#108]
Hi,

my task is to parse some docx files, extracting plain text and images from them.

am i right in thinking (after reading the docs and playing around with some code) that there is no way so far to extract images from a document? I.e. I know that the document has an `inline_shapes` property, but:
- the run doesn’t have one, so I can’t establish the link between an image and a run
- `InlineShape` doesn’t have a method for saving an image to disk?

I conjecture that the best way I have is to unzip the docx and parse xml?

**Comment by yashugupta786** [comment]
@scanny  I want to extract the text and  images  with their location and need to write in new docx file . I have extracted all the text from the docx file and write it to a new file but when i am not able to extract the images and write it to new file please help me . As i am stuck .  I have already raised issue in stackoverflow
'''
https://stackoverflow.com/questions/65843126/how-to-extract-text-and-images-from-a-docx-file-and-write-it-to-new-docx-file-wi
'''
Thanks in advance
