### ISSUE TITLE
Add Tables/ Images above Captions

### ISSUE THREAD

**Issue by Rene1695** [python-openxml/python-docx#1096]
Hey,

i am trying to manipulate an existing docx document, that contains some chapters without any content. What i want to do is:

1. Add a new sub-chapter to the main chapter.
2. Insert a table and a caption to this sub-chapter. 

My workflow so far:

1. Create new paragraph with style=Heading 2, this will be the new sub-chapter
2.  Move this paragraph underneath the main chapter --> `insert_paragraph_after`
3. Add a caption (paragraph) for the table --> `add_table_caption`
4. Move the paragraph underneath the new sub-chapter
5. Add a new table with data
6. Move this table underneath the sub chapter --> `insert_table_after`

From my understanding, if i first move the caption and than move the table underneath the sub-chapter, the caption should be underneath the data table. However, whatever i try, the caption will always be above the table. Any ideas? 

```
def insert_paragraph_after(paragraph, text, style=None):

    new_p = OxmlElement("w:p")
    paragraph._p.addnext(new_p)
    new_para = Paragraph(new_p, paragraph._parent)
    if text:
        new_para.add_run(text)
    if style is not None:
        new_para.style = style

    return new_para
```

```
def insert_table_after(location, table, doc):

    regexp = re.compile(location)
    for paragraph in doc.paragraphs:
        if paragraph.text and regexp.search(paragraph.text):
            tbl, p = table._tbl, paragraph._p
            p.addnext(tbl)
```

```

def add_table_caption(location, text, doc):

    paragraph = doc.paragraphs[-1]

    for para in doc.paragraphs:
        if para.text == location:
            paragraph = insert_paragraph_after(para, "Table ", style="Caption")

    run = paragraph.add_run()
    r = run._r
    fldChar = OxmlElement('w:fldChar')
    fldChar.set(qn('w:fldCharType'), 'begin')
    r.append(fldChar)
    instrText = OxmlElement('w:instrText')
    instrText.text = ' SEQ Table \\* ARABIC'
    r.append(instrText)
    fldChar = OxmlElement('w:fldChar')
    fldChar.set(qn('w:fldCharType'), 'end')
    r.append(fldChar)

    paragraph.add_run(f": {text}")
```
```
def insert_material_list(doc, string, project):

    add_table_caption("List of Materials", "List of Materials for this harness", doc)

    mat = doc.add_table(rows=1, cols=5)
    mat.style = "Grid Table 1 Light"
    mat.alignment = WD_TABLE_ALIGNMENT.CENTER
...
    insert_table_after("List of Materials", mat, doc)
...
    doc.save(project.path_to_file)
```
![image](https://user-images.githubusercontent.com/71972934/172458611-f60c8222-299e-454c-bd42-65fbb6571bdf.png)

**Comment by icegreentea** [comment]
Hey, I don't know if you're still stuck on this, but I think in your particular example, the problem is that "List of Materials" appears in your caption so the regex in `insert_table_after()` matches it.
