### ISSUE TITLE
Is somebody maintaining this repo? 

### ISSUE THREAD

**Issue by zparcheta** [python-openxml/python-docx#1098]
Hi all! I see that there are a lot of useful PRs that weren't merged In this repo. I'm using this repo in my project and I would prefer to use it instead of forks (it is already in pip).

Kind regards

**Comment by 42sol-eu** [comment]
I would double that question and ask how we could help.
having 11 contributers  but no document about contribution seems strange.

3500 stars show this is a well liked project.

What is the limiting factor? Time, money or interest in the topic?
would love to read from you.

**Comment by scanny** [comment]
Hi Zuzanna, yes and no is the best short answer I suppose. I'm still here, just that work is busy and I've had to step back quite a bit.

Unfortunately the process of incorporating new features is much, much more involved than simply merging PRs. Doing so would lead rapidly to instability in the library and general chaos in the code base. In general, the PRs we receive are not production-worthy, lacking both documentation and tests and also often inconsistent with the architecture of the existing code. This is why so few are merged. In general it would be faster to re-develop the "feature" myself than get the PR to a suitable state. Extending a stable code base is hard, and most folks either don't have the required skills or experience or aren't willing to do the work.

If you have a long-term commitment to the project and would like to become part of the maintenance team, I'd be very pleased to speak with you about how you might contribute.

**Comment by zparcheta** [comment]
Dear @scanny, 
thank you for your answer. I'm open to collaboration. Hope I can be useful.

**Comment by creyD** [comment]
Hi @scanny

Thanks for all the hard work. You implied that you look through the PRs (I hope I read that correctly) and they are just not good enough. Could you close the ones you already looked through? Or comment on then what's missing? This would probably be very helpful and prevents the creators from pushing their PR multiple times.

Also this issue could be closed.

**Comment by scanny** [comment]
`python-docx` is getting some new love, turns out LLMs are hungry to ingest Word files so I'll be more active than usual here for a while :)
