### ISSUE TITLE
Add Column is ignored for a 1x1 table

### ISSUE THREAD

**Issue by msebas** [python-openxml/python-docx#1104]
I would like to report the following bug:

If I run 
```
import docx

d = docx.Document()
t = d.add_table(1, 1)
t.add_column(1)
t.add_row()

d.save("out.docx")
```
a docx with a table with exact 1 column and 2 rows is created. The `t.add_column(1)` is ignored, but

```
import docx
 
d = docx.Document()
t = d.add_table(0, 0)
t.add_column(1)
t.add_column(1)
t.add_row()
t.add_row()
 
d.save("out.docx")
```

behaves exactly as expected (creates a 2x2 table).

OpenSuSe 15.3
Python 3.9.1
python-docx 0.8.11

**Comment by keithbriggs** [comment]
It is working correctly.   In the first code, you are getting a new very narrow column.
