### ISSUE TITLE
How to delete all runs in paragraph?

### ISSUE THREAD

**Issue by jerrylsu** [python-openxml/python-docx#1128]
My purpose is to delete all the runs in the paragraph, and then reconstruct  all new runs at the character level. **Runs**  have been all deleted, but **all_runs** have some left. What is the difference between **runs** and **all_runs**, how can I delete all runs?
 
![2](https://user-images.githubusercontent.com/18185325/184347297-1b8ce4fa-de71-49ef-bc65-a5d3b9d88abc.png)

**Comment by icegreentea** [comment]
I'm not sure where `all_runs` is coming from? It's not in the `python-docx` source code as far as I can tell, and I can't access it when messing around myself. Are you sure there isn't some other piece of code in your code base adding that attribute to the paragraphs as you go along?

**Comment by jerrylsu** [comment]
@icegreentea Oh, I forgot I was using  [bayoo-docx](https://github.com/BayooG/bayoo-docx) instead of **python-docx**.  I tested and found that  **Bayoo-docx** added the **all_run** attribute. Thank you for your reply.
