### ISSUE TITLE
Convert the docx created to pdf file

### ISSUE THREAD

**Issue by sabygo** [python-openxml/python-docx#113]
Can we convert the docx file created by python-docx to pdf or there is any way to save as the docx file to pdf.

**Comment by thisisprabin** [comment]
Any other module because pywin doesn't work in ubuntu

**Comment by jorgeas80** [comment]
I upload the docx to Google Drive and download a PDF version. It's not perfect, but works for me, and can be done with the Google Python libraries

**Comment by Schleehauf** [comment]
For conversion have look at pandoc [https://pandoc.org/](url)

**Comment by pylang** [comment]
@fstraw 's solution works well.  Here's some more info:

Install pywin32 via:
- download [binaries](https://sourceforge.net/projects/pywin32/files/pywin32/)
- or install the latest wheel via PyPI, i.e. `> pip install pywin32`


You may need to refresh your session if using a script or notebook.

```python
import win32com.client as client


def convert_to_pdf(filepath:str):
    """Save a pdf of a docx file."""    
    try:
        word = client.DispatchEx("Word.Application")
        target_path = filepath.replace(".docx", r".pdf")
        word_doc = word.Documents.Open(filepath)
        word_doc.SaveAs(target_path, FileFormat=17)
        word_doc.Close()
    except Exception as e:
            raise e
    finally:
            word.Quit()
```

I've found this approach to preserve embedded images and styles from a `.docx` file (compared to pandoc).

**Comment by luke4u** [comment]
@pylang , do you have a solution that is not based on win32com? Our MS macro has been disabled by the firm.  cannot use anything based on win32com.

**Comment by juan-gama** [comment]
> @pylang , do you have a solution that is not based on win32com? Our MS macro has been disabled by the firm. cannot use anything based on win32com.

You can use pandoc https://pandoc.org/
Keep in mind you have to install pdfTex which comes on the texlive package, so in general you would want to in Ubuntu/Debian like OS:

1. `sudo apt install texlive`
2. Download pandoc deb
3. `sudo dpkg -i pandoc.deb`

At the end you can run:
`pandoc -s test.docx -o testt.pdf`
