### ISSUE TITLE
Default document size

### ISSUE THREAD

**Issue by ISipi** [python-openxml/python-docx#1131]
So I have an issue where the created document defaults to 'Letter' size rather than A4 size. Is there an easy way of changing this default?

**Comment by scanny** [comment]
Easiest way is to create your own template file and then start with that when generating a new .docx file:
```python
document = Document("my-template.docx")
```

While you're at it you can add the styles, margins, etc. you want to that file and so on, so you always have the starting point you want.

When you start a new document with:
```python
document = Document()
```
all its doing is pulling that starting template document (which is from about ten years ago) from the source-tree, so if you want something different you can make whatever template you like :)
