### ISSUE TITLE
docx.opc.exceptions.PackageNotFoundError

### ISSUE THREAD

**Issue by pratiknht** [python-openxml/python-docx#1133]
### Bug Metadata:

- python-docx version : 0.8.11
- Python version: 3.9
- OS version : Ubuntu 18.04.6 LTS

### Bug description:
- I have a python program that reads a docx file; edits its content and saves it.
- Recently the library is throwing error  **docx.opc.exceptions.PackageNotFoundError**
- The error is very random; most of the time the same file works perfectly but randomly throws the error.
- After the error, it fails even if retried with the same file several times.
- Once this error occurs for a particular file, it throws an error for all other files.
- The application runs inside python docker; when the docker has restarted the library works fine until the next trigger for the error.

### Code snippet
```
import docx as docs

doc = docs.Document(document_path)

```
Attaching the logs for more information

```
Traceback (most recent call last):
  File "/home/app/apps/assembly/executionmanager.py", line 65, in excute_tempalte_document
    doc = docs.Document(document_path)
  File "/usr/local/lib/python3.9/site-packages/docx/api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "/usr/local/lib/python3.9/site-packages/docx/opc/package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/usr/local/lib/python3.9/site-packages/docx/opc/pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/usr/local/lib/python3.9/site-packages/docx/opc/phys_pkg.py", line 30, in __new__
    raise PackageNotFoundError(
docx.opc.exceptions.PackageNotFoundError: Package not found at 'media/documents/6d6bdb66-fbe5-43aa-8d87-de048b5e3d34/Data Protection Template.docx'


```

**Comment by Nicecheat** [comment]
I encounter the same issue, then I found that my docx file actually is a doc file when I check the binary form of my docx file, so I open my word and save this file as docx format, the encoding switched to docx form successully and it works.
Notice that general save won't change encoding of docx file, change suffix name won't work either, it only works by word processable application.

**Comment by scanny** [comment]
@Nicecheat's account makes sense. This error arises under two conditions:
1. There is no file at the given path
2. The file is not a zip archive (a .docx file is a zip archive, just not with a .zip extension)

So your debugging should focus there. It's not going to have anything to do with the part of `python-docx` that loads the file. I would suspect something like your docker disk space is small and gets full after awhile and you can't save the file anymore, but there's no way to tell from this distance. Find the file and try to open it with zip, like `unzip -l path/to/file.docx` and if that doesn't work, there's your problem :)

**Comment by chaoStart** [comment]
some file is ".docx"，but actually，it just changed the suffix name . For example ,you change the suffix of  ".doc"  into ".docx". In fact,it's not a  ".docx" file, so it won't work!
