### ISSUE TITLE
Tables containing dropdown menus

### ISSUE THREAD

**Issue by hatschiman** [python-openxml/python-docx#1136]
Hello folks,

I have noticed that tables are not read properly when they contain dropdon menus.
It seems that there are two types of dropdown menus - one which results in an empty cell and the other will be just ignored and the next cell will shift in its place, which results messing up the tables contents completely.

[Dropdown.docx](https://github.com/python-openxml/python-docx/files/9548048/Dropdown.docx)

The Issue can be reproduced by using this code snippet and the attached *.docx file.

```from docx.api import Document

doc = Document(r"path-to-document")
table = doc.tables[0]

for i, row in enumerate(table.rows):
    for j, cell in enumerate(row.cells):
        print(f"({i}, {j})", end=' ')
        print(cell.text if cell.text != '' else " ", end='\t')
    print('\n')
```

The output should look like this:

```(0, 0) Header A (0, 1) Header 1

(1, 0) A        (1, 1) 1

(2, 0) B        (2, 1) 

(3, 0) C        (3, 1) 

(4, 0) D        (4, 1) 4
```

but looks like this:

```(0, 0) Header A (0, 1) Header 1

(1, 0) A        (1, 1) 1

(2, 0) B        (2, 1) C

(3, 0)          (3, 1) D

(4, 0) 4
```

Any ideas how to solve that issue?

Thanks and best wishes

**Comment by scanny** [comment]
What's happening in this case is that the `w:tc` element for cell (2, 1) is enclosed in a `w:sdt/w:sdtContent` element subtree. `sdt` stands for _structured document_ something or other, tag maybe, and is the bit that lets you pick from a list.

`python-docx` doesn't know about structured document fields like this and what you're seeing is its best idea of what the table contents are.

If you wanted it badly enough, you could parse the cells yourself, something on the order of:
```python
def iter_row_cells(row):
    r = row._r
    tcs = r.xpath("./w:tc | ./w:sdt/w:sdtContent/w:tc")
    return (_Cell(tc, row) for tc in tcs)

for row in table.rows:
    for cell in iter_row_cells(row):
        print(cell.text)
```

**Comment by jayco10125** [comment]
As a beginner trying to understand why the table is changing its dimensions this is highly annoying. All I need is that cell to be outputted as an empty cell but still taking up space so that the table dimensions are kept the same.
