### ISSUE TITLE
How to preserve docx text properties/styles after colour shades from NER model tagged results using library Python-docx

### ISSUE THREAD

**Issue by DeantaUmesh** [python-openxml/python-docx#1137]
Hi @scanny 
I have results generated from spacy NER model which are tagged and coloured based on tag group(both Background and font colour). Am happy with results from NER model, But when am pasting these coloured results in Existing open docx, its loosing all properties. While adding new run in it. I used existing colour shade method of "OxmlElement('w:shd')" for colour the text. Looking for help in this, for preserving all text properties(font, bold, italic etc.) after colour in docx file.

`# Iterate through each row in the para_runs dataframe(para_runs is tageed entity with colour code values)

    for i in range(len(para_runs.index)):
        # Identify the text for the current row/run
        run_text = para_runs.text[i]

        # Add a new run to the paragraph, keep track of this new run in the variable new_run
        new_run = para.add_run(text = run_text)
        # for run in para.runs:
            # Check to see if the current para_runs font is not an empty tuple (ie, has some colour to
            # be applied to it). If there is none, leave the font as 0,0,0 rgb ie black
        if not para_runs.font_colour_rgb[i] == ():
            # Update the font colour by using RGBColor function from python-docx package
            r, g, b = para_runs.font_colour_rgb[i]
            new_run.font.color.rgb = RGBColor(r, g, b)
        else:
            r, g, b = (0, 0, 0)
            new_run.font.color.rgb = RGBColor(r, g, b)

        # Check and see if the current run should have background colour applied, ie is not an
        # empty tuple
        if not para_runs.background_colour_rgb[i] == ():
            # Convert rgb to hex, as required by docx xml
            background_colour_hex = '#%02x%02x%02x' % para_runs.background_colour_rgb[i]
            # Create run_rag variable which will be used to store information on the shading (shd)
            # xml element
            run_tag = new_run._r

            # Create and set the values for the shd element
            shd = OxmlElement("w:shd")
            shd.set(qn("w:val"), "clear")
            shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"), background_colour_hex)

            # Add shd properties to the run properties element
            run_tag.rPr.append(shd)`

**Comment by scanny** [comment]
Closed inactive.
