### ISSUE TITLE
How to know if a paragraph contains a picture?

### ISSUE THREAD

**Issue by Alonshow** [python-openxml/python-docx#1140]
I'm processing a document with pictures and I want my program to treat each paragraph differently depending on whether it contains a picture or just text. How can I find out if a paragraph contains a picture? I couldn't see anything in the API documentation that discusses this.

Note: I'm an experienced programmer but I'm new to Python, I only started coding in Python about a month ago.

**Comment by scottzach1** [comment]
Hi @Alonshow,

To the best of my knowledge there isn't an elegant way to pull this information via the API. However, you can probably identify this based on the underlying XML.

See [Picture — python-docx 0.8.11 documentation](https://python-docx.readthedocs.io/en/latest/dev/analysis/features/shapes/picture.html)

```python
from docx.text.paragraph import Paragraph


def paragraph_contains_image(p: Paragraph) -> bool:
    return any("pic:pic" in run.element.xml for run in p.runs)
```

Let me know if that helps! (or others let me know if there is an easier way!)

**Comment by scanny** [comment]
Somewhat more efficient and perhaps more reliable would be to use XPath:

```python
paragragph_contains_image(paragraph: Paragraph) -> bool:
    return bool(
        paragraph._p.xpath(
            "./w:r/w:drawing/*[self::wp:inline | self::wp:anchor]/a:graphic/a:graphicData/pic:pic"
        )
    )
```

A complicating factor is that a picture can be "nested" inside a hyperlink element, or a `w:ins` or `w:del` element if there are unaccepted revisions in the document. You'd need to adjust the XPath to find those if you need them and avoid false positives on for example, deleted images.
