### ISSUE TITLE
how to get the all headers and footers value from document?

### ISSUE THREAD

**Issue by hemilparmar** [python-openxml/python-docx#1143]
i am facing issue that document is not giving all the unique header and footer from document like all page numbers along with some text but i am getting not all the values. so how to do that ?

Thank You

i am below code

doc = Document(doc_file)

for section in doc.sections:
    footer = section.footer.paragraphs
    header = section.header.paragraphs
    for i in footer:
        print(i.text)
    for i in header:
        print(i.text)

**Comment by scanny** [comment]
Not all headers or footers are active. In particular you need to be checking the `Header.is_linked_to_previous` attribute to see if it uses the same text as it did in the prior section.
