### ISSUE TITLE
How to copy table styles from another document?

### ISSUE THREAD

**Issue by iclite** [python-openxml/python-docx#1145]
like this:

```python
input = docx.Document("input.docx")
template = docx.Document("template.docx")

input.styles.add_style('SD Table', WD_STYLE_TYPE.TABLE)
input.styles['SD Table'] = template.styles['SD Table']

for table in input.tables:
    table.style = 'SD Table'
```

**Comment by coolkau** [comment]
There are so many open requests related to copying from one document to another. There might be good reasons why most of docx is read only. Yet, copying over a style only by being able to copy it over on the smallest of all granularites is a lot of work.

**Comment by scanny** [comment]
Yeah, I don't see this being on the roadmap anytime soon. This sort of thing would require someone with project dollars to sponsor it. The general challenge is reconciling references to external objects within whatever is being copied over and that's going to require a lot of tedious research and experimentation to get right. I'd be looking for alternatives and maybe using a paid option if it's really important to your project.
