### ISSUE TITLE
Document(docx) raise BadZipFile("Bad CRC-32 for file %r" % self.name)

### ISSUE THREAD

**Issue by dongfang-fang** [python-openxml/python-docx#1152]
hello,python version is 3.9.6,docx version is 0.8.11.
I offer have an error which is Document(docx) raise BadZipFile("Bad CRC-32 for file %r" % self.name).
how to solve it？
thanks

**Comment by subingxi** [comment]
I'm having the same issue

**Comment by scanny** [comment]
I expect it means what it says, that the file is not a Zip archive or is corrupted. If you can't unzip the file then it's not a valid .docx file.

This library won't work for legacy `.doc` files by the way.
