### ISSUE TITLE
Why some words break in the middle

### ISSUE THREAD

**Issue by xin-kevin** [python-openxml/python-docx#1158]
Hi,
I use the following code snippet to receive the font of words in a word file:

from docx import Document
document = Document('Test_Word.docx')
for paragraph in document.paragraphs:   
    for run in paragraph.runs:
        if run.font:
            print ('\n')
            print (run.font.name)
            print (run.text)

Sorry, I don't know why the code snippet lost the indentation.
In the output, some words break in the middle, for example:

Courier New
u

Courier New
ri

In the example above, 'uri' breaks into 'u' and 'ri'.

Could you please help prevent a word from breaking?

I also attached this word file.
[Test_Word.docx](https://github.com/python-openxml/python-docx/files/10101700/Test_Word.docx)

Any comment would be appreciated!

**Comment by danielichis** [comment]
some answer ? i have the same issue.

**Comment by garnik-arut** [comment]
I suppose the reason is that they belong to different runs, hence the break.
If you try this
```
wd = Document('Test_Word.docx')
for paragraph in wd.paragraphs:
    print(paragraph.text)
```
output should be fine.
