### ISSUE TITLE
Need to convert docx to pdf

### ISSUE THREAD

**Issue by eshagupta31** [python-openxml/python-docx#1162]
It is possible to convert a docx document generated by python-docx to pdf? Please help!!!

**Comment by ahmadalwareh** [comment]
it is possible if the output is not corrupted, also, you can automate it with `fitz` or with the code below:
```python
from docx2pdf import convert

convert("input.docx")
convert("input.docx", "output.pdf")
convert("my_docx_folder/")
```
sure you have to install it first with: `pip install docx2pdf`, or you can run it from bash:
```bash
docx2pdf input.docx output.pdf
```
