### ISSUE TITLE
sys.argv being split on spaces

### ISSUE THREAD

**Issue by rickmedlin** [python-openxml/python-docx#1166]
My PHP program passes a string similar to this to a Python script:

$description = escapeshellcmd('ACSB9(E374T) B-labeled');

The Python script then uses docx to assign the value to a cell in a table:

product_table.cell(0, 1).text = str(sys.argv[3])    # Description

For this string only, the value is being split where a space occurs. I've tried to add quotes in the PHP and tried .join in the Python script with no success. Any ideas would be welcome.

**Comment by jessicaanhel** [comment]
The separator for `sys.argv`  is space. It is advisable to avoid using spaces in your parameters if you can. If you need to enter an argument that contains a space, you will need to surround it with quotation marks, such as "argument with space".

f"Arguments: '${argument with space}' ${argument-without-space"}"
or
sh''' program.py "${argument with space}" ${argument-without-space"} '''
