### ISSUE TITLE
Funcktion has wrong answer

### ISSUE THREAD

**Issue by Higherupanddown** [python-openxml/python-docx#1171]
When i use func run.bold or run.italic, run.underline etc. i have "True" or "None" in result. Why isn't it "True" or "False"??? I have searched func for watching font style an hour, it's illogical, fix this shit if you can, please

**Comment by buhtz** [comment]
You forgot the magical word "please".

Please be aware that the maintainer does create and evolve that package in his spare time. Please hold a second, breath deeply and think about your words.

**Comment by Higherupanddown** [comment]
Sorry for my anger, i was tired at that moment. I delited my code with examples and can't give you more Informathion
