### ISSUE TITLE
Paragraph Formatting 

### ISSUE THREAD

**Issue by decadance-dance** [python-openxml/python-docx#1183]
I have a paragraph like in the screenshot.
![image](https://user-images.githubusercontent.com/86170544/217584986-ca5d08a7-5833-4af4-b552-ac7426b1d487.png)
It has a blue background and white font color.
Tell me how can I reset its "style" settings to normal (black font, white background)
For a long time I can not figure out which attributes I need to change.
Thank you

**Comment by ahmadalwareh** [comment]
`style` is an attribute inside the paragraph property, if you access the protected attribute `_p` then you can get the `pPr`, after that, you can set the `style` to `None` because of the `style.setter` and that can let you format the style
