### ISSUE TITLE
Reading bullet point values 

### ISSUE THREAD

**Issue by GPrakruth** [python-openxml/python-docx#1187]
[sample document.docx](https://github.com/python-openxml/python-docx/files/10895500/sample.document.docx)
Is there a possible way to read bullet point text and corresponding values 
like the for example 1.1 Sample text is in bullet point format, can we get values of 1.1 as well while reading text from bullet points

toc = []
for para in document.paragraphs:
    # print(para.style.name)
    if para.style.name =='List Paragraph':
        print(para._element.xpath('./w:pPr/w:numFmt/w:numId/w:val'))
        # print(test.xpath('./w:ilvl')[0].get('w:val'))

tried the following code only to get none values, also tried "numPr" but same print is displaying None

**Comment by scanny** [comment]
Closing as inactive.

**Comment by sharmakrishn** [comment]
Hi, I also tried to extract bullet points from the docs but didn't find any way can any one tell me how can i do that?

**Comment by GPrakruth** [comment]
this issue still persist, any update from developers on this ?
