### ISSUE TITLE
soft carriage return

### ISSUE THREAD

**Issue by HuiDBK** [python-openxml/python-docx#1195]
How do I replace a soft carriage return with a hard carriage return in a docx document

**Comment by ME-researchgroup** [comment]
In Word you can replace `^l` (lowercase L) with `^p` to turn line breaks into new paragraphs, which I guess is what you're referring to. As far as I know, this is not supported in this library. Seeing that @scanny no longer seems to maintain any of his great libraries, I don't expect this will ever be implemented either..

I think your best bet would be to loop over your paragraphs' text and create a new paragraph whenever you encounter a `\n`. This is kind of hacky and it will not be trivial to keep track of any markup in the text.
