### ISSUE TITLE
Won't install under Python3.9

### ISSUE THREAD

**Issue by bcraigie** [python-openxml/python-docx#1202]
Hi.  I tried installing python-docx under Python3.9 and it gave me an error :
 ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
I spent ages trying to find out what was wrong with my python environment before I found that it would install under python 3.6

Python 3.6 was end of support 23 Dec 2021.

Would it be possible to update this excellent library to be able install under Python 3.9 (or later) please?
:-)

**Comment by scanny** [comment]
Installs fine for me in 3.7, 3.8, 3.9, 3.10, and 3.11.
