### ISSUE TITLE
unable to install with python 3.8.2

### ISSUE THREAD

**Issue by davidchapuis** [python-openxml/python-docx#1203]
have the following message when trying to install the package from pycharm with Python 3.8.2

    ERROR: Could not install packages due to an OSError: 
    HTTPSConnectionPool(host='files.pythonhosted.org', port=443): 
    Max retries exceeded with url: /packages/8b/a0/52729ce4aa026f31b74cc877be1d11e4ddeaa361dc7aebec148171644b33/python-docx-0.8.11.tar.gz 
    (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x110a88b50>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)'))

@scanny

**Comment by scanny** [comment]
Closing as stale/inactive.
