### ISSUE TITLE
Python 3.10 add_row inserts empty rows as well as populated rows

### ISSUE THREAD

**Issue by mmoye** [python-openxml/python-docx#1210]
When writing a very simple table of 3 rows and a heading I end up with 2 empty rows and 3 rows with data. Anyone know how to not have the empty rows?

```
import docx
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

try:
    records = [('apple', 'tomato', 'car'), ('banana', 'squash', 'bicycle'), ('grapes', 'carrot', 'motorcycle')]
    # Count records
    records_count = len(records)
    # Create an instance of a word document
    doc = docx.Document()

    # Create data table
    table = doc.add_table(rows=records_count, cols=3)
    table.autofit = False
    table.style = 'Table Grid'
    table.columns[0].width = Inches(1.3)
    table.columns[1].width = Inches(1)
    table.columns[2].width = Inches(5.25)
    for cell in table.columns[0].cells:
        cell.width = Inches(1.3)
    for cell in table.columns[1].cells:
        cell.width = Inches(1)
    for cell in table.columns[2].cells:
        cell.width = Inches(5.25)
    # set headers
    row = table.rows[0].cells
    row[0].text = 'Fruit'
    row[1].text = 'Vegetable'
    row[2].text = 'Transportation'

    # populate data
    for a, b, c in records:
        row = table.add_row().cells
        row[0].text = str(a)
        row[1].text = str(b)
        row[2].text = str(c)

    # save document
    doc.save('test.docx')

except:
    print("Error")

finally:
        print("Done \n")
```

**Comment by Austin1990** [comment]
if you want to create an empty table then populate it, use **enumerate** to index the rows.
Note: you need an extra row for the header text when you create the table.

`import docx
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

try:
    records = [('apple', 'tomato', 'car'), ('banana', 'squash', 'bicycle'), ('grapes', 'carrot', 'motorcycle')]
    # Count records
    records_count = len(records) + 1
    # Create an instance of a word document
    doc = docx.Document()

    # Create data table
    table = doc.add_table(rows=records_count, cols=3)
    table.autofit = False
    table.style = 'Table Grid'
    table.columns[0].width = Inches(1.3)
    table.columns[1].width = Inches(1)
    table.columns[2].width = Inches(5.25)
    for cell in table.columns[0].cells:
        cell.width = Inches(1.3)
    for cell in table.columns[1].cells:
        cell.width = Inches(1)
    for cell in table.columns[2].cells:
        cell.width = Inches(5.25)
    # set headers
    row = table.rows[0].cells
    row[0].text = 'Fruit'
    row[1].text = 'Vegetable'
    row[2].text = 'Transportation'

    # populate data
    for idx, s in enumerate(records, start=1):
        row = table.rows[idx].cells
        row[0].text = s[0]
        row[1].text = s[1]
        row[2].text = s[2]

    # save document
    doc.save('test.docx')

except:
    print("Error")

`

**Comment by mmoye** [comment]
That did it, thanks! Looks like [this ](https://www.geeksforgeeks.org/working-with-tables-python-docx-module/) guide could use a refresh.

**Comment by Austin1990** [comment]
I'm confused, the guide looks correct if you used the fix from my 1st comment.

**Comment by mmoye** [comment]
I modeled my code after that guide and it did not work. It also doesn't account for the extra (header) row.

**Comment by mmoye** [comment]
Yep, I see my error now, thanks again!

**Comment by Austin1990** [comment]
you're welcome.
