### ISSUE TITLE
How to remove the default title underline in style of “Title”

### ISSUE THREAD

**Issue by timewaitsfor** [python-openxml/python-docx#1211]
My code is as follows, there is always an underline in the default format of the title, how can I remove the underline?
```python
    document = Document()
    title = document.add_heading('', level=0)
    run = title.add_run("Title")
    run.font.size = Pt(22)
    run.font.color.rgb = RGBColor(0, 0, 0)
```
The generated result is as follows:
![image](https://github.com/python-openxml/python-docx/assets/67723549/6b72ec3e-5840-4ad3-a8ff-8cabff3709df)

**Comment by Austin1990** [comment]
You need to modify the border styling for the chosen heading level in Word itself.
