### ISSUE TITLE
'Document' object has no attribute 'comments'

### ISSUE THREAD

**Issue by pcesarano** [python-openxml/python-docx#1215]
I have a folder with Word .docx files that have both "track changes" and "comments". I am trying to take each file (there are around 150), and strip/delete all comments while leaving the "track changes" modifications untouched, and store the new .docx files (without comments) in a different folder "output_files". 

However, no matter what I try, I ALWAYS get the error: 'Document' object has no attribute 'comments'.

I'll attach an image of the VERY short .py script I've been using, and the error message. Please help!
![removecomments](https://github.com/python-openxml/python-docx/assets/56978055/954b25b1-4484-4d73-8464-d764ad478d6b)
![error_message](https://github.com/python-openxml/python-docx/assets/56978055/98c1ec39-bdb1-4634-b256-c0b21618a26f)

**Comment by scanny** [comment]
There is no comments support in `python-docx` yet.
