### ISSUE TITLE
How to extract the text of ordered list or unordered list

### ISSUE THREAD

**Issue by zysNLP** [python-openxml/python-docx#1218]
My docx looks like:
<img width="200" alt="image" src="https://github.com/python-openxml/python-docx/assets/45376689/6744ea59-0567-4e50-a8a7-9c75f40b98dc">
```python
from docx import Document
docx_path = "./docx_output/lists.docx"

document = Document(docx_path)
for p in document.paragraphs:
    if p._element.get_or_add_pPr().get_or_add_numPr().numId is not None:
        num_id = p._element.get_or_add_pPr().get_or_add_numPr().numId
        print(f"{num_id.val = }")

```
I used this code to parse the paragraph object, but the result of this code is:
```
num_id.val = 1
num_id.val = 1
num_id.val = 2
num_id.val = 2
num_id.val = 3
num_id.val = 3
num_id.val = 3
```
It looks like it recognizes that it's a list, but it doesn't recognize whether it's an ordered list or an unordered list, and it doesn't extract the text that precedes a paragraph. 
how could I get the order text like: two black point or 1、2 or 一、二、三？

**Comment by TTCoding** [comment]
同学你找到解决方案了吗？我也遇到相同的困惑。
Have you got any solution?

**Comment by TTCoding** [comment]
I can get the list level now.
```
from docx import Document
d = Document('t.docx')
s = d.element.xml
p = d.paragraphs[0]._element.xpath('./w:pPr/w:numPr/w:ilvl')[0].val
