### ISSUE TITLE
Auto Fit Picture

### ISSUE THREAD

**Issue by jrykalsky** [python-openxml/python-docx#1222]
I would like to be able to auto-fit pictures to a table in a word doc. I have images of different native sizes so I don't want to have to define a specific height and width. A blank word doc does this by default with the code 
"DefaultTableBehavior:=wdWord9TableBehavior, AutoFitBehavior:= _wdAutoFitFixed"

Is there a way to do this with docx? I tried the property "Table.allow_autofit" but this doesn't appear to work (unless I'm doing it wrong which is very possible).

**Comment by BenoitMarchand** [comment]
Hi, 

I was able to do something like that by : 
1) checking the cell width of the table
2) inserting the picture with a fixe width
3) allignment of the paragraph horizontally and the cell vertically

All together, the code look like (once the selected cell is set in cell variable) :

from docx.shared import Cm # for table column size
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL

[...]
# Selection of the target cell in the target table

width = cell.width.cm
paragraph = cell.paragraphs[0]
paragraph.alignement = WD_ALIGN_PARAGRAPH.CENTER
run = paragraph.add_run()
run.add_picture(picture_path, width=Cm(width))
paragraph.alignement = WD_ALIGN_PARAGRAPH.CENTER
cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER

Hope it helps

**Comment by jrykalsky** [comment]
Thank you so much!

For whatever reason I only ended up needing 2 of those lines though. I only needed:
width = cell.width.cm
run.add_picture(picture_path, width=Cm(width))

This got me what I was hoping for and the other code didn't seem to do anything for me.

Either way, thanks again!
