### ISSUE TITLE
Pyright return errors with WD_ORIENT, WD_STYLE_TYPE, WD_ALIGN_PARAGRAPH

### ISSUE THREAD

**Issue by ucomru** [python-openxml/python-docx#1224]
Good day!
Im getting Pyright errors, but py script with docx run correctly.

```bash
❯ python3 -m platform
macOS-13.4.1-arm64-arm-64bit

❯ python3 -c "import docx; print(docx.__version__)"
0.8.11
```

**Pyright** import errors:
```python
from docx.enum.section import WD_ORIENT # <<< Error!
# Pyright: "WD_ORIENT' is unknown import symbol Pyright (reportGeneralTypeIssues)

from docx.enum.text import WD_ALIGN_PARAGRAPH # <<< Error!
# "WD _ALIGN_PARAGRAPH'' is unknown import symbol Pyright (reportGeneralTypeIssues)
```

**WD_STYLE_TYPE.PARAGRAPH**:
```python
doc.styles.add_style('Head', WD_STYLE_TYPE.PARAGRAPH)  # <<< Error!
# Cannot access member "PARAGRAPH" for type "type [WD_STYLE_TYPE]"
# Member "PARAGRAPH" is unknown Pyright (reportGeneralTypeIssues)
```

**Pyright** with **Sublime Text**:
.
<img width="1347" alt="WD_ALIGN_PARAGRAPH" src="https://github.com/python-openxml/python-docx/assets/101626426/0d135ff5-bff6-486d-a5f2-ee7f40228860">
.
<img width="1203" alt="WD_ORIENT" src="https://github.com/python-openxml/python-docx/assets/101626426/72f0d040-c552-4af3-9a01-5502f770073f">
.
<img width="1267" alt="WD_STYLE_TYPE--PARAGRAPH" src="https://github.com/python-openxml/python-docx/assets/101626426/f4f14db6-02be-4cdd-87dc-a40dc525a38a">
.
**Pyright** with **NeoVim**:
.
<img width="1411" alt="nvim_WD_ALIGN_PARAGRAPH" src="https://github.com/python-openxml/python-docx/assets/101626426/eb37f4c9-eb7b-45b7-8c3f-4d03c0153b22">
.
<img width="1035" alt="nvim_WD_ORIENT" src="https://github.com/python-openxml/python-docx/assets/101626426/af847c68-5a29-4fea-acfa-1ad59452ee4a">

**Comment by scanny** [comment]
@ucomru  These "short" names are unknown to `pyright` because they are added with some sort of indirect magic. This is an example: https://github.com/python-openxml/python-docx/blob/master/docx/enum/text.py#L12-L13 (it seemed like a good idea at the time :)

If you use the long names they should type-check fine:

```python
from docx.enum.section import WD_ORIENTATION as WD_ORIENT
```
