### ISSUE TITLE
How to find paragraph position based on content?

### ISSUE THREAD

**Issue by xichichixi** [python-openxml/python-docx#1225]
Hello dear developer！
I currently have such a need. When locating a table in a docx file, I would like to know the contents of the lines above the table, what method should I use?
For example, after I locate the following table through `document.tables[i],` how can I get the lines of text marked with a red line above it? Looking forward to your reply, thank you
<img width="502" alt="屏幕截图 2023-07-14 113959" src="https://github.com/python-openxml/python-docx/assets/94942409/88e43db4-76a7-4997-8024-56ae704588cf">

**Comment by robinsonmd** [comment]
```python
from docx import Document
from docx.table import Table
from docx.oxml.text.paragraph import CT_P
from docx.text.paragraph import Paragraph
from docx.oxml.table import CT_Tbl
docx_file = Document("xxxx")
contents=[]
for element in tqdm(docx_file.element.body):
    if isinstance(element, CT_Tbl):
        table_text = "--------------------table-------------------"
        keys = None
        table = Table(element, docx_file)
        for i, row in enumerate(table.rows):
            text = (cell.text for cell in row.cells)
            if i == 0:
                keys = tuple(text)
                continue
        contents.append(table_text)
    if isinstance(element, CT_P):
        paragraph = Paragraph(element, docx_file)
        contents.append(paragraph.text)
```

**Comment by scanny** [comment]
@robinsonmd what is `tqdm()`?

**Comment by robinsonmd** [comment]
> @robinsonmd what is `tqdm()`?

a progress bar
