### ISSUE TITLE
Can't seem to figure out if i can embed objects (binary files) in MS Word document

### ISSUE THREAD

**Issue by coobr01** [python-openxml/python-docx#1234]
Is it possible using this package to embed binary objects (i.e., OLE objects) into a MS Word document and have an icon represent them like in the sample image below? I'm looking for a cross-operating system compatible way of generating .docx files containing an unknown number of small embedded files.

![image](https://github.com/python-openxml/python-docx/assets/1842830/b48bfc14-121d-43d3-b1b9-ebce1e3c2db2)

**Comment by scanny** [comment]
Not presently. That feature does exist in `python-pptx` however, if you're flexible as to the document format.
