### ISSUE TITLE
Any roadmap or new release?

### ISSUE THREAD

**Issue by wqh17101** [python-openxml/python-docx#1236]
Is there someone maintains this repo?

**Comment by grahamanderson** [comment]
ditto. Python-docx is a great package!

**Comment by scanny** [comment]
@translation-robot there are currently no active developers or maintainers, but the library is still in wide use. It looks like it might get some new love before long because I'm likely to be using it in my next gig.

**Comment by titusjan** [comment]
> ...there are currently no active developers or maintainers ...

@scanny , i thought you were the maintainer and original author? Am I mistaken?

In any case, great to hear that you want to spend time on it. It's a very useful package and well documented.

**Comment by scanny** [comment]
Yes, that's true, just lately I haven't had time or motive to attend to maintenance or development on it. That generally happens when I need to use it in my day job, which is what looks like is coming up soon here :)
