### ISSUE TITLE
Loop through all elements of a doc and determine their type?

### ISSUE THREAD

**Issue by enrac5** [python-openxml/python-docx#1239]
I have a word doc that's structured with two tables, both of the same column headers, but different purposes. I need the second table. There's some text that precedes each table which I can use to figure out if the table is the one I want, but in order to do that, I need to loop over all the elements in the doc and see which one is the text I need, and then look at the table after that. I don't see in the documentation how to loop through all elements, can anyone help please?

**Comment by scanny** [comment]
If you search Google on `iter_block_items` you'll find what you need. This is the first search result:
https://github.com/python-openxml/python-docx/issues/40

There were several refinements, so I think this implementation at the bottom is what you're after:
https://github.com/python-openxml/python-docx/issues/40#issuecomment-1503337928
