### ISSUE TITLE
Modify bookmark's text

### ISSUE THREAD

**Issue by vonyang** [python-openxml/python-docx#1241]
Hello,
I have a Word document with existing bookmarks, and I want to replace the text, I saw it creating the bookmarks but that didn't work for me. I´m using Python and the only thing I have already achieve is to see the names of the bookmarks. This is the code I'm using:

```
from docx import Document
from docx.oxml.shared import qn
  
document = Document('MyWordDocument')
  
documentElement = document.part.element
bookmarks = documentElement.findall('.//' + qn('w:bookmarkStart'))
  
for bookmark in bookmarks:
  
      nombreMarcador = bookmark.get(qn('w:name'))
      print(nombreMarcador)
```

**Comment by scanny** [comment]
What is the specific problem? "Didn't work" isn't enough to go on :)

If your query didn't find the bookmarks you expected, try an XPath expression instead, something like `documentElement.xpath(".//w:bookmarkStart")`.

The .find/.findall() query API is legacy for compatibility with ElementTree; XPath is much more capable and faster too I believe.

**Comment by vonyang** [comment]
I need a method to substitute a blank space of a bookmark's text field for text, for example: 'bookmark1': '', to, 'bookmark1': 'Hello World', the way I found was to replace all the paragraph with the word, but I want to replace it only in the bookmark's text field. But I don't find the way.

> What is the specific problem? "Didn't work" isn't enough to go on :)
> 
> If your query didn't find the bookmarks you expected, try an XPath expression instead, something like `documentElement.xpath(".//w:bookmarkStart")`.
> 
> The .find/.findall() query API is legacy for compatibility with ElementTree; XPath is much more capable and faster too I believe.

**Comment by scanny** [comment]
Try:
```python
bookmarks = documentElement.xpath(".//w:bookmarkStart") in the snippet you provided and see if that doesn't produce better results.
```

**Comment by vonyang** [comment]
I tried but the text I want to insert in the bookmark can' t be seen in the Word document, and I tried a few codes and none of them work. The code I used the last try was the following:
```
for bookmark in bookmarks:

        nombreMarcador = bookmark.get(qn('w:name'))
        idMarcador = bookmark.get(qn('w:id'))

        parentMarcador = bookmark.getparent()
        bookmarkParentStart = parentMarcador.getparent()
        startIndex= bookmarkParentStart.index(parentMarcador)

        for bookmarkEnd in bookmarksEnd:

            if bookmarkEnd.get(qn('w:id')) == idMarcador:

                parentEnd= bookmarkEnd.getparent()
                bookmarkParentEnd= parentEnd.getparent()
                finalIndex= bookmarkParentEnd.index(parentEnd)
                break

        if nombreMarcador == 'bookmark1':

            t_element = bookmark.find(qn('w:t'))
            t_element = parentMarcador.makeelement(qn('w:t'))
            bookmark.insert(startIndex, t_element)

            t_element.text = 'The text has been introduced'
            print(t_element.text)
```

**Comment by vonyang** [comment]
To modify a bookmark text field, you can use the following code to get access to the text field of the bookmark. This is only valid with bookmarks in paragraphs:
```
document = Document('MyDocument.docx')
documentElement = document.part.element
bookmarks = documentElement.xpath('.//w:bookmarkStart')

for bookmark in bookmarks:
    #   Modify the text inside the bookmark
    bookmarkElement = bookmark.getnext() #  The next element that it should be a <w:r>

    #   Iterate over the sublevels elements
    for textElement in bookmarkElement.iter():
        if 'Text' in str(textElement):  #   Check if it's a <w:t> to get access to the content
            textElement.text = 'BookmarkChange' #   Change the text (With variable or raw string)
            print(textElement.text)
```
