### ISSUE TITLE
pip install on Windows fails

### ISSUE THREAD

**Issue by weegreenblobbie** [python-openxml/python-docx#125]
On Windows 7 64 bit with python 2.7.8 and pip 1.5.6, intall docx via pip: `C:\> pip install docx`

Results in a docx package without a Document class or an api module.

    >>> from docx import Document
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name Document

There is also no version information:

    >>> import docx
    >>> print docx.__version__
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute '__version__'

Expected to run the demo on the documentation page but it fails.

**Comment by weegreenblobbie** [comment]
Looks like PyPI has 0.2.4!  Too old!

**Comment by scanny** [comment]
Installation is covered in the documentation here:
http://python-docx.readthedocs.org/en/latest/user/install.html

The package name is 'python-docx', not 'docx'.

'docx' is the legacy package, a now-distant predecessor.
