### ISSUE TITLE
how to extract two level of bullet points from the docs 

### ISSUE THREAD

**Issue by sharmakrishn** [python-openxml/python-docx#1254]
I want to extract two level of bullet points like

- here something
        - here something 
        
     then i need to extract them exactly and save in other file.

**Comment by scanny** [comment]
@sharmakrishn support questions like this are likely to get more attention on StackOverflow. Make sure you use the `python-docx` tag on your question.

**Comment by sharmakrishn** [comment]
ok, I will ask the same on stackOverFlow

**Comment by sharmakrishn** [comment]
https://stackoverflow.com/questions/77226712/how-to-extract-bullet-points-from-the-docs-using-python

here the link where I have asked the same problem
