### ISSUE TITLE
how to extract and deal with toggle field code

### ISSUE THREAD

**Issue by 1krishnasharma** [python-openxml/python-docx#1255]
I have so many toggle field code in the docs and i want to extract them and then modify them using python only. how can i do it with python-docx https://stackoverflow.com/questions/77243481/how-to-extract-and-add-toggle-field-code-from-the-docs-using-python

**Comment by sharmakrishn** [comment]
@scanny  Please provide some directions do extract toggle field code.

**Comment by scanny** [comment]
@sharmakrishn Google is your friend, ChatGPT too maybe. Here's one search result from Googling `python-docx field codes`
https://stackoverflow.com/questions/58479000/how-to-update-fields-in-ms-word-with-python-docx

**Comment by sharmakrishn** [comment]
yeah I also found that I thought there is some more easy way to do it may be so ask here. Anyway thank you @scanny
