### ISSUE TITLE
0.7.6 demo fails

### ISSUE THREAD

**Issue by weegreenblobbie** [python-openxml/python-docx#126]
I downloaded and install python-docx-0.7.6 on Windows 7 64-bit, and I tried to run the demo but it encounters an error:

    >>> for item in recordset:
    ...     row_cells = table.add_row().cells
    ...     row_cells[0].text = str(item.qty)
    ...     row_cells[1].text = str(item.id)
    ...     row_cells[2].text = item.desc
    ...
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    NameError: name 'recordset' is not defined

I expected the demo to work.

**Comment by scanny** [comment]
Hi @weegreenblobbie, please post questions like this on the mailing list at python-docx@googlegroups.com. We reserve the issues list here for feature requests and for the occasional bug report.
