### ISSUE TITLE
Regarding errors when writing tables in word

### ISSUE THREAD

**Issue by BigFish3710** [python-openxml/python-docx#1263]
When dictionary data is written into a table in Word, data in the dictionary is missing. Dictionary data is written starting from the first column of the fourth row of the table in word. If there are merged cells in the first to third rows of the table in Word, data in a certain column will be missing in the final generated Word file.

**Comment by scanny** [comment]
Need more to go on. What kind of dictionary data? like `Dict[str, Any]` or some non-Python kind of dictionary?

Show minimally reproducible code.
