### ISSUE TITLE
HTML in word

### ISSUE THREAD

**Issue by SystemError7** [python-openxml/python-docx#1266]
In ```Microsoft Word``` I saw an option to add a html to the document, or to open a ```.html``` using Word, I know that the style, distribution or the format will change. Is there a way to open or add a ```.html``` using ```python-docx``` or there´s a possible to be a feature in a future to do that?
To be more accurate, there's an option by ```Insert``` --> ```Text``` --> ```Object``` --> ```Insert text from a file```
Thanks.

**Comment by scanny** [comment]
Sorry, no, you'd have to parse the HTML yourself and insert it how you see fit :)
