### ISSUE TITLE
Font Theme 

### ISSUE THREAD

**Issue by kill390** [python-openxml/python-docx#1267]
Reopened again
Hi

So I am facing really annoying problem with trying to read the font name of the paragraph.

First when choosing a normal font "Times New Roman" everything seems to work correctly.

Second, the problem occurs when trying to choose a Font that has a theme for example "Times New Roman (Headings)" or (Body)
it returns every time None 
I am checking the runs
I am also checking the inheritance of styles but also Nothing

what I am trying to do is to check a document for a specific style one of these things is checking the font name

please don't close the issue until I am done Thank you

```python
def __check_inherited_style(self, style, key: str, value):
    """
    Check if the style is inherited from the base style Recursively and return the value of the key
    """
    if style is None:
        return None

    result = getattr(style.font, key)
    if key == "color" and result is not None:
        result = result.rgb

    if result is None:
        return self.__check_inherited_style(style.base_style, key, value)

    return result

def __check_font(
    self,
    expected_font: dict,
    run: docx.text.run.Run,
    paragraph: docx.text.paragraph.Paragraph,
):
    """Check the font of the run with the expected font"""
    if run.font is None:
        return

    for key, value in expected_font.items():
        result = getattr(run.font, key)

        if key == "color":
            result = result.rgb

        if result is None:
            inherit = self.__check_inherited_style(paragraph.style, key, value)
            if inherit is None:
                inherit = False

            if inherit != value:
                self.errors.append(
                    f"Expected font to be '{key}' of value '{value}' but found '{inherit}' "
                    f"in '{paragraph.text}'")

        elif result != value:
            self.errors.append(
                f"Expected font to be '{key}' of value '{value}' but found '{result}' "
                f"in '{paragraph.text}'")`
```

**Comment by scanny** [comment]
A couple things. Character formatting is governed by character-styles, not paragraph-styles directly. A paragraph-style can have an associated character-style and those can also be inherited (have a base-style) so you probably want to check that way.

Also, I would definitely have a look directly at the XML and see if I could figure out how Word was implementing those "special" styles. You could look at the document.xml to see what the style reference was and then the styles.xml to see where those attributes are actually defined.

Once you know how it's implemented and what these UI indications actually mean then the implementation should be clear.

**Comment by kill390** [comment]
[testcover.zip](https://github.com/python-openxml/python-docx/files/12919665/testcover.zip)

**Comment by kill390** [comment]
I hope you actually make a notice for other people 
Thank you sm for your help.
