### ISSUE TITLE
Drawing shapes with python-docx

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [python-openxml/python-docx#1269]
Seems I'm in need to draw shape (Rectangle, Triangle, Circle) and fill with specified color with python on a .docx file but seems I can't find any way to do so! I also need to detect a shape and fill that with a color! Is it possible to do so?

Thanks in advance!

**Comment by scanny** [comment]
There's no support for this in `python-docx` at present. These go into a `<w:drawing>` element which would be a child of a run (`w:r`) element. You can get access to these something like this:

```python
from docx.drawing import Drawing

for item in run.iter_inner_content():
    if isinstance(item, Drawing):
        print(item._element.xml)
```

Using this you could inspect the XML of such a drawing you made manually in Word and get an idea what kind of XML would need to be added and where.

**Comment by Sayad-Uddin-Tahsin** [comment]
Hey @scanny,
Can you tell me is there any way you know to revert XML to docx? I was thinking to get the `xml -> edit -> docx`. is it possible? If yes, is there any way to get the full docx XML from `python-docx`?

**Comment by scanny** [comment]
I'm not getting what you're asking. Are you saying edit the XML inside a docx directly? You can do that with `opc-diag` here: https://opc-diag.readthedocs.io/en/latest/

I think you'll need to install that from the develop branch on GitHub: https://github.com/python-openxml/opc-diag/tree/develop

Basically it lets you extract the XML from the docx to a directory (like unzip the docx file), edit the XML, then repackage it back into a .docx file. https://opc-diag.readthedocs.io/en/latest/quickstart.html#use-case-4-extract-a-package-to-a-directory

Is that what you're talking about?

Any tool that lets you edit the contents of a zip archive should do the trick. I use Neovim for that almost every day these days.
