### ISSUE TITLE
no "rPr" node under "paragraph._p.pPr" node

### ISSUE THREAD

**Issue by ghmole** [python-openxml/python-docx#1274]
some styles as "w:asciiTheme" and "w:hAnsiTheme" under this node, so can't modify document with these styles, make the final doc seem strange.

**Comment by scanny** [comment]
Sorry, I don't understand what the problem is. You'll need to say more. Feel free to re-open if you're willing to elaborate your question with context and a specific example.

**Comment by ghmole** [comment]
if a paragraph is auto numbering, a subnode '<numPr>' will create under the node  '<pPr>', also another subnode '<rPr>' will create to save the auto numbering's font/size and other attributes, so if the '<pPr>' node haven't this subnode, you can't modify the auto numbering's attributes, make the document seem very strange.
