### ISSUE TITLE
WD_ORIENTATION import Error

### ISSUE THREAD

**Issue by SystemError7** [python-openxml/python-docx#1276]
I´m trying to change the orientation of the pages of the document, so I saw the official document from the ```python-docx 1.0.1``` and I found this: ```section.orientation = WD_ORIENT.LANDSCAPE```, but when I import that it raised the following error:
```ImportError: cannot import name 'WD_ORIENTATION' from 'docx.section'```.
The code is the following:
```
    from docx.section import WD_ORIENTATION

    Word = Document()
    section = Word.sections[-1]
    print(section.orientation, "\n", section.page_height, "\n", section.page_width)

    if pageFormat in ["A4", "Vertical"]:
        section.page_height = Mm(210)
        section.page_width = Mm(297)

    elif pageFormat == "Horizontal":
        section.orientation = WD_ORIENTATION.LANDSCAPE
        section.page_height = Mm(297)
        section.page_width = Mm(210)

    print(section.orientation, "\n", section.page_height, "\n", section.page_width)

```

**Comment by SystemError7** [comment]
UPDATE:
The error was that I import wrong the ```WD_ORIENTATION```.
But still don't aply the orientation ```LANDSCAPE``` or Horizontal.

**Comment by scanny** [comment]
What orientation did you end up importing?
What is the output from the print statements when you run this?

**Comment by SystemError7** [comment]
Well, I found out that the proper module is ``` from docx.enum.section import WD_ORIENT``` instead of ```from docx.enum.section import WD_ORIENTATION```, but it could be confusing for the people that there are 2 modules with a similar name, and I don't know the difference, if you could explain me the difference between them, I will apreciate it.
Thanks in advance
