### ISSUE TITLE
How to get raw byte data from a Document object without saving it?

### ISSUE THREAD

**Issue by akashjainCT** [python-openxml/python-docx#1278]
I have a requirement where I need to pass `"mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"` content in a request. I want to avoid writing the data to a file and then reading it back again using `document_content = open(file_path, "rb").read()`. Is there a way to directly get this content  from Document object?

**Comment by scanny** [comment]
Write to an `io.BytesIO` object then use `.getvalue()` to directly get the bytes.

```python
import io

out = io.BytesIO()
document.save(out)
doc_bytes = out.getvalue()
```

**Comment by akashjainCT** [comment]
Thanks!
