### ISSUE TITLE
Align floating elements

### ISSUE THREAD

**Issue by SystemError7** [python-openxml/python-docx#1279]
Hi,
I used the following script that the user @dothinking in the following issue of ```pdf2docx```:
https://github.com/dothinking/pdf2docx/issues/54
to create a floating image, then I tried to do a center align to the image but it didn't work, so I want to know if it's possible to align a floating ```Office Word``` element, I suppose it's like a drawing.

**Comment by dothinking** [comment]
Floating image means you can put it where you want to, so you're not able to align it center like a normal flowing element. Instead, you can calculate the position (x,y coordinates of top-left corner) where it's center aligned, then set it directly when creating the floating image.
