### ISSUE TITLE
Bug: text always underlined in Wordpad

### ISSUE THREAD

**Issue by Keredu** [python-openxml/python-docx#1282]
**System Info**
python-docx==1.0.1

**Problem**
I copied an example from the official documentation and added the option to toggle the font underline:

```
document = Document()

p = document.add_paragraph('A plain paragraph')
p.add_run('bold').bold = True
p.add_run(' and some ')
p.add_run('italic.').italic = True
p.add_run(' underline.').underline = True
document.save('hello.docx')
```
When I open it with WordPad, switching the bold and italic attributes to True or False produces the expected result. However, whether I set underline to True or False, the text always appears underlined.

**How can it be solved?**

add_run('my_text').underline = True should make 'my_text' appear underlined, while add_run('my_text').underline = False should leave 'my_text' not underlined.

**Comment by scanny** [comment]
Try setting `run.underline` to `None`. It's possible that WordPad is misinterpreting the spec and showing underline whenever the `<w:i>` element appears, even if its value is False.
```python
run = p.add_run('underline') = True
run.underline = None
```
