### ISSUE TITLE
Relating Tables to their Paragraphs

### ISSUE THREAD

**Issue by aanastasiou** [python-openxml/python-docx#1283]
Is it possible to get any indication of which paragraph a table appears in?

At the moment, we have `.paragraphs`, `.tables` at the level of `Document` and `.part` at the level of each element. However, I have not worked out how I could infer the "order" by which elements appear in a document.

Within `docx`, elements appear one after the other. I was wondering if there was a way to get all block elements in the order they appear in the document (?).

The specific problem I am dealing with is documents where information appears sometimes within a table within a paragraph or the paragraph's plain text.

**Comment by scanny** [comment]
There is a recent addition to the API you can use for that:

```python
for section in document.sections:
    for item in section.iter_inner_content():
        if isinstance(item, Paragraph):
            # -- do paragraph thing ... --
        elif isinstance(item, Table):
            # -- do table thing ... --
```

This will produce sections, paragraphs, and tables in document order.

The only time this won't work is if the document has no sections, but I've only see that occur in Microsoft Teams chat-transcripts exported to .docx format. As far as I've ever seen, Word-produced documents _always_ have one section by default and more if the author adds them.

That said, it's on the docket to add `BlockItemContainer.iter_inner_content()` which will work in the no-sections case which also includes table cells, headers, and footers.

**Comment by scanny** [comment]
Btw, a table cannot appear in a paragraph; did you mean "which table a paragraph appears in"?.
> Is it possible to get any indication of which paragraph a table appears in?

**Comment by aanastasiou** [comment]
Thank you very much @scanny , that is exactly what I was looking for.

To your question: 

The document I am interested in parsing has "normal text" (organised in paragraphs) interdispersed with tables (and of course, the content of tables is itself organised in paragraphs and runs). Just going by `.paragraphs`, I was missing half the content that was under a given paragraph but stored in a table. And going by tables only, I would be missing the rest.

But the inner content iterator on the section seems to work exactly as I would expect it to.

Thanks for your resposne, and python-docx.
