### ISSUE TITLE
Text around image

### ISSUE THREAD

**Issue by wedersonrsouza** [python-openxml/python-docx#1284]
How to insert an image on the right side of a text without using a table? And that the text surrounds the image?

Example:
![image](https://github.com/python-openxml/python-docx/assets/22062123/2f753f06-d35b-4afd-9d74-555a6859c5a8)

**Comment by scanny** [comment]
This is sometimes called a "floating image", one that is freely positionable as opposed to "inline" with the text.

`python-docx` doesn't have this functionality yet but if you do a search on "python-docx floating image" I expect you'll find some prior efforts of getting this to work. Here's another issue that makes some progress on that: https://github.com/python-openxml/python-docx/issues/1188
