### ISSUE TITLE
auto numbering paragraph need a rPr node to adjust font/size

### ISSUE THREAD

**Issue by ghmole** [python-openxml/python-docx#1286]
if a paragraph is auto numbering, a subnode '<w:numPr>' will be create under the node '<w:pPr>', also another subnode '<w:rPr>' need be create to save the auto numbering's font/size, so if the '<w:pPr>' node haven't this subnode, you can't modify the auto numbering's font attributes, the different font size will display on same line.

**Comment by scanny** [comment]
A `w:pPr` element is added to a `w:p` element when necessary to add settings, in particular `.alignment`, and `.style`. This is done using `CT_P.get_or_add_pPr() -> CT_PPr`. It always returns the `w:pPr` element, adding it only when necessary. You can use it like this:
```python
pPr = paragraph._p.get_or_add_pPr()
```
