### ISSUE TITLE
`CT_PPr.get_or_add_rPr()` 

### ISSUE THREAD

**Issue by ghmole** [python-openxml/python-docx#1289]
But a "w:rPr" is existed under node "w:pPr", it is automatically created when the paragraph is autonumbering, with the node "w:numPr" at same time. how can I access it to modify the font attribute?
=============================================
        
      Okay, so what you want is `CT_PPr.get_or_add_rPr()` which _could_ be there (`w:pPr` can have a `w:rPr` child) but unfortunately is not. So you would need to add it if you want it. The procedure would be something like:
```python
from docx.oxml import OxmlElement
rPr = OxmlElement("w:rPr")
pPr.append(rPr)
```

_Originally posted by @scanny in https://github.com/python-openxml/python-docx/issues/1288#issuecomment-1795856369_

**Comment by scanny** [comment]
@ghmole Please do not open a new issue to continue an existing conversation. If you have something more to ask or say just do it in the existing conversation.

**Comment by ghmole** [comment]
Sorry, I have comment in an old conversation, but no reply.
By the way, How to solve this issue?

**Comment by scanny** [comment]
This question is answered in #1288
