### ISSUE TITLE
Checking for particular style using python-docx

### ISSUE THREAD

**Issue by strvijay** [python-openxml/python-docx#129]
# Import the module
from docx import *

# Open the .docx file
document = Document('ABC.docx')

for paragraph in document.paragraphs:
    for run in paragraph.runs:
        if run.style == 'Strong':
            print run.text

This is the code I am using to open a docx file and to check if there is Bold text but I am not getting any result. If I remove the if statement , the entire file is printed without any formatting / styles. Can you please let me know how to identify text in particular style like Bold or Italics using python-docx ?
Thank you

**Comment by scanny** [comment]
I answered this one that you posted on StackOverflow:
http://stackoverflow.com/a/27910938/1902513

Please upvote and accept it there if it answers your question. Otherwise elaborate your question if you need more.

----

Although bold and the character style Strong appear the same when rendered, they use two different mechanisms. The first applies bold directly and the second applies a character style that can include any number of font characteristics.

To identify all occurrences of text that appears in bold, you may need to do both.

But to just find the text having bold applied you would do something like this:

```python
for paragraph in document.paragraphs:
    for run in paragraph.runs:
        if run.bold:
            print run.text
```

Note there are ways this can miss text that appears bold, like text that appears in a paragraph whose font formatting is bold for the entire paragraph (Heading1 for example). But I think this is the property you were looking for.

**Comment by Ankit-Vohra** [comment]
@scanny It would be helpful if you could suggest a way through which I can identify Headings as well. Currently, I have written a script to identify bold, italics, and other styles, but my code misses on few bold texts which are generally headings. Can you please suggest how to identify bold text and headings both with a small sample code and a docx file.

Thanks in advance

**Comment by me-suzy** [comment]
```
import os
import docx

def run_get_style(run) -> str:
    if run.bold and run.italic:
        return "bold-italic"
    elif run.bold:
        return "bold"
    elif run.italic:
        return "italic"
    else:
        return "normal"

def convert_docx_to_html_style(para):
    result = ""
    if para.runs:
        html_para = '<p>'
        current_style = None
        current_text = ""

        for run in para.runs:
            run_style = run_get_style(run)
            if run_style == current_style:
                current_text += run.text
            else:
                if current_style:
                    if "bold" in current_style:
                        html_para += '<b>'
                    if "italic" in current_style:
                        html_para += '<em>'
                    html_para += current_text
                    if "italic" in current_style:
                        html_para += '</em>'
                    if "bold" in current_style:
                        html_para += '</b>'
                current_style = run_style
                current_text = run.text

        if current_style:
            if "bold" in current_style:
                html_para += '<b>'
            if "italic" in current_style:
                html_para += '<em>'
            html_para += current_text
            if "italic" in current_style:
                html_para += '</em>'
            if "bold" in current_style:
                html_para += '</b>'

        html_para += '</p>\n'
        result += html_para
    return result

# Citirea documentului DOCX
document = docx.Document("bebe.docx")

# Deschiderea fișierului HTML pentru scriere
with open("bebe.html", "w", encoding="utf-8") as html_file:
    # Scrierea începutului fișierului HTML
    html_file.write("<html>\n<head>\n<title>Document</title>\n</head>\n<body>\n")

    # Parcurgerea și conversia fiecărui paragraf în HTML
    for paragraph in document.paragraphs:
        converted_paragraph = convert_docx_to_html_style(paragraph)
        # Scrierea paragrafului convertit în fișierul HTML
        html_file.write(converted_paragraph)

    # Scrierea sfârșitului fișierului HTML
    html_file.write("</body>\n</html>")

print("Conținutul din bebe.docx a fost salvat în bebe.html.")

```
