### ISSUE TITLE
Part of the text in bold

### ISSUE THREAD

**Issue by wedersonrsouza** [python-openxml/python-docx#1290]
How to make some parts of the text bold?

Example:
test = 'This is the text I would like <b>THIS SECTION</b> to be in bold.'

doc.add_paragraph(test).

**Comment by scanny** [comment]
See this SO answer: https://stackoverflow.com/a/68507579/1902513

**Comment by wedersonrsouza** [comment]
I don't understand how this function can help me in my specific case.

**Comment by scanny** [comment]
Well, in your case, if the text is not already in the document, you can just do this:
```python
para = doc.add_paragraph()
para.add_run("This is the text I would like ")
para.add_run("THIS SECTION").bold = True
para.add_run(" to be in bold.")
```

An example like this is in the quickstart example in the docs here: https://python-docx.readthedocs.io/en/latest/
