### ISSUE TITLE
Type hint error

### ISSUE THREAD

**Issue by anci3ntr0ck** [python-openxml/python-docx#1291]
The type hint of `_Row.cells()` is wrong.
![image](https://github.com/python-openxml/python-docx/assets/55662947/0b8c21b6-22bb-49bf-bb98-3ab1c867aa66)
`Tuple[_Cell]` means there is only one `_Cell` object in tuple, so when I try to get the 2nd, 3rd `_Cell` object, Pylance tells me there is a IndexError.
![image](https://github.com/python-openxml/python-docx/assets/55662947/46d748ca-b5a6-4a21-a687-5872083437d4)
Change the type hint to `Tuple[_Cell, ...]` should fix this.

**Comment by scanny** [comment]
Good catch, thanks @anci3ntr0ck that will go in on the next release :)
