### ISSUE TITLE
Must be changed the way the "Python-docx library" creates the structure of the DOCX file

### ISSUE THREAD

**Issue by me-suzy** [python-openxml/python-docx#1292]
The code below is good, it converts well, they open with word, everything is ok. But the problem is that the docx files are not readable when I upload them to google translate documents

https://translate.google.ro/?sl=auto&tl=ro&op=docs

Google gives me the error: **"Can't translate this file right now. Try again in a few minutes."**

I think the text is read and written correctly in terms of UTF-8 encoding. The problem I'm having with Google Translate may not be related to the script itself, but rather to the way the **python-docx library** creates the structure of the DOCX file.

DOCX files are actually ZIP archives that contain a number of XML files and other resources. Google Translate might have problems with some of these internal XML files if they don't conform exactly to what Google Translate expects to find.

Attach docx file, to test it

[Pizarro, Narciso. - Tratado de metodología de las ciencia sociales [1998].docx](https://github.com/python-openxml/python-docx/files/13316693/Pizarro.Narciso.-.Tratado.de.metodologia.de.las.ciencia.sociales.1998.docx)

**The Python code:**

```
import os
from docx import Document

# Funcție pentru citirea textului dintr-un fișier
def read_text_from_file(file_path):
    with open(file_path, encoding='utf8', errors='ignore') as f:
        text = f.read()
        return text

# Funcție pentru scrierea textului într-un fișier
def write_to_file(text, file_path):
    with open(file_path, 'wb') as f:
        f.write(text.encode('utf8', 'ignore'))

# Setează calea către directorul cu fișierele TXT
txt_folder_path = r'D:\2022_12_02'

# Setează calea către directorul în care vor fi salvate fișierele DOCX
docx_folder_path = r'D:\2022_12_02\word 2'

# Creează directorul pentru fișierele DOCX dacă nu există deja
os.makedirs(docx_folder_path, exist_ok=True)

# Parcurge fiecare fișier TXT din director
for filename in os.listdir(txt_folder_path):
    if filename.endswith(".txt"):
        txt_file_path = os.path.join(txt_folder_path, filename)

        # Citeste continutul fisierului TXT
        content = read_text_from_file(txt_file_path)

        # Setează calea pentru fișierul DOCX de salvat
        docx_file_path = os.path.join(docx_folder_path, f"{os.path.splitext(filename)[0]}.docx")

        # Crează un document DOCX și adaugă continutul
        doc = Document()
        doc.add_paragraph(content)

        # Salvează documentul ca fișier DOCX
        doc.save(docx_file_path)

        print(f"Conversie: {txt_file_path} -> {docx_file_path}")

print("Conversiile au fost finalizate.")



```

**Comment by scanny** [comment]
Sorry, no idea why that might be. You kind of lost me at "opens fine in Word", so probably need to ask the Google translate folks or experiment with different modifications to the file to see what works.

Maybe open with Word and save again and then see what changes in the XML.

Feel free to reopen if you're able to narrow it down to a specific behavior.

**Comment by me-suzy** [comment]
That file was convert from txt to docx, with **python-docx** library. 

But the same .txt file I convert it in docx with "Okdo Document Converter Professional", than google can translate it.

So, I don't know where is the bug. Or Google Translate, or python-docx library ? Where is the problem?
