### ISSUE TITLE
How to take an OPENXML XML file and convert it to a DOCX file?

### ISSUE THREAD

**Issue by heiheiheibj** [python-openxml/python-docx#1294]
DOCX file to XML is easy, how can you convert XML to DOCX file. 
does it have to be something like "for element in openxml_root" or is there a more convenient way?
thanks .

**Comment by scanny** [comment]
You'll have to say more about what you're trying to accomplish. A .docx file is already OpenXml. If you're talking about ODT format you should look at LibreOffice.
