### ISSUE TITLE
add_section() overwrites the previous section

### ISSUE THREAD

**Issue by SystemError7** [python-openxml/python-docx#1296]
I want to have 2 sections, the first will have a ```WD_ORIENT.LANDSCAPE```, the second ```WD_ORIENT.PORTRAIT```. I modify the first section before I add the new section, then, I modify the second and when I printed the results have the same values but are different objects:
```
from docx import Document
from docx.oxml import OxmlElement
from docx.shared import Mm
from docx.enum.section import WD_ORIENT, WD_SECTION

word = Document()

firstSection = word.sections[0]
firstSection.page_width, firstSection.page_height = Mm(148), Mm(210)
firstSection.orientation = WD_ORIENT.LANDSCAPE

word.add_section(WD_SECTION.NEW_PAGE)
newSection = word.sections[-1]
newSection.page_width, newSection.page_height = Mm(210), Mm(297)
newSection.orientation = WD_ORIENT.PORTRAIT

```

These are the result from both
```
First section:
<docx.section.Section object at 0x0000024BAEEBC750> PORTRAIT (0) 21.00086111111111 29.70036111111111 3.175 3.175 2.54 2.54

Second section:
<docx.section.Section object at 0x0000024BAEEBC810> PORTRAIT (0) 21.00086111111111 29.70036111111111 3.175 3.175 2.54 2.54
```

This is what I expected:
```
First section:
<docx.section.Section object at 0x0000024BAEEBC750> LANDSCAPE (1) 14.800791666666667 21.00086111111111 3.175 3.175 2.54 2.54

Second section:
<docx.section.Section object at 0x0000024BAEEBC810> PORTRAIT (0) 21.00086111111111 29.70036111111111 3.175 3.175 2.54 2.54
```

**Comment by scanny** [comment]
You left out the print statements, so there's no way to see what happens before and what happens after.

A couple things to keep in mind:

- A `Section` object is a _proxy_ object and is created newly on each access, like `document.sections[0]`.

- What matters is what XML element the proxy object is _pointing to_, which you can determine by comparing the elements of the proxy objects:
```python
def sections_are_the_same_section(section: Section, other_section: Section) -> bool:
    return section._sectPr is other_section._sectPr
```

Also, the way sections work in Word, the default (and last) section is at the end of the document like `/w:document/w:body/w:sectPr`. Any additional sections are _above_ that and a child of a `w:p` element, like `/w:document/w:body/w:p/w:sectPr`. So when you call `add_section()` a new `w:sectPr` is added _above_ the one at the end.

But your `first_section` is still pointing at the one at the end. I think if you do this after all your code above you'll see what you're looking for:
```python
print(sections[0])
print(sections[-1])
```

This gets a "fresh" proxy based on the _new_ positions of those elements after your mutation (`add_section()`). I think you're just using a stale reference and both the `first_section` and `new_section` proxies are pointing to the same element.
