### ISSUE TITLE
Add new section for the following pages after/before content

### ISSUE THREAD

**Issue by SystemError7** [python-openxml/python-docx#1299]
I'm trying to add a new section with ```start_type = WD_SECTION.NEW_PAGE``` to generate a new page with a second section, then, I add a ```html``` to the body of the document with the following code:
```
    package = word.part.package
    partname = package.next_partname('/word/altChunk%d.html')
    AltPart = Part(partname, 'text/html', html.__str__().encode(), package)
    r_id = word.part.relate_to(AltPart, RT.A_F_CHUNK)
    altChunk = OxmlElement('w:altChunk')
    altChunk.set(qn('r:id'), r_id)
    word.element.body.addprevious(altChunk)
```
Expecting that the first page will have the first section, and the other pages will have the second section.

But all the content have the first section and, the last page (in blank) have the second section.
And if I add the section after, it does the same.

The problem is that it doesn't insert the content as tables, paragraphs or images. All the content is in the tag ```<w:altChunk>```. As you can see bellow:
```
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" 
xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 wp14">
  <w:altChunk r:id="rId9"/>
  <w:body>
    <w:p>
      <w:pPr>
        <w:sectPr>
          <w:pgSz w:w="11906" w:h="16838"/>
          <w:pgMar w:top="0" w:right="0" w:bottom="567" w:left="0" w:header="720" w:footer="720" w:gutter="0"/>
          <w:cols w:space="720"/>
          <w:docGrid w:linePitch="360"/>
        </w:sectPr>
      </w:pPr>
    </w:p>
    <w:sectPr w:rsidR="00FC693F" w:rsidRPr="0006063C" w:rsidSect="00034616">
      <w:pgSz w:w="16838" w:h="11906" w:orient="landscape"/>
      <w:pgMar w:top="1134" w:right="0" w:bottom="567" w:left="0" w:header="720" w:footer="720" w:gutter="0"/>
      <w:cols w:space="720"/>
      <w:docGrid w:linePitch="360"/>
    </w:sectPr>
  </w:body>
</w:document>
```

Each ```<w:sectPr>``` represents the sections in the document.
So if I do a ```word.element.body.addnext(altChunk)``` it would have the first page in blank with the first section, and the rest of the pages with the ```html``` content with the second section.

So, how can I do to achieve what I expect??

Thanks in advance.

**Comment by scanny** [comment]
Try `document.paragraphs[0].addnext(altChunk)` then see if you can figure out why that works.

**Comment by SystemError7** [comment]
It raised the following error:
```AttributeError: 'Paragraph' object has no attribute 'addnext'```

I needed ```document.add_paragraph()``` because I didn't have any paragraph.
I'm using ```python-docx v1.1.0```

**Comment by scanny** [comment]
Post the minimal reproducible example and the full stack trace.

**Comment by SystemError7** [comment]
This is the minimal code:
```
def add_html_to_docx(HTMLstring):

    word = Document()
    wordBytes = BytesIO()
    soup = BeautifulSoup(HTMLstring, 'html.parser')

    word.add_section(WD_SECTION.NEW_PAGE)
    insert_HTML_content(word, soup)
    word.save(wordBytes)
    wordBytes.seek(0)

def insert_HTML_content(word, html):

    package = word.part.package
    partname = package.next_partname('/word/altChunk%d.html')
    AltPart = Part(partname, 'text/html', html.__str__().encode(), package)
    r_id = word.part.relate_to(AltPart, RT.A_F_CHUNK)
    altChunk = OxmlElement('w:altChunk')
    altChunk.set(qn('r:id'), r_id)
    word.element.body.addnext(altChunk)
```
And the xml is the first I show

**Comment by scanny** [comment]
Need the full stack trace.

**Comment by SystemError7** [comment]
This is the trace if I insert the ```document.paragraphs[0].addnext(altChunk)```:
```
  File "flask\app.", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "", line 43, in generacionDocumentos
    archivoModificado = Documento64_HTML(StringBase64, formatoSalida, valorJSON_MarcadoresDocumento)
  File "", line 37, in Documento64_HTML
    fileName, StringBase64HTML = add_html_to_docx(html)
  File "", line 105, in html2word
    insert_HTML_content(word, soup)
  File "", line 261, in insert_HTML_content
    word.paragraphs[0].addnext(altChunk)
```

This is the trace if I insert an error after inserting the ```html```:
```
  File "flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "", line 43, in generacionDocumentos
    archivoModificado = Documento64_HTML(StringBase64, formatoSalida, valorJSON_MarcadoresDocumento)
  File "", line 37, in Documento64_HTML
    fileName, StringBase64HTML = add_html_to_docx(html)
  File "", line 123, in html2word
    print(word._element.xml, word.paragraphs[3])
```

If that isn't useful for you or is not enough please tell me, and give an example of what that means, I don't know what 'full stack trace' means, sorry.
Thanks.

**Comment by scanny** [comment]
@SystemError7 Google is your friend on that sort of thing :) https://realpython.com/python-traceback/

But this gives me enough for present purposes, I'll take a look in a minute here ...

**Comment by scanny** [comment]
Okay, so `document.paragraphs[0]` is a `Paragraph` (proxy) object. It is _not_ an `lxml` element. However, `document.paragraphs[0]._p` _is_ an `lxml` element and it's the one for that paragraph.

If you use `document.paragraphs[0]._p.addnext(altChunk)` you won't get this error.

That doesn't mean you won't get a different error however, and if you're going to work at the level of XML elements you probably need to understand more clearly the domain your working in and why these things work (or don't).

For example, you should be familiar with the `lxml.etree._Element` interface, which is where `.addnext()` comes from. https://lxml.de/api/lxml.etree._Element-class.html

**Comment by SystemError7** [comment]
Thanks, I will take a look and see if I can solve it.

**Comment by SystemError7** [comment]
I tried and it didn't raised an error, but it didn't work, I saw in ```MS Word``` that if you add a section with ```WD_SECTION.CONTINUOUS```, the following page will have a different section so it can be modified. Altough, I didn't achieve anything, I will be looking for more info.

**Comment by scanny** [comment]
If you're going to modify the XML directly, I recommend you produce a document that looks the way you want by hand, using Word, then inspect the XML of that document and work out how to use `python-docx` to produce the same XML. Trial and error without some sort of known working end-state like that will be very time-consuming and unproductive unless you happen to get lucky.

**Comment by SystemError7** [comment]
The problem is that when I try to produce the document, it insert like the elements it's self (tables, paragraphs, ....), not as a ```altChunk``` element.
