### ISSUE TITLE
Determine Empty Paragraph Color

### ISSUE THREAD

**Issue by jalius** [python-openxml/python-docx#1304]
I'm trying to iterate over `document.paragraphs` and delete all paragraphs with red text.
For paragraphs with `len(runs) > 0`, I am checking `run[n].font.color.rgb == RGBColor(255, 0, 0)`.
For blank paragraphs with `len(runs) == 0`, I cannot figure out how to determine the color.

![Screenshot 2023-11-21 113200](https://github.com/python-openxml/python-docx/assets/24768951/83be3efc-f486-4be0-950b-0dfd741b270b)

**Comment by scanny** [comment]
Get one of the paragraphs and print out the XML. That should tell the story:
```python
para = document.paragraphs[9]
print(para.xml)
```

I expect it will either be the default run properties, something like `p/pPr/rPr` or a style applied.
