### ISSUE TITLE
No possible way to truly set Table Preferred Width

### ISSUE THREAD

**Issue by stackindachedda** [python-openxml/python-docx#1305]
Currently there is no possible way to set Table Preferred Width despite having this setting available within Word settings menu:  Table -> Table Properties. Requesting addition of a feature to assist with this, since manually setting table width via xml modification (w:TblW modification to fixed width, etc), column width, or cell width, do not actually check this box within Word (although I have gotten to the point of having a greyed out default width that gets enabled when I go into that settings menu and check the box manually for each table).

Current settings only allow for 'soft' fixed width setting, but everything defaults to auto-width and column/cell resizing, even fixed width, once you resize your window to be smaller than the table width. This isn't a 'true' fixed width and Word does have this option available via the table settings menu if you manually check a box. 
 
Requesting that python-docx gets a way to 'check this box' within word settings via some command for the table during initialization of the table in the python script, so that you don't have to manually select each table and enter a menu window to check this box for every table in the final document. 
<img width="490" alt="Screenshot 2023-11-24 at 9 43 11 PM" src="https://github.com/python-openxml/python-docx/assets/97990465/5c4a1003-087f-4dd0-8a4e-a0c2636346a0">
<img width="487" alt="Screenshot 2023-11-24 at 9 41 51 PM" src="https://github.com/python-openxml/python-docx/assets/97990465/314314ad-5d89-44f3-8751-7a4e732120fe">

**Comment by stackindachedda** [comment]
Bump

**Comment by scanny** [comment]
@stackindachedda if you want this feature you're going to need to do your own research to figure out the precise XML behavior that makes this work. There are no active developers here waiting to pick up new feature requests.

I expect you'll find that it's not a single attribute setting on a single element.

You'll want to compare the XML you produce by hand using Word that has this setting to code generated by `python-docx` that doesn't and see if you can narrow it down. A document that contains only a small table, maybe 3x3 columns is where I would start.

Feel free to reopen this if you come up with something :)

**Comment by alexinnex** [comment]
In case someone is interested in developing the feature, here's the XML difference on a 3x3 empty table:
Auto sized (preferred width unticked)
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document>
    <w:body>
        <w:tbl>
            <w:tblPr>
                <w:tblStyle w:val="TableGrid" />
                <w:tblW w:w="0" w:type="auto" />
                <w:tblLook w:val="04A0" w:firstRow="1" w:lastRow="0" w:firstColumn="1"
                    w:lastColumn="0" w:noHBand="0" w:noVBand="1" />
            </w:tblPr>
            <w:tblGrid>
                <w:gridCol w:w="3005" />
                <w:gridCol w:w="3005" />
                <w:gridCol w:w="3006" />
            </w:tblGrid>
            <!-- Table rows etc. - should stay the same-->
            <!-- ... -->
```
Preferred width set to 0.1cm
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document>
    <w:body>
        <w:tbl>
            <w:tblPr>
                <w:tblStyle w:val="TableGrid" />
                <w:tblW w:w="57" w:type="dxa" />
                <w:tblLook w:val="04A0" w:firstRow="1" w:lastRow="0" w:firstColumn="1"
                    w:lastColumn="0" w:noHBand="0" w:noVBand="1" />
            </w:tblPr>
            <w:tblGrid>
                <w:gridCol w:w="222" />
                <w:gridCol w:w="222" />
                <w:gridCol w:w="222" />
            </w:tblGrid>
```
