### ISSUE TITLE
How to add a diagonal Line in the cell(1,A)

### ISSUE THREAD

**Issue by i2w3** [python-openxml/python-docx#1306]
just like the tittle, how to add a diagonal Line in a cell, like this:
![photo](https://cdn-adclh.nitrocdn.com/zciqOWZgDznkuqFpvIJsLUeyHlJtlHxe/assets/images/optimized/rev-8cfa674/trumpexcel.com/wp-content/uploads/2020/12/Dataset-with-cell-that-has-a-diagonal-line.png)
thanks.

**Comment by scanny** [comment]
That looks like an Excel spreadsheet. You'd have to ask wherever you get those from;  `python-docx` can't help you with that.

**Comment by i2w3** [comment]
> That looks like an Excel spreadsheet. You'd have to ask wherever you get those from; `python-docx` can't help you with that.

sorry for the pic, I just want to ask how to add the diagonal line in the table by python-docx. My current method is to read a word with diagonal lines, not generate them entirely with code by python-docx.

**Comment by scanny** [comment]
That feature is not yet implemented in `python-docx`. The general approach would be to figure out what the XML for that looks like and then add it in yourself using a function that manipulates the table XML directly.

If you print out the XML for the first row of that table that's likely to be a good start at discovering how that's done:
```python
print(table.rows[0]._tr.xml
```

**Comment by i2w3** [comment]
> h

thanks for your suggestion, I use [this code](https://stackoverflow.com/questions/33069697/how-to-setup-cell-borders-with-python-docx), to implemented diagonal lines for cell border. Here is my code:
```python
# can find the xml by print(table.cell(row,0)._tc.xml)
set_cell_border(table.cell(row, 0), tl2br={"sz": 4, "val": "single", "space":0})
```
