### ISSUE TITLE
Cells contents not reporting correctly

### ISSUE THREAD

**Issue by enrac5** [python-openxml/python-docx#1311]
[butt.docx](https://github.com/python-openxml/python-docx/files/13621156/butt.docx)

I'm trying to write a parser for a document like the one attached, which uses a table. However, when I try to get the contents of the columns, I'm getting very odd results. This is a snippet of my code:  

```python
from docx import Document

doc_path = '[path to attached]/butt.docx'
wordDoc = Document(doc_path)
for table in wordDoc.tables:
    for row in table.rows:
        print("0 is {} and 1 is {}".format(row.cells[0].text, row.cells[1].text))
```

The output is:  

```
0 is Shot and 1 is Footage / Timecode
0 is 1 and 1 is 1
0 is 2 and 1 is 2
0 is 3 and 1 is 3
```

Which is incorrect. Is this something with the document? I've tried copying and pasting the doc's contents and get the same results. Is there some API call I'm missing?

**Comment by enrac5** [comment]
err, the formatting isn't what I expected, but I hope the issue is obvious.

**Comment by scanny** [comment]
I think you'll find that there are more cells in the table that you expect and that the first two columns of the data area are merged. All "layout" cells that are part of a merged cells report the same content.

Maybe try:
```python
for row_idx, row in enumerate(table.rows):
    for col_idx, cell in enumerate(row.cells):
        print(f"cell ({row_idx), {col_idx}): {repr(cell.text)}")
```
and see what that exhaustive listing of cell contents tells you about the structure of the table.

This section of an analysis page of the documentation explains more about what's happening with merged cells.

**Comment by enrac5** [comment]
> I think you'll find that there are more cells in the table that you expect and that the first two columns of the data area are merged. All "layout" cells that are part of a merged cells report the same content.
> 
> Maybe try:
> 
> ```python
> for row_idx, row in enumerate(table.rows):
>     for col_idx, cell in enumerate(row.cells):
>         print(f"cell ({row_idx), {col_idx}): {repr(cell.text)}")
> ```
> 
> and see what that exhaustive listing of cell contents tells you about the structure of the table.
> 
> This section of an analysis page of the documentation explains more about what's happening with merged cells.

Hi, thank you for your response. I didn't see a link in your mention of the analysis page. I wonder if it makes sense to pick the later occurrences of the columns instead of the first one.

**Comment by scanny** [comment]
Oph, apologies, neglected to paste that in:
https://python-docx.readthedocs.io/en/latest/dev/analysis/features/table/cell-merge.html#accessing-a-merged-cell

**Comment by scanny** [comment]
This might also be of interest, to iterate (horizontally) merged cells exactly once.
https://stackoverflow.com/a/48105910/1902513

**Comment by enrac5** [comment]
> This might also be of interest, to iterate (horizontally) merged cells exactly once. https://stackoverflow.com/a/48105910/1902513

Ah thank you, I think this could help actually. I need to get the right indices for the column headers that you see in the example doc.

**Comment by scanny** [comment]
What did the exhaustive iteration of table cells reveal? How many actual columns and rows are there?

You can find more about why this can happen in Word by searching on "python-docx misaligned duplicate cells" in Google.

**Comment by enrac5** [comment]
> ```python
> for row_idx, row in enumerate(table.rows):
>     for col_idx, cell in enumerate(row.cells):
>         print(f"cell ({row_idx), {col_idx}): {repr(cell.text)}")
> ```

This is my output for the first row at least:  

cell (0, 0): 'Shot'
cell (0, 1): 'Footage [/](https://file+.vscode-resource.vscode-cdn.net/)\nTimecode'
cell (0, 2): 'Footage [/](https://file+.vscode-resource.vscode-cdn.net/)\nTimecode'
cell (0, 3): 'Shot Description/Dialogue'
cell (0, 4): 'Shot Description/Dialogue'
cell (0, 5): 'Title'
cell (0, 6): 'Start'
cell (0, 7): 'End'
cell (0, 8): 'End'
cell (0, 9): 'Dur.'
cell (0, 10): 'Subtitle/Spotting'

**Comment by enrac5** [comment]
So it looks like multiple duplicated columns

**Comment by scanny** [comment]
Yeah. If the second ("Footage ...") or third ("Shot Desc ...") "visual" column includes a row where that cell is split, that will do this. Also could be a slight misalignment of cells you can detect via inspection in Word.
