### ISSUE TITLE
Why is Document() not a constructor?

### ISSUE THREAD

**Issue by TERNION-1121** [python-openxml/python-docx#1318]
Why is that `Document()` is a function but not constructor that instantiates an object?

![image](https://github.com/python-openxml/python-docx/assets/97667653/a73d58da-019b-468a-b907-756c8d7bbe65)

**Comment by scanny** [comment]
Seemed like the right idea at the time, which was about ten years ago. That was before typing came to Python. If I had it to do over again I suppose I'd work out a way to make it work directly on the class, perhaps using an alternate constructor like `Document.open()`. But that is the most fundamental part of the interface so too late to change it now :)
