### ISSUE TITLE
Search an entire document with tables?

### ISSUE THREAD

**Issue by enrac5** [python-openxml/python-docx#1329]
Hi there, I need to search through a docx file with multiple tables for a string, but additionally, I also need the formatting from it. I saw [this](https://stackoverflow.com/questions/116139/how-can-i-search-a-word-in-a-word-2007-docx-file) on stackoverflow, however, I can't seem to get the `search` function to work (python doesn't find it). How should I be searching the word doc, and how can I get the formatting information? Thanks in advance.

**Comment by scanny** [comment]
That SO post is very old and refers to a prior `docx` module, not `python-docx`, so that's unlikely to be much help.

[This one](https://stackoverflow.com/questions/24805671/how-to-use-python-docx-to-replace-text-in-a-word-document-and-save) is probably a better place to start.

**Comment by enrac5** [comment]
Okay, thank you. From a quick look (and implementing my own search), I can see why people can't stand Word....
