### ISSUE TITLE
Exceptions when working with own document

### ISSUE THREAD

**Issue by me21** [python-openxml/python-docx#1333]
I saved an empty docx file in my Microsoft Word. When I open it with python-docx and try to add a heading, I get `KeyError: "no style with name 'Heading 1'"`. My code looks like `document.add_heading('Visitor Information', level=1)`.

If I open that empty document, add a heading of the 1st level, then delete it again, and save the document, the code works.

**Comment by scanny** [comment]
Yep, definitely. Try listing out the style names and picking one of those, something like:
```python
for style in document.styles:
    print(style.name)
```

You might want to narrow it down to paragraph styles. You can also probably use the name the way it shows up in the version of Word you used to create the document if that's faster.

**Comment by me21** [comment]
Your code snippet returned:
```
Normal
Default Paragraph Font
Normal Table
No List
```

If I add `document.styles.add_style('Heading 1', docx.enum.style.WD_STYLE_TYPE.PARAGRAPH, builtin=True)`, the error is gone.

But another similar error remains when I use `list_number` from `haggis` package to add a numbered list to the Word document. The error thrown is

```
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\haggis\files\docx.py", line 578, in list_number
    numbering = doc.part.numbering_part.numbering_definitions._numbering
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\docx\shared.py", line 242, in __get__
    value = self._fget(obj)
            ^^^^^^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\docx\parts\document.py", line 99, in numbering_part
    numbering_part = NumberingPart.new()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azarubkin\Documents\Python Projects\edoc2\venv\Lib\site-packages\docx\parts\numbering.py", line 15, in new
    raise NotImplementedError
```
