### ISSUE TITLE
How to order hyperlink and run in a block

### ISSUE THREAD

**Issue by Flordjam** [python-openxml/python-docx#1340]
Hello evrybody :), 

I have a link to a paragraph in one of the sentences in my docx: "You can click on the _paragraph_ if you want". I use the following function to parse my document:

`for block in iter_block_items(document):`

`def iter_block_items(parent):`

    `if` isinstance(parent, _Document):
        parent_elm = parent.element.body
    elif isinstance(parent, _Cell):
        parent_elm = parent._tc
    else:
        raise ValueError("something's not right")
    for child in parent_elm.iterchildren():
        if isinstance(child, CT_P):
                yield Paragraph(child, parent)
        elif isinstance(child, CT_Tbl):
            yield Table(child, parent)`

But when I receive the block with the line "You can click on the _paragraph_ if you want"

On the Runs I have two run "You can click" on the" and "if you want"
And on Hyperlinks I have one Hyperlink "paragraph"

To transform this in HTML I want to reconstitue the sentence in the good order, but I can't find out the way to do it.
Could you please give me an hand if you can?

Thank you. ;)

**Comment by scanny** [comment]
Use the new `.iter_inner_content()` method on `Paragraph`: https://github.com/python-openxml/python-docx/blob/master/src/docx/text/paragraph.py#L98
This will give you `Run` and `Hyperlink` objects in whatever order they appear in the paragraph.
