### ISSUE TITLE
feature: index entries

### ISSUE THREAD

**Issue by wfb** [python-openxml/python-docx#137]
I am creating a large (200+ pages) document using python-docx, and I need to create an index of all names in the document. I understand that Word marks index entries a using special XE (Index Entry) field that includes the marked main entry, e.g. { XE indexed-name }. Is it possible to do this using python-docx? I would be happy to create the actual index manually at the end, as long as the index entries are generated automatically.

**Comment by scanny** [comment]
Hi Walter, not presently unfortunately. This is part of the fields capability if I'm not mistaken and hasn't been implemented yet. I'll leave this issue open as a feature request for it.

**Comment by wfb** [comment]
With Steve's excellent help, I got it all working. Here is the relevant piece of code for marking index entries:

from docx.oxml import OxmlElement
from docx.oxml.ns import qn
...

def MarkIndexEntry(entry,paragraph):
    run = paragraph.add_run()
    r = run._r
    fldChar = OxmlElement('w:fldChar')
    fldChar.set(qn('w:fldCharType'), 'begin')
    r.append(fldChar)
    run = paragraph.add_run()
    r = run._r
    instrText = OxmlElement('w:instrText')
    instrText.set(qn('xml:space'), 'preserve')
    instrText.text = ' XE "%s" '%(entry)
    r.append(instrText)
    run = paragraph.add_run()
    r = run._r
    fldChar = OxmlElement('w:fldChar')
    fldChar.set(qn('w:fldCharType'), 'end')
    r.append(fldChar)

Thank you so much, Steve!
Walter

**Comment by scanny** [comment]
Glad to hear you got it working Walter :)

**Comment by hannesharms** [comment]
Would be great if you could explain how to use the function for images or tables  for a newbie.
The folllong has no effect on my document:

```python
document.add_picture('test.png', width=Inches(5.25))
paragraph = document.paragraphs[-1]
MarkIndexEntry("Test Caption",paragraph)
```

**Comment by scanny** [comment]
@hannesharms Please use the mailing list for support questions:
https://groups.google.com/forum/#!forum/python-docx.

**Comment by mlateb** [comment]
Thank you so much for sharing the code @wfb

**Comment by TerryDSydney** [comment]
I copied your code into my python program and it worked first time. Thanks very much, @wfb

**Comment by 42scientific** [comment]
This discussion is very valuable, thank you!
i am wondering, how to refer in the document back to the figure that was referenced by the method described above. So, if you define

Figure 1: <some figure caption>,

how can you refer back to this figure in the text, such as

"Figure 1 states that..."?
