### ISSUE TITLE
How to serialize a CT_Tbl object?

### ISSUE THREAD

**Issue by wennycooper** [python-openxml/python-docx#1379]
I would like to serialize a CT_Tbl object using pickle in python. But I got:

== code ==
    import pickle
    pickle.dumps(tbl)
    =>
    TypeError: cannot pickle 'CT_Tbl' object

====
Any suggestion will be appreciated. Thanks!

**Comment by wennycooper** [comment]
Would you please give us more hints?
Say, is there any serialization method applicable to _Element? 
Can we use pickle to do that?

**Comment by scanny** [comment]
Say more about what you're doing that requires you to serialize a table.

**Comment by lowellknight1114** [comment]
We want to read a table from a source doc and copy it to a destination doc by retrieving the XML string from table._tbl.xml
```
doc = DocumentDocx(filename)
table = doc.tables[0]
xml_string = table._tbl.xml

## save xml_string to a file
```

```
## read xml_string from a file
#??? how to implement a CT_Tbl object using an XML string.
#add_tbl: CT_Tbl = ???

doc_new = DocumentDocx()
paragrap = doc_new.add_paragraph()
paragrap._p.addnext(add_tbl)
```
We can't figure out how to convert XML to a CT_Tbl object as we do with etree.fromstring(xml_table). Can you help us with this?

**Comment by scanny** [comment]
I think what you're looking for is `docx.oxml.parser.parse_xml(xml: str | bytes) -> BaseOxmlElement`.

**Comment by lowellknight1114** [comment]
Yes, this is what we need, Thanks.
