### ISSUE TITLE
support more keys in nsmap.

### ISSUE THREAD

**Issue by flyingpang** [python-openxml/python-docx#1382]
<img width="755" alt="image" src="https://github.com/python-openxml/python-docx/assets/8081542/02c823a5-8038-4fa8-8258-bbbcd06da3ea">

When I used package to parse textbox in docx file, I found a namespace problem, so I had to redefine all elements that used xpath function (because xpath function couldn't support the incoming nsmap parameter). Could you support more key values for nsmaps or support xpath nsmap parameters.

**Comment by scanny** [comment]
@flyingpang `docx.oxml.ns.nsmap` is a `dict`. So just add the values you need before you call the parser or xpath.

If there are specific ones you find yourself needing let us know and we can add them.
