### ISSUE TITLE
DocumentPart' object has no attribute '_rels'.

### ISSUE THREAD

**Issue by theodore86** [python-openxml/python-docx#1384]
It seems like [python-docx](https://github.com/python-openxml/python-docx/releases/tag/v1.1.1) has released an new version:

```console
python-docx==1.1.1
docxtpl==0.16.8
```

```python
uri = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/header'
    def get_headers_footers(self, uri):
>       for relKey, val in self.docx._part._rels.items():
E       AttributeError: 'DocumentPart' object has no attribute '_rels'. Did you mean: 'rels'?
```

**Comment by scanny** [comment]
v1.1.2 released this morning includes an accommodation for this, although it should be fixed upstream to use `DocumentPart.rels` rather than `._rels` (which was an implementation detail that changed.
