### ISSUE TITLE
track-changes in python-docx

### ISSUE THREAD

**Issue by Dinesh728439** [python-openxml/python-docx#1388]
I am having the docx filename[simple.docx]
I have make some changes through python-docx and save to another filename[newSimple.docx]

Here I need to track the changes from simple.docx to newSimple.docx
How to tackle this with the python-docx

**Comment by scanny** [comment]
Describe the behavior you're looking for more specifically.

**Comment by Dinesh728439** [comment]
### simple.docx
![simple.docx](https://github.com/python-openxml/python-docx/assets/148439007/42ce66db-9389-4053-b65b-ee64370aa3ea)

### newSimple.docx
![newSimple.docx](https://github.com/python-openxml/python-docx/assets/148439007/3807791b-b265-4cb1-a2ed-db78f169d9e7)

### required output
![required output](https://github.com/python-openxml/python-docx/assets/148439007/ea5834ac-570c-42a7-8b92-c4aed72414f5)

Here I need to **track the changes.**

**Comment by scanny** [comment]
Ah, I see. Unfortunately `python-docx` does not support adding revision marks in the document.

**Comment by Dinesh728439** [comment]
Thank Steve

Is there any other way than python--docx

**Comment by scanny** [comment]
There might be a Microsoft solution. You'll have to search on Google and see what you can find :)
