### ISSUE TITLE
Add text with specific style witthout line break

### ISSUE THREAD

**Issue by hervekhg** [python-openxml/python-docx#141]
Hello,
I want to set a specific style in some rows of my table, without having line break before text. Could you help me.

This is my code:
p3 = cell.add_paragraph(text=valeur, style="Normalgras")

**Comment by scanny** [comment]
A cell must contain at least one paragraph. So new ones are created containing a single empty paragraph. You have to use that one up before you add more, otherwise it appears as a blank line before the new text.

Something like this:

```python
paragraph = cell.paragraphs[0]
paragraph.text = valeur
paragraph.style = 'Normalgras'

p2 = cell.add_paragraph(...)
```

**Comment by hervekhg** [comment]
Thank You very much. It's work

**Comment by sfcl** [comment]
It worl!
