### ISSUE TITLE
Workaround to set <w:bidi/> property on a paragraph's properties <w:pPr>?

### ISSUE THREAD

**Issue by jamesbcd** [python-openxml/python-docx#1411]
Hi,

Can anyone help with a work-around to set the <w:bidi/> property on a paragraph's properties <w:pPr>?
This is necessary to set the whole paragraph to have a right-to-left text direction.

Any help appreciated!

**Comment by scanny** [comment]
In general, for this sort of thing:
1. Get as close as possible to the desired location in the XML using `python-docx` (proxy) objects.
2. Use `lxml.etree._Element` methods to manipulate the XML from there.

`<w:bidi>` is an _element_, not an _attribute_. That distinction matters here.

`<w:pPr>` is the "parent" element. You can get the `w:pPr` element you want from the paragraph like so:
```python
paragraph = ...  # -- however you arrive to the right one --
pPr = paragraph._p.pPr
```

From there you want to create your new element,
```python
from docx.oxml.parser import OxmlElement

bidi = OxmlElement("w:bidi")
```

Then insert it in the right sequence within the child-elements of `pPr`:
```python
pPr.insert_element_before(
    bidi,
    (
        "w:adjustRightInd",
        "w:snapToGrid",
        "w:spacing",
        "w:ind",
        "w:contextualSpacing",
        "w:mirrorIndents",
        "w:suppressOverlap",
        "w:jc",
        "w:textDirection",
        "w:textAlignment",
        "w:textboxTightWrap",
        "w:outlineLvl",
        "w:divId",
        "w:cnfStyle",
        "w:rPr",
        "w:sectPr",
        "w:pPrChange",
    )
```

**Comment by jamesbcd** [comment]
Thanks so much @scanny, that's really helpful.

(The only tweaks I had to make were calling `get_or_add_pPr()` in case there was no existing `<w:pPr>` element yet, and unpacking the list of child elements.)

```python
from docx.oxml.parser import OxmlElement

pPr = para._p.get_or_add_pPr()
bidi = OxmlElement("w:bidi")
pPr.insert_element_before(bidi,
    *(
        "w:adjustRightInd",
        "w:snapToGrid",
        "w:spacing",
        "w:ind",
        "w:contextualSpacing",
        "w:mirrorIndents",
        "w:suppressOverlap",
        "w:jc",
        "w:textDirection",
        "w:textAlignment",
        "w:textboxTightWrap",
        "w:outlineLvl",
        "w:divId",
        "w:cnfStyle",
        "w:rPr",
        "w:sectPr",
        "w:pPrChange",
    )
)
```
