### ISSUE TITLE
section's right_margin property unchangeable

### ISSUE THREAD

**Issue by ThreefoldBurly** [python-openxml/python-docx#142]
There seems to be no way to change the right margin property on a section (on the default one as well as on an added one). It's set in stone with the value of 3.175 cm for some reason. Changing values of the other margins works with no hassle.

I'm using python-docx 0.8.0 with Python 2.7.8 on Ubuntu 14.10.

**Comment by scanny** [comment]
Hi @ThreefoldBurly, if you could provide the minimum code it takes to reproduce this that will speed diagnosis.

**Comment by ThreefoldBurly** [comment]
Sure I can. Not much experience with bug reporting (or GitHub for that matter) so bear with me. As I don't see a way to attach a file here like on Launchpad (apart from pictures that is) I guess I should use gists, right? If that's correct you'd find the code for the issues I raised there. That leaves me wondering where should I put the generated docx files you asked...Don't worry I'll figure that out too :)

**Comment by ThreefoldBurly** [comment]
As it turns out it works correctly and I made a typo in my code. Silly me. Thx @scanny checking on it and sorry for raising a non-issue. Closing.
