### ISSUE TITLE
Autoescape should be TRUE by default

### ISSUE THREAD

**Issue by HongYang01** [python-openxml/python-docx#1421]
Refer Doc: https://docxtpl.readthedocs.io/en/latest/#escaping-1

Block of source code:
```py
# docxtpl\template.py
{...}
def render(
        self,
        context: Dict[str, Any],
        jinja_env: Optional[Environment] = None,
        autoescape: bool = False
    ) -> None:
{...}
```

I suggest this because I was new to python-docx and generating reports that contained `< > &` characters. At first, I was miserable; the report was generated successfully but was corrupted when opened in MS Word.

**Comment by scanny** [comment]
@HongYang01 this code is in the `docxtpl` project, not this one. You'll need to take it up with them :)
https://github.com/elapouya/python-docx-template
