### ISSUE TITLE
Cannot access contents of first page footer and header if both first-page and regular headers and footers are present

### ISSUE THREAD

**Issue by dsugarmansqp** [python-openxml/python-docx#1424]
In my doc (attached), I know that there is a first-page-only footer:
- viewing the Word doc, I can see a different footer on page 1 than on pages 2-n
- when I modify `document.sections[0].paragraphs[0].text`, the change appears on pages 2 through n.

However, when I try to access the text in the first-page-only footer, I can't--I can see that it must be there, but I can't print it, and when I try to modify it, no change appears on my Word document. See the below code and output:

```
for section in new_document.sections:
    print(f"# of paragraphs in first footer: {len(section.first_page_footer.paragraphs)}")
    print(f"first paragraph: {section.first_page_footer.paragraphs[0].text}")
    print(f"does it have a different setting? {section.different_first_page_header_footer}")
    print(f"is it linked to previous? {section.first_page_footer.is_linked_to_previous}")
    print(f"what about even and odd? {new_document.settings.odd_and_even_pages_header_footer}") 
print(f"# of sections: {len(new_document.sections)}")
```

Results:
```
# of paragraphs in first footer: 1
first paragraph: 
does it have a different setting? True
is it linked to previous? False
what about even and odd? False
# of sections: 1
```

This document also has a first-page-only header, and does not have a regular header. If I try to access the first-page-only header present in this document, I can read/write as expected. However, if I add a regular header, I lose my ability to access the first-page-only header, but I can access the regular header just fine.

Digging into the xml, I noticed that there is a `footer1.xml` file as well as a `footer2.xml`. `footer1.xml` contains the regular (non-first-page-only) footer, and `footer2.xml` contains the first-page-only one. Same with headers.

It seems like if both the regular and first-page header or footer are present in the document, python-docx cannot access the first-page one, perhaps because it can't access the `header2.xml` or `footer2.xml` file that contain those text runs.
[template.docx](https://github.com/user-attachments/files/16775832/template.docx)

**Comment by scanny** [comment]
Inspecting the XML, your first-page footer contains a `<w:sdt>` block item followed by an empty paragraph. Look up "word sdt structured data tags" to understand more about those, they're basically "form-fields", or template placeholders for inserted paragraphs etc.

`python-docx` does not yet support those, which is why your text does not appear. Looks like it says "Footer PAGE 2 of NUMPAGES" roughly.

Anyway, I expect that explains the behavior.
