### ISSUE TITLE
sections don't work as intended

### ISSUE THREAD

**Issue by ThreefoldBurly** [python-openxml/python-docx#143]
The documentation on Document's add_section() method says that it "allows a new section to be started at the end of the document. Paragraphs and tables added after calling this method will appear in the new section."

While adding a new section appends it to the list of sections in the document object, it doesn't show up in the saved docx file. When I open it in LibreOffice 4.3.3.2 it displays one page with the properties of the old section. Adding a heading before adding a section and then adding a table (in the code) ends with having a heading and immediately after it a table on the same page (in LibreOffice). 

If I get how it's supposed to be after reading the documentation, it should show a heading on one page with the old section properties and a table on another page with the added section properties. Right?

**Comment by scanny** [comment]
Can you provide a snippet of the code you're using?

**Comment by scanny** [comment]
This one works as intended on my side.

This is perhaps obscured somewhat in the UI by choosing a table for the second block element. There is a difference in how LibreOffice interprets tables and it spreads them pretty wide if you don't set the cell widths. We'll remedy that here pretty soon. In the meantime, if you set table cell widths to reasonable values that will make the table appear more as expected.

Try this and I think the behavior will be more clear:
```python
from docx import Document
from docx.shared import Cm

document = Document()
document.add_paragraph("This appears on the first page, in section 1")
document.add_section().page_height = Cm(10)
document.add_paragraph("This appears on the second page, in section 2")
document.save('issue-143.docx')
```
