### ISSUE TITLE
alignment of paragraphs in a table unchangeable if set earlier in the table style 

### ISSUE THREAD

**Issue by ThreefoldBurly** [python-openxml/python-docx#144]
Setting an alignment property on a ParagraphFormat object of a table style (I tested with WD_ALIGN_PARAGRAPH.LEFT) renders other alignment values unusable on table paragraphs afterwards. If, for instance, you set each paragraph to WD_ALIGN_PARAGRAPH.RIGHT while populating the table with content (say you'd like one column to be aligned differently than the others) it's still aligned to the left in LibreOffice. 

That of course forces the user to unset it in the table style and align each paragraph individually, thus voiding the purpose of having the style in the first place.

**Comment by scanny** [comment]
Hi @ThreefoldBurly, can you provide a snippet of code to reproduce this?

Also, if you could send a document showing this behavior that would be a big help in diagnosis, perhaps the one generated by the code snippet.

**Comment by scanny** [comment]
It appears LibreOffice (LO) is behaving rather badly in this case, perhaps as a compromise related to preferring ODF format.

It looks like LO takes all the table style value and applies them directly to each element of the table, including paragraphs in this case, where they overwrite whatever was applied directly. This has the additional implication that it effectively interrupts the style inheritance hierarchy for tables.

There's unfortunately nothing to be done on the python-docx side to remedy this. python-docx faithfully writes the `<w:jc w:val="right'/>` element on the paragraphs in question here, only to have that overwritten by LO Writer when it opens the file.

The only solution I can see is to avoid using a table style or to open the file in LO and let it have its way, and then adjust the file afterward to make the desired settings. I'd be inclined to prefer the former. I'm not sure LO wouldn't just overwrite custom settings again next time the file was opened if you took the latter approach.

You could avoid using a table style in cases where additional customization was required by applying all the formatting directly to the table elements after it was created; basically the same approach LO is taking.

**Comment by ThreefoldBurly** [comment]
Applying all formatting directly - that's exactly what I did to circumvent it. Thanks a lot for clearing this up. It's not gonna be much of a problem for me, if it's all LO's fault, because actually the files I generate with the python script I'm working on are to be used with MS Word. I just happen to prefer Linux as my development environment.
