### ISSUE TITLE
Constructor throw "File is not a zip file" on file created using Word 

### ISSUE THREAD

**Issue by swarmttied** [python-openxml/python-docx#1452]
Hi. I'm trying to parse docx using the BytesIO overload of the Document ctor.  when I parse any docx created using python-docx, the codes snippet below works just fine. However, with those saved from Word, I get the "File not valid zip" error.   I notice that the Word-created files are indeed larger than those created using python-docx, indicative of it not being a zip file. Is there a way to parse a non-zipped stream in this case? I'm on Python 3.11

![image](https://github.com/user-attachments/assets/ccb1a355-d034-4b24-aa2e-b41c89053acb)

**Comment by scanny** [comment]
I'm not seeing any `doc.save()` call. What's the traceback?

I don't know what the type of `stream` is, but it will need to be `IO[bytes]`, meaning either an open file or an instance of `io.BytesIO`, not just `bytes`.

**Comment by swarmttied** [comment]
@scanny , The exception is thrown at the constructor so I still don't have the chance to save the file. Just curious, if I'm just parsing why would I call save()? 

The other files created using python-docx work. Only those created in Microsoft Word fail. I got the stream using this function 

![image](https://github.com/user-attachments/assets/5432a554-8af9-49be-90bd-dd99f588f17b)

and is based on Microsoft suggestion [here](https://learn.microsoft.com/en-us/answers/questions/2112448/how-to-read-text-from-doc-and-docx-files-in-azure)
 
![image](https://github.com/user-attachments/assets/5e8aca55-b054-496d-bc37-b5c3f679eecd)

And lastly, the trace

![image](https://github.com/user-attachments/assets/7acc0167-eee6-41f7-aca5-b4a15339c717)

I hope these make things clear. Thanks for looking into this

**Comment by scanny** [comment]
It looks like the problem is getting from Azure to `BytesIO`. I expect if you just save the BytesIO to a file then Word will not open it and probably not zip either. Maybe the `.readinto()` mechanism defaults to text (str) rather than bytes, I'm not familiar. But the problem occurs before you get to `python-docx`.

**Comment by swarmttied** [comment]
The do open after saving to Azure. I suspect it's Word that's doing something to it. Too bad because all I did here is plain-vanilla save and this is what we expect from our users too.

I'll try to experiment with other versions of the lib and python.

Thank you for your time.

**Comment by swarmttied** [comment]
My colleague figured this out. It was the cp037 encoding used by Word.

**Comment by swarmttied** [comment]
My colleague figured this out. It was the cp037 encoding used by Word.
