### ISSUE TITLE
Create style.

### ISSUE THREAD

**Issue by awatar** [python-openxml/python-docx#147]
Sorry for my English first. I have one question. Can anybody tell how i can create my own style (with code please). I want create it with parameters: 
1 .font.size = Pt(14) 
2 .font.name=('Times New Roman') 
3. space between lines of the paragraph (front = 0, after = 0) (default: front = 0, after = 10)
I will be grateful if someone can help me with this.
At "http://python-docx.readthedocs.org/en/latest/api/style.html#"I did not understand anything unfortunately. I'm just learning Python.

Saving default document (C:\Python27\Lib\site-packages\docx\templates) with the necessary gives nothing. Text automatically  added in 11, Cambria,  (front = 0, after = 10).

**Comment by scanny** [comment]
Try this page of the documentation:
http://python-docx.readthedocs.org/en/latest/user/styles-using.html

**Comment by scanny** [comment]
Also it looks like you have the legacy version of python-docx installed. You'll want to:
```bash
pip uninstall docx
pip install python-docx
```

**Comment by ThreefoldBurly** [comment]
@awatar: you actually need two styles: a paragraph style and a character style.

```python
from docx import Document
from docx.shared import Pt
from docx.enum.style import WD_STYLE_TYPE

doc = Document()
# getting access to the list of styles in the document
my_styles = doc.styles()

# creating the paragraph style
p_style = my_styles.add_style('name-of-p-style', WD_STYLE_TYPE.PARAGRAPH)
# doesn't hurt to make it inherit from something sensible (I don't remember if it's specified in the documentation what the defaults are)
p_style.base_style = my_styles['Normal']
# setting properties
p_style.paragraph_format.space_before = Pt(0)
p_style.paragraph_format.space_after = Pt(10)
# ...and so on

# creating the character style
ch_style = my_styles.add_style('name-of-ch-style', WD_STYLE_TYPE.CHARACTER)
# doesn't hurt to make it inherit from something sensible (I don't remember if it's specified in the documentation what the defaults are)
ch_style.base_style = my_styles['Default Paragraph Font']
# setting properties
ch_style.font.name = 'Times New Roman'
ch_style.font.size = Pt(14)
# ...and so on
```
then each time you'd like a paragraph formatted in the style you specified you create it passing the created style's name as argument
```python
new_paragraph = doc.add_paragraph(style = 'name-of-p-style')
```
but remember - that only gives you paragraph formatting (spacing, alignment and whatnot). If you want your text to receive the character formatting, you have to pass it when adding runs to the paragraph you've just created
```python
new_paragraph.add_run('the-body-of-the-actual-text', style = 'name-of-ch-style')
```
Read the docs, though. They're not bad. I recommend downloading them as PDF for easy searchability.

**Comment by scanny** [comment]
Paragraph styles include character formatting. You only need character styles for situations where you want a word or phrase to be formatted differently than the rest of the paragraph.

**Comment by ThreefoldBurly** [comment]
@scanny of course, you're right. Now I see in the API that _ParagraphStyle class has indeed a Font object. Wouldn't hurt to stress this better in the docs then.

**Comment by awatar** [comment]
Thank you so much for efficiency. I have not checked the code yet, but I am sure that everything will turn out as hoped. Good luck to you.

**Comment by awatar** [comment]
I get error..... :(
Traceback (most recent call last):
 File "G:/styles.py", line 7, in <module>
 my_styles = doc.styles()
TypeError: 'Styles' object is not callable
can you tell me what i need to do?

**Comment by awatar** [comment]
Can someone tell this error just me? .... Please..... i very very  need to use this code.

**Comment by scanny** [comment]
`Document.styles` is a property, not a function, so you don't use the parentheses.

```python
from docx import Document

document = Document()
styles = document.styles
```

In future, for support questions like this, please use the mailing list here:
https://groups.google.com/forum/#!forum/python-docx

We prefer to reserve the issues list here for suspected bugs and feature requests.

As it happens, due in large part to the thorough testing regimen, there turn out to be very few bugs; so if you're just getting started and something's not behaving as you expect, it's best to bring it up on the mailing list until there's some reasonable confidence there's actually something not behaving correctly.
