### ISSUE TITLE
Upgrade python-docx to 0.8.2. breaks script

### ISSUE THREAD

**Issue by tooh** [python-openxml/python-docx#148]
Probably the upgrade 0.8.0 caused this
```
File "/Scripts/html/tag_dispatchers/__init__.py", line 5, in <module>
    from docx.text import Paragraph
ImportError: cannot import name Paragraph
```

I don't know how to fix this.

https://github.com/fokoenecke/html_docx/issues/3

**Comment by tooh** [comment]
changed 
```
from docx.text import Paragraph
```
to
```
from docx.text.paragraph import Paragraph
```

**Comment by scanny** [comment]
Hi Peter, yes, there was some reorganization of the internals in the 0.8.0 release to make room as the code base grows.

That class isn't intended to be constructed directly though, how do you have occasion to need to import it?

**Comment by tooh** [comment]
@scanny Thanks again for your reply.
I used the code from @fokoenecke to import Markdown into python-docx.
fokoenecke/html_docx#3
This code does the import. I must say I do not understand the code, I was only able to use is :)

**Comment by scanny** [comment]
Ah, right, I remember now. Just the wages of using internals for workarounds I'm afraid, part of the pains of bearing with us while we grow the code base :)

In general, the published API is warranted to be stable; the few occasional changes to that we can't avoid get documented as backward incompatibilities.

The internals on the other hand, are subject to change on any given commit. They don't usually of course, but from time to time they do as we reorganize the code base or whatever. Interim workarounds to implement features are very useful and I definitely endorse them as a way to complete apps while we're still building, but unfortunately vulnerable to reorganizations like this and have to be fixed up from time to time when updating to a new version.
