### ISSUE TITLE
Tests don't run

### ISSUE THREAD

**Issue by kushal124** [python-openxml/python-docx#151]
On invoking python setup.py test,
the tests don't run.

I get an exit status OK with Ran 0 tests in 0.000s

**Comment by scanny** [comment]
In the project directory:

```python
flake8  #optional but I run it every time
py.test -x
behave --stop
```

I couldn't get `python setup.py test` to work last time I tried.

You can also use `tox`, but you'll need environments for 2.6, 2.7, 3.3, and 3.4. You can run for example `tox -e py33` to run just one of them.

**Comment by kushal124** [comment]
The tests run with this command in th git source and the tarballs.
I am trying to package the library for use in Fedora.

The tests fail in the build of fedora.
The errors : http://fpaste.org/187988/24420612/

**Comment by scanny** [comment]
Hmm, I'm not familiar with the details of RPM packaging. What version of Python is running when that error is produced?

Also, can you tell what the current working directory is when it is run?

It looks like something to do with sys.path not having the tests/ directory in it, but it usually doesn't need it because it's run from the project directory.

Is this for the official Fedora RPM package repository or just to distribute with your application?

**Comment by kushal124** [comment]
I am running with python2.7
The test run in the root of the project. 
And yes this is for the official Fedora RPM repo.

**Comment by scanny** [comment]
Ah, okay, I think I worked out what's happening. The tests that are being run are pulling from the tarball, is that right? I notice that the files in question are not included in the tarball for some reason.

I'll work out why they're not being included and push up on a test branch for you to try again.

**Comment by scanny** [comment]
Ok, I think this does the trick. Want to try to patch on your side? It's a one-liner, probably easier than republishing the whole code tree ... it's in line 2 of MANIFEST.in in the project directory. Then `make sdist` should create a new tarball in `/dist`.

```diff
:) ± diff MANIFEST.in new-MANIFEST.in                                                                                                                       !60623
2c2
< include tests/*.py
---
> recursive-include tests *.py
```

Let me know if that won't work for you, I can publish another way this evening some time if you let me know what you need.

**Comment by kushal124** [comment]
Yes, you are right. I checked in the build, the tests are not included and hence the problem.
I will try fixing with this to see if it works.

For packaging, I can add small patches , but it would be nice to have the fix upstream.

**Comment by kushal124** [comment]
Ok, I figured out the error. The problem was on my side.
The source for packaging was from pypi. That source tar didn't have all the tests.

I am currently building from github releases and everything seems to be fine.

So, once it is packed and approved I would let you know here.

Thanks for the help :)

**Comment by scanny** [comment]
I'll push this fix up to PyPI tonight as a point release. Might as well have it work the same everywhere :)

Thanks for letting me know about this Kushal :)

**Comment by scanny** [comment]
Ok Kushal, this fix is included in python-docx v0.8.4, just pushed up to PyPI a few minutes ago. You should be able to package straight from the PyPI distribution now.

It's actually probably the safer bet. The `master` branch on GitHub generally follows exactly, but the PyPI distribution is the authoritative version for a given release :)

Feel free to reopen if it gives any more trouble :)

**Comment by kushal124** [comment]
Hi,
The package has been packed for fedora and currently under testing. 
Should be available soon in the official repos,

if you want to try it on Fedora 21:
sudo yum install https://kojipkgs.fedoraproject.org//packages/python-docx/0.8.5/2.fc21/noarch/python3-docx-0.8.5-2.fc21.noarch.rpm

or 

sudo yum install https://kojipkgs.fedoraproject.org//packages/python-docx/0.8.5/2.fc21/noarch/python-docx-0.8.5-2.fc21.noarch.rpm

Thanks for the quick fixes :)

**Comment by scanny** [comment]
Great news @kushal124, thanks for letting us know :)
