### ISSUE TITLE
Too slow document creation

### ISSUE THREAD

**Issue by shreyasHpandya** [python-openxml/python-docx#158]
I am creating a docx and writing nothing but a table in it with around 1k-2k rows and 5 columns. It takes around a minute to create on my MBP 8GB RAM and i5 cpu. On a shared hosting server with 512RAM it takes forever and the process gets killed eventually. Is it normal to take it this long? 
Any suggestion?

**Comment by scanny** [comment]
That seems like a pretty long time. Does the document open up okay in Word when you're done? I don't believe I've ever seen a table with that many rows in it.

How big is the .docx file it produces? And what is the source of the data you're putting in the rows?

**Comment by scanny** [comment]
On my machine it takes about a second to add 1000 rows to a 5-column table. I expect the trouble is in sourcing the data. You could try accessing the data without actually writing it to the document and see how long that takes. If you're executing a SQL query for each row that would be the sort of thing that would explain the long time you're seeing.
