### ISSUE TITLE
python 2.x compatibility

### ISSUE THREAD

**Issue by snodo** [python-openxml/python-docx#168]
there is a problem in
CT_CoreProperties._set_element_text (line 299)

```
value = str(value)
```

which will will fail in a default windows-python2.x installation when supplying unicode strings (e.g.):

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 0: ordinal not in range(128)

This is because there is no default system encoding, so python tries to encode the unicode-string using 7-bit-ASCII, which of course fails.

My solution: Only convert to string, if its necessary. If it's already a string/unicode, don't touch.

```
if not isinstance(value, basestring):
    value = str(value)
```

**Comment by scanny** [comment]
Fixed in release v0.8.7 circa Aug 18 2018.
