### ISSUE TITLE
Get word/document.xml

### ISSUE THREAD

**Issue by philippmayrth** [python-openxml/python-docx#178]
What would be the right way to get the word/document.xml as xml without saving the file to disk first after a modification?

**Comment by scanny** [comment]
Here's one way:

```python
document = Document('original_doc.docx')
... make some changes ...
document_xml = document.element.xml
```

I'm not sure if its type is `str` or `unicode`, and it may vary, but I suspect it's `unicode`.

If you'll describe what you're trying to achieve one of the other approaches might suit better.

**Comment by philippmayrth** [comment]
My goal is to replace some text in a document but keep images. The example you gave is what I was looking for. Thanks.
