### ISSUE TITLE
Documentation Update Request for Paragraph left_indent

### ISSUE THREAD

**Issue by j4w** [python-openxml/python-docx#183]
The below is not reflected properly in python-docx documentation:

"The left_indent property was moved to the paragraph_format "sub-object" a couple releases back as the ParagraphFormat class is used by both the Paragraph and ParagraphStyle objects."

http://stackoverflow.com/questions/30584681/how-to-properly-indent-with-python-docx

Thanks!

**Comment by scanny** [comment]
Fixed in release v0.8.7 circa Aug 18 2018.
