### ISSUE TITLE
Breakline instead of newline in tables' cells

### ISSUE THREAD

**Issue by sawka6630** [python-openxml/python-docx#185]
I've got two source *.docx files with one table inside each of them. I need to generate a new file with new table containing first columns of source files' tables.
As far as I know, there's no way to simly copy first columns from source tables and assign them to new table. I mean, next code won't work:
```python
col1 = doc1.tables[0].columns[0]
col2 = doc2.tables[0].columns[0]
new_table.columns[0] = col1
new_table.columns[1] = col2
```
So I have to read cells' text one cell by one, and then assign it to according cells of new table. Thet's not a really big problem, BUT... What I get is not what I tried to achieve. All 'new line' sympols (**^p** in Word) were replaced with 'break line' symbols (**^l** in Word). See the example screenshot:
![2015-06-12_231707](https://cloud.githubusercontent.com/assets/12865350/8139051/2c0f3494-1159-11e5-94dc-1330adfd9634.jpg).
Left column shows the source text, and right column contains resulting text.
I don't know if it is a bug or a feature. I'm almost sure I'm making some mistake. But I don't know where to search for it. I may understood the working logic wrong. Maybe you can show the wright way =) Or *maybe* this report will help you to find a bug in your lib.
P.S. Sorry for my English, it's not my native language. And hope I've find the right place for this text, 'couse I'm new to GitHub.

**Comment by scanny** [comment]
This behavior is a consequence of the way we chose some "convenience" API methods. If you include the code you use I can point out more specifically, but essentially the `.text` property for the cell has to convert a potentially complex XML hierarchy into a single string that's useful for general purposes.

If you want to get your text more exactly, you'll need to do that conversion yourself by looping through the paragraphs in the cell and inserting them as paragraphs in the new cell. So something roughly like:

```python
for paragraph in cell.paragraphs:
    ... copy paragraph contents to new table ...
```

If you want to preserve font formatting, you'll need to go down to the run level.

Another possible option is to use deepcopy() to copy the XML in the cell and write it into the new cell. This is a bit more brittle theoretically, but might turn out to be easier for your case. You'll need some understanding of how python-docx uses lxml to manipulate the underlying XML to make this work.

**Comment by sawka6630** [comment]
Hi, **scanny**! Thanks for your reply.
Here, I've created [a gist with my code] (https://gist.github.com/sawka6630/f0b2288a5ab2a67d2312#file-table_merger) to show what I'm talking about. To test it you should create two files named "en.docx" and "ua.docx" (for example) and place a table 2x2 cells inside each of them. Fill this tables' *first* columns with text (including paragraphs in single cell). Place created files and table_merger.py in one folder, open the console and type in: `python table_merger.py en.docx ua.docx`. A file called "result.docx" should appear in the same folder. It's contents will be looking like shown on screenshot from my first message: first column from "en.docx" became a first column in "result.docx" and first column from "ua.docx" became a *second* column in "result.docx".
In general, I understood that I should copy cells' contents using `for paragraph in cell.paragraphs`. Thank you for that, I'll try to. There's no need to preserve a font formatting in this work (at least, for now). But if you could point to any mistakes in my code, that would be highly appreciated. I'm not a pro in Pyton =)
P.S. Also a nice point for me will be replacement of Word's **"^p"** with simple text **"\P"** so that the final cell's text will be looking like a single line: `Text1\PText2\PText3`. But that's a job to do a little bit later. I see it as a fallback plan. Anyhow I would like to know what you think about whole this situation =) If you don't mind, of course.

**Comment by scanny** [comment]
Yep, it's as I suspected. When you use the .text method for getting and setting it has to make some assumptions about what you mean by '\n'. You might like to look at the code that the .text method uses since you'll be doing something of a variant on it:
https://github.com/python-openxml/python-docx/blob/master/docx/table.py#L252-L271

**Comment by sawka6630** [comment]
O'key, thanks for the explanations. I'll try to deal with `paragraph`s =)
