### ISSUE TITLE
How to set table cell vertical alignment?

### ISSUE THREAD

**Issue by zhaozhiming** [python-openxml/python-docx#191]
HI ALL,
I use table merge cell method to merge some cells to a cell, and I want to set the vertical alignment of the merge cell, but I only find the horizontal alignment set method like this:

```python
table = document.add_table(3, 3)
a = table.cells(0, 0)
b = table.cells(1, 1)
A = a.merge(b)
p = A.add_paragraph("test")
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
```

How could I set the merge cell vertical alignment to center? Thanks.

**Comment by scanny** [comment]
That feature isn't implemented yet. At the XML level I think you're looking for the vAlign element, that fits in roughly like this, w:tc being table cell:

```xml
<w:tc>
  <w:tcPr>
    <w:vAlign ...>
```

There is some context analysis here:
http://python-docx.readthedocs.org/en/latest/dev/analysis/features/table-cell.html

You'd need to dig into the schema to work out the specifics of the w:vAlign element or just inspect some Word XML. Then you can get at it with lxml calls from the w:tcPr element. You can get the w:tcPr element with:

```python
tc = cell._tc
tcPr = tc.get_or_add_tcPr()
```

If you google on "python-docx OxmlElement" you'll find how to use some of the internal python-docx helper functions to get it done. Here's one to get you started:
https://github.com/python-openxml/python-docx/issues/55#issuecomment-43914055

**Comment by zhaozhiming** [comment]
OK, thank you very much.

**Comment by hmlee9** [comment]
@zhaozhiming @scanny 
it should be like 

 ```
tc = row.cells[0]._tc
tcPr = tc.get_or_add_tcPr()
tcVAlign = OxmlElement('w:vAlign')
tcVAlign.set(qn('w:val'), "center")
tcPr.append(tcVAlign)
```

**Comment by zooyf** [comment]
cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER

**Comment by edvard-munch** [comment]
> tcVAlign.set(qn('w:val'), "center")

What is `qn`?
