### ISSUE TITLE
Replacing cell text and keeping existing style and alignment

### ISSUE THREAD

**Issue by seanacais** [python-openxml/python-docx#194]
Let me start by saying GREAT LIBRARY!! 

Here's the problem.

I'm opening an existing document and need to replace the values in a couple of cells in a table.

The original value of the cell may be empty, but the cell has a style attached and is formatted for a CENTER alignment.

Here is the row from opc output as it comes to me in the original docx.

      <w:tr w:rsidR="00904541" w:rsidRPr="001B6270" w:rsidTr="00E65FCB">
        <w:trPr>
          <w:cantSplit/>
          <w:trHeight w:val="413"/>
        </w:trPr>
        <w:tc>
          <w:tcPr>
            <w:tcW w:w="1560" w:type="dxa"/>
            <w:vAlign w:val="center"/>
          </w:tcPr>
          <w:p w:rsidR="00904541" w:rsidRPr="001B6270" w:rsidRDefault="00904541" w:rsidP="00537926">
            <w:pPr>
              <w:pStyle w:val="aTableText"/>
              <w:jc w:val="center"/>
            </w:pPr>
          </w:p>
        </w:tc>
        <w:tc>
          <w:tcPr>
            <w:tcW w:w="992" w:type="dxa"/>
            <w:vAlign w:val="center"/>
          </w:tcPr>
          <w:p w:rsidR="00904541" w:rsidRPr="001B6270" w:rsidRDefault="00904541" w:rsidP="00537926">
            <w:pPr>
              <w:pStyle w:val="aTableText"/>
              <w:jc w:val="center"/>
            </w:pPr>
            <w:r>
              <w:t>1.0</w:t>
            </w:r>
          </w:p>
        </w:tc>
        <w:tc>
          <w:tcPr>
            <w:tcW w:w="3402" w:type="dxa"/>
            <w:vAlign w:val="center"/>
          </w:tcPr>
          <w:p w:rsidR="00904541" w:rsidRPr="001B6270" w:rsidRDefault="00904541" w:rsidP="00537926">
            <w:pPr>
              <w:pStyle w:val="aTableText"/>
              <w:jc w:val="center"/>
            </w:pPr>
          </w:p>
        </w:tc>
        <w:tc>
          <w:tcPr>
            <w:tcW w:w="3468" w:type="dxa"/>
            <w:vAlign w:val="center"/>
          </w:tcPr>
          <w:p w:rsidR="00904541" w:rsidRPr="001B6270" w:rsidRDefault="00904541" w:rsidP="00537926">
            <w:pPr>
              <w:pStyle w:val="aTableText"/>
              <w:jc w:val="center"/>
            </w:pPr>
            <w:r>
              <w:t>Initial version</w:t>
            </w:r>
          </w:p>
        </w:tc>
      </w:tr>

I then run the following code

<pre>
revTableCell = doc.tables[0].cell(4,0)
revTableCell.text = u'2015-08-04'

revTableCell = doc.tables[0].cell(4,1)
tpar = revTableCell.add_paragraph(u'New Version',style='a_Table_Text')
tpar.alignment = WD_ALIGN_PARAGRAPH.CENTER

revTableCell = doc.tables[0].cell(4,2)
revTableCell.text = u''
tpar = revTableCell.add_paragraph(u'New Author',style='a_Table_Text')
tpar.alignment = WD_ALIGN_PARAGRAPH.CENTER`
</pre>

and I end up with the following in the docx.

      <w:tr w:rsidR="00904541" w:rsidRPr="001B6270" w:rsidTr="00E65FCB">
        <w:trPr>
          <w:cantSplit/>
          <w:trHeight w:val="413"/>
        </w:trPr>
        <w:tc>
          <w:tcPr>
            <w:tcW w:w="1560" w:type="dxa"/>
            <w:vAlign w:val="center"/>
          </w:tcPr>
          <w:p>
            <w:r>
              <w:t>2015-08-04</w:t>
            </w:r>
          </w:p>
        </w:tc>
        <w:tc>
          <w:tcPr>
            <w:tcW w:w="992" w:type="dxa"/>
            <w:vAlign w:val="center"/>
          </w:tcPr>
          <w:p w:rsidR="00904541" w:rsidRPr="001B6270" w:rsidRDefault="00904541" w:rsidP="00537926">
            <w:pPr>
              <w:pStyle w:val="aTableText"/>
              <w:jc w:val="center"/>
            </w:pPr>
            <w:r>
              <w:t>1.0</w:t>
            </w:r>
          </w:p>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="aTableText"/>
              <w:jc w:val="center"/>
            </w:pPr>
            <w:r>
              <w:t>New Version</w:t>
            </w:r>
          </w:p>
        </w:tc>
        <w:tc>
          <w:tcPr>
            <w:tcW w:w="3402" w:type="dxa"/>
            <w:vAlign w:val="center"/>
          </w:tcPr>
          <w:p>
            <w:r/>
          </w:p>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="aTableText"/>
              <w:jc w:val="center"/>
            </w:pPr>
            <w:r>
              <w:t>New Author</w:t>
            </w:r>
          </w:p>
        </w:tc>
        <w:tc>
          <w:tcPr>
            <w:tcW w:w="3468" w:type="dxa"/>
            <w:vAlign w:val="center"/>
          </w:tcPr>
          <w:p w:rsidR="00904541" w:rsidRPr="001B6270" w:rsidRDefault="00904541" w:rsidP="00537926">
            <w:pPr>
              <w:pStyle w:val="aTableText"/>
              <w:jc w:val="center"/>
            </w:pPr>
            <w:r>
              <w:t>Initial version</w:t>
            </w:r>
          </w:p>
        </w:tc>
      </w:tr>

In the first cell I write a new text string to the cell using _Cell.text = 'string'. It appears that the style is completely removed although the alignment is kept.  That makes sense.

In the second cell I run _Cell.add_paragraph() so I can apply a style.  This doesn't get rid of the original string.

In the third cell, I attempt both a text assignment and an add_paragraph.  What you get is two runs.  (Again makes sense).

It doesn't appear to me that the 'paragraph_format' property is available from the _Cell object.  If it is available an example of how to reference it would be helpful.

Is there a way to simply replace the text of a cell without disturbing the existing formatting and style?

Thank you.

Kevin

**Comment by scanny** [comment]
I have to claim TL;DR; on your post, but I think this is what you're after:

The `.text` property replaces all the paragraphs in a cell, taking any paragraph or cell-level formatting with it. If you want to preserve the formatting, you need to work at the run level. In this case I think you want to add runs to an existing paragraph, so something like:

```python
paragraph = cell.paragraphs[0]  # there will always be at least one, even if cell is empty
run = paragraph.add_run(...)
run.text = "new text"
```

In case of XML above, the "center" property is on the paragraph. Since you preserve the paragraph, that formatting is preserved. If it were italics or something and that formatting was applied at the run level, you'd have to get a handle for the particular run and manipulate the text inside it to preserve its formatting.

**Comment by seanacais** [comment]
That does indeed sound like exactly what I'm after.  It never occurred to me to grab the paragraph reference directly.  

Sorry for the long post.  Was trying to get the info you might need to answer the question.

Thank you!  Again what a great library!

Kevin

**Comment by scanny** [comment]
Closing resolved.
