### ISSUE TITLE
Feature: Adding picture to table cell

### ISSUE THREAD

**Issue by floatc** [python-openxml/python-docx#216]
A perfect use for a tool such as python-docx is to archive a large number of images in an automated fashion.  Unfortunately, floating images is a poor way of doing this and inserting the images in table cells is my preferred route.  I had hoped that python-docx would allow me to do that (and it was, in fact, the only reason I needed it for).  However, it seems to support only floating pictures at this time.  I urge you to consider adding extra functionality to table cells, along the lines of:
row.cells[1].add_picture('image-filename.png', width=Inches(1.0))
Thanks.

**Comment by wabbitbear** [comment]
This is currently possible, you just have to append the runs in the empty cells. Something like this should work:

`import docx`
`pic = "some_picture.jpg"`
`document = docx.Document()`
`tbl = document.add_table(rows=1, cols=1)`
`row_cells = tbl.add_row().cells`
`paragraph = row_cells[0].paragraphs[0]`
`run = paragraph.add_run()`
`run.add_picture(pic, width = 1400000, height = 1400000)`
`document.save("demo.docx")`

**Comment by peterk** [comment]
I can confirm that it works very well for using label template files by opening them and adding images to the template table cells. I have used this for DataMatrix codes. This issue should be closed.

**Comment by 12345data** [comment]
Using the similar code mentioned above I was saving some pictures to a document in a loop. that is i was writing an image in a location with its file name in a document as below.
1.jpg   [image file]
2.jpg   [image file]
3.jpg   [image file]
.....
But when the first was successfully written in the document, others are not written and it shows the error 
docx.image.exceptions.UnrecognizedImageError
Can anyone tell me whats the error.

**Comment by SolomonLeon** [comment]
run = paragraph.insert_paragraph_before().add_run()

**Comment by malj390** [comment]
How could I insert the image in the first row of a 2 row table? With this method is inserted in the last always.

Thanks

**Comment by malj390** [comment]
> How could I insert the image in the first row of a 2 row table? With this method is inserted in the last always.
> 
> Thanks

Solved adding paragraph in this line.
```
row_cells = tbl.add_row().cells
row_cells[0].add_paragraph()
paragraph = row_cells[0].paragraphs[0]
```

**Comment by scanny** [comment]
```python
# --- add a 2 x 2 table as an example ---
table = document.add_table(rows=2, cols=2)
# --- get the first cell of the first row ---
cell = table.rows[0].cells[0]
# --- by default a cell has one paragraph with zero runs ---
paragraph = cell.paragraphs[0]
# --- add a run in which to place the picture ---
run = paragraph.add_run()
# --- add the picture to that run ---
run.add_picture(pic)
```

**Comment by malj390** [comment]
Thanks a lot! That works, but how to add text to the next cell? 
```
cell2 = table.rows[0].cells[1]
paragraph = cell.paragraphs[0]
paragraph.text = 'footnote'
```
This doesn't work. It raises an error. Index out of range.

**Comment by mirshod1257** [comment]
python inlinebuttons add photo?

**Comment by damies13** [comment]
This is really useful information, can this somehow be added to the documentation for the next documentation release?
FYI - I searched for how to do this in the docs couldn't figure it out then google brought me here.

**Comment by Vallejos1797** [comment]
Hi. this an example as list users with image
import os
from docx import Document

             document = Document()
             table = document.add_table(1, 4, style="MiEstilo")

            # -------- create headers
            heading_cells = table.rows[0].cells
            heading_cells[0].text = 'Nº'
            heading_cells[1].text = 'Nombres Apellidos'
            heading_cells[2].text = 'Habilidades'
            heading_cells[3].text = 'Foto'

            # Added rows
            count = 1  # initialize count for position image by row
            for user in usuarios:
                cells = table.add_row().cells
                cells[0].text = ''
                cells[1].text = user['first_name'] + ' ' + user['last_name']
                cells[2].text = user['skills']
                # pic = "C:\\Users\\Abrah\PycharmProjects\\backEnd-auditProcess\\central_app\\central_app\\documents\\perfil\\image.png"
                pic = "./central_app/documents/" + user['image']  # path image
                cell = table.rows[count].cells[3]  # position specific of image count=row and 3=column
                paragraph = cell.paragraphs[0]
                run = paragraph.add_run()
                run.add_picture(pic, width=1400000, height=1400000)  # size image
               count = count + 1

  document.save('nuevoDOC.docx')
   os.system("start nuevoDOC.docx")
