### ISSUE TITLE
Reading/Adding paragraphs appears to be slow

### ISSUE THREAD

**Issue by davemenc** [python-openxml/python-docx#218]
I'm opening a bunch of docx files, pulling the text out and adding it to a single output file. I currently only have a few documents I'm working with (less than a dozen) and yet it takes a few minutes. 

This seems slow to me, especially since I intend to eventually have ~100 documents.

**Comment by scanny** [comment]
Please post the code you're using on a Gist or similar and link here.

**Comment by davemenc** [comment]
Sorry, I can't reproduce it in a simpler case so it must be my code. It looks like it takes .01 seconds to open a file, extract the text and add it to another document. No complaints.
