### ISSUE TITLE
Page Numbers (feature request)

### ISSUE THREAD

**Issue by davemenc** [python-openxml/python-docx#219]
It would be incredibly useful to me to be able to predict what page I'm on. That is, I add some text to a document and can have the program figure out how long the document is in pages. 

Or maybe I can ask "what page is the element at index X on" which would be even better. 

My usecase for this is that I want to generate a book and, somehow, I have to create a table of contents and an index. Both of these require that I know what page something will be on eventually.

**Comment by scanny** [comment]
Unfortunately, this can't be done simply by reference to the document file. A rendering engine would be required to do the page layout and determine where page breaks would occur. That's out of scope for python-docx I'm afraid. Probably best to stick with Microsoft engines if you really need that sort of thing.
