### ISSUE TITLE
 python-docx-0.8.5 is broken? 0.7.6 can work btw

### ISSUE THREAD

**Issue by nghenglim** [python-openxml/python-docx#228]
using example code 
```
from docx import Document
from docx.shared import Inches
```

cannot import name Document

however version 0.7.6 working fine and generated document

**Comment by scanny** [comment]
I haven't heard this from anyone else and 0.8.5 has been out there for quite a while.

I'd be suspecting an install problem or something else in your particular environment. Maybe install it on another machine or in a virtualenv to satisfy yourself 0.8.5 works.
