### ISSUE TITLE
can't open a .docx file

### ISSUE THREAD

**Issue by song147liang** [python-openxml/python-docx#229]
The code is like this,

from docx import Document
from docx.shared import Inches
document=Document('123.docx')

but i get an error like this,

Traceback (most recent call last):
  File "C:/Python27/myDocx.py", line 5, in <module>
    document=Document('123.docx')
  File "C:\Python27\lib\site-packages\python_docx-0.8.5-py2.7.egg\docx\api.py", line 28, in Document
    raise ValueError(tmpl % (docx, document_part.content_type))
ValueError: file '123.docx' is not a Word file, content type is 'application/vnd.openxmlformats-officedocument.themeManager+xml'

How to handle this problem?

**Comment by scanny** [comment]
What application did you use to create 123.docx?

And does it open up okay in Microsoft Word?

That's an odd content type for it to have. It sounds like a Microsoft Office theme file, one that only contains color palettes and perhaps certain styles.

**Comment by kmarcello** [comment]
The same issue here and I have used Microsoft office to create a name.docx

**Comment by lieuzhenghong** [comment]
@scanny, I have the same issue and the file opens fine in LibreOffice Writer, Microsoft Word online and Google Docs (after conversion).

```
ValueError: file './form_letter.doc' is not a Word file, content type is 'application/vnd.openxmlformats-officedocument.themeManager+xml'
```

I tried to view the XML file with `opc browse file.doc core.xml` but this gives `KeyError: No item with name 'core.xml'`.

**Comment by scanny** [comment]
The opc command should be:

`opc browse file.docx \[Content_Types\].xml`

It's odd for the file to end with .doc. Usually that means it's saved in the legacy pre-Word 2007 format.

**Comment by lieuzhenghong** [comment]
> It's odd for the file to end with .doc. Usually that means it's saved in the legacy pre-Word 2007 format.

Does this library not work for the legacy `.doc` format?

```
opc browse form_letter.doc \[Content_Types\].xml
b'<?xml version=\'1.0\' encoding=\'UTF-8\' standalone=\'yes\'?>\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n  <Default Extension="xml" ContentType="application/xml"/>\n  <Override PartName="/theme/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>\n  <Override PartName="/theme/theme/themeManager.xml" ContentType="application/vnd.openxmlformats-officedocument.themeManager+xml"/>\n</Types>\n'(env)
```

**Comment by lieuzhenghong** [comment]
@scanny Sorry, I RTFM-d and 

> You can open any Word 2007 or later file this way (.doc files from Word 2003 and earlier won’t work). While you might not be able to manipulate all the contents yet, whatever is already in there will load and save just fine.

I converted the `.doc` file to `.docx` and now it works. Thank you!

**Comment by scanny** [comment]
Glad you got it working :)

**Comment by mohammedyunus009** [comment]
Helps convert doc to docx. this code u may include in your script
```
import glob
import subprocess

for doc in glob.iglob("*.doc"):
    subprocess.call(['soffice', '--headless', '--convert-to', 'docx', doc])
```
DISCLAIMER: it will work only on linux(ubuntu )

**Comment by wxjeacen** [comment]
where can I download the "soffice" binary for windows?
