### ISSUE TITLE
How to print a word document?

### ISSUE THREAD

**Issue by song147liang** [python-openxml/python-docx#231]
I mean, use the printer. Does something in python-docx or in other packages can achieve such a job?

**Comment by scanny** [comment]
No. This type of thing requires a rendering engine and python-docx doesn't have one of those. For this sort of thing you'll need to use the Microsoft API or perhaps the LibreOffice API.

**Comment by song147liang** [comment]
Thanks

**Comment by wellmonwu** [comment]
i really need this function
