### ISSUE TITLE
Feature Suggestion: Plain text markdown/Org interface.

### ISSUE THREAD

**Issue by timoc** [python-openxml/python-docx#234]
The basic is that i can use Emacs/Vim or some other more rational editor and edit text in markdown/org-mode. Ideally i want to be able to 'connect' to the document to edit it, and when i make changes, the windows client and the word document is updated/recreated. 

Not sure how close to the actual implementation this is, but would it be possible to use python-docx to control MS word like this?

**Comment by scanny** [comment]
I think this is the same as #49, isn't it?

**Comment by timoc** [comment]
Not quite, my concept was more 'live' than post processing a markdown file, i can do some of that with pandoc. I will close this though and check into the possibilities for re-use.
