### ISSUE TITLE
Get text of specific chapter in docx file

### ISSUE THREAD

**Issue by germanpetrov** [python-openxml/python-docx#237]
Hi! 

How can I get access to the specific chapter as an object? For example, I have a docx file with 10 chapters, each chapter has sub-chapters with different styles. And what I'd like to do:

doc = Document(/path/to/docx)
for chapter in doc.chapters:
     print chapter.name
     print chapter.style
     print chapter.text
     for sub_chapter in chapter.chapters:
           print ....
           etc.

Is that possible? I know how to get all text via paragraph objects, but it's not very manageable.. Thanks!

**Comment by scanny** [comment]
Hi @germanpetrov, I think you might have better luck with this question on stackoverflow.com. I need to close it here because this area is reserved for issues like bug reports and feature requests.
