### ISSUE TITLE
Table style

### ISSUE THREAD

**Issue by zhongle** [python-openxml/python-docx#240]
Hi, Scanny,

Got a problem about the table style,   like below:
"doc.add_table(device_table_info.rows, device_table_info.cols, 'LightGrid-Accent3')"

there will be a warning "UserWarning: style lookup by style_id is deprecated. Use style name as key instead. warn(msg, UserWarning)", I search the whole package, but can not find the key of style
'LightGrid-Accent3', would you pls give some suggestion?

Thanks,
Le

**Comment by scanny** [comment]
Try the style name exactly as it appears in the UI, like perhaps 'Light Grid - Accent 3' in this case. If you can't get it that way, you can examine the styles.xml in the .docx package using opcdiag. The value of the 'name' attribute of the style is what you want to match.
