### ISSUE TITLE
How to add Paragraph object to new Document

### ISSUE THREAD

**Issue by incredibleharry** [python-openxml/python-docx#244]
Hi -- I've created a new Paragraph object, comprising several Runs, each of which have different formatting.  I would like to append this new Paragraph object to a Document object.  Unfortunately, the Document.add_paragraph() method takes a string and a style, which would clobber all of my nested formatting.  How can I add my artisinal Paragraph to a Document?  Apologies in advance if there is an obvious answer here -- I'm new to Python.

**Comment by scanny** [comment]
Hi @incredibleharry, I expect you've figured out you need to create the Paragraph where you want it (using the likes of Document.add_paragraph()) and then add the runs and so forth.

Closing this on that assumption, feel free to reopen if you still need help on this one :)
