### ISSUE TITLE
How to insert a paragraph to a specific section?

### ISSUE THREAD

**Issue by ssfjhh** [python-openxml/python-docx#259]
Since python-docx can’t add or change things like headers or footnotes yet, but if the document has them python-docx is polite enough to leave them alone and smart enough to save them without actually understanding what they are.

So I make a "template.docx" file include searval sections. Different sections have different headers and footers. The question is "how can I insert a paragraph or a picture to specific section?"

**Comment by ssfjhh** [comment]
I make a "template.docx" file by MS Word include searval sections. Different sections have different headers, footers and some other dirrerent things.

**Comment by scanny** [comment]
I think the best you could do with this currently is to add a marker paragraph at the beginning of each section that you could use as a cursor and call .insert_paragraph_before() from there.

The good news is that headers and footers are under active development, so will hopefully appear soon :)

I'll close this one for now, but if someone needs to add content to a specific section we can reopen and consider adding something like Section.paragraphs holding just the paragraphs in the specified section.

**Comment by ssfjhh** [comment]
I have done what you said before you reply to me. But thanks for your reply all the same.

**Comment by anakrino10** [comment]
@scanny 
Anything on implementation of something like "Section.paragraphs", or similar to "know where paragraph sits in document layout and sections"?

**Comment by abubelinha** [comment]
@scanny 
First of all, thanks a lot for this awesome tool.

Could you elaborate a bit [your comment](https://github.com/python-openxml/python-docx/issues/259#issuecomment-213237150) __add a marker paragraph (...) and call .insert_paragraph_before() from there__?

I understand you mean something like a paragraph with some particular property that lets you find it again later. 
But how do you do this? Could you post an example code?

**Comment by scanny** [comment]
What I think I meant by a marker paragraph was just a paragraph in the template ("starting") document that had distinctive text such that you could find it later. So the paragraph would have text perhaps like "+=+!+= start section 3 =+!+=+" that was unlikely to be "naturally occurring" and you could identify the paragraph by something like:

```python
for paragraph in document.paragraphs:
    if paragraph.text == "+=+!+= start section 3 =+!+=+":
        print("found it")
```

**Comment by anakrino10** [comment]
Dear Steve

Thanks for the response. I now understand what you mean.

Kind Regards
Ana

**Comment by abubelinha** [comment]
Thanks for explaining, @scanny  I’m doing like that and it works great.
The only thing I could’t solve is keeping the paragraphs hidden. Could you take a look at that?

**Comment by scanny** [comment]
@abubelinha I think the idea is you would replace the text in that marker paragraph as part of the operation. If you leave it there of course it will show in the final document.
