### ISSUE TITLE
feature: Font.spacing

### ISSUE THREAD

**Issue by crazylyf** [python-openxml/python-docx#269]
Is there any way to adjust the inter-character space (kerning)? It can be adjusted in my office2010, while in python-docx, I could not find the way to change it.
Thanks in advance!

**Comment by scanny** [comment]
This is not yet implemented. I'll leave this issue open as a feature request.

**Comment by scanny** [comment]
There are two properties I can find related to this. One is Font.Kerning, which takes a point value below which text is not kerned. The other is Font.Spacing, which adds (or subtracts) a certain amount of space between characters.

Which did you have in mind?

**Comment by crazylyf** [comment]
Thanks for your reply~

I tried a indirect way to solve this problem, by adding a space where needed, and tuning the font size of space to adjust the spacing. 

As for the two proposed properties, I prefer the first strategy, as it offers control the size of spacing.

**Comment by scanny** [comment]
No, not yet, but you might find the thread on this issue helpful: https://github.com/python-openxml/python-docx/issues/154

**Comment by crazylyf** [comment]
Great! Thanks~

**Comment by scanny** [comment]
Issue #243 is feature request for Font.spacing.
