### ISSUE TITLE
Image lost after save

### ISSUE THREAD

**Issue by biggosh** [python-openxml/python-docx#272]
Hello.

I'm new to this library, all things I need are available. I found a strange behavior: 
Case 1:
a) open a file with an image
b) save the file with an other name without any change
c) the document is equal to the original one

Case 2:
a) open the same original file
b) change the text in a run
c) save the document with a new name
d) the image is not more displayed.

I checked and the image is still listed in relations file, it's stored in media directory but in document.xml the piece of xml code that refers to the image is not present.

Where am I wrong with my code?

Thanks in advance and thanks for the great job
Christian

**Comment by scanny** [comment]
Please post the code you're using to locate the run and to change the text in the run.

**Comment by biggosh** [comment]
The test code I used is:

```
from docx import Document

doc = Document("./cv_it_12.docx")

for p in doc.paragraphs:
	for r in p.runs:
		r.text = r.text.replace("@"," (at) ")

doc.save("./result.docx")
```

I attached two files of the test.
[cv_it_12.docx](https://github.com/python-openxml/python-docx/files/162051/cv_it_12.docx)
[result.docx](https://github.com/python-openxml/python-docx/files/162052/result.docx)

**Comment by scanny** [comment]
When you assign to Run.text, it deletes all the contents of that run (including any images) and replaces it with the text you assign.

You could append text to the run using Run.add_text(). Otherwise you would have to go down to the lxml level underneath the Run and operate on individual `<w:t>` (text) elements.

The `w:r` run element is available on Run._r, and it has a .t_lst element that will get you the w:t elements under it, then I believe those have a read/write .text property you can use.

**Comment by biggosh** [comment]
Thanks for the explanation. I'll try.

**Comment by noamshamir** [comment]
> When you assign to Run.text, it deletes all the contents of that run (including any images) and replaces it with the text you assign.
> 
> You could append text to the run using Run.add_text(). Otherwise you would have to go down to the lxml level underneath the Run and operate on individual `<w:t>` (text) elements.
> 
> The `w:r` run element is available on Run._r, and it has a .t_lst element that will get you the w:t elements under it, then I believe those have a read/write .text property you can use.

If I want to replace text no add it, how would I do this without losing the image
