### ISSUE TITLE
add.picture corrupt file

### ISSUE THREAD

**Issue by enira** [python-openxml/python-docx#273]
Hello,

I am getting a corrupted file once I add an image to a file. Code:
```
    def replace_image(self, search, image):
        # search the paragraph where to replace the text
        for paragraph in self.document.paragraphs:
            text = paragraph.text
                        
            if search in text:
                style = paragraph.runs[0].style 
                paragraph.clear()
                newtext = text.replace(search, "")
                run = paragraph.add_run(text=newtext, style=style)
                run.add_picture(image)

                break
```

It says: header3.xml error when I open the file.

**Comment by scanny** [comment]
If you call `paragraph.clear()` on a paragraph that contains an image you'll get this sort of error. You can try this without that line to see if that avoids the error.

You can also try it without the .add_picture() call. I don't think that one is causing the problem.

In any case, you need to localize the problem on your side. You want to get it down to the minimum number of lines that produces the error.

Those are the two places I would look for a start.

**Comment by enira** [comment]
This bare minimum still produces the error:

```
def replace_image(self, search, image):
        for paragraph in self.document.paragraphs:
            text = paragraph.text
            if search in text:
                paragraph.runs[0].add_picture(image)
                break
```

Am I missing something? Do I need to add something?

**Comment by enira** [comment]
Ok I've found the weird error. 

Below the image I was inserting there was another image. Once I deleted this in the original file and put it in another paragraph everything works. Quite odd... however it works now.

**Comment by scanny** [comment]
Hmm, this seems odd. You should be able to add an image to an arbitrary run (including one that already contains an image) without causing a problem. Are you sure you didn't still have the paragraph.clear() call in there somewhere?

**Comment by enira** [comment]
Yeah with or without it. The clear doesn't seems to be a problem now. It works once I moved the old image inserted below. Perhaps it was due to this image pasted from an Excel?

**Comment by scanny** [comment]
Can you provide a sample file that recreates the problem? If there's an actual issue here we'd like to resolve it.
