### ISSUE TITLE
Can not import docx,because of lxml.etree.

### ISSUE THREAD

**Issue by ghosttk** [python-openxml/python-docx#280]
from lxml import etree
ImportError:DLL load failed.
In lxml folder,etree is in etree.pyd file,I think this is why import failed.

**Comment by scanny** [comment]
lxml is a little tricky to get installed on Windows. Until it's properly installed, python-docx can't access it. This is not a problem with python-docx. No other program that relies on lxml will work either.

Search on 'python-docx lxml error' to see the well-known solutions out there, here's one:
http://stackoverflow.com/questions/27589971/unable-to-install-python-docx
