### ISSUE TITLE
class docx.text.run.Font.highlight_color missing?

### ISSUE THREAD

**Issue by ATPs** [python-openxml/python-docx#282]
I am new comer, trying using this package. I am using 0.8.5, the Font class do not have highlight_color? I checked the code, and did not find the feature.

**Comment by scanny** [comment]
It hasn't been committed to a release yet, but is checked in on the `develop` branch. If you install from develop you will have it available.

We have a new release coming out pretty soon, I might get to it this weekend. That would be 0.8.6.

**Comment by ATPs** [comment]
Thank you very much for the comments!

**Comment by sintrb** [comment]
I'm meet this problem too, and waitting for 0.8.6. Thanks a lot.
