### ISSUE TITLE
docs: mention 'rb' needed to get readable ZipFile file object

### ISSUE THREAD

**Issue by paolopiace** [python-openxml/python-docx#283]
It works OK with:
wdocx = Document("wfile.docx")

It fails with:
fobj = open("wfile.docx",'r')
wdocx = Document(fobj)

Error Log:
  File "/usr/local/lib/python3.5/site-packages/python_docx-0.8.5-py3.5.egg/docx/api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "/usr/local/lib/python3.5/site-packages/python_docx-0.8.5-py3.5.egg/docx/opc/package.py", line 116, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/usr/local/lib/python3.5/site-packages/python_docx-0.8.5-py3.5.egg/docx/opc/pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/usr/local/lib/python3.5/site-packages/python_docx-0.8.5-py3.5.egg/docx/opc/phys_pkg.py", line 101, in __init__
    self._zipf = ZipFile(pkg_file, 'r')
  File "/usr/local/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by scanny** [comment]
Hmm, interesting. A few questions to help with the diagnosis:

* What version of Python are you running?
* What do you get when you print fobj (something like <file object at 0x0...>)? In other words, what kind of object is it?
* What does fobj return for `isinstance(fobj, str)`?

**Comment by scanny** [comment]
Also, what OS are you running on. In Windows, if I recall correctly, you need 'rb' for the file mode, not just a plain 'r'. In any case, it's worth trying adding the 'b'. A Zip file is binary, not text.

**Comment by paolopiace** [comment]
I am using Python 3.5.1 on Ubuntu 12.04

'rb' was the trick. Thanks a lot!

May I suggest to say that in section 2.3.3 of python-docx Documentation

**Comment by scanny** [comment]
Glad to hear it @paolopiace :)

Is this the section you meant in the documentation?
http://python-docx.readthedocs.org/en/latest/user/documents.html#opening-a-file-like-document

By the way, can you describe your use case? We thought something like this would be useful, but haven't learned of too many specific cases in which it is. If you could describe yours, that would help us understand better how it's being used :)

**Comment by paolopiace** [comment]
Yes, that's the section. It's 2.3.3 in the PDF.
I do not need to open and read the file object explicitly. Providing the file name directly is fine with me.
I reported what I thought to be an issue, which is not.

I'm parsing many table with technical content. All parsing is based on regex.

If I can ask one thing, it would be a method to iterate across the documents, like the function iter_block_items() described in issue 114.

**Comment by scanny** [comment]
There's a fresh workaround function for the iter_block_items() here if that helps:
https://github.com/python-openxml/python-docx/issues/276#issuecomment-199502885

**Comment by scanny** [comment]
This is fixed and will appear in the upcoming release.
