### ISSUE TITLE
docs: typo in "Working with Sections"

### ISSUE THREAD

**Issue by adustinsky** [python-openxml/python-docx#285]
In the web page:  https://python-docx.readthedocs.org/en/latest/user/sections.html
a sample code has a mistake in writing:

**Adding a new section**
The Document.add_section() method allows a new section to be started at the end of the document. Paragraphs and tables added after calling this method will appear in the new section:

>>> current_section = document.section[-1]  # last section in document

Here,  the "section[-1] "  shoule be  " sections[-1] ".

**Comment by adustinsky** [comment]
`<<<current_section = document.section[-1]  # last section in document`

**Comment by scanny** [comment]
Thanks @adustinsky, this is fixed and will go out with the upcoming release :)
