### ISSUE TITLE
how to read text along with inline shapes info?

### ISSUE THREAD

**Issue by pronan** [python-openxml/python-docx#286]
I have a simple docx file [like this][1](just insert a inline png file to text):[![enter image description here][2]][2]

I've tried:

    >>> x=docx.Document('12.docx')
    >>> for p in x.paragraphs:
        print(p.text)

        
    headend
    >>> list(x.inline_shapes)
    []

And I unzip `12.docx` file, found `word/media/image1.png` is the location. So is there a way to get a output like:

    >>> for p in x.paragraphs:
        print(p.text_with_image_info)

        
    head<word/media/image1.png>end

  [1]: http://pan.baidu.com/s/1mieqg2k
  [2]: http://i.stack.imgur.com/bJQTp.png

**Comment by scanny** [comment]
Not presently. You would have to iterate through the child elements of the `<w:p>` element for the paragraph at the lxml level for the time being.

There's been some talk about adding a `Paragraph.iter_run_level_items()` method that would do that but there's no clear commit on when that might be implemented.
