### ISSUE TITLE
enum missing

### ISSUE THREAD

**Issue by boukepieter** [python-openxml/python-docx#288]
I cannot find the enumerator WD_COLOR_INDEX. It is in the docs: https://python-docx.readthedocs.org/en/latest/api/enum/WdColorIndex.html. But I cannot find it in the code, so I cannot import it. I want to use it to highlight text.

**Comment by DKWoods** [comment]
It's in docx/enum/text.py of the develop branch rather than the master 
branch.

David

**Comment by scanny** [comment]
@boukepieter -- DKWoods contributed the highlight color feature a few weeks back (and it's already quite popular, I don't think we had any idea how quickly it would be :)

It's committed to the develop branch, but we haven't cut a new release that includes it, I'll try to get to that this week.

In the meantime, you can install from the develop branch if you like, which will give you access to that set of features.
