### ISSUE TITLE
When extracting table from docx the cell paragraph loses its format

### ISSUE THREAD

**Issue by MetaSKX** [python-openxml/python-docx#290]
Hi, I am trying to extract the content from a cell from a docx. I'm running this func

document = Document('my docx')
tables = document.tables
table = tables[1]

def get_bold_lines_from_cell(cellColumn, cellRow):
	#print table.cell(cellRow, cellColumn).text
	for paragraph in table.cell(cellRow, cellColumn).paragraphs:
		print paragraph._p
		for run in paragraph.runs:
			if run.bold:
				#do stuff

Even tho the paragraph is filled with bold letters, it doesn't recognize any

**Comment by scanny** [comment]
I expect the bold is being applied by a style rather than directly.

**Comment by MetaSKX** [comment]
If I run 

	for table in tables:
		for row in table.rows:
			for cell in row.cells:
				for paragraph in cell.paragraphs:
					for run in paragraph.runs:
						if run.bold:
							print run.text

It does find the .bold format

**Comment by scanny** [comment]
sounds like you need to narrow down where it's not doing what you expect.

**Comment by PradeepSmg** [comment]
@scanny ,

I am also facing same problem , run.bold not working for some columns .
Here is my code:
```
for table in WordDoc.tables:
    for i in xrange(1, len(table.rows)):
        for para in table.rows[i].cells[0].paragraphs:
            for run in para.runs:
                if run.bold and run.font.color.rgb == RGBColor(255,0,0):
                    print (run.text)
```
It does returns the bold text if change cells[0] to cells[1] but i have bold text in both cell 0 and cell 1.
I f you need I can upload the docx file aslo.
