### ISSUE TITLE
Iterate through paragraphs in w:sdtContent

### ISSUE THREAD

**Issue by BGrigorovich** [python-openxml/python-docx#295]
Hi, @scanny !

I have a template from client with paragraphs in w:body -> w:sdt -> w:sdtContent. The point is document.paragraphs doesn`t include it. Is there any way to get and iterate through this paragraphs?

**Comment by scanny** [comment]
If you'll prepare a minimum XML sample I'll have a look.

**Comment by BGrigorovich** [comment]
Here it is



    <w:body>
        <w:sdt>
            <w:sdtPr>
                <w:id w:val="1057208915"/>
                <w:docPartObj>
                    <w:docPartGallery w:val="Cover Pages"/>
                    <w:docPartUnique/>
                </w:docPartObj>
            </w:sdtPr>
            <w:sdtEndPr/>
            <w:sdtContent>
                 <w:p ... >
                    <w:pPr>
                        <w:pStyle w:val="Heading2"/>
                    </w:pPr>
                    <w:r w:rsidRPr="00021A82">
                        <w:t>Paragraph that is absent in document.paragraphs</w:t>
                    </w:r>
                </w:p>
                # another paragraphs that is absent in document.paragraphs
            </w:sdtContent>
        </w:sdt>
        <w:p ... >
            <w:pPr>
                ...
            </w:pPr>
            <w:r w:rsidRPr="00392B2D">
                <w:rPr>
                    ...
                </w:rPr>
                <w:t xml:space="preserve">Paragraph that is present in document.paragraphs</w:t>
            </w:r>
        </w:p>
        # another paragraphs that is present in document.paragraphs
    </w:body>

**Comment by scanny** [comment]
Can you provide some psuedo-code of what you'd like to accomplish?

Like just the paragraphs in a particular w:sdt or them mixed in, in order, with regular paragraphs?

**Comment by scanny** [comment]
The general approach would be to use XPath to identify the elements you're interested in, then construct Paragraph instances with those elements. So for example:

```python
document = document('my-docx.docx')
body = document._body._body
ps = body.xpath('//w:p')
for p in ps:
    yield Paragraph(p, document._body)
```

I haven't tested this code, so I expect it would have to be tweaked a bit, but should give an idea.

**Comment by BGrigorovich** [comment]
Your code works great, that was exactly what I need! Thanks a lot!

**Comment by scanny** [comment]
Glad you got it working :)

**Comment by marcj** [comment]
I had to iterate through sdtPr/sdtContent as well, but they were withing w:p, like so

```xml
 <w:p w14:paraId="2E615ACB" w14:textId="76945A11" w:rsidR="00265042" w:rsidRDefault="00000000"
     w:rsidP="00DC2005">
    <w:pPr>
        <w:ind w:left="3827" w:hanging="3402"/>
    </w:pPr>
    <w:sdt>
        <w:sdtPr>
            <w:rPr>
                <w:rFonts w:cs="Arial"/>
                <w:szCs w:val="22"/>
            </w:rPr>
            <w:alias w:val="Projekt"/>
            <w:tag w:val="Projekt"/>
            <w:id w:val="1036313954"/>
            <w:placeholder>
                <w:docPart w:val="E0B48EFE95594B67B366D4C5EBE98D8F"/>
            </w:placeholder>
            <w:comboBox>
                <w:listItem w:displayText="Projekt:" w:value="Projekt:"/>
                <w:listItem w:displayText="Warenart:" w:value="Warenart:"/>
            </w:comboBox>
        </w:sdtPr>
        <w:sdtContent>
            <w:r w:rsidR="00212B54">
                <w:rPr>
                    <w:rFonts w:cs="Arial"/>
                    <w:szCs w:val="22"/>
                </w:rPr>
                <w:t>Projekt:</w:t>
            </w:r>
        </w:sdtContent>
    </w:sdt>
    <w:r w:rsidR="00212B54">
        <w:rPr>
            <w:rFonts w:cs="Arial"/>
            <w:szCs w:val="22"/>
        </w:rPr>
        <w:tab/>
    </w:r>
    <w:r w:rsidR="00DC2005" w:rsidRPr="00774494">
        <w:t>Modernisierung von Stahlwerk</w:t>
    </w:r>
    <w:r w:rsidR="006F5945">
        <w:t>s</w:t>
    </w:r>
    <w:r w:rsidR="00DC2005" w:rsidRPr="00774494">
        <w:t>komponenten</w:t>
    </w:r>
</w:p>
```

For anyone with the same issue, here is how I solved it:

```python

import docx
from docx.oxml import CT_P, register_element_cls
from docx.text.paragraph import Paragraph

register_element_cls('w:sdtContent', CT_P)

file = "file.docx"
my_doc = docx.Document(file)

for p in my_doc.paragraphs:
    sdtContent = p._element.xpath('.//w:sdtContent')
    for additional in sdtContent:
        p2 = Paragraph(additional, my_doc._body)
        print(p2.text)
    print(p.text)
```
