### ISSUE TITLE
py3 Error: isinstance(Length, paragraph_format.line_spacing)

### ISSUE THREAD

**Issue by waterdr0p** [python-openxml/python-docx#297]
https://python-docx.readthedocs.io/en/latest/user/text.html

Line spacing
>>> from docx.shared import Length
>>> paragraph_format.line_spacing
None
>>> paragraph_format.line_spacing_rule
None

>>> paragraph_format.line_spacing = Pt(18)
>>> isinstance(Length, paragraph_format.line_spacing)
In [20]: isinstance(Length, pfmt.line_spacing)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-c40a854323de> in <module>()
----> 1 isinstance(Length, pfmt.line_spacing)

TypeError: isinstance() arg 2 must be a type or tuple of types
In [23]: type(Length)
Out[23]: type

In [24]: type(pfmt.line_spacing)
Out[24]: docx.shared.Twips

**Comment by scanny** [comment]
Fixed. Will appear in next release. Thanks for the heads-up @waterdr0p :)
