### ISSUE TITLE
styles['Heading 1'].next_paragraph_style don't work well

### ISSUE THREAD

**Issue by waterdr0p** [python-openxml/python-docx#299]
https://python-docx.readthedocs.io/en/latest/user/styles-using.html#add-or-delete-a-style
issue: I have tried following python demo code, but I can't see them work well in office word2016.(No Error Raised)

'''
>>> from docx import Document
>>> document = Document()
>>> styles = document.styles

>>> styles['Heading 1'].next_paragraph_style = styles['Body Text']
'''

# my demo code
styles = document.styles
styles['Heading 1'].next_paragraph_style = styles['Colorful Grid']
document.add_paragraph("Working with Styles", style='Heading 1')
p7 = document.add_paragraph('next_paragraph_style' * 20)

# ipython shell code
In [14]: styles['Heading 2'].next_paragraph_style
Out[14]: _ParagraphStyle('Normal') id: 2512638940664

**Comment by scanny** [comment]
I believe 'Colorful Grid' is a table style. Does it work with paragraph styles?

**Comment by waterdr0p** [comment]
I tried using paragraph styles, 'Colorful Grid' is another try for table style, but still don't work. 
The code:
import os
from docx import Document
document = Document()
styles = document.styles
styles['Heading 1'].next_paragraph_style = styles['List Bullet']  
document.add_paragraph("Working with Styles", style='Heading 1')
p7 = document.add_paragraph('next_paragraph_style' * 20)
fn = 'styles.docx'
document.save(fn)
os.popen(fn)

**Comment by scanny** [comment]
So it looks like no error is raised. What's the behavior you expect and what behavior are you observing instead?

**Comment by waterdr0p** [comment]
I expect the next paragraph style will be "List Bullet" by default, but the variable "p7" create paragraph  style for "Normal" instead of  "List Bullet".
I can also specify paragraph styles through  "p7 = document.add_paragraph('next_paragraph_style' * 20, style='List Bullet')" to observe the different with "styles['Heading 1'].next_paragraph_style = styles['List Bullet']".

**Comment by scanny** [comment]
This setting isn't operative in python-docx, only in Word. If you want to add a following paragraph in python-docx, you'll need to set it to the style you want yourself.

**Comment by waterdr0p** [comment]
OK, I see, thank you.
