### ISSUE TITLE
Getting an empty string from hyperlink text in table cell

### ISSUE THREAD

**Issue by lseongjoo** [python-openxml/python-docx#304]
When extracting text from hyperlink in table cell, below either cell.text or paragraphs in cell

``` python
for cell in row.cells:
    print(cell.text) # if hyperlink, empty
    cell_text = ''    
    for p in cell.paragraphs:
        cell_text += p.text # if hyperlink, empty
    print(cell_text, end=' ')
```

**Comment by q210** [comment]
I too stumbled into this problem. 
Sadly it's not that easy to fix ( reasons are explained here - https://github.com/python-openxml/python-docx/pull/377#issuecomment-287474988 ).
 
AFAIK there is some progress on this in the issue #85 and official patch will be released eventually, but if you need this working right now and content only getting text from hyperlinks, you can install package with this quick and dirty hack https://github.com/q210/python-docx/commit/336ed9fed27ff0460b674d91ba1646ded9cecb59 from my own fork (based on patch proposed by Brad-Python in #85 )

pip command is:
`pip install git+git://github.com/q210/python-docx.git@336ed9fed27ff0460b674d91ba1646ded9cecb5`

P.S. I'll copy answer this to relevant SO questions and other similar issues just so people googling it in the future will spend less time understanding the problem than I did yesterday.

**Comment by EZFPM7856C** [comment]
I suggest you can better select the piece of text and press ctrl+shift+F9
All hyper links will be removed and will display the plain text(Display text)

**Comment by scanny** [comment]
`Paragraph.text` will include the text of hyperlinks in the forthcoming `v1.0` due out in a week or so.
