### ISSUE TITLE
style is changed when replace text in table

### ISSUE THREAD

**Issue by yangyaofei** [python-openxml/python-docx#314]
when i execute this code below ,the changed sell's style is not same as the onther cells in this tables too.
``` python
document = Document(name)
tables = [table for table in document.tables];

for table in tables:
    for row in table.rows:
        for cell in row.cells:
            if "AAA" in cell.text:
                cell.text = cell.text.replace("AAA","ASD")
```

**Comment by scanny** [comment]
Please post support questions on StackOverflow. The issues list is for feature requests and suspected bugs.

This behavior is expected and covered in the documentation.
