### ISSUE TITLE
No relationship issue

### ISSUE THREAD

**Issue by boxconnect** [python-openxml/python-docx#318]
When trying to open a `.dot` file, I am getting the error:

    KeyError: "no relationship of type 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument' in collection"

I have searched on the internet including stackoverflow but have not come to a satisfying result - what is the actual problem here?
Thanks a lot!

**Comment by scanny** [comment]
Are you sure it's an XML-based word file? The .dot extension was for the earlier Word format which python-docx doesn't support.
https://support.office.com/en-us/article/Introduction-to-new-file-name-extensions-eca81dcb-5626-4e5b-8362-524d13ae4ec1

**Comment by boxconnect** [comment]
The file in question is https://www.dropbox.com/s/i9x7byy2js0z5qy/aa.dot?dl=0 I did ask on [SO](http://stackoverflow.com/questions/39104325/no-relationship-of-type-when-opening-word-document-with-python/39104723?noredirect=1#comment65584172_39104723) as well.

**Comment by boxconnect** [comment]
Not sure why, but when saving the `.dot` as `docx`, it works.

**Comment by scanny** [comment]
For anyone finding this on search, the file in question was a legacy (Word 2003 and earlier) template file, which is not supported in `python-docx`. Only the OpenXML-based Word 2007 file formats are supported.
