### ISSUE TITLE
Can python-docx be accessed from IronPython?

### ISSUE THREAD

**Issue by GeoffSchmidt** [python-openxml/python-docx#325]
I am trying to use IronPython to create and manipulate Word document via python-docx.  My code runs using Python27 but when using IronPython I receive an ImprtError:  cannot import etree from lxml.    Any help would be GREATLY appreciated.  This is all very new to me.   Thanks!

**Comment by scanny** [comment]
Yes, it can. I use IronPython whenever I need to check some aspect of the MS API.

The problem you're having seems to indicate you don't have `lxml` installed. `lxml` needs to be installed as a binary distribution on Windows unless you have a C compiler installed. A search on 'install lxml windows' should get you the information you need.
