### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by marcmaxson** [python-openxml/python-docx#334]
I used `pip install python-docx` and it installed without an error. But in python 2.7.5 I see:

>>> import docx
>>> import docx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/keystonetech/lib/python2.7/docx/__init__.py", line 3, in <module>
    from docx.api import Document  # noqa
  File "/home/keystonetech/lib/python2.7/docx/api.py", line 14, in <module>
    from docx.package import Package
  File "/home/keystonetech/lib/python2.7/docx/package.py", line 11, in <module>
    from docx.opc.package import OpcPackage
  File "/home/keystonetech/lib/python2.7/docx/opc/package.py", line 12, in <module>
    from .part import PartFactory
  File "/home/keystonetech/lib/python2.7/docx/opc/part.py", line 12, in <module>
    from .oxml import serialize_part_xml
  File "/home/keystonetech/lib/python2.7/docx/opc/oxml.py", line 12, in <module>
    from lxml import etree
ImportError: /home/keystonetech/lib/python2.7/lxml/etree.so: undefined symbol: PyUnicodeUCS2_DecodeLatin1

What's wrong?

**Comment by marcmaxson** [comment]
it worked on my local machine running anaconda, but on my server (centos 7) I cannot install it and run it.

**Comment by scanny** [comment]
This looks like an lxml install error of some type. I recommend searching on 'centos lxml install' or such, maybe including the error message.

One of the common problems on Linux is not having the libxml2 and libxslt installed; this might be related to that.

**Comment by marcmaxson** [comment]
python has lxml installed, and THAT imports fine. Is that different from the centos lxml?

**Comment by scanny** [comment]
does `from lxml import etree` work from the Python command line? That's the call that giving rise to the error.

**Comment by marcmaxson** [comment]
from webfaction, the hosting company: they said uninstall my user lxml, and
use the system default lxml instead. This solved the problem. There was
probably some version conflict between both lxml modules on the system. I
didn't know centos 7 came with lxml, but this version does.

**Comment by scanny** [comment]
Glad you got it work @marcmaxson :)
