### ISSUE TITLE
No option to set the text direction?

### ISSUE THREAD

**Issue by SHxKM** [python-openxml/python-docx#349]
I'm trying to read and write (to a new) document in RightToLeft, non-latin language. After a few hours I'm almost done, and a little horrified as I don't see an option or anything in the documentation on setting the text direction. (specifically in my case: from LTR to RTL)

Does python-docx not have the ability to set it? 

Thanks for a great library!

**Comment by saeedb73** [comment]
I have the same problem. Did you find any solution?

**Comment by SHxKM** [comment]
Hi @saeedb73. Luck you, I've opened this over three years ago but found the relevant snippet I used:

```python
...
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

...
first_paragraph = new_document.add_paragraph()
run_format = first_paragraph.paragraph_format
run_format.alignment = WD_ALIGN_PARAGRAPH.RIGHT # <---
rel_text = first_paragraph.add_run(list_of_paragraphs[i])
rel_text.style = mystyle
font = rel_text.font
font.rtl = True # <---
...

```

**Comment by yoeldk** [comment]
@SHxKM Thanks for this. However, it seems the text direction in the created document is still LTR instead of RTL (see attached image). This means that any bullets added will be shown on the left side. Did you manage to solve that too?
TIA!
![image](https://github.com/python-openxml/python-docx/assets/12507451/7d10211d-9fa5-41ea-a2cc-fadb65abae89)

**Comment by SwimmingRieux** [comment]
> @SHxKM Thanks for this. However, it seems the text direction in the created document is still LTR instead of RTL (see attached image). This means that any bullets added will be shown on the left side. Did you manage to solve that too? TIA! ![image](https://private-user-images.githubusercontent.com/12507451/308544603-7d10211d-9fa5-41ea-a2cc-fadb65abae89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDUzNDcsIm5iZiI6MTcxODcwNTA0NywicGF0aCI6Ii8xMjUwNzQ1MS8zMDg1NDQ2MDMtN2QxMDIxMWQtOWZhNS00MWVhLWEyY2MtZmFkYjY1YWJhZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEwMDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTNkMTYwMDFmY2I4NGYwZDAwZWRjM2E5M2Y1NGJmZGUzODk4MzY3MTkxMjU0ODVlOThhODE4ZWNkYjkwYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DIZOe5O7YiwtO7_Eq-e1tv0jXcW2C-c26VjNZzud_EE)

https://stackoverflow.com/a/67648283

works for me!
