### ISSUE TITLE
"Table of Contents" Feature

### ISSUE THREAD

**Issue by dmr** [python-openxml/python-docx#36]
I just discovered this great project and I wonder if there is a feature to add a Table of Contents to a document that I create with python-docx.
I need to generate a .docx file for a customer and he wants to have a TOC in it.

**Comment by mustash** [comment]
Hi @scanny , as always, thanks for your extensive help with using python-docx on various forums. Out of curiosity, how would I add the value "TOC \* MERGEFORMAT" in your example (or in my case,  TOC \o "1-3" \h \z \u  -- as seen from the XML listing of a ToC I inserted into a word doc).

It appears I can "append" a new element, or "set" an attribute to any tag, but I have yet to come across any LXML documentation that describes how I can set the tag value itself (the content between the open and close tags).

Any input would be appreciated.

**Comment by mustash** [comment]
Thanks for the preview of the solution, @scanny . Cannot tell you how useful your comments are in implementing the few outstanding to-do features in what truly is a fantastic library.

For anyone else looking for a full working solution, here is what I came up with, to generate the single line that inserts the TOC field. Auto-updating the TOC was outside of my capabilities for the time being so I'll leave it to someone else to take over:

		paragraph = self.document.add_paragraph()
		run = paragraph.add_run()
		fldChar = OxmlElement('w:fldChar')  # creates a new element
		fldChar.set(qn('w:fldCharType'), 'begin')  # sets attribute on element
		instrText = OxmlElement('w:instrText')
		instrText.set(qn('xml:space'), 'preserve')  # sets attribute on element
		instrText.text = 'TOC \o "1-3" \h \z \u'  # change 1-3 depending on heading levels you need
				
		fldChar2 = OxmlElement('w:fldChar')  # creates a new element
		fldChar2.set(qn('w:fldCharType'), 'separate')  # sets attribute on element
		fldChar3 = OxmlElement('w:t')  # creates a new element
		fldChar3.text = "No table of contents entries found."
		fldChar2.append(fldChar3)

		fldChar4 = OxmlElement('w:fldChar')  # creates a new element
		fldChar4.set(qn('w:fldCharType'), 'end')  # sets attribute on element

		r_element = run._r
		r_element.append(fldChar)  # adds new element as last child
		r_element.append(instrText)
		r_element.append(fldChar2)  # adds new element as last child
		r_element.append(fldChar4)
		p_element = paragraph._p

**Comment by madphysicist** [comment]
I ran into this issue when searching for how to make a TOC. For my purposes, having a stub that the user can click on to update is better than nothing. Therefore, if even the partial solution were to make it into python-docx, I would use it immediately. I am currently using @mustash's code for doing just that.

**Comment by xie186** [comment]
@mustash Thanks for the code you posted. It works. But I need to update the fields manually. Is there a way to update the field in the python code?

**Comment by snowflake01986** [comment]
@mustash Could you please complete your code a little more, I am too naive to work it out. Besides, where does the 'self' come from? Thank you. wish you could still see my question :)

    paragraph = self.document.add_paragraph()
    run = paragraph.add_run()
    fldChar = OxmlElement('w:fldChar')  # creates a new element
    fldChar.set(qn('w:fldCharType'), 'begin')  # sets attribute on element
    instrText = OxmlElement('w:instrText')
    instrText.set(qn('xml:space'), 'preserve')  # sets attribute on element
    instrText.text = 'TOC \o "1-3" \h \z \u'   # change 1-3 depending on heading levels you need

    fldChar2 = OxmlElement('w:fldChar')
    fldChar2.set(qn('w:fldCharType'), 'separate')
    fldChar3 = OxmlElement('w:t')
    fldChar3.text = "Right-click to update field."
    fldChar2.append(fldChar3)

    fldChar4 = OxmlElement('w:fldChar')
    fldChar4.set(qn('w:fldCharType'), 'end')

    r_element = run._r
    r_element.append(fldChar)
    r_element.append(instrText)
    r_element.append(fldChar2)
    r_element.append(fldChar4)
    p_element = paragraph._p

**Comment by Sup3rGeo** [comment]
@snowflake01986 just replace `self.document` with your `document` object.

**Comment by Sup3rGeo** [comment]
If we need to generate a PDF, this project uses word to actually update the docx (including TOC) file prior to exporting. It does not actually saves the updated docx file and of course you need MS Word installed.
https://github.com/cognidox/OfficeToPDF

@scanny is it possible that an open-source software like LibreOffice have this TOC update implemented that could be used by this project?

**Comment by scanny** [comment]
It's possible. It's been a while since I've looked into it, but I believe there is some sort of library (API) access to LibreOffice. I don't believe it's Python. I think it's Java or C++, possibly both. I don't know if it requires the LibreOffice application to be running or not (the way the Microsoft VBA API does). It may be worth taking a look at though. A search on "libreoffice api" will get you where you want to start looking.

**Comment by Sup3rGeo** [comment]
@scanny Thanks for the directions.
Based on this idea I actually have just started a project this is an application to use LibreOffice to update indexes and generate a pdf. It seems to be working already and it should work on Windows and Linux:
https://github.com/typhoon-hil/LibreOfficeToPDF

I am working on generating binaries so no need to be tied to python.

Why not
1- add @mustash code to insert a TOC element in the main python-docx library
2- add to documentation that, to update indexes, both OfficeToPDF and LibreOfficeToPDF can be used?

**Comment by wangcheng-git** [comment]
Is there a solution that supports liunx?

**Comment by gshmu** [comment]
@wangcheng-git libreoffice with pyton3-uno work well under ubuntu.
you can see @Sup3rGeo 's project. but the project can't work under mac OS, because: libreoffice's Python not work.

**Comment by rohitg-lotusdew** [comment]
After two days of searching exhaustively for a solution, here is what I found (just summarizing the info and adding one additional step I couldn't directly find anywhere):

- Showing up a ToC in Word works in two steps:
1. Inserting the ToC metadata (style, position, indentation)
2. Actually rendering the ToC

Code provided by @mustash is currently the best (and sufficient) way to achieve #1. 

There are a number of ways to achieve #2. But **all** of those ways require running Word layout engine - meaning running MS Word either directly or through CLI/VBA/pywin32/etc.

Quick ways to do it:
1. Insert the line `fldChar.set(qn('w:dirty'), 'true')` next to the line `fldChar.set(qn('w:fldCharType'), 'begin')` in the code provided by @mustash . This will trigger word to prompt the user to run update on opening the Word document (everytime it is opened) and the ToC will get updated once user clicks Yes
2. If the document is being created on a Windows machine and has MS Word installed, add the following method to the python script and call it with the name of the docx file (after running doc.save(file_name))
```
def update_toc(file_name):
    script_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
    file_path = os.path.join(script_dir, file_name)
    word = win32com.client.DispatchEx("Word.Application")
    doc = word.Documents.Open(file_path)
    doc.TablesOfContents(1).Update()
    doc.Close(SaveChanges=True)
    word.Quit()
```
Sources:
1. @scanny answers on this issue
2. https://groups.google.com/d/msg/python-docx/VnHD7AwmPgY/VxwhZwB-UcwJ
3. https://stackoverflow.com/a/34818909/7720280
4. http://www.ericwhite.com/blog/exploring-tables-of-contents-in-open-xml-wordprocessingml-documents-part-2/

**Comment by FatimaArshad-DS** [comment]
Is there any way to not prompt a user to update and automatically update the TOC?

**Comment by chrischma** [comment]
> 

+1

**Comment by ndahn** [comment]
Is it possible to set the TOC's style? For me it always defaults to Arial 9 on update.

**Comment by deepak-coding-art** [comment]
is there is any other eat to update table of content indexes without this manual step

**Comment by nathan-149** [comment]
+1

**Comment by dmr** [comment]
I ended up using latex for documents that need a TOC, unsure if there is something new in the python docx world

**Comment by dribeiro09** [comment]
Using the `updateFields` seems to prompt the user to update all other fields marked as dirty. On my particular scenario I have the TOC being generated by a user of the application. I would then like to change the document in a way that every time it opens the document it will ask to update the table of contents only. Any idea on how to achieve this ?

**Comment by Flyomega** [comment]
I have a bug using this code. the problem is that it creates me multiple table of contents in the doc. I dont know why. There are all the same but the final document has 3 or 4 toc.

**Comment by Ahellrigel33** [comment]
> Is it possible to set the TOC's style? For me it always defaults to Arial 9 on update.

It appears to inherit styles based off the 'Normal' style when it generates the needed styles on update. Whatever is set in document.styles['Normal'] will be used when generating these styles. However, I'm not sure how to get it to use different styles for the different "Levels" in the TOC.

**Comment by ajaydevaraj63** [comment]
hi ,Is this works for  linux system

paragraph = self.document.add_paragraph()
run = paragraph.add_run()
fldChar = OxmlElement('w:fldChar')  # creates a new element
fldChar.set(qn('w:fldCharType'), 'begin')  # sets attribute on element
instrText = OxmlElement('w:instrText')
instrText.set(qn('xml:space'), 'preserve')  # sets attribute on element
instrText.text = 'TOC \o "1-3" \h \z \u'   # change 1-3 depending on heading levels you need

fldChar2 = OxmlElement('w:fldChar')
fldChar2.set(qn('w:fldCharType'), 'separate')
fldChar3 = OxmlElement('w:t')
fldChar3.text = "Right-click to update field."
fldChar2.append(fldChar3)

fldChar4 = OxmlElement('w:fldChar')
fldChar4.set(qn('w:fldCharType'), 'end')

r_element = run._r
r_element.append(fldChar)
r_element.append(instrText)
r_element.append(fldChar2)
r_element.append(fldChar4)
p_element = paragraph._p

**Comment by Zzabi** [comment]
Hi,

How can I add numbers to toc

As in

1. Main heading
    1.1 sub heading
2. Main heading
    2.1 sub heading
    2.2 sub headin

**Comment by scottzach1** [comment]
@Zzabi numbering is not configured in the TOC but instead by configuring numbering for the headings. That is beyond this scope of this issue but your best bet to achieve this would be:

1. Generate a blank document using python-docx

   ```python
   from docx import Document

   doc = Document()
   doc.save("template.docx")
   ```

2. Open the document using Microsoft Word
3. Configure numbered headings

    _Make sure to create a heading and ensure the numbering is applied before clearing the document. For the reason why see https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html#why-doesn-t-the-style-i-applied-show-up_

    ![Image](https://github.com/user-attachments/assets/400ed826-fc6a-4985-b6e6-4c39c4eb35ae)

4. Save the document
5. You may now use the template.docx file for your scripts

   ```python
   from docx import Document

   doc = Document("template.docx")
   doc.add_heading("Hello World", 1)
   ... # <- insert your table of contents using method above
   ```

I was developing a proper work around for this but unfortunately I ran out of time debugging. I may come back around to this in the future.

**Comment by scottzach1** [comment]
This is the solution I ended up settling on. It's pretty similar to @mustash's implementation, but contains some subtle XML differences. These changes were generated using the latest Microsoft Word.

```python
from docx import Document
from docx.opc.oxml import BaseOxmlElement
from docx.oxml import OxmlElement
from docx.oxml.ns import qn


def add_toc(document: Document):
    r"""
    Insert a blank table of contents.

    Derived from the following comment: https://github.com/python-openxml/python-docx/issues/36#issuecomment-145302669

    Raw XML to insert:
    ```xml
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
        <w:r>
            <w:fldChar w:fldCharType="begin"/>
        </w:r>
        <w:r>
            <w:instrText xml:space="preserve"> TOC \o "1-3" \h \z \u </w:instrText>
        </w:r>
        <w:r>
            <w:fldChar w:fldCharType="separate"/>
        </w:r>
        <w:r>
            <w:rPr>
                <w:b/>
                <w:bCs/>
                <w:noProof/>
                <w:lang w:val="en-US"/>
            </w:rPr>
            <w:t>Right click to update TOC</w:t>
        </w:r>
        <w:r>
            <w:rPr>
                <w:b/>
                <w:bCs/>
                <w:noProof/>
            </w:rPr>
            <w:fldChar w:fldCharType="end"/>
        </w:r>
    </w:p>
    ```
    """
    paragraph = document.add_paragraph()
    _ = document.add_paragraph()  # add paragraph after TOC for convenience

    # noinspection PyListCreation
    items: list[list[BaseOxmlElement]] = []

    # <w:fldChar w:fldCharType="begin"/>
    items += [[OxmlElement("w:fldChar", attrs={qn("w:fldCharType"): "begin"})]]

    # <w:instrText xml:space="preserve"> TOC \o "1-3" \h \z \u </w:instrText>
    items += [[OxmlElement("w:instrText", attrs={qn("xml:space"): "preserve"})]]
    items[-1][0].text = ' TOC \\o "1-3" \\h \\z \\u '
    # <w:fldChar w:fldCharType="separate"/>
    items += [[OxmlElement("w:fldChar", attrs={qn("w:fldCharType"): "separate"})]]
    # <w:rPr>
    #     <w:b/>
    #     <w:bCs/>
    #     <w:noProof/>
    #     <w:lang w:val="en-US"/>
    # </w:rPr>
    # <w:t>No table of contents entries found.</w:t>
    items += [[OxmlElement("w:rPr"), OxmlElement("w:t")]]
    items[-1][0].append(OxmlElement("w:b"))
    items[-1][0].append(OxmlElement("w:bCs"))
    items[-1][0].append(OxmlElement("w:noProof"))
    items[-1][0].append(OxmlElement("w:lang", attrs={qn("w:val"): "en-US"}))
    items[-1][1].text = "Right click to update TOC"

    # <w:rPr>
    #     <w:b/>
    #     <w:bCs/>
    #     <w:noProof/>
    # </w:rPr>
    # <w:fldChar w:fldCharType="end"/>
    items += [[OxmlElement("w:rPr"), OxmlElement("w:fldChar", attrs={qn("w:fldCharType"): "end"})]]
    items[-1][0].append(OxmlElement("w:b"))
    items[-1][0].append(OxmlElement("w:bCs"))
    items[-1][0].append(OxmlElement("w:noProof"))

    for run_contents in items:
        run = paragraph.add_run()

        for item in run_contents:
            # noinspection PyProtectedMember
            run._r.append(item)
```

**Comment by Caxxxxie** [comment]
I met with the same problem today so I wanted to ask if it's possible to run LibreOffice's UNO (Universal Network Objects) API? It would be really nice if someone has tried this approach!
