### ISSUE TITLE
WD_ROW_HEIGHT_RULE conflict with docs v0.8.6 

### ISSUE THREAD

**Issue by klingerdinger** [python-openxml/python-docx#362]
[The v0.8.6 documentation](http://python-docx.readthedocs.io/en/latest/api/enum/WdRowHeightRule.html) implies that an enum exists that allows one to set the row height, however this appears to be in conflict with the master (and PIP) branch. Can this development feature be filtered through to the master, or should the documentation be amended to indicate that this isn't available yet?

**Comment by scanny** [comment]
I find these in place and in good order. What behavior leads you to conclude they are not there?

**Comment by scanny** [comment]
Ah, yes, I see. These are part of a feature branch that hasn't been committed yet. This will be in the next release.

**Comment by rustymyers** [comment]
Well, that explains why I can't get it to work! Spent the last day trying to get a _Row height when it told me _Row didn't have a height, but the docs and code said it was there. Tried updating through pip, but didn't' get 0.8.6, and through they would be in 0.8.5. Cool cool cool cool.

**Comment by mattychen** [comment]
Any updates on this?

**Comment by Aens** [comment]
Still missing, apparently.

**Comment by melona277** [comment]
Still missing :( Any updates?

**Comment by scanny** [comment]
Fixed in release v0.8.7 circa Aug 18 2018.
