### ISSUE TITLE
where is WD_ROW_HEIGHT?

### ISSUE THREAD

**Issue by retsyo** [python-openxml/python-docx#369]
I am reading https://python-docx.readthedocs.io/en/latest/api/enum/WdRowHeightRule.html

But I can't find WD_ROW_HEIGHT. What happened?

**Comment by scanny** [comment]
`WD_ROW_HEIGHT` is a (shorter) "alias" for `WD_ROW_HEIGHT_RULE`. You include it from the same place as the full-length version and use it the same way.

Some of the enumeration names get long, so shorter versions are provided to keep the code more compact. They're noted as an "alias:" in the documentation page for that enumeration, as you can see on the page you linked.
