### ISSUE TITLE
How to create numbered structured text and numbered figure?

### ISSUE THREAD

**Issue by frenet** [python-openxml/python-docx#37]
I'd like to create  in docx by python-docx  such a structured text：
1.  chapter 1
1.1.    section 1
1.2.    section 2
2.  chapter 2
2.1.    section 1
2.2.    section 2
2.3.    chapter 3
2.3.1.  subsection 1
2.3.2.  subsection 2

which can also be edited in ms office, when I delete "2.2.  section 2", then "2.3.  chapter 3", will become “2.2. chapter 3” automatically, and its subsection number will change automatically too, that is "2.3.1.    subsection 1" to "2.2.1.    subsection 1", "2.3.2.  subsection 1" to "2.2.2.    subsection 1"

In fact, the structured text in ms word format is from a .xmind file created by xmind 3.4.1, so I wonder whether it can be created by python-docx?  

A similar question is about the numbered figures, how can the number of figures can change automatically, for example, when I delete a figure, those figure  number behand this figure will reduce 1 automatically.

**Comment by Thebee23** [comment]
Hi frenet, have you got solution for that?

**Comment by de-adshot** [comment]
Hi is there a solutioin for this thread.. I dont see any sollution for the initial question anywhere @scanny @frenet ?

**Comment by Test202010** [comment]
> I'm not familiar with xmind @frenet, but it sounds like what you're looking for is auto-numbering chapter and section headings. That is definitely doable with python-docx.
> 
> [Here's one link](http://shaunakelly.com/word/numbering/numbering20072010.html) that should get you started.
> 
> Essentially what you do is define your Heading 1 - Heading 9 styles so they are connected to an outline-numbered numbering definition. Then they automatically number themselves like you want. All that's left is to apply the right level heading style to the chapter and heading paragraphs.

The number should be re-auto-numbering in different section. The solution above don't satisfied the need.
