### ISSUE TITLE
Adding header not working

### ISSUE THREAD

**Issue by ardyflora** [python-openxml/python-docx#373]
hi,

I was looking at this pull request:
https://github.com/python-openxml/python-docx/pull/291

I went on to test it and did the following:
header = section.header
header.text = 'foobar'
Reference for code:
http://python-docx.readthedocs.io/en/latest/dev/analysis/features/header.html?highlight=header

Section object has no object [header]

I think this feature is implemented but not included. Please correct if I am wrong.

http://python-docx.readthedocs.io/en/latest/api/section.html#docx.section.Section

I am not sure as it says it is active. I think it means work is been done.

**Comment by scanny** [comment]
I was using the `active` flag to identify pull requests that were being worked on, but this one has stalled (as many of them do) and the work didn't progress very far I'm afraid. In any case, it hasn't been merged and so that feature is still pending.

**Comment by ardyflora** [comment]
oh do you have an idea when it will be added?

**Comment by scanny** [comment]
If you want a delivery commitment you'll need to build it yourself or sponsor the feature.
