### ISSUE TITLE
docx fails to import when python run with -OO optimizations

### ISSUE THREAD

**Issue by rasjidw** [python-openxml/python-docx#375]
The docx.enum.base module fails to load when python is run with -OO optimizations turned on, which means that docx itself cannot be imported.

The issue is in line 60 of docx.enum.base.py: 
`cls_docstring = self._clsdict['__doc__']`

A KeyError is not raised, but instead cls_docstring is set to None, which causes the textwrap.dedent call to fail.

**Comment by scanny** [comment]
This came up on `python-pptx` earlier. This is fixed by adding:

```python
if cls_docstring is None:
    return ''
```

after the try block. I'll get this into the next release.

**Comment by scanny** [comment]
Fixed in release v0.8.7 circa Aug 18 2018.
