### ISSUE TITLE
File corrupted on  paragraph insert with text Box

### ISSUE THREAD

**Issue by mbdax034** [python-openxml/python-docx#388]
Hello

I found this function to add content to another docx:

```
  def direct_insert(self,doc_dest, doc_src):
      for k,p in enumerate(doc_src.paragraphs):
            inserted_p = doc_dest._body._body._insert_p(p._p)
            if p._p.get_or_add_pPr().numPr:
                inserted_p.style = "ListNumber"
```

When i open the file with MS WORD i got message : 

> We’re sorry. We can’t open DocumentName.docx because we found a problem with its contents.
> When I want to see Details the following message shows:
> Unspecified error
> Location: Part: /word/document.xml, Line 2, Column: 0.

i have done a break in loop for paragraph to debug and i realise that is the textBox hwo makes problems

**Comment by scanny** [comment]
This is a random block of code that manipulates the underlying XML directly. There's no guarantee from me (of course) that this sort of thing will work. It's commonly done, but relies on the skill of the developer to understand what they're doing and get it right. I suggest you appeal to the author for help or work out how to write your own.

**Comment by mbdax034** [comment]
Thanks for your response

**Comment by Clorel** [comment]
i have this problem, the support of block alternatecontent is possible ?
When i repared the file, the majority changes has keys rIdPr, rIdR, etc in document.xml

You see others changes in yours .docx ?
