### ISSUE TITLE
How to change the font of heading?

### ISSUE THREAD

**Issue by frenet** [python-openxml/python-docx#390]
the python code is as following, it runs without any error happened, but the font of the heading does not changed at all:

def test_hyperlinnk():
    import docx
    document = docx.Document() 
    from docx.enum.style import WD_STYLE_TYPE    
    styles = document.styles
    new_heading_style = styles.add_style('New Heading', WD_STYLE_TYPE.PARAGRAPH)
    new_heading_style.base_style = styles['Heading 1']
    font = new_heading_style.font
    font.name =u'楷体';     
    h=document.add_paragraph(style='New Heading') 
    add_hyperlink(h, 'http://www.sohu.com/', u'搜狐新闻, 楷体显示')
    document.save('demo_hyperlink.docx')

**Comment by frenet** [comment]
![Uploading QQ截图20170421094415.jpg…]()

**Comment by frenet** [comment]
![qq 20170421094415](https://cloud.githubusercontent.com/assets/6078409/25259431/95ba35fc-2678-11e7-9507-d75083bdcd4d.jpg)

**Comment by scanny** [comment]
see #154
