### ISSUE TITLE
Adding new pages to label document

### ISSUE THREAD

**Issue by ronyan1** [python-openxml/python-docx#391]
I am using python-docx to automate the filling in of cells of a label template which I open in python-docx. What I need to do is add a page containing a table that matches the formatting of the original table on the first page of the template each time the number of cells is exceeded for the current page (this is normally done just by tabbing on the last cell of the page). I believe I can do this by adding a page_break then adding a table to new page (and setting the formatting), but I have not got the code to work so far.

**Comment by scanny** [comment]
This sounds like a topic best taken up on StackOverflow @ronyan1 

Make sure you actually formulate your question before you post (above is a statement, not a question) and tag it with 'python-docx'.
