### ISSUE TITLE
Caption numbering and cross-references

### ISSUE THREAD

**Issue by KevinVancauwenbergh** [python-openxml/python-docx#398]
When adding a caption to a figure or table, the caption is inserted as flat text.
In order to have automatic caption numbering, and to be able to create cross-references and index tables, this should be a field.

Is there already functionality to achieve this or should I clone the project and try to implement this myself?

Kind regards,
Kevin

**Comment by KevinVancauwenbergh** [comment]
Solved by implementing #359.
Thanks!

**Comment by SaetreS** [comment]
How did you solve the cross-reference part?

**Comment by Anne1029384756** [comment]
I would like to reference specific figures and tables in text paragraphs. I used  [#359](https://github.com/python-openxml/python-docx/issues/359) to add numbered captions. How can I reference them?

**Comment by merati** [comment]
any updates on the create cross-references feature?
