### ISSUE TITLE
feature: BlockItemContainer.iter_block_items()

### ISSUE THREAD

**Issue by danmilon** [python-openxml/python-docx#40]
I'd like to iterate over the elements of they document as they appear in it. For example if there is a paragraph a table and then a paragraph again, I want to get them in that order. AFAIK currently there are two properties on `Document`, `paragraphs` and `tables` but have no notion of ordering between them.

**Comment by cez81** [comment]
Is there a way of doing this after the recent changes to docx.Document?

**Comment by scanny** [comment]
Not yet; this feature is still in the backlog. The last release focused on styles support.

**Comment by scanny** [comment]
Oh, I think I misinterpreted your question. Some of the imports have to change due to recent refactoring:
```python
from docx.document import Document
from docx.oxml.text.paragraph import CT_P
from docx.text.paragraph import Paragraph
```

Is that what you were asking @cez81 ?

I've updated the example.

**Comment by cez81** [comment]
Yes I think it was. Unfortunately I can't get it to work tho... I get an error creating the Document instance
"TypeError: __init__() missing 1 required positional argument: 'part'". I'm guessing it has to do with the first line importing the wrong Document class?

    from docx.document import Document
    from docx.oxml.text.paragraph import CT_P
    from docx.text.paragraph import Paragraph

    def iter_block_items(parent):
        """
        Yield each paragraph and table child within *parent*, in document order.
        Each returned value is an instance of either Table or Paragraph. *parent*
        would most commonly be a reference to a main Document object, but
        also works for a _Cell object, which itself can contain paragraphs and tables.
        """
        if isinstance(parent, Document):
            parent_elm = parent._document_part.body._body
        elif isinstance(parent, _Cell):
            parent_elm = parent._tc
        else:
            raise ValueError("something's not right")

        for child in parent_elm.iterchildren():
            if isinstance(child, CT_P):
                yield Paragraph(child, parent)
            elif isinstance(child, CT_Tbl):
                yield Table(child, parent)
                
                
    doc = Document('test.docx')
    for block in iter_block_items(doc):
        print(block.text)

**Comment by scanny** [comment]
Ah, right. If you do this that should fix your case where you have them both in the same module and need to use both the docx.document.Document class and the docx.Document factory function:

```python
import docx

doc = docx.Document('test.docx')
for block in iter_block_items(doc):
    print(block.text)
```

**Comment by pdelsante** [comment]
Hi, I think cez81 is right: there seems to be something more that changed in your code lately. To make your example work again with 0.8.4 I had to change it like this:

```python
from docx.document import Document
from docx.oxml.table import CT_Tbl
from docx.oxml.text.paragraph import CT_P
from docx.table import _Cell, Table
from docx.text.paragraph import Paragraph


def iter_block_items(parent):
    """
    Yield each paragraph and table child within *parent*, in document order.
    Each returned value is an instance of either Table or Paragraph. *parent*
    would most commonly be a reference to a main Document object, but
    also works for a _Cell object, which itself can contain paragraphs and tables.
    """
    if isinstance(parent, Document):
        parent_elm = parent.element
    elif isinstance(parent, _Cell):
        parent_elm = parent._tc
    else:
        raise ValueError("something's not right")

    for child in parent_elm.iterchildren():
        if isinstance(child, CT_P):
            yield Paragraph(child, parent)
        elif isinstance(child, CT_Tbl):
            yield Table(child, parent)
```

In particular, I had to change the following line:

```python
        parent_elm = parent._document_part.body._body
```

to this:

```python
        parent_elm = parent.element
```

**Comment by scanny** [comment]
Ah, yes, I see what you're saying. The way to get a reference to to the `<w:body>` element changed as well. I think what you want is this though:

```python
if isinstance(parent, Document):
    parent_elm = parent.element._body
```

... because `parent.element` is the `<w:document>` element if I'm reading the code correctly.

Apologies I don't have time to test this right now, but hope that helps. Such are the wages of workaround functions because they rely on internals that aren't guaranteed to be stable between releases.

**Comment by cez81** [comment]
Ok got it working now! Changed it to:
```
if isinstance(parent, Document):
    parent_elm = parent.element.body
```
Thanks for the help both of you!

**Comment by nguyen1110935** [comment]
Hi @scanny 

your iter_block_items() parse paragraph and table in docx file.
I'm a beginner in python. 
Could you please update to parse all headings (Heading 1, Heading 2,..etc), paragraphs and tables.

Thank you.

**Comment by emishaikh** [comment]
In my case, i have double column in my paragraph also , i wanted to extract that also
if i am using 
  `for child in parent_elm.iterchildren():
        if isinstance(child, CT_P):
            yield Paragraph(child, parent)
        elif isinstance(child, CT_Tbl):
            yield Table(child, parent)`

It is taking Double column text as a paragraph. Please help me to find double column also in my paragraph

**Comment by igorsavinkin** [comment]
how to get text then from yielded Table object?

**Comment by alfiyafaisy** [comment]
Hi @scanny  ,
I tried your code, but Im facing a problem in the section mentioned below.

    for block in iter_block_items(doc):
        print(block.text)

Here Im getting the error **_"AttributeError: 'Table' object has no attribute 'text'"_** .
Can anyone please help me to solve this issue? 
Thanks in advance.

**Comment by alfiyafaisy** [comment]
> how to get text then from yielded Table object?

Hey @igorsavinkin , this worked for me.

    for block in iter_block_items(doc):
        if isinstance(block, Table):
            for row in block.rows:
                row_data = []
                for cell in row.cells:
                    for paragraph in cell.paragraphs:
                        row_data.append(paragraph.text)
                print("\t".join(row_data)

**Comment by shulinwz** [comment]
nested tables should be easy to handle with recursion

```python
def iter_block_items(parent):
    if isinstance(parent, Document):
        parent_elm = parent.element.body
    elif isinstance(parent, _Cell):
        parent_elm = parent._tc
    else:
        raise ValueError("something's not right")

    for child in parent_elm.iterchildren():
        if isinstance(child, CT_P):
            yield Paragraph(child, parent)
        elif isinstance(child, CT_Tbl):
            table = Table(child, parent)
            for row in table.rows:
                for cell in row.cells:
                    yield from iter_block_items(cell)
```

**Comment by romran** [comment]
Hello everyone,
It helped me a lot when parsing docx files. 
May you tell, if it is possible to refactor this function and also find `InlineShapes` ?

**Comment by Slowhalfframe** [comment]
Hello everyone.
I have a question: how to use Python to read pictures in word order？

**Comment by lxj0276** [comment]
I want to know how to read pictures or charts like function "iter_block_items"

**Comment by Slowhalfframe** [comment]
> I want to know how to read pictures or charts like function "iter_block_items"

def read_item_block(parent):
    '''
    顺序读取wordneir
    :param parent: 文档
    :return: p/t
    '''
    if isinstance(parent, _Document):
        parent_elm = parent.element.body
    elif isinstance(parent, _Cell):
        parent_elm = parent._tc
    elif isinstance(parent, _Row):
        parent_elm = parent._tr
    else:
        raise ValueError("something's not right")
    for child in parent_elm.iterchildren():
        if isinstance(child, CT_P):
            count = 1
            count_flase = 0
            res = Paragraph(child, parent)
            if res.text != '':
                yield (res,count_flase)
            else:
                try:
                    # 试着去取内联元素
                    from xml.dom.minidom import parseString
                    DOMTree = parseString(child.xml)
                    data = DOMTree.documentElement
                    nodelist = data.getElementsByTagName('pic:blipFill')
                    print('*nodelist'*9,nodelist)
                    if len(nodelist) < 1:
                        yield (res,count_flase)
                    else:
                        yield (res, count)
                except Exception as e:
                    print('*'*9,e)
                    yield (res,count_flase)
        elif isinstance(child, CT_Tbl):
            yield (Table(child, parent),)


This is how I read pictures.

**Comment by lxj0276** [comment]
> > I want to know how to read pictures or charts like function "iter_block_items"
> 
> def read_item_block(parent):
> '''
> 顺序读取wordneir
> :param parent: 文档
> :return: p/t
> '''
> if isinstance(parent, _Document):
> parent_elm = parent.element.body
> elif isinstance(parent, _Cell):
> parent_elm = parent._tc
> elif isinstance(parent, _Row):
> parent_elm = parent._tr
> else:
> raise ValueError("something's not right")
> for child in parent_elm.iterchildren():
> if isinstance(child, CT_P):
> count = 1
> count_flase = 0
> res = Paragraph(child, parent)
> if res.text != '':
> yield (res,count_flase)
> else:
> try:
> # 试着去取内联元素
> from xml.dom.minidom import parseString
> DOMTree = parseString(child.xml)
> data = DOMTree.documentElement
> nodelist = data.getElementsByTagName('pic:blipFill')
> print('*nodelist'_9,nodelist) if len(nodelist) < 1: yield (res,count_flase) else: yield (res, count) except Exception as e: print('_'*9,e)
> yield (res,count_flase)
> elif isinstance(child, CT_Tbl):
> yield (Table(child, parent),)
> 
> This is how I read pictures.

加我微信交流呗lixianjie0518

**Comment by devanshugupta** [comment]
Having this error in your code:

Traceback (most recent call last):
  File "C:/Users/home/PycharmProjects/Sentiment_analysis/yup.py", line 46, in <module>
    for cell in row.cells:
  File "C:\Users\home\Desktop\devu\venv\lib\site-packages\docx\table.py", line 401, in cells
    return tuple(self.table.row_cells(self._index))
  File "C:\Users\home\Desktop\devu\venv\lib\site-packages\docx\table.py", line 106, in row_cells
    return self._cells[start:end]
  File "C:\Users\home\Desktop\devu\venv\lib\site-packages\docx\table.py", line 173, in _cells
    cells.append(cells[-col_count])
IndexError: list index out of range

**Comment by Labyrins** [comment]
> Ok got it working now! Changed it to:
> 
> ```
> if isinstance(parent, Document):
>     parent_elm = parent.element.body
> ```
> 
> Thanks for the help both of you!

Thank you. this works to me!

**Comment by div1996** [comment]
how to read paragraph,table,shapes all in one place....Kindly Help ASAP

**Comment by ejaca** [comment]
Hi admin,

Do you have any idea what can I change in the code?

This is the current code I have in iterating tables and paragraphs:

```
def iterate_tables_and_paragraphs(
    parent: Union[DocxDocument, _Cell]
) -> Union[DocxParagraph, DocxTable]:
    if isinstance(parent, DocxDocument):
        parent_elm = parent.element.body
    elif isinstance(parent, _Cell):
        parent_elm = parent._tc
    else:
        raise ValueError("Invalid type parameter, expected DocxDocument or _Cell")

    for child in parent_elm.iterchildren():
        if isinstance(child, CT_P):
            yield DocxParagraph(child, parent)
        elif isinstance(child, CT_Tbl):
            yield DocxTable(child, parent)
```

There were no problems in running the code but the output was incorrect.

The problem is that in my document, there are 2 tables on top of each other but they don't have the same number of columns. Table 1 has 18 columns while table 2 has 20 columns but this code sets the number of columns to the max which is 20 so when I tried reading the data, table 1 produced incorrect results since it looped 20 times so some data from the next row were included as table headers.

Please help. Thanks.

**Comment by abubelinha** [comment]
@scanny could you post the most updated version of the function which should currently work?
I tried to implement the different commented changes above, but for some reason it is not working recursively.
I post a full example, creating a document with a table and some inner paragraphs with text.
My code is only returning the paragraphs outside table:

```Python
def iter_block_items(parent):
	debug=False
	from docx.document import Document
	from docx.oxml.table import CT_Tbl
	from docx.oxml.text.paragraph import CT_P
	from docx.table import _Cell, Table
	from docx.text.paragraph import Paragraph
	if debug:
		print(type(parent))
	if isinstance(parent, Document):
		parent_elm = parent.element.body
	elif isinstance(parent, _Cell):
		parent_elm = parent._tc
	else:
		raise ValueError("something's not right")

	for child in parent_elm.iterchildren():
		if debug:
			print(type(child))
		if isinstance(child, CT_P):
			yield Paragraph(child, parent)
		elif isinstance(child, CT_Tbl):
			yield Table(child, parent)

def recursivetest():
	""" Create a document with tables and inner paragraphs to test iter_block_items()"""
	from docx import Document
	d = Document()
	d.add_heading('Heading')
	d.add_paragraph('A paragraph.')
	d.add_heading('Heading 2', level=2)
	d.add_paragraph('Another paragraph.')
	d.add_heading('My table comes here', level=2)
	t = d.add_table(rows=4, cols=3)
	for r,row in enumerate(t.rows):
		for c,cell in enumerate(row.cells):
			cell.text = "Row {} / Column {}".format(r+1,c+1)
			cell.add_paragraph("with some text below")
	d.add_heading('The end', level=2)
	d.add_paragraph('bye bye !!')
	d.save("recursive.docx")
	e=0
	from docx.text.paragraph import Paragraph
	for elem in iter_block_items(d):
		e+=1
		print(e,type(elem))
		if isinstance(elem, Paragraph):
			print("   ",elem.text)

recursivetest()
```

**OUTPUT:**

```
1 <class 'docx.text.paragraph.Paragraph'>
    Heading
2 <class 'docx.text.paragraph.Paragraph'>
    A paragraph.
3 <class 'docx.text.paragraph.Paragraph'>
    Heading 2
4 <class 'docx.text.paragraph.Paragraph'>
    Another paragraph.
5 <class 'docx.text.paragraph.Paragraph'>
    My table comes here
6 <class 'docx.table.Table'>
7 <class 'docx.text.paragraph.Paragraph'>
    The end
8 <class 'docx.text.paragraph.Paragraph'>
    bye bye !!

```

**Comment by cyrillkuettel** [comment]
The imports are tricky to get right, so here you go. This should work for the latest version. 

```python

from docx.text.paragraph import Paragraph
from docx.document import Document
from docx.table import _Cell, Table
from docx.oxml.text.paragraph import CT_P
from docx.oxml.table import CT_Tbl
import docx

def iter_block_items(parent):
    if isinstance(parent, Document):
        parent_elm = parent.element.body
    elif isinstance(parent, _Cell):
        parent_elm = parent._tc
    else:
        raise ValueError("something's not right")

    for child in parent_elm.iterchildren():
        if isinstance(child, CT_P):
            yield Paragraph(child, parent)
        elif isinstance(child, CT_Tbl):
            table = Table(child, parent)
            for row in table.rows:
                for cell in row.cells:
                    yield from iter_block_items(cell)
                    
doc = docx.Document('word.docx')
for block in iter_block_items(doc):
	print(block.text)
```

**Comment by abubelinha** [comment]
@cyrillkuettel  Thanks for sharing

@abubelinha

**Comment by aarongundel** [comment]
I'm currently using this function (thanks so much for writing it, it's very useful!).  I noticed that when I did table-based operations - like add_row - on the table provided here, it wasn't added to the table that I ended up saving.  I looked a little deeper and it appears that it is not the same table as the one in the actual document, so any rows I add are discarded.  This makes sense at some level; but I'm trying to get a reference to that actual table so that i can modify it/add rows.  Is there any way to do that?

**Comment by scanny** [comment]
Added `BlockItemContainer.iter_inner_content()` in v.1.0.2. `Document`, `Header`, `Footer`, and (table) `_Cell` are all block-item containers. The behavior is to generate `Paragraph | Table` in document-order from within that container. Contrast with `Section.iter_inner_content()` which does the same but only within a single section.

It is not recursive, so you'll need to take care of that aspect if you want it (not everyone will hence why it's not implemented here).

Maybe something like:

```python
def recursively_iter_block_items(blkcntnr: BlockItemContainer) -> Iterator[Paragraph | Table]:
    for item in blkcntnr.iter_inner_content():
        if isinstance(item, Paragraph):
            yield item
        elif isinstance(item, Table):
            for row in item.rows:
                for cell in row.cells:
                    yield from recursively_iter_block_items(cell)
```

**Comment by LucianoMan** [comment]
> The imports are tricky to get right, so here you go. This should work for the latest version.
> 
> ```python
> from docx.text.paragraph import Paragraph
> from docx.document import Document
> from docx.table import _Cell, Table
> from docx.oxml.text.paragraph import CT_P
> from docx.oxml.table import CT_Tbl
> import docx
> 
> def iter_block_items(parent):
>     if isinstance(parent, Document):
>         parent_elm = parent.element.body
>     elif isinstance(parent, _Cell):
>         parent_elm = parent._tc
>     else:
>         raise ValueError("something's not right")
> 
>     for child in parent_elm.iterchildren():
>         if isinstance(child, CT_P):
>             yield Paragraph(child, parent)
>         elif isinstance(child, CT_Tbl):
>             table = Table(child, parent)
>             for row in table.rows:
>                 for cell in row.cells:
>                     yield from iter_block_items(cell)
>                     
> doc = docx.Document('word.docx')
> for block in iter_block_items(doc):
> 	print(block.text)
> ```

This works wonderfully, however It seems to repeat text that are in tables. Does anyone know how to stop the code from doing this. I attempted to use sets but that got rid of repeated text that I need.

**Comment by scanny** [comment]
Something like this should do the trick:
```python
def iter_visible_row_cells(row: Row) -> Iterator[_Cell]:
    """Generate only "concrete" cells, those with a `tc` element.

    Vertically spanned cells have a `tc` element but are skipped.
    """
    yield from (_Cell(tc, row) for tc in row._tr.tc_lst if tc.vMerge != "continue")
```

**Comment by LucianoMan** [comment]
@scanny would you happen to know how to append one word document to another?

**Comment by scanny** [comment]
Not related so not a good use of this thread.

That topic comes up from time to time, search should be your first stop. Google knows many things about `python-docx` :)

**Comment by LucianoMan** [comment]
I apologize for the off topic question but my friend and I looked everywhere and could not find anything :'(.

**Comment by cyrillkuettel** [comment]
If you have `pandoc` you can run

```bash
pandoc -s document1.docx document2.docx  -o merged.docx
```

This can work for simple cases.
