### ISSUE TITLE
Adding new Merge Fields in Word Documents...

### ISSUE THREAD

**Issue by tbrenenstuhl** [python-openxml/python-docx#401]
Hello,

I have spent a few hours researching how to create Merge Fields within a .docx using Python.

My use case is I have a list of students (or hotels, or activities, or dates, or cities, or a number of other possible fields) and I have documents that outline these lists, like a participant list of students for group trips but each of these trips tend to have different numbers of students.

I can go in and manually create the Merge Fields to have the exact number of students needed for each trip  but it would be best to be able to do this through using the python-docx package in order to automate it.

If anyone has any tips or suggestions on how to use the python-docx package to do this would be much appreciated.

With kind regards,
T

**Comment by scanny** [comment]
There's no API support for this yet. The general capability is known as "fields" on this issues list. If you do a search on "field" you'll find other issues that have some detail that might be useful to you. Basically you'd have to insert the required XML for a field using `lxml` calls and so forth. Closing this as duplicate.
