### ISSUE TITLE
How can I get text/images/tables between two bookmarks

### ISSUE THREAD

**Issue by MarcAtHTW** [python-openxml/python-docx#404]
Hello,

I have the problem, that I can't get the full content between two headlines from a docX-document to copy it to another docX-document. The content between these headlines could be everything thats possible in a docX-document (text, tables, images, etc.). I hope somebody can help.

The idea is, to set two bookmarks (start and end) under a headline of the source-document (template), to copy all content in between into another docX- document (result-document).

For example the following structure of the source-document is givin:

```
Headline1
Headline2
 content
Headline1
Headline1
Headline2
 content
```

Now it should be possible to set Bookmarks between the content which I need to copy into the result-docX-Document

```
Headline1
Headline2
[BOOKMARK START]
 content
[BOOKMARK END]
Headline1
Headline1
Headline2
[BOOKMARK START]
 content
[BOOKMARK END]
```
What I need now is the whole content between the created bookmarks, to copy it in the next step into the result-docx-document. But how can i get all the content?

I haven't got much experiences with docX, but I started with something like this:

```
from docx import Document
from xml.dom.minidom import parseString

source_document = Document('/path-to-source_document.docx')
xml_string = source_document._body._element.xml
xml = parseString(xml_string)
contents = xml.getElementsByTagName('w:bookmarkStart')
```
I have no idea how I could iterate through the elements in between both bookmarks..

**Comment by scanny** [comment]
`python-docx` is based on the `lxml` package, which is uses to do all the XML manipulation. That means that every element can be manipulated with `lxml` methods, in particular the ones here: http://lxml.de/api/lxml.etree._Element-class.html

It also means that `xml.dom.minidom` has no place here. It does not mix with `lxml` and `lxml` can do whatever you need with the XML.

It sounds like maybe the `.getnext()` method would do what you're looking for. You could just `.getnext()` your way though from the bookmark start until you hit the bookmark end.

**Comment by MarcAtHTW** [comment]
Thanks for the fast respond. I did it with a different approach, without Bookmarks. Now I get all paragraphs of the Document using  docx.Document.paragraphs built-in-functiion. Afterwards I iterate through the paragraphs und search for combinations of paragraph.style.name and paragraph.text. 

Now Im using the heading-name (docx.paragraph.text) and his heading-level as trigger and get all paragraphs in between.

**Comment by baranskib** [comment]
@MarcAtHTW Can you possibly provide the solution for this? I am currently stuck on the same problem.
