### ISSUE TITLE
How to read text in Text Box?

### ISSUE THREAD

**Issue by niharikakrishnan** [python-openxml/python-docx#416]
Is it possible to read details in a text box using python-docx? Searched for a fix for this but in vain. Kindly help me out.

**Comment by scanny** [comment]
(Floating) text boxes are not yet supported in `python-docx`.

**Comment by pradeepm2017** [comment]
Are text boxes are supported in python-docx? Please let me know if there is any other option.

**Comment by martinmde** [comment]
Can this be closed? 
Text boxes not available.

**Comment by niharikakrishnan** [comment]
Yes it can be closed. Couldn't find any alternative for reading text boxes.
