### ISSUE TITLE
how to find the merged cell from table?

### ISSUE THREAD

**Issue by lxj0276** [python-openxml/python-docx#424]
Hi
Is it possible to find the merged cell from table?

**Comment by lanbin45** [comment]
@lxj0276 hi, did you solve this? I'm desiring this requirement too...

**Comment by lxj0276** [comment]
> @lxj0276 hi, did you solve this? I'm desiring this requirement too...

留微信，我加你

**Comment by lanbin45** [comment]
@lxj0276 微信号： twilight19911027
