### ISSUE TITLE
Auto-filling text into a Word document

### ISSUE THREAD

**Issue by MTHuffness** [python-openxml/python-docx#431]
I have found an issue that occurs when you have a completed document, in this case an application, with the goal of taking inputs and adding them into the document. The example i'm using are the inputs are location, resident name, move-in date, etc. for a leasing document.

The Word document contains text to be replaced that looks like {applicant}. I then search through the paragraphs and runs for that replaceable text, which is to be replaced by the input string. 

This creates a bunch of bugs including issues with spacing around the replaced text, words in between 2 replaced text going missing, and in some situations the code will not replace the text with the user input.

any help would be great!

Thanks,

Mike

**Comment by scanny** [comment]
The algorithm here should allow you to replace text without disturbing the formatting or spacing of surrounding text: https://github.com/python-openxml/python-docx/issues/30#issuecomment-879593691

You might also check out the `python-docx-template` project here: https://github.com/elapouya/python-docx-template
