### ISSUE TITLE
Quick Parts, field formula

### ISSUE THREAD

**Issue by realoriginal** [python-openxml/python-docx#435]
Would it be possible to add a Quick parts, > field, then formula with this program?

**Comment by scanny** [comment]
I've no idea what you're talking about. When adding an issue, please take the time to fully describe the issue, including enough background on what you're trying to achieve to give context to your request.

**Comment by realoriginal** [comment]
sorry, was in a rush.


Essentially, in MS word, you can go to  the insert tab, then click "Quick Parts", field, and then select your field type to be a formula. Therein, type in a formula to be executed upon opening the document


Would this be possible within your program?

**Comment by scanny** [comment]
There's no direct API support for this. If you search on 'python-docx field' you'll find a few situations where folks have gotten something like this working using a workaround function that accesses the underlying XML.
