### ISSUE TITLE
Index - Table of Contents, update

### ISSUE THREAD

**Issue by nordic-melon** [python-openxml/python-docx#436]
Hi, I've read the docs and searched through the issues but haven't found the solution, if there is any. I am working on a medium size docx file creator and at the end of it, after populating vars and paragraphs I would like to update the Index at the beginning. This function is offered when clicking on the mentioned index and a blue little label is shown with an arrow. When clicking on it we can "Update table..."

Is there an implementation of this in the library?

Much appreciated,

nM

**Comment by scanny** [comment]
Try searching on 'python-docx table of contents'. This topic has been well-discussed, here for example #36.

**Comment by nordic-melon** [comment]
Thanks for the tip

**Comment by botzill** [comment]
Hi, not sure what are the latest changes related to this issue, but seems that there is method `qn` anymore. Any updates on this ?

**Comment by deepak-coding-art** [comment]
Did you fond a solution to update the indexes in table of content without prompting user

**Comment by nathan-149** [comment]
Also wondering this
