### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by cuiyonglei** [python-openxml/python-docx#438]
How to adding header and footer?
I did with the python-docx document，but it didnot work.

**Comment by dinhvankiet124** [comment]
What error did you get?

**Comment by KailiDing** [comment]
The content in the python-docx documentation about adding header and footer is an enhancement proposal. Currently there is no available API for doing this. I guess the error may be 'section has no attribute called header'? One solution is to open a docx with header and footer and add content in it.

**Comment by scanny** [comment]
Duplicate of #104.
