### ISSUE TITLE
Can't import WD_ALIGN_PARAGRAPH

### ISSUE THREAD

**Issue by leijyuho** [python-openxml/python-docx#439]
Could someone help me?

I'm learning to use docx to manipulate alignment.

However, I can't import WD_ALIGN_PARAGRAPH at all.

Pycharm keeps telling me unresolved reference .

This is what I have -
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

Thank you so much.

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the 'python-docx' tag. This issues list is for suspected bugs and feature requests.
