### ISSUE TITLE
Working with a single page

### ISSUE THREAD

**Issue by nawuy** [python-openxml/python-docx#440]
Given a doc file of N amount of pages. How can I work with a single page?
If for example I only need to work on Page 3

Thank you!

**Comment by scanny** [comment]
This is not possible because pagination is done at runtime by Microsoft Word (or LibreOffice). Determining page boundaries is determined by the rendering application and is not recorded in the XML for the document.

**Comment by nawuy** [comment]
Thank you scanny, I will find another solution for my project :)
