### ISSUE TITLE
Is it possible to know a paragraph on which page

### ISSUE THREAD

**Issue by C1tas** [python-openxml/python-docx#442]
Is it possible to know a paragraph on which page
I want to auto gen the TOC with page num

i've read the document.xml there isn't some sign

**Comment by scanny** [comment]
No. If you search on "python-docx TOC" you'll find more detailed explanation.

**Comment by C1tas** [comment]
thanks for your information

i edit document.xml but always get a broken notice before i open it

is there some useful way to avoid it ?

**Comment by C1tas** [comment]
It's my mistakes !!!
when i use python-docx it work's very well 
Thanks for your work,
Is there some lower api  document like
```
In [10]: a._element.xpath("/w:document/w:body/w:sdt")
Out[10]: [<Element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}sdt at 0x1116a6748>]

In [11]: from copy import deepcopy

In [12]: wp = a._element.xpath("/w:document/w:body/w:sdt/w:sdtContent/w:p")

In [13]: tmp_xml = deepcopy(wp[6])

In [14]: sdct = a._element.xpath("/w:document/w:body/w:sdt/w:sdtContent")

In [15]: sdct
Out[15]: [<Element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}sdtContent at 0x111689488>]

In [16]: sdct = sdct[0]

In [17]: sdct.insert(3, tmp_xml)

In [18]: a.save('testx.docx')
```
