### ISSUE TITLE
Bugfix: MSOffice detects docx files as corrupted

### ISSUE THREAD

**Issue by naimulhaider** [python-openxml/python-docx#446]
The generated docx file opens fine with Google Docs or Libreoffice, but if it's opened with Microsoft Office, the file is detected as corrupted but it works fine after that. Looking for fix for the corrupt notification.

p.s I have tried with different contents, but it's always the same issue. So this doesn't relate to inserting tables/images/etc, must have something to do with the way python-docx is packaging the docx file.

**Comment by scanny** [comment]
Please narrow down the code that produces the "repair" error and post it here.

I doubt it's a packaging problem. I expect it's non-conforming XML that Google and LibreOffice ignore.

**Comment by naimulhaider** [comment]
Basically the code takes a template file (docx), modifies the file (fills the table with data, etc) and then saves it. Even if nothing is modified, the fact that python-docx saved it produces the Corrupt File issue.
```
    template_file_path = sys.argv[1]

    try:
        template_file = open(template_file_path, 'r+b')
    except IOError as e:
        sys.exit("I/O error({0}): {1}".format(e.errno, e.strerror))

    document = Document(template_file)

    # modify `document` with data at this point, error persists even if this is removed

    document.save(template_file)

    template_file.close()
    report_data_file.close()
```

**Comment by scanny** [comment]
Try it with these changes and let me know what happens:

* Save the file to a new path rather than reusing an open file as the target.
* Give `Document()` the `template_file_path` directly instead of an open file.

**Comment by naimulhaider** [comment]
Yes! Saving the document to a new file did the job. Thanks a lot. Closing this.
