### ISSUE TITLE
how to extract certain page from the whole document?

### ISSUE THREAD

**Issue by gustavkkk** [python-openxml/python-docx#447]
I want to extract some pages from the whole document. For example, the total page number is 100. I want to make a new document with page 70~90.  I used delete paragraphs, but it deletes the contents of paragraph. it doesn't delete the page entirely. and other problem is that tables are treated in different structure. so it doesn't work. what is the solution?

**Comment by scanny** [comment]
Please use StackOverflow for support questions, using the 'python-docx' tag.

The short answer is page boundaries aren't stored in the Word file, their position is determined by the renderer (Word application) which "flows" the document onto pages.

I suspect what you want is `iter_block_items`, if you search on 'python-docx iter_block_items' you'll find more on that.
