### ISSUE TITLE
List bullets do not work

### ISSUE THREAD

**Issue by huangsam** [python-openxml/python-docx#452]
Encountering `KeyError: "no style with name 'List Bullet'"` and `KeyError: "no style with name 'ListBullet'"` whenever I try things like the following:

```python
document.add_paragraph('blah', style='List Bullet')
document.add_paragraph('blah', style='ListBullet')
```

This baffles me since the [home page](http://python-docx.readthedocs.io/en/latest/index.html) shows it working. FYI I'm currently adding content to an existing Word document.

Has anyone come across this issue and found a solution?

**Comment by scanny** [comment]
This means your "starting" document does not have these styles defined.

Make sure you understand these two pages in the documentation: 
http://python-docx.readthedocs.io/en/latest/user/styles-understanding.html 
http://python-docx.readthedocs.io/en/latest/user/styles-using.html

**Comment by austinweisgrau** [comment]
It seems like using a pre-existing document, rather than creating a new one from `docx.Document()` sometimes means styles won't be available. I looked into a way to inherit the default styles into a document, but couldn't figure out a way to make it work. It seems like that should be possible though.

**Comment by scanny** [comment]
Make sure you read and understand this and the following page in the documentation on styles. That explains how you get the styles you want in your "template" document. Basically you have to use them at least once in that document but can delete all instances of them before saving.
