### ISSUE TITLE
Apply latent style to paragraph

### ISSUE THREAD

**Issue by lvovil** [python-openxml/python-docx#453]
Hi,

My issue is that I have `List Bullet 2` style in list of latent styles. I'm trying to apply the style to the paragraph but have following errors:

```
>>> p = doc.add_paragraph()
>>> p.style = 'List Bullet 2'
KeyError: "no style with name 'List Bullet 2'"
>>> doc.styles.latent_styles.default_to_hidden
False
>>> doc.styles.latent_styles.default_to_locked
False
>>> s = doc.styles.latent_styles['List Bullet 2']
>>> s.priority
1
>>> s.hidden
False
>>> s.quick_style
True
>>> p.style = s
TypeError: unhashable type: '_LatentStyle'
```

Could you help me please with the issue? 

Thanks

**Comment by scanny** [comment]
Make sure you understand this page in the documentation:
http://python-docx.readthedocs.io/en/latest/user/styles-understanding.html

Briefly, latent styles cannot be applied to a paragraph (or other object) in `python-pptx`. Only defined styles available in `document.styles` can be applied. So you either restrict yourself to styles already available in the document, or add any desired styles before attempting to use them.

See this documentation page as well:
http://python-docx.readthedocs.io/en/latest/user/styles-using.html

**Comment by lvovil** [comment]
> So you either restrict yourself to styles already available in the document, or add any desired styles before attempting to use them.
Could you then tell me how can I add my own f.e. `List Bullet 2 Custom` if I have `List Bullet 2` style in latent styles and I can't inherit from it for my style?

Thanks.

**Comment by scanny** [comment]
Having a latent style by a particular name doesn't prevent you from defining a style with the same name. That's exactly what Word does the first time you apply a style that isn't defined yet. The latent styles (in addition to any defined styles that are not also latent) determines what shows up in the list to pick from in the Word UI. But if you apply a latent style that isn't yet defined *in that document*, Word defines it there based on some built-in presets. That way the document doesn't have to carry around a lot of style definitions it doesn't use.

Short story is you can just define "List Bullet" and then use it. You can either define it in the starting document using Word, or use the `python-pptx` API to define it. To define it using Word, just apply that style to a new paragraph and then delete that paragraph. The paragraph goes away, but the style remains.

**Comment by lvovil** [comment]
> To define it using Word, just apply that style to a new paragraph and then delete that paragraph. The paragraph goes away, but the style remains.

Actually that's I'm doing at the moment. But I'd like to add the List styles automatically.

>Short story is you can just define "List Bullet" and then use it.
Sorry, maybe that's a stupid question but I tried this one and it doesn't work. I mean the format of added paragraph is not a `List Bullet 2`
```
>>> styles.add_style('List Bullet 2', WD_STYLE_TYPE.PARAGRAPH)
>>> doc.add_paragraph('some text', style='List Bullet 2')
```

**Comment by scanny** [comment]
Did you read the documentation I linked to? To define a style you need to set its attributes to what you want. It doesn't pick those up automatically from the latent style, if that's what you were expecting. Word does that based on internal presets; we don't maintain presets for that because they change based on locale, Word version etc.

Creating a list bullet style is going to be tough because of the numbering object required. That style is much more sophisticated than just say "Heading 1". You'll be on your own to hack the XML to get the numbering working.
