### ISSUE TITLE
how to add or product catalog ?

### ISSUE THREAD

**Issue by luyuan410117** [python-openxml/python-docx#457]
I get a new docx file with a document use python-docx, but I don't know  how to  generate a catalog in specified place.
thanks for your help

**Comment by WilliamLin1990** [comment]
I also need to generate a catalog in .docx file, but I google it and cannot find a way. If you have some way to solve it, please let me know, thank you!

**Comment by SkyGra** [comment]
hi,
have you solve ther problem, I also want to add catalog.

**Comment by scanny** [comment]
I think you might mean "table of contents", or perhaps "index". If you search on "table of contents" and/or TOC then you should find what information is available.
