### ISSUE TITLE
Count lines in paragraph

### ISSUE THREAD

**Issue by danielegrattarola** [python-openxml/python-docx#470]
Is there a way to count lines in a paragraph?
Right now it's only possible to access the text data as a string, and use information on the font size, line height, etc. to infer the number of lines that are rendered. 
Is there a way to do it properly? If not, can it be added somehow?

Thanks

**Comment by scanny** [comment]
No. The line breaks are determined at rendering time, based on the capabilities of the computer display and/or the attached printer. They are not stored in the .docx file itself.

The duty of wrapping lines falls to the *renderer*. `python-docx` does not include a renderer nor is it ever likely to.

The most reliable way to determine this is using the Microsoft API itself (using COM32 or IronPython), which will run an instance of Word on the same machine and access its rendering engine. It's a pain in the rear, is brittle, not scalable, and not possible on Linux, but it should give you the information you seek.

**Comment by danielegrattarola** [comment]
Thanks, I'll just drop this task altogether :)

**Comment by Himanshu-Singh-HS** [comment]
ohk, thanks for letting us know!
