### ISSUE TITLE
Extracting table cell data from docx to xlsx

### ISSUE THREAD

**Issue by Kara43** [python-openxml/python-docx#472]
Hi,

I am new to python and I am looking to automate process of extracting table data from docx to xlsx file. 
I have attached the sample files to work with and their structure replicates exactly my original files.

Steps:
1. Navigating to SPP-RFCOMM table in Docx.
2. Comparing 'Test Case' column for test case matches with the 'Test Case' name in xlsx.
3. If matches, need to extract 'VERDICT' & 'Date' cell data from docx to xlsx ( 'Test Case Results (Pass, Fail or Not Required)' & 'Test Execution Date') 

It would be great if someone helps me in resolving it.

Thanks.

[TDU-QR-XXX.xlsx](https://github.com/python-openxml/python-docx/files/1706690/TDU-QR-XXX.xlsx)
[XXX_XX_Test Report.docx](https://github.com/python-openxml/python-docx/files/1706691/XXX_XX_Test.Report.docx)

**Comment by Kara43** [comment]
I am using python2.7

**Comment by scanny** [comment]
@Kara43 This isn't the right place for a question like this, although to be fair, I'm not sure there is such a place. You might try StackOverflow, although they discourage questions like this.
