### ISSUE TITLE
Unittests are failing

### ISSUE THREAD

**Issue by Benjamin-T** [python-openxml/python-docx#475]
Dear All, 

Have anyone here actually succeeded running the unittests of this package?  For me these end in a bunch of errors, can anybody verify that the unittests are indeed working? 

In order to clarify the issues, I've attached the logfile of the pytest output:

[log.txt](https://github.com/python-openxml/python-docx/files/1756466/log.txt)

**Comment by scanny** [comment]
All unit tests pass on every commit. It looks like there's something funky with the `lxml`, or it could possibly be related to running the tests on Windows, not too many folks do that. Possibly a git setting that automatically translates newlines into CR/LF.

**Comment by DKWoods** [comment]
I run the unit tests on Windows.  There are a couple of test files I use 
windows-specific versions of because of the CR/LF issue, but that's only 
for a few tests.  The remainder of the tests run fine.  I'm not at home 
right now, but can fill in the details on Friday if you need me to.

David

**Comment by Benjamin-T** [comment]
Thanks for the reply, I'll try and look into the Newline or CR/LF settings tonight.

**Comment by Benjamin-T** [comment]
Allright! the line ending characters were indeed the issue, for future reference: 

this can be fixed by setting the default line endings to lf:
```bash
git config --global core.autocrlf false
```
