### ISSUE TITLE
Template docx

### ISSUE THREAD

**Issue by RicoSpm** [python-openxml/python-docx#477]
Hi everyone,
I work for a company that has a specific docx template (with some colors and images) for writing official documentation. I developed a python program which uses python-docx library to automatically create a docx report and I should use the company template. Is it possible to do this kind of stuff?

**Comment by scanny** [comment]
Yes. Please use StackOverflow for future support questions, using the `python-docx` tag :)

**Comment by RicoSpm** [comment]
Yes, but how?

**Comment by lxj0276** [comment]
> Hi everyone,
> I work for a company that has a specific docx template (with some colors and images) for writing official documentation. I developed a python program which uses python-docx library to automatically create a docx report and I should use the company template. Is it possible to do this kind of stuff?

Did  you accomplish it?
