### ISSUE TITLE
Can't read the text in ContentControl

### ISSUE THREAD

**Issue by GoliardYou** [python-openxml/python-docx#480]
Hello everybody, I need your help. 
I tried to read a docx document by using Python-docx, but all of the text I wanted were in the ContentControl. When I try to print the text of the paragraphe including a ContentControl, error occurs.

For exemple, I try to print the 14th paragraphe, using
`print(p[13].text)`
then I get an error like: 
`UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 8: illegal multibyte sequence`

So what should I do to get the text in ContentControl?
Thanks a lot for your help!

**Comment by scanny** [comment]
Hi Goliard, please use StackOverflow (with tag 'python-docx') for user support questions. This issues list is reserved for feature requests and suspected bugs.

**Comment by GoliardYou** [comment]
No problem. Sorry, I didn't know that rule. Thanks!
