### ISSUE TITLE
python-docx 0.8.7?

### ISSUE THREAD

**Issue by raphaelvalentin** [python-openxml/python-docx#487]
Dear Developers, 
the last release of python-docx has been submitted around 2-year ago. Is there any future or schedule for a version 0.8.7?
Thank you very much,

**Comment by scanny** [comment]
Yes.

**Comment by mnlbox** [comment]
@scanny can you explain more?

**Comment by Benjamin-T** [comment]
Perhaps we could try to get an overview of what features are planned for the next release, and more importantly who is going to do what :)

If there is a backlog/to do list, people might be more willing to contribute. 

We could also try to split some of the bigger projects into smaller, easier to implement parts. For instance, implement only the oxml part of a bigger feature, which can be committed to its feature branch, giving other people the chance to continue working on it. 

If I would have to make a list right now, it would something like this:

1. Headers and Footers
2. Bookmarks
3. Fields 
4. Hyperlinks
5. Edit Styles using python-docx
6. Add custom document properties

**Comment by raphaelvalentin** [comment]
May I add:

7. Extend list of Image format with wmf/emf

**Comment by Benjamin-T** [comment]
@raphaelvalentin I would say, create a PR, a feature analysis (is this code all we need, or is there something else required. for instance, I do see a difference between the *.PNG image implementation and the *.BMP implementation) and commit this code together with the required functional and unit tests!

**Comment by yeshida** [comment]
I'm sorry that I'm still a rookie, so I can't play a big role, but I like this way of cooperation. I need to improve myself first. I hope to participate in the project one day

**Comment by scanny** [comment]
v0.8.7 was released a few weeks ago.
