### ISSUE TITLE
Can't get acess to the table in .docx file through python-docx api.

### ISSUE THREAD

**Issue by alexbalandi** [python-openxml/python-docx#488]
Hello!

I've made a minimal example of docx file, containing a single table with the formatting I faced in a real document. When I try:
`test_doc = docx.Document('non_readable_table.docx')`
`print(test_doc.tables)`
I get an empty list. All paragraphs are also empty. I'm not exactly familiar with xml stuff, that's why I use python-docx as some high-level api for the document so I can't really figure what's the problem here. I'm sorry in advance if this is not the issue with the library, but with my own skills.

I tried iterating over all objects as suggested [here](https://github.com/python-openxml/python-docx/issues/40) but to no avail: it yeilds a list of empty paragraphs and nothing more.
I attach the minimal example .docx file. 
[non_readable_table.docx](https://github.com/python-openxml/python-docx/files/1867861/non_readable_table.docx)

What is the correct way to handle such tables within python-docx api (if there is one)?

Regards,

Alex.

**Comment by scanny** [comment]
Your table is a graphical table, like those used in PowerPoint, not a native Word table. This is why it doesn't appear.

**Comment by xies4** [comment]
Is there a way to read a graphical table using python docx? Thanks.

**Comment by xies4** [comment]
> Is there a way to read a graphical table using python docx? Thanks.

A solution has been posted here: https://stackoverflow.com/questions/78875922/how-to-read-and-input-data-into-a-table-graph-in-an-template-word-file-using-pyt/78876278#78876278
