### ISSUE TITLE
Python-docx:  AttributeError: 'Section' object has no attribute 'header'

### ISSUE THREAD

**Issue by Cathay2017** [python-openxml/python-docx#490]
I use Python-docx = 0.8.6
I read the url  http://python-docx.readthedocs.io/en/latest/dev/analysis/features/header.html?highlight=footer. It mention: "Every section has a header; it is never None:"
>>> header = section.header
>>> header
<docx.hdrftr.Header object at 0x02468ACE>
However, when I code it, I encounter "AttributeError: 'Section' object has no attribute 'header'"
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import docx
>>> docx.__version__
'0.8.6'
>>> from docx import Document
>>> doc = Document()
>>> doc.sections[0].headers[0].add_paragraph(text = 'This is Header')

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    doc.sections[0].headers[0].add_paragraph(text = 'This is Header')
AttributeError: 'Section' object has no attribute 'headers'
>>> section = doc.sections[0]
>>> header = section.header

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    header = section.header
AttributeError: 'Section' object has no attribute 'header'
>>> 
Can anyone help me out? Also, What is the best way to edit the header and footer of a Word file(.docx).
Thank you very much in advance!

**Comment by scanny** [comment]
That page is an analysis document specifying the headers functionality, not documenting a feature.

The headers functionality has not been implemented yet.
