### ISSUE TITLE
Need a mechanism to add picture in table

### ISSUE THREAD

**Issue by nprashan** [python-openxml/python-docx#491]
Hi,
It would be good to have a mechanism to add picture in a table. Basically, please plan to implement add_picture() function in cell object 

thanks
Prashanth

**Comment by scanny** [comment]
You should be able to do this already with:

```python
paragraph = ...  # paragraph in cell
run = paragraph.add_run()
run.add_picture(...)
```

http://python-docx.readthedocs.io/en/latest/api/text.html#docx.text.run.Run.add_picture

**Comment by nprashan** [comment]
It did work!! Sorry for my ignorance. Appreciate your quick response. 

However, cell.add_paragrach would be straight forward and more intuitive. This is just my opinion) Thanks a lot anyways.

Regards,
Prashanth
