### ISSUE TITLE
Make a list number bold?

### ISSUE THREAD

**Issue by b4cktr4ck2** [python-openxml/python-docx#502]
I've made a paragraph with the style "ListNumber" and I'd like to make the numbered list bold as well. I saw on the documentation that a run is automatically created when you add a paragraph, but when I print out the paragraph runs, I get an empty list. How can I make my numbers in my numbered list bold?

Edit: For clarity, I want my numbers in my numbered list to look like this:

**1.**

Moreover, is it possible to add a subheading, so my list looks like:

**1.1** 

?

**Comment by Benjamin-T** [comment]
I would define a new number style, and try to apply this.

for instance, create a new number style in your template called "BoldNumberedList", and apply it to your list:

```python
doc = Document()
par = doc.add_paragraph(
    'first item in ordered list', style='BoldNumberedList'
)
doc.save('test.docx')
```

for the numbering, you would have to create a "numbering"  style.  I don't think you can create numbering styles from the python package. 

You could try and implement it, I think you can access the numbering from:

```python 
doc = Document()
doc.part.numbering
```
However, no methods are available (yet)

Assuming you have a numbering style set, I managed to create a list with multiple levels:

```python

doc = Document('docx_file_containing_list_numbering_style.docx
[docx_file_containing_list_numbering_style.docx](https://github.com/python-openxml/python-docx/files/2071464/docx_file_containing_list_numbering_style.docx)
')

par = doc.add_paragraph(
    'first item in ordered list', style='ListNumber'
)

par2 = doc.add_paragraph(
    'Indent_1', style='ListNumber'
)

par3 = doc.add_paragraph(
    'Indent_2', style='ListNumber'
)

PPr = par._element.getchildren()[0]
numpr = OxmlElement('w:numPr')
val = OxmlElement('w:ilvl')
val.set(qn('w:val'), "0") #<---- sets the list level
numid = OxmlElement('w:numId')
numid.set(qn('w:val'), '5') #<---- Contains the reference to your numbering style
numpr.append(val)
numpr.append(numid)
PPr.append(numpr)

PPr = par2._element.getchildren()[0]
numpr = OxmlElement('w:numPr')
val = OxmlElement('w:ilvl')
val.set(qn('w:val'), "1") #<---- sets the list level
numid = OxmlElement('w:numId')
numid.set(qn('w:val'), '5')
numpr.append(val)
numpr.append(numid)
PPr.append(numpr)


PPr = par3._element.getchildren()[0]
numpr = OxmlElement('w:numPr')
val = OxmlElement('w:ilvl')
val.set(qn('w:val'), "2") #<---- sets the list level
numid = OxmlElement('w:numId')
numid.set(qn('w:val'), '5')
numpr.append(val)
numpr.append(numid)
PPr.append(numpr)

doc.save('test.docx')
```

You can find the reference to your numbering style using the Open XML SDK productivity tool, and check the '/word/numbering.xml' part. There you'll find the `numId` values:

```xml
<w:num w:numId="5" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:abstractNumId w:val="8" />
</w:num>
```

and the corresponding numbering style can be found in the referenced `w:abstractNum` file, I've only included the first three levels (` <w:lvl w:ilvl="0">,  <w:lvl w:ilvl="1"> and  <w:lvl w:ilvl="2">`):

```xml
<w:abstractNum w:abstractNumId="8" w15:restartNumberingAfterBreak="0" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:nsid w:val="126D0B76" />
  <w:multiLevelType w:val="multilevel" />
  <w:tmpl w:val="0809001F" />
  <w:lvl w:ilvl="0">
    <w:start w:val="1" />
    <w:numFmt w:val="decimal" />
    <w:lvlText w:val="%1." />
    <w:lvlJc w:val="left" />
    <w:pPr>
      <w:ind w:left="360" w:hanging="360" />
    </w:pPr>
  </w:lvl>
  <w:lvl w:ilvl="1">
    <w:start w:val="1" />
    <w:numFmt w:val="decimal" />
    <w:lvlText w:val="%1.%2." />
    <w:lvlJc w:val="left" />
    <w:pPr>
      <w:ind w:left="792" w:hanging="432" />
    </w:pPr>
  </w:lvl>
  <w:lvl w:ilvl="2">
    <w:start w:val="1" />
    <w:numFmt w:val="decimal" />
    <w:lvlText w:val="%1.%2.%3." />
    <w:lvlJc w:val="left" />
    <w:pPr>
      <w:ind w:left="1224" w:hanging="504" />
    </w:pPr>
  </w:lvl>
  <w:lvl w:ilvl="3">
    <w:start w:val="1" />
    <w:numFmt w:val="decimal" />
    <w:lvlText w:val="%1.%2.%3.%4." />
    <w:lvlJc w:val="left" />
    <w:pPr>
      <w:ind w:left="1728" w:hanging="648" />
    </w:pPr>
  </w:lvl>
</w:abstractNum>
```


I've attached the file I've used to generate this, good luck, and I hope you succeed

**Comment by 1kozlovsas** [comment]
Thank you for your reply! Honestly until this API is a bit more fleshed out I've decided to look into C# as it has an official Microsoft library for interacting with Word documents. I really appreciate the insight however and may return to this library once it has a few more features.
