### ISSUE TITLE
Highlighting is applied to all text

### ISSUE THREAD

**Issue by halobeau** [python-openxml/python-docx#512]
I'm trying to highlight each paragraph that contains a matching string. Problem is, the entire document is highlighted yellow. Any help is appreciated.

```
 for paragraph in document.paragraphs:
      for run in paragraph.runs:
           if run.text.find("text to find") >= 0:
                paragraph.style.font.highlight_color = WD_COLOR_INDEX.YELLOW
```

**Comment by scanny** [comment]
Try printing out the text instead of highlighting it and make sure your find is working the way you expect. If it is, narrow it down to a single call that's doing something unexpected. Otherwise there's no direct evidence of an issue.

**Comment by halobeau** [comment]
The highlight was being applied to the style for the document since the paragraph has no explicit style set. Just had to create a new style and apply it to the paragraph.

```
  review_style = document.styles.add_style("Review Highlight", WD_STYLE_TYPE.PARAGRAPH)
  review_style.font.highlight_color = WD_COLOR_INDEX.YELLOW
  for paragraph in document.paragraphs:
     for run in paragraph.runs:
        if run.text.find("text to find") >= 0:
           paragraph.style = review_style

```
