### ISSUE TITLE
Is this library not updated? Everybody gave up?

### ISSUE THREAD

**Issue by yeshida** [python-openxml/python-docx#521]
Is this library not updated? Everybody gave up?

**Comment by Benjamin-T** [comment]
What would you like to see implemented? See issue #487, for nice to have functionalities. And if you want to add something to the list, feel free to start working on a feature analysis :)

**Comment by wheeled** [comment]
I was wondering the same.  The last commit was two years ago, or am I looking at the wrong repo?

I started looking for functionality that seemed to be described in the dev docs - reading/updating the text in headers and footers.  Is it implemented?  The dev docs indicated that "every section has a header" but if I tried the obvious section.header there is no such attribute.

I also noticed that the TOC (reading from an existing file) gets saved to the output but doesn't seem to be updating any more.  The bookmarks for each heading are present bu the table itself doesn't seem to be marked as a TOC.
