### ISSUE TITLE
Editing text in header

### ISSUE THREAD

**Issue by Spandan-Madan** [python-openxml/python-docx#527]
Spent hours trying to make this work. I have a docx file and I want to edit some things in the header. Other issues talked about extracting text. I can extract text from headers, my problem is I need to edit it. Any workarounds on how to do it?

If you're interested in just accessing the data, use this:- 

```
parts = document.part.package.parts
for part in parts:
    if part.partname.find('header')>0:
        header_text = part.blob.decode()
        print(header_text)
```

How do I go about editing this? I tried editing the part.blob property, but I got this error:- 

`AttributeError: can't set attribute`

Any leads would be greatly appreciated!

Thanks,
Spandan

**Comment by scanny** [comment]
Header and footer support will be released with v0.8.8 in the next day or two. Until then a working version is available on the `spike-header` branch.
