### ISSUE TITLE
Documentation suggests deprecated usage

### ISSUE THREAD

**Issue by TomFaulkner** [python-openxml/python-docx#528]
The documentation https://python-docx.readthedocs.io/en/latest/index.html suggests using `style='IntenseQuote` for `add_paragraph`. This usage produces a deprecation warning. I've not used the library until trying it out today, otherwise I would create a PR with what the proper usage should be.

```
document.add_paragraph('hello world', style='IntenseQuote')
/.env/lib/python2.7/site-packages/docx/styles/styles.py:54: UserWarning: style lookup by style_id is deprecated. Use style name as key instead.
  warn(msg, UserWarning)
```

**Comment by scanny** [comment]
The styles should now be specified with the name exactly as they appear in the style gallery of the Word application UI, so 'Intense Quote' in this case (note the added space character).

I've updated the documentation page to reflect this.

Thanks for reporting :)

**Comment by johnchiverton** [comment]
For anyone looking here in 2023 (like me), list the available styles with:

`
for style in doc.styles:
    if "_TableStyle" in str(style):
        print(style)
`

The table styles shown in Word when hovering over the thumbnails sometimes have hyphens in. These should be excluded from the code. E.g. to use the style 'Colorful Shading - Accent 3' (as shown in Word), use `table.style = "Colorful Shading Accent 3"` (no hyphen).
