### ISSUE TITLE
Can’t connect securely to this page This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.

### ISSUE THREAD

**Issue by vonmoosa** [python-openxml/python-docx#529]
I receive a security error when trying to connect to:  

https://files.pythonhosted.org/packages/54/a6/43be8cf1cc23e3fa208cab04ba2f9c3b7af0233aab32af6b5089122b44cd/lxml-4.2.3.tar.gz#sha256=622f7e40faef13d232fb52003661f2764ce6cdef3edb0a59af7c1559e4cc36d1

Any plans to update the TLS security settings?

**Comment by RolandColored** [comment]
What's the deal with lxml here? Isn't it more a pip issue?

**Comment by scanny** [comment]
Cannot reproduce.

**Comment by ITExperienceNET** [comment]
Got this same error as vonmoosa. Turned out to be a config issue in my Edge browser. I had SSL 3.0 checked, but that seems to conflict with the TLS 1.0-TLS 1.2 checkmarks. See first screenshot:
http://www.itexperience.net/2018/11/16/fix-edge-error-cant-connect-securely-page/

**Comment by TheRealKnurft** [comment]
Got this same error as vonmoosa. Turned out to be a config issue in my Edge browser. I had SSL 3.0 checked, but that seems to conflict with the TLS 1.0-TLS 1.2 checkmarks. See first screenshot:
http://www.itexperience.net/2018/11/16/fix-edge-error-cant-connect-securely-page/
