### ISSUE TITLE
Any functionality to extract words per pages count?

### ISSUE THREAD

**Issue by melancholiaque** [python-openxml/python-docx#530]
Currently I’m trying to implement ugly algorithm which will fill pages (their sizes i get from `sectPr`) one by one with paragraphs (like tetris), which will (conceptually) yield a distribution of paragraphs across pages and therefore their textual content.
I have two questions:
1) How can i calculate space that paragraph will occupy to "fill the tetris"?
2) Am i stuck with stupid decision? Maybe this function already implemented or maybe i misunderstood library functionality capabilities? Could you give me a piece of advise.

I shall be very grateful.

**Comment by RolandColored** [comment]
docx files are kind of fluid files, which means they do not determine, where each paragraph gets rendered. It's only possible to know the position of a text block, after the document gets rendered, e.g. in Word.
We are dealing with a similar problem. In the end, we are converting the docx to a pdf, a fixed layout format, and extract the location information from there. We use LibreOffice (via unoconv) for this, which works quite well if you have all needed fonts in place.

**Comment by scanny** [comment]
Thanks @RolandColored, well done :)
