### ISSUE TITLE
replace text using python docx

### ISSUE THREAD

**Issue by MaaleRw** [python-openxml/python-docx#533]
I try to change the text in the original docx - file.

I wrote the codes:   

for paragraph in document.paragraphs:
    for run in paragraph.runs:
        if run.font.size:
            run.text = ' " ' + run.text + ' " '
       
but the order dosen't replace the text in the original file.

**Comment by Benjamin-T** [comment]
you might want to double check the if statement; because this code example works for me:

```python
from docx import Document
document = Document()
par = document.add_paragraph('test text')
for paragraph in document.paragraphs:
    for run in paragraph.runs:
#         if run.font.size:
        run.text = ' " ' + run.text + ' " '

for paragraph in document.paragraphs:
    for run in paragraph.runs:
        print(run.text)
>>>   " test text " 
```

**Comment by MaaleRw** [comment]
thx, but I want python to add quotation marks only while the font text size is 15 and not for each run...

In addition, I thought about it, and if python will add quotation marks to each run, it might to add

it even when there is a sequence of run in size 15, therefor, prehaps I will need to order:

"while run.font.size...."

[likes for "HELLO WORLD i like to..." --> " 'HELLO' 'WORLD' i like to..." (I use upper case to present 

letter in size 15). Anyway, right now I didn't succeed do it even for each run.

**Comment by martinmde** [comment]
Is this really an issue? Can it be closed?

**Comment by jonasao** [comment]
Try reading the font size from `paragraph.style.font.size` instead of reading it from `paragraph.runs...`.

**Comment by scanny** [comment]
@MaaleRw StackOverflow is a good place for learning-support questions like this. Make sure you use the "python-docx" tag on the question so those of us that follow that tag will see it.
