### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by mwen1993** [python-openxml/python-docx#534]
Hi,
while following the documentation on merging cells i came across a typo in the example code.

Link to the documentation page: 
http://python-docx.readthedocs.io/en/latest/dev/analysis/features/table/cell-merge.html

Under the Section: Basic merge protocol

the sample code:

>>> table = document.add_table(3, 3)
>>> a = table.cells(0, 0)
>>> b = table.cells(1, 1)
>>> A = a.merge(b)

instead of table.cells it should be table.cell

Thank you

**Comment by scanny** [comment]
Thanks @mwen1993, I've updated the docs and the fix should appear in next release :)
