### ISSUE TITLE
Add picture with width or height, whichever is greater

### ISSUE THREAD

**Issue by mx2048** [python-openxml/python-docx#535]
My idea is to confine too wide or too long images.  I've already done that, and it works fine:
```
import requests
from docx.image.image import Image, _ImageHeaderFactory

def get_binary_image(image_url):
    response = requests.get(image_url)
    binary_img = io.BytesIO(response.content)
    return binary_img

# Some code here to initialise paragraph `p` 

binary_img = get_binary_image(sn)
image_stream = Image(None, None, _ImageHeaderFactory(binary_img))
if image_stream.width > image_stream.height:
    p.add_run().add_picture(binary_img, width=Inches(2))
else:
    p.add_run().add_picture(binary_img, height=Inches(1.5))
```

My question is: Is it the most efficient way to implement that?

**Comment by slash5k1** [comment]
Seems pretty straight forward.. 

You have a function that grabs the binary image and then your conditionally checking the width to then add to a paragraph. - I would leave it.

I would suggest closing the issue and asking the question on stackoverflow and tagging the question against python-docx if your not happy with your code.
