### ISSUE TITLE
Add nested table without newline

### ISSUE THREAD

**Issue by brainrecursion** [python-openxml/python-docx#541]
Currently when you add a new table into an existing table cell there is a newline inserted before the table. I understand this is because the standard requires a paragraph element in each cell. Is there a way to make this paragraph not add a newline? 

An example of the table you currently get is:

![screen shot 2018-08-30 at 11 37 20](https://user-images.githubusercontent.com/16461841/44846882-ac69b900-ac49-11e8-9af8-2c4db8f1dd78.png)

Where as I would like:
![screen shot 2018-08-30 at 11 38 21](https://user-images.githubusercontent.com/16461841/44846887-affd4000-ac49-11e8-8723-c5a93465ab4f.png)

This must be possible as if you generate a nested table using python-docx and then open the document with Word it is possible to manually remove the newline to get the table above. Looking at the document.xml after this change the paragraph element appears to be deleted.

**Comment by scanny** [comment]
If you add this code before each `cell.add_table()`, I think that will do the trick:

```python
cell._element.clear_content()
```

There is a `.clear()` method  on some other API objects which does about the same. It might be a good feature request to have one on `_Cell` as well for just this situation. It could also be used to make adding a set of paragraphs uniform; as it stands the first (default) paragraph needs to be handled differently than those subsequent, which can complicate code like that.

Note that as you observe above, if you clear the content without adding the table you might get a repair error.

**Comment by brainrecursion** [comment]
Thanks this works great.
