### ISSUE TITLE
How to add text in shade/picture?

### ISSUE THREAD

**Issue by MatthewP-Newbee** [python-openxml/python-docx#544]
Hello, I need to create 2 shades/pictures(see below `title` and `Some String`)
![image](https://user-images.githubusercontent.com/34641678/45076166-feb04b80-b11b-11e8-83e6-bdb371d051c9.png)
My MS-word language isn't English. The shade with `Some String` seems to be a build-in style. However I can not get the English name of that style use [DocTools](https://www.thedoctools.com/word-macros-tips/word-macros/create-style-name-list/).   
Anyone know how to create this two shades?  
Thinks.

**Comment by scanny** [comment]
Please ask support questions on StackOverflow and tag the question with `python-docx`. This issues list is for feature requests and suspected bugs.

A lot more people monitor StackOverflow and will invest the time to help you if you accept correct answers and upvote all those that have been helpful (including the correct one).
