### ISSUE TITLE
How can I sort a table in a docx file?

### ISSUE THREAD

**Issue by moshesak** [python-openxml/python-docx#546]
I have a report that consists out of hundreds of tables. I want to be able to go over the whole document and change the sorting of certain tables according to a certain column (the left most) this is true for most of the tables in this report. This is essential for me because this I generate these kind of reports once in a while and I can;t control the sorting format in this system.

I already know how to find the number of tables in the document:

```
import docx

document = docx.Document('demo.docx')
len(document.tables)
```

I know how to deal with each of these tables but I haven't found the way to change the sorting of a column.
What I need is to know if there is a method that deals with the sort function ?

**Comment by moshesak** [comment]
I saved this issue by using macro script

**Comment by ndahn** [comment]
For future reference, the macro could look like this:

```
Sub SortTables()
    Dim tbl As Table
    For Each tbl In ActiveDocument.Tables
        tbl.Select
        Selection.Sort ExcludeHeader:=True, FieldNumber:="Column 1", SortFieldType:=wdSortFieldAlphanumeric, SortOrder:=wdSortOrderAscending
    Next
End Sub
```
