### ISSUE TITLE
inserting xml-snippet into docx using the python-docx api

### ISSUE THREAD

**Issue by ghost** [python-openxml/python-docx#55]
We need to change header text-orientation of tables. We are aware that this may not be possible with the current state of the API.  We identify the xml-snippet to be inserted using opc-diag as suggested elsewhere. Can we use xml-snippet insertion to achieve this? If yes what is the API-command to do the xml-insertion at a specific point of the docx?
-- sub

**Comment by trampas** [comment]
I have just upgraded python-docx and the following code no longer works.

       hdr_cells = table.rows[0].cells
        print hdr_cells
        hdr_cells[0].text = title
        set_merge(hdr_cells[0],nCols)
        for ki in range(nCols-1):
                if len(hdr_cells)>1:
                    n=hdr_cells.__getitem__(1)._tc
                    if (n!=None):
                        hdr_cells._tr.remove(n)

Specifically I get the following error:
    hdr_cells._tr.remove(n)
AttributeError: 'tuple' object has no attribute '_tr'

I use the _tr for accessing XML for the row in several places and was
wondering if there was a better way with new code?

For example I set the row height like:
def set_row_height(row, height):
    tr = row._tr
    trPr = tr.find(qn('w:trPr'));
    if trPr==None:
        x=OxmlElement('w:trPr')
        tr.append(x);
        trPr = tr.find(qn('w:trPr'));
    textDirection = OxmlElement('w:trHeight')
    textDirection.set(qn('w:val'), str(height))
    trPr.append(textDirection)

Thanks
Trampas
