### ISSUE TITLE
new request: add picture from clipboard

### ISSUE THREAD

**Issue by jopasi** [python-openxml/python-docx#553]
Hello,
Thank you for developing this app. It is really useful.

If you do not mind, I raise a request to add new feature.
Could you please, add a possibility to copy a picture to a docx document from clipboard?
Paste from paperclip module like:

doc.add_picture(**paperclip.paste()**,width=doc.shared.Cm(10), height=doc.shared.Cm(15)) 

I really appreciate your solution/development.

Thank you,
Lac

**Comment by scanny** [comment]
A feature like this would not be appropriate to `python-docx`. The reason being it would represent an integration with the operating system (OS X, Linux, Windows), which is more appropriate for the application developer to make decisions about. If there is a suitable Python clipboard library available I'm sure you can readily integrate the two.
