### ISSUE TITLE
Python-docx prerequisites

### ISSUE THREAD

**Issue by Arunava78** [python-openxml/python-docx#555]
Do I need to have MS Word installed on the system where I'm using Python-docx? 

Currently I'm just reading a docx file and heavily relying on the paragraph styles to parse the document. In my local system it is working perfectly but the same code is not recognizing any paragraph styles when run from a box where everything is installed except MS Word.

**Comment by Arunava78** [comment]
I need some urgent help here, also I'm open to suggestions on any workaround.

**Comment by scanny** [comment]
No. `python-docx` does not rely on MS Word in any way.

**Comment by scanny** [comment]
If you want more help with your problem, best bet is to post a question on StackOverflow using the 'python-docx' tag. You'll need to provide much more detail about the problem and best if you narrow it down to the smallest reproducible example, like open doc, read style, look for style, exception.

**Comment by Arunava78** [comment]
Thanks @scanny for the response.

This is the code I'm using. When I'm running the code in the other box the "str(para.style)" is returning me 'nothing'
A little more info My local box is Win10 and the remote is Windows Server
----------------------------------------
from docx import Document

stylestoconsider = ["Heading 1", "Subtitle", "Title Centered", "TOC Title", "Heading 2"]
docTitle = ""
def presentinlist(paragraphstyle):
    retval = 0
    for style in stylestoconsider:
        if style in paragraphstyle:
            retval = 1
            break
        else:
            retval = 0
    return retval

# This is the Word Document on hard drive
doc = Document('C:\\Users\\agho10\\PycharmProjects\\SDLC_BOT_SIMPLE.docx')

# Retrieve the doc title
for para in doc.paragraphs:
    parastyle = str(para.style)
    result = presentinlist(parastyle)
    # Capture the Document Title
    if "Project Title" in parastyle or "Title Centered" in parastyle:
        if docTitle == "":
            docTitle = para.text
            print(docTitle)


# Reading the docx file and build the data
for para in doc.paragraphs:
    # Build the document structure
    parastyle = str(para.style)
    result = presentinlist(parastyle)
    if result == 1 and not para.text == "":

**Comment by scanny** [comment]
I think you'll want to use `paragraph.style.name` rather than `str(paragraph.style)`:

```python
for paragraph in document.paragraphs:
    style_name = paragraph.style.name if paragraph.style else 'None'
    print(style_name)
```

For further help with support questions like these, please use StackOverflow. You can post a question with the 'python-docx' tag and a lot of helpful folks will see it.

**Comment by Arunava78** [comment]
I tried this but the paragraph.style is coming as Nothing and so is the paragraph.style.name

**Comment by scanny** [comment]
Sounds like you're due for some quality time with the documentation on styles:  
https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html  
https://python-docx.readthedocs.io/en/latest/user/styles-using.html  

This is the expected behavior. Not all paragraphs have a style. Absent an explicit style, a paragraph inherits the document default paragraph style, which is almost always the paragraph style named 'Normal'.

Your code will need to accommodate that common situation.

**Comment by Arunava78** [comment]
Thanks for the reference @scanny but this document has styles applied in all the paragraphs when it was created in MS Word. The same document and code is working perfectly in my laptop but not in the remote machine. This is where I'm getting puzzled.

**Comment by scanny** [comment]
Do you have the same version of `python-docx` running on the server? There was an old version named just `docx` (like `pip install docx`) that was very different and is now very much behind the current version of `python-docx`.

If that's not it, you'll just have to troubleshoot your particular installation and deployment situation until you find what's wrong. It sounds like the `python-docx` code is working as expected (your laptop being the proof of that).
