### ISSUE TITLE
Max size option for adding images

### ISSUE THREAD

**Issue by xavikxavik** [python-openxml/python-docx#559]
I usually set height for the size of the image added. However, if images with different sizes are added this is a problem because the image can extend beyond the limit of the page if it had a small height.

Setting the width would make some images too small.

Therefore it would be interesting to have for example a maximum width option so at least it doesn't get out of the page.

**Comment by scanny** [comment]
This is the application-specific sort of thing we would expect you to implement yourself. It's important to keep the already very broad API for `python-docx` as simple as possible and a big part of this is keeping the interface general-purpose. Such an approach might not be a perfect fit for anyone, but gives everyone what they need to get their particular job done.

The object returned by `Document.add_picture` has read/write `.width` and `.height` attributes you could use something like this:

```python
def scale_picture(picture, new_height):
    aspect_ratio = float(picture.width) / float(picture.height)
    picture.width = int(aspect_ratio * new_height)
    picture.height = new_height

picture = document.add_picture(...)
if picture.height > max_picture_height:
    scale_picture(picture, max_picture_height)
```
