### ISSUE TITLE
can't get font styles of paragraph

### ISSUE THREAD

**Issue by moda20** [python-openxml/python-docx#562]
hey !
I am using the final version of python-docx. and i tried to get the fonts of a paragraph, then change its text, then affect back the original font to the changed paragraph. 
I am doing this because i was loosing the original font style after changing the text.
but even after doing so it still doesn't work. 

while the doc clearly has the `calibri` font i still get None when printing the paragraph.font.name. the paragraph has the general style of `Heading 1` but has a different font name and size and those differences don't show up on the python code. 

Why is this happening, Is this a bug ?

**Note :** I did read about the hierarchy styles, but there is no docs on that.

**Comment by scanny** [comment]
You'll generally get better response to support questions on StackOverflow (be sure to use 'python-docx' tag). Make sure you post the code you used that's giving you this behavior.
