### ISSUE TITLE
Prb with encoding of accents

### ISSUE THREAD

**Issue by kociak** [python-openxml/python-docx#57]
Hi

I have used this beautiful piece of code and I am really astonished how easy it is to use.
Now, I have a problem. When generating a docx containing accents (french, spanish, german.... any!), wrong characters are printed. I am encoding in UTF8 before fetching the strings to add_run, but this does not work... Is this a bug?

Thanks for the answer

cheers

**Comment by TrongNguyenVann** [comment]
Thank you @scanny very much. It helps me solve the same problem when working with japanese too!
