### ISSUE TITLE
Line spacing on single paragraph

### ISSUE THREAD

**Issue by IntelligentFunction** [python-openxml/python-docx#575]
Line_spacing for a single paragraph does not appear to work:
```
from docx.enum.text import WD_LINE_SPACING

doc = Document()
para = doc.add_paragraph()
para.line_spacing = WD_LINE_SPACING.DOUBLE
```

Has no effect on the paragraph in question. Line spacing does work on a document level through the Document.styles, but this creates too much white space for tables or single line paragraphs. in the rest of a document.

**Comment by scanny** [comment]
The `Paragraph` object has no `.line_spacing` attribute. Your last like of code just adds a `.line_spacing` instance attribute to no effect.

The `.line_spacing` property is on `ParagraphFormat`:

```python
paragraph = document.add_paragraph()
paragraph.paragraph_format.line_spacing = WD_LINE_SPACING.DOUBLE
```

**Comment by IntelligentFunction** [comment]
Yes you are right that does work, I see my error now, I should have asked about ONE_POINT_FIVE, that doesn't work.

**Comment by scanny** [comment]
Okay, actually if you're going to use a member of `WD_LINE_SPACING`, the proper attribute is `.line_spacing_rule` (see the link to API docs below):

```python
paragraph.paragraph_format.line_spacing_rule = WD_LINE_SPACING.DOUBLE
```

Another valid way to set that is with the `.line_spacing` property like:

```python
paragraph.paragraph_format.line_spacing = 1.5
```

**Comment by IntelligentFunction** [comment]
Thank you scanny, you are an absolute star! this one has had me stumped for a few weeks. Really appreciate the work that you!
