### ISSUE TITLE
Fails to detect underscore after some minor changes in the word file

### ISSUE THREAD

**Issue by siddharth-das** [python-openxml/python-docx#589]
First the python script was executed on SampleUnchanged.docx file and the result was correct. All underscores were detected.

![sampleunchanged](https://user-images.githubusercontent.com/35198631/50443093-bcf41c80-0927-11e9-9214-dab7841c467b.PNG)

In the second attempt minor changes were made to the SampleUnchanged.docx file and was saved with the name SampleChanged.docx and the same python script was executed to read the new file. None of the undesrscores of the second paragraph were detected. 

![samplechanged](https://user-images.githubusercontent.com/35198631/50443100-c5e4ee00-0927-11e9-9ca7-85a0900f0b21.PNG)

@scanny Please have a look. I have also uploaded the respective docx files that were used as inputs

[SampleUnchanged.docx](https://github.com/python-openxml/python-docx/files/2710055/SampleUnchanged.docx)
[SampleChanged.docx](https://github.com/python-openxml/python-docx/files/2710056/SampleChanged.docx)

**Comment by scanny** [comment]
The inserted underscores in SampleChanged.docx appear inside a fill-in field. If you insert them as plain text it should work fine.
