### ISSUE TITLE
How to read word doc in sequence?

### ISSUE THREAD

**Issue by ErickGSJ** [python-openxml/python-docx#593]
hi

Word doc has texts, tables and pictures and they are always mixed up.  How to read word doc in sequence?
Going through the docs but didn't find that. Python-docx either handle all tables or texts at one time.

**doc file:**
**Chapter 1**
paragraph 1
table1
pic1
**Chapter 2**
paragraph 2
table2
pic2

I want to parse the doc in the same sequence and display in frontend, how can i do that?

Thanks in advance

**Comment by scanny** [comment]
Please use StackOverflow (using the "python-docx" tag) for support questions.  https://stackoverflow.com/questions/tagged/python-docx

If you search there on "python-docx iter_block_items" you should find what you're looking for.
