### ISSUE TITLE
Tutorial bug - "Header" style already exists

### ISSUE THREAD

**Issue by skrupenin1** [python-openxml/python-docx#597]
I get an error when following the _2.6.3 Adding “zoned” header content_ section of the latest (0.8.9) [tutorial](https://media.readthedocs.org/pdf/python-docx/latest/python-docx.pdf) with the 0.8.10 release. The error is "ValueError: document already contains style 'Header'". Steps to reproduce:

`from docx import Document`
`from docx.enum.style import WD_STYLE_TYPE`
`document = Document()`
`styles = document.styles`
`style = styles.add_style("Header", WD_STYLE_TYPE.PARAGRAPH)`

Apparently, the default docx template now contains a header style, where it did not previously.

**Comment by scanny** [comment]
Ah yes! Thanks for reporting this. I wrote the user docs before developing the feature (very far) and by the end of development I figured it wouldn't do for folks to have to add that every time.

I'll get this fixed up to be part of the next release.

**Comment by jmreyen** [comment]
I have a script I wrote 3 years ago that gets this error.

`  
def __init__ ...
       self.header_style = self.document.styles.add_style('header', WD_STYLE_TYPE.PARAGRAPH)
        self.header_style.font.name = "Arial"
        self.header_style.font.size = Pt(10)
        self.header_style.font.all_caps = True
        self.header_style.font.bold = True
`
I wonder how to fix it properly. Can I just use another name or do I have to get the header style from the default template?

**Comment by scanny** [comment]
Fixed in release v0.8.11 on May 15, 2021.
