### ISSUE TITLE
Paragraph Spacing - lineRule options

### ISSUE THREAD

**Issue by DKWoods** [python-openxml/python-docx#598]
I recently discovered some DOCx files that specify the paragraph spacing a bit differently.  Instead of <w:spacing w:line="240" w:lineRule="exact"/>, it uses <w:spacing w:line="240" w:lineRule="exactly"/>, using a different value for the lineRule parameter.  

My copy of Word 2010 uses 'lineRule="exact"', as does python-docx.  I have not been able to find any documentation online that specifies allowable values for this parameter.  Does anyone know where I can find out if "exactly" is a synonym, perhaps used by a later version of Word?  The only other possibility I can think of is that the program producing these DOCx files is doing it wrong, but that's not really something I have control over.

**Comment by DKWoods** [comment]
Thanks Steve.  This is really helpful.

ISO-IEC-295000-1.pdf, in the ref directory, lists the value as "exactly" 
on page 252 at the bottom.  wml.xsd clearly uses "exact", as you have 
said.  ECMA 376 agrees with xml.xsd that the value is "exact", not 
"exactly".

When I create a simple example document in Word 2010 and replace "exact" 
with "exactly" in document.xml, then load the document, the line spacing 
in the Paragraph Formatting dialog is displayed as "Multiple" rather 
than "Exactly".  So there's that. Behaviorally, at least for Word 2010, 
the parameter must be "exact".

The source documents which are causing me this problem turn out to be 
converted PDF files which mix images and text.  The lineRule specs seem 
to appear in empty paragraphs preceding image specifications, so I'm 
guessing they're used in an attempt to mimic the PDF's layout.  They are 
honestly kind of a mess, as I look at them more closely.

So the other guy is wrong.  That and a dollar will buy me ... what, a 
quarter cup of coffee maybe?  I still have to support import of his 
documents, and based on previous experience, the developer of the other 
product is ... not open to suggestions for improving his code at this 
level.  It may well not even be his code that is introducing this issue.

So on a practical level, I suppose I will have to trap the error and 
ignore the incorrect value.  Right now, it raises an exception and 
blocks import of the document entirely.  Or maybe I should try to add 
"exactly" as a synonym for "exact" for lineRule.

Thanks for the insight.  I feel better knowing the correct answer, even 
if I'm not in a position to force the issue.

David

**Comment by scanny** [comment]
Hmm. The discrepancy in the spec is a plausible explanation for how the error got there. Although the Xml Schema is the final word, not the spec. And the fact that Word doesn't accept it seals the case for me.

One thing you might consider is writing a transform on the input XML, or even just doing a search and replace as a pre-processing step. You could use `opc-diag` to extract the package into a directory and then just use command-line tools like `sed` or `awk` or whatever to do an edit on document.xml or whatever part, and then load the .docx straight from the directory (no need to repackage). I suppose all those steps could be bundled up into a shell script.

A transform (like an XSLT transform) would be more powerful, but much more sophisticated and perhaps not worth the trouble unless there were multiple other repairs involved.
