### ISSUE TITLE
Error in the Picture Documentation?

### ISSUE THREAD

**Issue by kingdish** [python-openxml/python-docx#599]
Hi,

I might find a deprecated API usage (or new feature?) in the Candidate Protocol section in the [Picture documentation](https://python-docx.readthedocs.io/en/latest/dev/analysis/features/shapes/picture.html?highlight=add%20inline%20picture). It writes
`run = paragraph.add_run()`
`inline_shape = run.add_inline_picture(file_like_image, MIME_type=None)`
`inline_shape.width = width`
`inline_shape.height = height`

However, when the code is executed, an error will be thrown:
`AttributeError: 'Run' object has no attribute 'add_inline_picture'`

I think the correct usage in the current version (0.8.9) should be
`inline_shape = run.add_picture(file_like_image)`

Also it seems `MIME_type` is not supported
`TypeError: add_picture() got an unexpected keyword argument 'MIME_type'`

**Comment by scanny** [comment]
yeah, the analysis documents don't necessarily reflect the actual as-implemented interface, although we try to update them with as-built to avoid confusion like this. I'll mark this one for update next time we make a release.

**Comment by scanny** [comment]
Fixed in release v0.8.11 on May 15, 2021.
