### ISSUE TITLE
Can't import WD_ALIGN_PARAGRAPH，How to align the text at both ends

### ISSUE THREAD

**Issue by shuguoli68** [python-openxml/python-docx#601]
I want the text to be justified, but I can't use from docx.enum.text import WD_ALIGN_PARAGRAPH, I get an error: "Cannot find reference 'WD_ALIGN_PARAGRAPH' in 'text.py' less... (Ctrl+F1)"
I found the WD_PARAGRAPH_ALIGNMENT class in test.py and tried to import from docx.enum.text import WD_PARAGRAPH_ALIGNMENT, but this class doesn't seem to have any useful methods. Can you help me? Any help will be appreciated!
My goal: to align the text at both ends instead of the default left alignment.

**Comment by kingdish** [comment]
From [this documentation](https://python-docx.readthedocs.io/en/latest/api/enum/WdAlignParagraph.html?highlight=WD_ALIGN_PARAGRAPH), you indeed need to import that first
`from docx.enum.text import WD_ALIGN_PARAGRAPH`

So you can set the alignment of your paragraph like this
`your_paragraph.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.DISTRIBUTE`

**Comment by scanny** [comment]
Please use StackOverflow with the "python-docx" tag to ask support questions. When you do you'll want to include the code you used and the actual error.  
https://stackoverflow.com/questions/tagged/python-docx

**Comment by shuguoli68** [comment]
> From [this documentation](https://python-docx.readthedocs.io/en/latest/api/enum/WdAlignParagraph.html?highlight=WD_ALIGN_PARAGRAPH), you indeed need to import that first
> `from docx.enum.text import WD_ALIGN_PARAGRAPH`
> 
> So you can set the alignment of your paragraph like this
> `your_paragraph.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.DISTRIBUTE`
> 
> EDIT: Oops... didn't see you couldn't import that class... As a temporary fix, you can set that to 4, which is the value of `WD_ALIGN_PARAGRAPH.DISTRIBUTE`. But you should fix the import problem anyway...

Thank you very much, just use your_paragraph.paragraph_format.alignment = 3 to solve the problem. I looked at the source code of python-docx, it should be the name of the class modified, and an alias.
This is the source I found in docx.enum.text.py:
`@alias('WD_ALIGN_PARAGRAPH')
class WD_PARAGRAPH_ALIGNMENT(XmlEnumeration):
    """
    alias: **WD_ALIGN_PARAGRAPH**

    Specifies paragraph justification type.

    Example::

        from docx.enum.text import WD_ALIGN_PARAGRAPH

        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    """`
