### ISSUE TITLE
Table styles not found

### ISSUE THREAD

**Issue by bferguson3** [python-openxml/python-docx#603]
This code works, from the examples in the docs:
`table.style = 'LightShading-Accent1' `
while generating a deprecation warning.

This code does not:
`table.style = 'Light Shading - Accent 1' `
says no style find.

In Word 365, on Windows 10, the name of "LightShading-Accent1" is 'Light Shading - Accent 1' as expected, though as I said python-docx does not recognize it as a style.

Plain styles such as 'List Table 3' (verbatim as displayed in the Word table styles list) will give a `no style found` error for both `ListTable3` and `List Table 3`.

Is there no way to simply generate a legal list of table styles that your extension will support?

**Comment by bferguson3** [comment]
This also does not work by creating a new style in Word with a name e.g. 'CustomStyle1'.

**Comment by scanny** [comment]
Check out the documentation on styles here:  
https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html

and here:  
https://python-docx.readthedocs.io/en/latest/user/styles-using.html

The former lists all the style names in the default .docx. Try "Light Shading Accent 1" (drop the hyphen). The docs also give a snippet for printing out styles by name.

**Comment by bferguson3** [comment]
Thanks - that list at the bottom was exactly what I was looking for, not sure how I missed it the first time.
