### ISSUE TITLE
Python to search for a specific table in word document

### ISSUE THREAD

**Issue by rahul12987** [python-openxml/python-docx#613]
Hi,

I am new to python.. and have done a small hands-on on the python-docx module.
I am having a requirement in which I have to read a word document which contains multiple tables and text.
Out of this document I have to select  specific table to read and that selection depends on the text written in the line just above the table, and then I have to process the data of that table.

I am able to read the table data by referring the table with its index, but in this case the table index is unknown and it can be at any position in the document. The only thing by which I can identify the table is the text written in the line just above the table.

Can you please help me achieving this?

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the "python-docx" tag. This issues list is for feature requests and suspected bugs.

You might also do a search on "python-docx iter_block_items" which might help you with table identification.
