### ISSUE TITLE
How can I find and replace a word in footer of word document using "Python docx"?

### ISSUE THREAD

**Issue by eranjan90** [python-openxml/python-docx#618]
It is very easy to create a footer by python-docx. But when I want to find and replace word in footer, I am unable to do that.
For example: I have a paragraph in footer i.e "Page 1 of 10". I want to find word "of"  and replace it with "to". So my result will be "Page 1 to 10". How can I do that.
![footer](https://user-images.githubusercontent.com/26632531/52945827-a4890700-3398-11e9-9919-e879338e150d.png)

**Comment by scanny** [comment]
You access and edit the text of a paragraph in a footer the same way you would in the document body:

```python
footer = section.footer
footer_text = footer.paragraphs[0].text
new_text = footer_text.replace("of", "to")
footer.paragraphs[0].text = new_text
```

**Comment by kartiksinghal2020** [comment]
Is there any way to change the ordering of the pages? As I'm designing a report with a Table of content and need to add Page numbers and internal hyperlinks to the table of Content. So, Can you suggest how can we achieve this feature?
