### ISSUE TITLE
Security vulnerability in /docx/parts/image.py

### ISSUE THREAD

**Issue by srtripathy** [python-openxml/python-docx#620]
Hi
Our security compliance tool has identified a vulnerability with the use of a broken or risky cryptographic algorithm.  I think the issue is a false positive as the hash algorithm is used to create a hash of an image blob.  This is the analysis and potential remediation info:
File Name: /docx/parts/image.py
Line Number: 168
Info: This function uses the hashlib.sha1() function, which uses a hash algorithm that is considered weak. In recent years, researchers have demonstrated ways to breach many uses of previously-thought-safe hash functions such as MD5.
 
Consider using a stronger algorithm in order to prevent attackers from being able to manipulate hash results. If this algorithm is being used to hash passwords, then consider using a strong computationally-hard algorithm such as PBKDF2 or bcrypt instead of a plain hashing algorithm.
 
 References: 
 CWE (http://cwe.mitre.org/data/definitions/327.html)

**Comment by scanny** [comment]
Hi @srtripathy, yes, I think that would qualify as a false positive. In this context, the `sha1` function is used solely to create an identifier for the image, to test its equality to another, like a git commit hash.

Thanks for reporting this though, I'll monitor and see if it gives anyone a problem.
