### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by ImageViewGlide** [python-openxml/python-docx#633]
Hello!

Is there a way to copy elements of a document, or a document in general to clipboard instead of saving it to a document? Sometimes I just want to produce part of a document, and it's annoying to have to save it as a new doc and then manually open, copy and delete it.

**Comment by lcrmorin** [comment]
bump as I have the same question.

**Comment by pidgeon777** [comment]
I'm also interested.

**Comment by scanny** [comment]
This is not a feature that fits with the current system concept for `python-docx`.

Developing a general-case capability like this, perhaps with the idea that it worked like manual copy-paste from a Word document when using Microsoft Word would certainly be non-trivial. One would have to research the I'm sure multiple formats placed in the clipboard and replicate each one from information available within `python-docx`.

However, if you were satisfied with plain text, then that would be readily achievable by writing your own function and using available packages or other methods to copy text into the system clipboard from sources like `Paragraph.text`.

If I personally needed this capability for some project I would probably look at a "live client" solution like controlling Word with VBA or maybe scripting LibreOffice using its Python API.

Closing this issue as it's not actionable and such a feature is not forthcoming.
