### ISSUE TITLE
 importing module successfully, but when implementing in code showing error

### ISSUE THREAD

**Issue by aqifilyaskhan** [python-openxml/python-docx#652]
I don't know why am getting this errors:

Importing module & you can see its importing successfully

But when when implementing in code showing error

If the module doesn't exist so it shouldn't be visible on Terminal

from docx import Document
from docx.shared import Inches
from docx.shared import Cm
from docx.enum.table import *
#from docx.enum.table import WD_ROW_HEIGHT_RULE

table = document.add_table(rows=1, cols=2)
table.style = 'Medium Shading 1 Accent 2'
table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY

#rest of my rows & column code here

![1](https://user-images.githubusercontent.com/5977042/55507153-7de50e00-5670-11e9-9326-d06019437901.PNG)
![2](https://user-images.githubusercontent.com/5977042/55507154-7de50e00-5670-11e9-8211-04eafbff6ffd.PNG)

i asked this question twice on stackoverflow but no-one answered

**Comment by SuchithSridhar** [comment]
Could you take a screenshot of the error ?

**Comment by scanny** [comment]
@Muhammad-Subhan-Khan your report is not consistent and not complete. This makes it impossible for us to reason about the possible causes without guessing, which asks us to waste our time. This is perhaps why you did not receive responses on StackOverflow.

In the top code, the import for `WD_ROW_HEIGHT_RULE` is commented out. This will cause an error when you try to use it.

In the second block, you use a different enumeration (`WD_TABLE_ALIGNMENT`) which has no `EXACTLY` member, which causes a different error.

Please produce a consistent example which demonstrates the error you are receiving, and like @SuchithSridhar  mentions, show us the full and exact error your receive (the full stack trace).

**Comment by Muhammad-Subhan-Khan** [comment]
ok wait

**Comment by Muhammad-Subhan-Khan** [comment]
from docx import Document
from docx.shared import Inches
from docx.shared import Cm
from docx.enum.table import WD_ROW_HEIGHT_RULE

document = Document()
document.add_heading('INVOICE', 0)

#rest of my paragraph etc

#654 now table code here

table = document.add_table(rows=1, cols=2)
table.style = 'Medium Shading 1 Accent 2'
table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY

#here am getting this error "Class 'WD_ROW_HEIGHT_RULE' has no 'EXACTLY' member"
#i saw source file & there EXACTLY is available even if i try LEFT or RIGHT still getting same error

               hdr_cells = table.rows[0].cells
                hdr_cells[0].text = 'Job Description'
                # hdr_cells[1].text = 'Id'
                for qty, id in records:
                    row_cells = table.add_row().cells
                    row_cells[0].text = str(qty)
                    row_cells[1].text = id

**Comment by scanny** [comment]
Try `print(WD_ROW_HEIGHT_RULE)` before line 108 and report what you get. The expected value is `<class 'docx.enum.table.WD_ROW_HEIGHT_RULE'>`. If it is not, perhaps you made an assignment to that name earlier in your code

**Comment by scanny** [comment]
Okay, on further inspection, I think this error is spurious. This is a `pylint` warning, not a Python error. The `WD_ROW_HEIGHT_RULE` adds its members using a metaclass, so they are not defined on the class itself. Pylint can't detect this.

You can either ignore this error or tell pylint to ignore it by adding `# pylint: disable=no-member` at the end of that line, like:

```python
... = WD_ROW_HEIGHT_RULE.EXACTLY  # pylint: disable=no-member
```

**Comment by Muhammad-Subhan-Khan** [comment]
@scanny  ok now am not getting that error, but my file is not opening 
if i remove your given code so i can open file then (but getting then error)

![2](https://user-images.githubusercontent.com/5977042/55675105-07961500-58d7-11e9-993f-8b0684b26bc7.PNG)
table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY# pylint: disable=no-member

**Comment by scanny** [comment]
If you remove that one line, does the error go away? If not, your problem is elsewhere.

**Comment by Muhammad-Subhan-Khan** [comment]
if i use this line 
table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY
so getting error
but if i use below code then not getting error in terminal but unable to open my saved / generated docx file

table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY # pylint: disable=no-member

**Comment by scanny** [comment]
what about if you comment out that line entirely? I expect you still get the "repair error", meaning this line is not the cause.

**Comment by Muhammad-Subhan-Khan** [comment]
if i comment or remove this line 
table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY
so not getting error, but obviously how i will  use this module then

i wanna use this "WD_ROW_HEIGHT_RULE.EXACTLY" 
that's the reason i asked for help, rest of my code is working fine but whenever i try to use above module or even "WD_TABLE_ALIGNMENT" so getting no-member error

**Comment by scanny** [comment]
Does the file save and open without error if you comment or remove that line? I'm having trouble following your English.

**Comment by Muhammad-Subhan-Khan** [comment]
yeah i am sorry my english is bad

i tried to clear in this post
1- if i use this line
table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY
so getting error in terminal "Class 'WD_ROW_HEIGHT_RULE' has no 'EXACTLY' member"

2- if i use this line
table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY # pylint: disable=no-member 

then not getting any error in my IDE Terminal but when i am trying to open that saved file so unable to open file (already shared a pic of my word error above)

3- if i don't use anything like above 1 & 2, so my code working fine & also able to open that generated file

**Comment by scanny** [comment]
Hmm, okay, that's weird.

Add this code in its place and post what output you get:

```python
print(table.rows[0]._tr.xml)
print("height_rule == %s" % table.rows[0].height_rule)
table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY # pylint: disable=no-member
print(table.rows[0]._tr.xml)
print("height_rule == %s" % table.rows[0].height_rule)
```

**Comment by Muhammad-Subhan-Khan** [comment]
$ C:/Python/python.exe f:/Python_Folder/invoice2.py
Enter The Date Which You Wanna Check: 1
<w:tr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word"
xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape">
  <w:tc>
    <w:tcPr>
      <w:tcW w:type="dxa" w:w="4320"/>
    </w:tcPr>
    <w:p/>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:type="dxa" w:w="4320"/>
    </w:tcPr>
    <w:p/>
  </w:tc>
</w:tr>

height_rule == None
<w:tr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word"
xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape">
  <w:trPr>
    <w:trHeight w:hRule="exact"/>
  </w:trPr>
  <w:tc>
    <w:tcPr>
      <w:tcW w:type="dxa" w:w="4320"/>
    </w:tcPr>
    <w:p/>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:type="dxa" w:w="4320"/>
    </w:tcPr>
    <w:p/>
  </w:tc>
</w:tr>

height_rule == EXACTLY (2)

**Comment by Muhammad-Subhan-Khan** [comment]
why all the link this output not working?

**Comment by scanny** [comment]
Hmm, the XML being produced is correct.

So you're setting the height-rule, but I don't see you actually setting the height. Try that and see if it fixes it. It would make sense that it needs to have both.

**Comment by Muhammad-Subhan-Khan** [comment]
still getting error, but now i got an alternate solution instead of using height-rule 
i have to use \n to increase height of rows my project almost done

BTW thanks this library is very helpful
