### ISSUE TITLE
How to access cell within table that is a table?

### ISSUE THREAD

**Issue by paulx509** [python-openxml/python-docx#655]
I have a table, in row 2, cell 1 there is another table. 
eg; row 2 cell 1 is itself a table

I am struggling to access the data within that table. If I do a simple iteration I can't get at it.
Thanks
```
a = tables[3]
for row in a.rows:
    for cell in row.cells:
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                print run.text
```

**Comment by scanny** [comment]
A cell is a block-item container, like the document itself is, and the cell object has a `.tables` property that provides access to any tables it contains. So in your case, you'd have something like:

table_within_cell = tables[3].cell(1, 0).tables[0]

**Comment by paulx509** [comment]
Perfect! Ver clear explanation, and sorry for being stupid.
