### ISSUE TITLE
Issue while adding new header to the existing document, if convert doc to docx using LibrOffice

### ISSUE THREAD

**Issue by swagat123** [python-openxml/python-docx#656]
Hi 

Adding new header worked fine for docx . We recently got "doc" file and i used the LibreOffice to convert doc to docx. I tried to add a header in this document , it throws error message 
document = Document("myfile.docx")
 document.add_heading('Heading, level 2', level=2)
  document.save("myfile.docx")
 KeyError: "no style with name 'Heading 2'"

Is this library not supporting to add the heading if  the doc is converted using LibrOffcie?

I appreciate your suggetsions.

**Comment by scanny** [comment]
Make sure you understand this page in the documentation and the page that follows it:  
https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html

The "doc" file doesn't have a "Heading 2" style and you need to add that if you want to use it.
