### ISSUE TITLE
There is any way to insert SVG picture into word document ?

### ISSUE THREAD

**Issue by Mkamal88** [python-openxml/python-docx#659]
I'm trying to insert svg into word document but I got this error:
docx.image.exceptions.UnrecognizedImageError

it seems the function add_picture doesn't support svg format, but it can be done using word UI

**Comment by madphysicist** [comment]
Seems like duplicate of #651.

**Comment by scanny** [comment]
I agree. Closing as duplicate of #651. Thanks @madphysicist :)

**Comment by goomesthiago** [comment]
Is there any update on this? Does python-docx already supports adding svg images into a word document?
