### ISSUE TITLE
How to install for Python3

### ISSUE THREAD

**Issue by micksulley** [python-openxml/python-docx#666]
This seems a basic question, but I cannot find the answer.
I have installed with 
`sudo pip install python-docx`
If I run
`python doctest.py`
it runs python 2.7.15 and works fine
If I run
`python3 doctest.py`
it runs python 3.6.7 and fails with 
ModuleNotFoundError: No module named 'docx'
I have also run
`sudo pip install --pre python-docx`
`sudo pip install -U setuptools
`
It looks like I have python-docx installed for 2.7 but not for 3.  How do I do it?
Thanks
Mick

**Comment by nmstoker** [comment]
Whilst I can guess some details I'm not entirely sure of your environment, but I suspect that if you try pip3 it might work.

Also, unless you have a particular reason to, generally you shouldn't use sudo with pip (or pip3). Some background on that here: https://dev.to/elabftw/stop-using-sudo-pip-install-52mn

**Comment by scanny** [comment]
Sounds right to me @nmstoker. @micksulley try `pip3 install python-docx`.

**Comment by micksulley** [comment]
I just tried that
`mick@Mint19Desk ~ $ pip3 install python-docx

Command 'pip3' not found, but can be installed with:

sudo apt install python3-pip

`

so I then ran
`mick@Mint19Desk ~ $ sudo apt install python3-pip
[sudo] password for mick:         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (9.0.1-2.3~ubuntu1).
0 to upgrade, 0 to newly install, 0 to remove and 6 not to upgrade.
mick@Mint19Desk ~ $ `
try again -
`mick@Mint19Desk ~ $ pip3 install python-docx

Command 'pip3' not found, but can be installed with:

sudo apt install python3-pip

mick@Mint19Desk ~ $ 

`
so what do I do now?

**Comment by nmstoker** [comment]
As this isn't related to this project, instead being a problem with your setup, it sounds like it's best to follow up with the support forum for your distribution (Mint):
https://forums.linuxmint.com

Best of luck with it :slightly_smiling_face:

**Comment by micksulley** [comment]
Thanks for your help.
I think I have now solved it.  I removed pip3, reinstalled it, then installed python-docx again and it all seems fine now.
Don't understand why, but it works :)

**Comment by SIMAKK** [comment]
Here's what i did for my windows install to successfully install with python 3

python -m pip install -U pip
python -m pip install -U setuptools

then proceed
