### ISSUE TITLE
document.paragraphs does not select the whole document in a mailmerged document

### ISSUE THREAD

**Issue by JamesFinlayson** [python-openxml/python-docx#669]
In a multi-page MailMerged document, where each page is a separate instance of the MailMerged data, document.paragraphs only contains paragraphs on the first page. iter_block_items is also only able to see page 1. 

I believe this may be occurring as it has multiple body elements, whilst a typical word document would only have one.

For clarity, this is not the MailMerge template, but its output.

**Comment by scanny** [comment]
Hmm, interesting. Can you provide an example document with a account of how it is produced?

**Comment by JamesFinlayson** [comment]
I tried replicating the issue with a mailmerge through Word's frontend and that document does _not_ have multiple body elements, as such, it looks like the creation of multiple body elements is an issue with [docx-mailmerge](https://github.com/Bouke/docx-mailmerge), as it shouldn't be creating the multiple body tags in the first place. Obviously I wouldn't expect python-docx to gracefully deal with an issue created upstream like this so I'll close this off and raise it on the docx-mailmerge repository. Thanks for your help :).

**Comment by scanny** [comment]
No problem James, glad you got it tracked down :)
