### ISSUE TITLE
Error when initializing Document()

### ISSUE THREAD

**Issue by Freakwill** [python-openxml/python-docx#671]
Got error when running `doc = Document(fo)`, the file really exists.

Following is the code
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import docx
with open('6.doc', 'rb') as fo:
    s = docx.Document(fo)

```

PS: I have uninstalled docx and installed python-docx

> Traceback (most recent call last):
>   File "/Users/william/script.py", line 6, in <module>
>     s = docx.Document(fo)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docx/api.py", line 25, in Document
>     document_part = Package.open(docx).main_document_part
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docx/opc/package.py", line 128, in open
>     pkg_reader = PackageReader.from_file(pkg_file)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docx/opc/pkgreader.py", line 32, in from_file
>     phys_reader = PhysPkgReader(pkg_file)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docx/opc/phys_pkg.py", line 101, in __init__
>     self._zipf = ZipFile(pkg_file, 'r')
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1222, in __init__
>     self._RealGetContents()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
>     raise BadZipFile("File is not a zip file")
> zipfile.BadZipFile: File is not a zip file

**Comment by scanny** [comment]
`python-docx` does not read pre-Word 2007 documents (typically having `.doc` extension). It only reads the XML-based format, typically with `.docx` filename extension.
