### ISSUE TITLE
different number of columns in different rows

### ISSUE THREAD

**Issue by b0207191** [python-openxml/python-docx#675]
suppose there is a table,  row 1 has 4 columns,  row 2 has 1 columns
why the code always report same column numbers?

    for i in range(0,len_row):
        len_col = len(table.row_cells(i))
        print('row ',i,' has column:',len_col)

（0，4）
（1，4）

I think it should be
(0,4)
(1,1)

**Comment by scanny** [comment]
Cells reported are _grid_ cells. If only _apparent_ cells were reported, information would be lost. Two grid cells being "merged" does not change the fact there are two grid-cells there.

Dealing with the presence of merged cells is tricky either way and the results are the same when there are no merged cells. So this is how we did it and I still think it was the best choice.
