### ISSUE TITLE
How to save the document with read write access? 

### ISSUE THREAD

**Issue by pgup2501** [python-openxml/python-docx#679]
I am using the Document api to create docs and save documents at a folder location on server. Since code is running with root access, The files are also written with rw-------. How can I give access rights while saving to path. The docs cannot be access by upstream system due to access issues.

**Comment by scanny** [comment]
One possible approach is to write to an `io.BytesIO` object and then use file-system operations to write the actual file and manipulate its permissions. There are no permissions settings built into Document.save().

So something along the lines of this with changes to accomplish the permissions you need:

```python
from io import BytesIO

document = Document()
in_memory_file = BytesIO()
document.save(in_memory_file)
with open(filepath, "w") as f:
    f.write(in_memory_file.getvalue())
```
