### ISSUE TITLE
feature: Paragraph.insert_paragraph_before()

### ISSUE THREAD

**Issue by scanny** [python-openxml/python-docx#68]
Add API method `Paragraph.insert_paragraph_before(text=None, style=None).

New paragraph is inserted directly above the 'cursor' paragraph.

``` python
>>> cursor_paragraph = document.paragraphs[2]
>>> cursor_paragraph.text
'foobar'
>>> new_paragraph = cursor_paragraph.insert_paragraph_above('barfoo')
>>> document.paragraphs[2].text
'barfoo'
>>> document.paragraphs[3].text
'foobar'
```

**Comment by auraking** [comment]
Python-docx is useful. But do you know to how add a picture at a certain page? Now adding a picture can only be done in the end of the document. Thanks
