### ISSUE TITLE
Not all text get converted after link - 

### ISSUE THREAD

**Issue by rakoivun** [python-openxml/python-docx#683]
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
python-docx 0.8.10

"I am ok" - text gets converted
"Not me" - does not get converted (in the same file)

If you store following .rtf file 
```
{\rtf1\ansi\deff3\adeflang1025
{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset0 Liberation Serif{\*\falt Times New Roman};}
}{\*\generator LibreOffice/5.4.5.1$Windows_x86 LibreOffice_project/79c9829dd5d8054ec39a82dc51cd9eff340dbee8}{\info{\creatim\yr2019\mo6\dy6\hr10\min1}{\revtim\yr2019\mo6\dy6\hr10\min1}{\printim\yr0\mo0\dy0\hr0\min0}}{\*\userprops}\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720\deftab720
\viewscale150
{\*\pgdsctbl
{\pgdsc0\pgdscuse451\pgwsxn12240\pghsxn15840\marglsxn2160\margrsxn1440\margtsxn1350\margbsxn1620\pgdscnxt0 Default Style;}}
\formshade{\*\pgdscno0}\paperh15840\paperw12240\margl2160\margr1440\margt1350\margb1620\sectd\sbknone\sectunlocked1\pgndec\pgwsxn12240\pghsxn15840\marglsxn2160\margrsxn1440\margtsxn1350\margbsxn1620\ftnbj\ftnstart1\ftnrstcont\ftnnar\aenddoc\aftnrstcont\aftnstart1\aftnnrlc\htmautsp
{\*\ftnsep\chftnsep}\pgndec\pard\plain \s331\ql\widctlpar\tqc\tx4320\tqr\tx8640\faauto\li0\ri0\lin0\rin0\fi0\ltrpar\cf17\kerning1\dbch\af20\langfe1033\dbch\af23\afs20\alang1025\loch\f5\fs20\lang1033\ql\hyphpar0\li0\ri0\lin0\rin0\fi0\sb60\sa60\ltrpar{\langfe1033\dbch\af23\afs20\alang1025\rtlch \ltrch\loch\fs20\lang1033\loch\f0\hich\af0
I am ok}{{\field{\*\fldinst HYPERLINK "javascript:link("1","4311.45013.50432.29517","","","DOC2036568")" }{\fldrslt {\cs33\cf2\ul\ulc0\rtlch \ltrch\loch
\line }{\cs33\cf2\ul\ulc0\langfe1033\dbch\af23\afs20\alang1025\rtlch \ltrch\loch\fs20\lang1033\loch\f0\hich\af0
Not}{}}}\langfe1033\dbch\af23\afs20\alang1025\rtlch \ltrch\loch\fs20\lang1033\loch\f0\hich\af0
 me}
\par }
```

and open in word (Microsoft Office 365 ProPlus, VErsion 1808 Build 10730.20344))-> save back in "bug.docx" and try to read it with :

```
import docx
pdf_file_object = open("bug.docx", 'rb')
other_doc = docx.Document("bug.docx")
for paragraph in other_doc.paragraphs:
    print(paragraph.text.encode('utf8'))

```
you will see "I am ok" printed but not "Not me".
I would expect also text "Not me" to be printed out.

**Comment by scanny** [comment]
What is the XML Word produces for that? You can find easily with:

```python
print(other_doc._element.xml)
```

**Comment by rakoivun** [comment]
Sorry took a while. Here is the output of:
Script:
`
import docx
pdf_file_object = open("bug.docx", 'rb')
other_doc = docx.Document("bug.docx")
for paragraph in other_doc.paragraphs:
    print(other_doc._element.xml)

`


Output:
`
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns:cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns:cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns:cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns:cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns:cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns:cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns:cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns:cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 w16se w16cid wp14">
  <w:body>
    <w:p w14:paraId="5B654C67" w14:textId="003BE074" w:rsidR="003B5751" w:rsidRPr="00FA4453" w:rsidRDefault="00B5539C" w:rsidP="003B5751">
      <w:pPr>
        <w:pStyle w:val="Footer"/>
        <w:tabs>
          <w:tab w:val="clear" w:pos="4320"/>
          <w:tab w:val="clear" w:pos="8640"/>
        </w:tabs>
        <w:suppressAutoHyphens/>
        <w:spacing w:before="60" w:after="60"/>
        <w:rPr>
          <w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>
        </w:rPr>
        <w:t>I am ok</w:t>
      </w:r>
      <w:hyperlink r:id="rId8" w:history="1">
        <w:r w:rsidR="003B5751" w:rsidRPr="00FA4453">
          <w:rPr>
            <w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>
          </w:rPr>
          <w:br/>
        </w:r>
        <w:r w:rsidR="002B76A7">
          <w:rPr>
            <w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>
          </w:rPr>
          <w:t>Not</w:t>
        </w:r>
      </w:hyperlink>
      <w:r w:rsidR="002B76A7">
        <w:rPr>
          <w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>
        </w:rPr>
        <w:t xml:space="preserve"> me</w:t>
      </w:r>
      <w:bookmarkStart w:id="0" w:name="_GoBack"/>
      <w:bookmarkEnd w:id="0"/>
    </w:p>
    <w:sectPr w:rsidR="003B5751" w:rsidRPr="00FA4453" w:rsidSect="006C0949">
      <w:pgSz w:w="12240" w:h="15840" w:code="1"/>
      <w:pgMar w:top="1350" w:right="1440" w:bottom="1620" w:left="2160" w:header="720" w:footer="720" w:gutter="0"/>
      <w:cols w:space="720"/>
      <w:docGrid w:linePitch="272"/>
    </w:sectPr>
  </w:body>
</w:document>`

**Comment by scanny** [comment]
okay, so I'm expecting what you're seeing from this test document is "I am ok me", is that right?

The problem is that `python-docx` cannot "find" the  "\nNot" run (`<w:r>` element) that is nested inside the `<w:hyperlink>` element.

The reason it can't is that sorting out which "wrapped" child runs are visible and which aren't is a fairly complex problem.

You might be able to get by with something like this in this particular case:

```python
from docx.text.run import Run

def iter_all_paragraph_runs(paragraph):
    rs = paragraph._p.xpath(".//w:r")
    for r in rs:
        yield Run(r, paragraph)
```

The problem comes in when you have, for example, unaccepted revision-marks and some of these nested runs actually represent deleted text.

**Comment by scanny** [comment]
`Paragraph.text` will include the text of hyperlinks in the forthcoming `v1.0` due out in a week or so.
