### ISSUE TITLE
how to make the first line by 2 ch?

### ISSUE THREAD

**Issue by paopjian** [python-openxml/python-docx#685]
paragraph_format.first_line_indent can only set by direct numbers, in word for Chinese,  the paragraph indentation special can set First line by 2 ch. I don't know how to make it.
I find CharacterUnitFirstLineIndent in VBA,but not find in python-docx
I find that w:firstLineChars can make "by" show the ch

![image](https://user-images.githubusercontent.com/20377352/59559791-f9354980-903b-11e9-9fb2-61a96a22b932.png)
![image](https://user-images.githubusercontent.com/20377352/59559794-05210b80-903c-11e9-89be-dfefc9e8acbc.png)

**Comment by gc13141112** [comment]
The configuration  "paragraph_format.first_line_chars_indent = 2 "  is not working. How to set the scripts?
