### ISSUE TITLE
WD_TABLE_ALIGNMENT has not CENTER member

### ISSUE THREAD

**Issue by NitinSharma87** [python-openxml/python-docx#690]
Whenever i am setting the table cell alignment to center , i am writing

table.alignment = WD_TABLE_ALIGNMENT.CENTER 
and it is throwing me the above title error

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the "python-docx" tag. Post the minimum code required to reproduce the error and the full stack-trace produced.
