### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by brpl20** [python-openxml/python-docx#708]
https://python-docx.readthedocs.io/en/latest/api/enum/WdLineSpacing.html

shows usage:
`paragraph.line_spacing_rule = WD_LINE_SPACING.EXACTLY`

but you have to especify paragraph_format before the .line_spacing: 
`paragraph.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY`

**Comment by scanny** [comment]
Good catch @pellibr, thanks! :)

I'll get that into the next release.

**Comment by scanny** [comment]
Fixed in release v0.8.11 on May 15, 2021.
