### ISSUE TITLE
Issue while reading the footer text 

### ISSUE THREAD

**Issue by meghabhamare** [python-openxml/python-docx#711]
Hello All, 

I am facing an issue while fetching the text from the footer paragraphs. This worked very well for me with header text and I am also able to translate the text and replace in header and footer. 
I have shown my code below.

AIHQ.docx is my input file and AIHQ_HF.docx is my output file. I see the footer text in the output file but I am unable to fetch it for translation.

Please let me know if there is any other way to achieve this.

[AIHQ_HF.docx](https://github.com/python-openxml/python-docx/files/3523678/AIHQ_HF.docx)

[AIHQ.docx](https://github.com/python-openxml/python-docx/files/3523679/AIHQ.docx)

```python
from docx import Document

document = Document("H:\\AIHQ.docx")
section = document.sections[0]
print((section.header))
print((section.footer))

print("testing header:",section.header.paragraphs[0].text)
print("header is_linked_to_previous :",section.header.is_linked_to_previous )
print("testing footer:",section.footer.paragraphs[0].text)
print("footer style :",section.footer.paragraphs[0].style)
print("footer is_linked_to_previous :",section.footer.is_linked_to_previous )
for head in section.header.paragraphs:
    print(head.text)
for foot in section.footer.paragraphs:
    print(foot.text)

document.save("H:\\AIHQ_HF.docx")
```

**Comment by scanny** [comment]
What output do you get? I think this is probably due to the "TITLE DOCUMENT" picture the heading starts with. Footer should come through fine though.
