### ISSUE TITLE
How do I add an image that is stored as binary in a BLOB column?

### ISSUE THREAD

**Issue by ArneAnka** [python-openxml/python-docx#712]
Hi!

Trying to add a picture to a document that is stored as binary straight into the DB. Bot PNG and GIF files. How do I approach this problem?

```python
document.add_picture(bin(item['data']))
```

`item['data']` is the column that has the binary for the image.

**Comment by scanny** [comment]
Wrap the image bytes in a file-like object:

```python
import io

image_stream = io.BytesIO(bin(item["data"]))
document.add_picture(image_stream)
```

**Comment by ArneAnka** [comment]
Thanks!

That gives me following error:
```python
Traceback (most recent call last):
  File "doc.py", line 30, in <module>
    image_stream = io.BytesIO(bin(item["data"]))
TypeError: 'NoneType' object cannot be interpreted as an integer
```

Tried to remove that bin part so the code looks like:
```python
document.add_picture(io.BytesIO(item['data']))
```

That gives me this error message:
```
....
....
  File "/usr/local/lib/python3.7/site-packages/docx/image/image.py", line 199, in _ImageHeaderFactory
    raise UnrecognizedImageError
docx.image.exceptions.UnrecognizedImageError
```

**Comment by scanny** [comment]
I have no way of knowing what `item["data"]` is, but it appears it is not the bytes of a common image type. The `bin()` wrapper is almost certainly not appropriate since it returns a string representation. Maybe you can try saving `item["data"]` to a file and see if it displays an image in your OS.

**Comment by ArneAnka** [comment]
`item["data"]` is the image binary. It´s a BLOB type. And I saved that binary like:

```sql
INSERT INTO table (data) VALUES LOAD_FILE("image.gif/png")
```

I have had that previous error (`docx.image.exceptions.UnrecognizedImageError`) before, I hade to convert the image with imagemagic `$ convert test.png test.png`, no idea why but it worked.

**Comment by scanny** [comment]
Probably the original doesn't store a conventional header. ImageMagick would repair that in the course of the transformation. Glad you got it working :)

**Comment by Jalkhov** [comment]
So no way for fix this via code?

**Comment by ArneAnka** [comment]
> So no way for fix this via code?

I will see if I can find the old project code. I know that I somehow got it to work.

**Comment by rickbps** [comment]
> Wrap the image bytes in a file-like object:
> 
> ```python
> import io
> 
> image_stream = io.BytesIO(bin(item["data"]))
> document.add_picture(image_stream)
> ```

I've been searching for this solution for weeks. I needed to insert a SharePoint image into a docx table and it ends up being 3 lines of code.  Thanks so much.
