### ISSUE TITLE
Delete hyperlinks from word document

### ISSUE THREAD

**Issue by dfann-cmi** [python-openxml/python-docx#720]
I am wanting to delete a hyperlink from docx. 
The xml looks similar to:

```xml
<w:p w:rsidP="00893654" w:rsidRDefault="00A04494" w:rsidRPr="00893654" w:rsidR="002B1D7E">
  <w:r w:rsidRPr="00893654">
    <w:t xml:space="preserve">Here is a text section. Hyperlink here: </w:t>
  </w:r>
  <w:hyperlink r:id="rId12" w:history="1" w:tgtFrame="_blank">
    <w:r w:rsidRPr="00893654">
       <w:t xml:space="preserve">This is the Hyperlink.  </w:t>
     </w:r> 
  </w:hyperlink>
</w:p>
```

I see it in the paragraph._element.xml, but it isn't editable.  I've been able to add xml tags in runs using the docx.oxml library but I haven't seen a way to edit existing xml tags.  Worst case would be to unzip the word file, and edit it via lxml and then rezip it.  But I would rather have a more elegant solution.  Ideas??

**Comment by dfann-cmi** [comment]
Thanks.  This did what I needed.

**Comment by scanny** [comment]
@dfann-cmi did you try leaving the relationship? I'm just curious as to what happens then.

**Comment by dfann-cmi** [comment]
It worked either way.  I'm planning on removing the relation just to keep it cleaner.  I'll be deleting a good number of hyperlinks, so no reason to leave them in.

**Comment by scanny** [comment]
k, thanks, good to know :)

**Comment by kinga-marszalkowska** [comment]
Hi! I've had a simillar use case and the code worked just fine. Out of pure curiosity I printed the hyperlink and label to the console and got something like this: 
hyperlink: <Element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}hyperlink at 0x211347f3947>
label: <CT_R '<w:r>' at 0x21135221d17>
Now I'm wondering what do the numbers mean, is this some kind of position of the hyperlink?

**Comment by yadneshSalvi** [comment]
> I'd say the job is this:
> 
> * Promote the enclosed `w:r` element to a _peer_ of `w:hyperlink`
> * Remove the relationship `"rId12"` from the document part (or other story part like header).
> * Remove the `w:hyperlink` element.
> 
> You probably need to start by getting references to the various elements, probably starting with the `w:p` container. This is simple enough once you've identified the paragraph:
> 
> ```python
> p = paragraph._p
> ```
> 
> The `w:hyperlink` is a child, so something like:
> 
> ```python
> hyperlink = p.xpath("./w:hyperlink")[0]
> ```
> 
> If you don't care about the enclosed run (the hyperlink "label") you can delete it with the hyperlink element:
> 
> ```python
> p.remove(hyperlink)
> ```
> 
> If you want to preserve it, you'll need to promote it (like move it out of being enclosed by hyperlink):
> 
> ```python
> label_r = p.xpath("./w:hyperlink/w:r")[0]
> hyperlink.add_previous(label_r)
> p.remove(hyperlink)
> ```
> 
> The last bit is the relationship, which might be okay to leave dangling, worth a try, or maybe you have to remove it:
> 
> ```python
> from docx.oxml.ns import qn  # ---for "qualified name", aka. Clark-notation tagname---
> hyperlink_rel_id = hyperlink.get(qn("r:id"))
> document_part = document.part
> docuemnt_part.drop_rel(hyperlink_rel_id)
> ```
> 
> Of course all this uses internals so comes with some risk of brittle breakage with new releases, but these parts have been stable for some time so probably work fine indefinitely.

This worked well, just had to use 'addprevious' in place of 'add_previous' wrote in this comment because I spend an hour finding out why it was failing.
