### ISSUE TITLE
Extract Multiple Tables in a word file to an Excel File using Python

### ISSUE THREAD

**Issue by Navodya1215** [python-openxml/python-docx#725]
Hi there, I have a Microsoft Word file which contains multiple tables. Word file has 8 pages. In each page there's a table. I want to extract the tables in that word file in to a single excel file. As i'm new to python, can anyone help me with it. 

Thanks in advance.

**Comment by jfthuong** [comment]
You need to loop for each table and write in Excel via `openpyxl` or `xlsxwriter`. The difference between the two is that `xlsxwriter` is better if you need to create an Excel from scratch, and `openpyxl` is the only option if you need to update an existing Excel file.

Here is a code to extract content from the tables in Word:
```python


from docx import Document
path = "toto.docx"

doc = Document(path)
for table in doc.tables:
    for row in table.rows:
        row_text = [c.text for c in row.cells]
        # TODO: print row in Excel with xlsxwriter or openpyxl

        # For xlsxwriter: use worksheet.write_row()
        # See https://xlsxwriter.readthedocs.io/worksheet.html for details

        # For openpyxl: see doc in https://openpyxl.readthedocs.io/en/stable/tutorial.htm
```

**Comment by Reventh** [comment]
Hi @jfthuong

I am trying to convert my word doc to xcel by implementing the above code provided

I have a small question.

What if my word document had hyperlinks, will it be there in excel doc as well? Please confirm

Thank you in advance

**Comment by jfthuong** [comment]
Hi @Reventh ,

Unfortunately, it does not support hyperlinks, because it is a bit tricky

There is a related question in StackOverflow, but not much answers:
https://stackoverflow.com/questions/53269311/extracting-url-from-inside-docx-tables
