### ISSUE TITLE
Index error when reading table

### ISSUE THREAD

**Issue by B0und** [python-openxml/python-docx#732]
I need to read data from the table in docx, but the loop raises IndexError. I tried to use iter_unique_cells method that i found, but it didnt solve the problem.Any help would be greatly appreciated !
[another_broken_table.docx](https://github.com/python-openxml/python-docx/files/3745747/another_broken_table.docx)

```
def iter_unique_cells(row):
    """Generate cells in *row* skipping empty grid cells."""
    prior_tc = None
    for cell in row.cells:
        this_tc = cell._tc
        if this_tc is prior_tc:
            continue
        prior_tc = this_tc
        yield cell
```
```
document = Document('another_broken_table.docx')
tables = document.tables
for table in tables:
      for row in table.rows:
            for cell in iter_unique_cells(row):
                pass
```

```
Traceback (most recent call last):
  File "d:/test.py", line 94, in <module>
    xml_string = loop_tables(tables)
  File "d:/test.py", line 52, in loop_tables
    for cell in iter_unique_cells(row):
  File "d:/test.py", line 12, in iter_unique_cells
    for cell in row.cells:
  File "D:\Python\Python36-32\lib\site-packages\docx\table.py", line 401, in cells
    return tuple(self.table.row_cells(self._index))
  File "D:\Python\Python36-32\lib\site-packages\docx\table.py", line 106, in row_cells
    return self._cells[start:end]
  File "D:\Python\Python36-32\lib\site-packages\docx\table.py", line 173, in _cells
    cells.append(cells[-col_count])
IndexError: list index out of range
```

**Comment by scanny** [comment]
What does `print(row._tr.xml)` output for the offending row?

You might also try:

```python
from docx.table import _Cell
row_cells = [_Cell(tc, table) for tc in row._tr.tc_lst]
```

**Comment by B0und** [comment]
Your solution worked ! Thank you very much.
Here is the output for
```
for table in tables:
      for row in table.rows:
            print(row._tr.xml)
``````

<w:tr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns:cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns:cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns:cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns:cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns:cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns:cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns:cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns:cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" w:rsidR="00690D7E" w:rsidRPr="001E70BF" w:rsidTr="00AE134D">
  <w:trPr>
    <w:gridAfter w:val="8"/>
    <w:wAfter w:w="2093" w:type="dxa"/>
    <w:cantSplit/>
    <w:trHeight w:val="259"/>
  </w:trPr>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="1916" w:type="dxa"/>
      <w:gridSpan w:val="6"/>
      <w:vMerge w:val="restart"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="00FD5BA7" w:rsidRDefault="00284124" w:rsidP="009C1219">
      <w:pPr>
        <w:ind w:right="57"/>
        <w:rPr>
          <w:sz w:val="24"/>
          <w:szCs w:val="24"/>
          <w:lang w:val="en-US"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="24"/>
          <w:szCs w:val="24"/>
          <w:lang w:val="en-US"/>
        </w:rPr>
        <w:t>1</w:t>
      </w:r>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="00FD5BA7" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
          <w:lang w:val="en-US"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
  <w:tc>
    <w:tcPr>
      <w:tcW w:w="273" w:type="dxa"/>
      <w:gridSpan w:val="2"/>
      <w:tcBorders>
        <w:top w:val="nil"/>
        <w:left w:val="nil"/>
        <w:right w:val="nil"/>
      </w:tcBorders>
      <w:vAlign w:val="center"/>
    </w:tcPr>
    <w:p w:rsidR="00690D7E" w:rsidRPr="009C1219" w:rsidRDefault="00690D7E" w:rsidP="008A2D0D">
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:rFonts w:ascii="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/>
          <w:sz w:val="10"/>
          <w:szCs w:val="10"/>
        </w:rPr>
      </w:pPr>
    </w:p>
  </w:tc>
</w:tr>

Traceback (most recent call last):
  File "d:/test.py", line 96, in <module>
    xml_string = loop_tables(tables)
  File "d:/test.py", line 55, in loop_tables
    for cell in row.cells:
  File "D:\Python\Python36-32\lib\site-packages\docx\table.py", line 401, in cells
    return tuple(self.table.row_cells(self._index))
  File "D:\Python\Python36-32\lib\site-packages\docx\table.py", line 106, in row_cells
    return self._cells[start:end]
  File "D:\Python\Python36-32\lib\site-packages\docx\table.py", line 173, in _cells
    cells.append(cells[-col_count])
IndexError: list index out of range
```

**Comment by kalaersun** [comment]
> What does `print(row._tr.xml)` output for the offending row?
> 
> You might also try:
> 
> ```python
> from docx.table import _Cell
> row_cells = [_Cell(tc, table) for tc in row._tr.tc_lst]
> ```

This must be the best way

**Comment by rphota** [comment]
> What does `print(row._tr.xml)` output for the offending row?
> 
> You might also try:
> 
> ```python
> from docx.table import _Cell
> row_cells = [_Cell(tc, table) for tc in row._tr.tc_lst]
> ```

Thanks. This helped me, as well.

**Comment by duongkstn** [comment]
Any updates ?
