### ISSUE TITLE
pip install gets old version

### ISSUE THREAD

**Issue by keithbriggs** [python-openxml/python-docx#739]
> pip3 install docx
...
Successfully installed docx-0.2.4

Why does this still exist on pypi?

**Comment by scanny** [comment]
The command you may be looking for is:

```bash
$ pip3 install python-docx
```

The original `docx` package has the same module name (`docx`, like `from docx import ...`) but a different package name (`docx` vs `python-docx`). There's not usually a lot of confusion there, but there is occasionally and you could ask that package's author to take it down if you wanted. I think it's fair to say that most people making this guess would mean `python-docx` and removing that package would prevent the occasional error.

This project took over the objectives of the original (with the blessing of the original author) but represents a complete rewrite and does not originate as a fork of that repository.

**Comment by keithbriggs** [comment]
Ok, thanks -

pip3 install python-docx

worked.   But there is potential for confusion because most pip packages do not have python- as part of the name.

Keith


________________________________
