### ISSUE TITLE
Remove or edit footer of document

### ISSUE THREAD

**Issue by SimplyPancake** [python-openxml/python-docx#741]
I am well aware that the 'header' represents both the header and footer of a Word document, however I am unable to even get the contents of a footer after two days of searching.

My primary goal is to remove the footer of a document completely.
How can I go about that?

If that's not possible, is there a way for me to edit the text in a document footer, because my code doesn't work.

With this code I can succesfully edit the headers of a document:
```python
def replaceh(document, find, replace):
    # HEADERS:
    section = document.sections[0]
    header = section.header

    for paragraph in header.paragraphs:
        ptext = paragraph.texts

        if find in ptext:
            newtext = ptext.replace(find, replace)
            paragraph.text = newtext
```

This doesn't work with footers however.

**Comment by scanny** [comment]
What code are you trying for footers?

I notice you only access the first section here (`document.sections[0]`) and there can be more, each potentially with its own distinct footer. Also, there is no `paragraph.texts`, only `paragraph.text`.

**Comment by SimplyPancake** [comment]
Thank you so much for replying!

I have realised that the footer contains a table which has text I want to replace. Even if the text is visually outside the table, it is still technically in the table.

I have the following code now to replace headers text:

```python
def replaceh(document, find, replace):
    # HEADERS:
    # section = document.sections[0]
    for section in document.sections:
        header = section.header

        for paragraph in header.paragraphs:
            ptext = paragraph.text

            if find in ptext:
                newtext = ptext.replace(find, replace)
                paragraph.text = newtext

        # tables in header:
        tables = section.tables
        for table in tables:
            for row in table.rows:
                for cell in row.cells:
                    for paragraph in cell.paragraphs:

                        ptext = paragraph.text

                        if find in ptext:
                            newtext = ptext.replace(find, replace)
                            paragraph.text = newtext
```

I have one more issue, which is that I can't get the tables of the footer via document.tables.
How can I get the tables of any header object? header.tables isn't working for me!

**Comment by scanny** [comment]
A footer is a header/footer object, but it is not found on section.header. If a footer contains a table, you should be able to find it on `section.footer.tables`. Note there can be three different footers for each section (although there is typically only one), the odd-page footer, the even-page footer, and the first-page footer. When there is only the odd-page footer it appears on all pages.

You can learn more about headers and footers on the documentation page here:  
https://python-docx.readthedocs.io/en/latest/user/hdrftr.html

And by studying the API documentation pages here:  
https://python-docx.readthedocs.io/en/latest/api/section.html#header-and-footer-objects

**Comment by SimplyPancake** [comment]
Thank you a lot! This helps me to progress in my code!
