### ISSUE TITLE
Copying a table between documents strip the embedded images

### ISSUE THREAD

**Issue by matosha** [python-openxml/python-docx#742]
I have two documents based on the same templates and styles. One document is constructed with variations depending on input and the other document keeps a list of the team with their images.

The teams are each a table object with their name and photo. When copying the table from one document to another, the images are lost. Everything else like text, style and bullets are copied without an issue. 

```
Table: Row2, Col1
######
#name#
######
#image#
######

document = Document('original.docx')
teams_doc = Document('team.docx')
paragraph = document.add_paragraph()
paragraph._p.addnext(teams_doc.tables[0]._tbl)

Copied table: Row2, Col1
######
#name#
######
#!Broken!#
######
```

**Comment by scanny** [comment]
It's a little more complicated than that. You'll need to understand how images are separate parts in the package and are related both by a relationship entry in the appropriate relationship part as well as a keyed reference to that relationship (like "rId"="3") in the referring XML.
