### ISSUE TITLE
how to set/change the Outline level of a paragraph <w:outlineLvl w:val="#"/>?

### ISSUE THREAD

**Issue by cali-hotplate** [python-openxml/python-docx#746]
Thanks for the project.  It's very appreciated.

I have an issue where despite me changing the styles, it does not change the outline level.  What I am trying to do is correct anything that matches the Normal Style to a Body (Outlinelvl = 9) however I have not figured out how I can modify this xml value.  Could anyone help?
```
<w:pPr>
    <w:pStyle w:val="TOC9"/>
    <w:outlineLvl w:val="3"/>
    <w:rPr>
      <w:rStyle w:val="Strong"/>
    </w:rPr>
  </w:pPr>
```

**Comment by scanny** [comment]
How far have you gotten? Post the code you're trying and in particular what `python-docx` object you're starting with and we'll see if we can help. Otherwise your question reduces to "how do I edit XML"? Which is a legitimate question if that's where you're at, but addressed very differently.

**Comment by cali-hotplate** [comment]
Absolutely, thanks for the response.  I have not gotten far, I was hoping if I may be missing some setter in the Paragraph object to change outlinelvl. 

I have the following code.  It's very simple it just looks for a paragraph that includes the word [Requirement] in the paragraph text and sets the style Normal which I was hoping would also change `outlineLvl w:val="3"` to `outlineLvl w:val="9"` (e.g. body text).  I've also tried other styles like Body_Text, TOC9 etc from the list of available styles however while the style changes, the outlinelvl does not change from `outlineLvl w:val="3"`.

```
print("\n\n*************************************")
print("Correcting Outline level for body text.")
print("*************************************\n")

for paragraph in document.paragraphs:
	ptext = paragraph.text
	p = paragraph._p	
	if ptext.find("[Requirement]") != -1: #[Requirement] found in text
		#print("\nFound [Requirement].")
		print(ptext)
		#pxml = p.xml
		print(p.xml)
		# set paragraphs with [Requirement] to Normal
		paragraph.style = document.styles['Normal'] 
		# *** have tried Normal, Body_Text, TOC9 etc. however the Outline level of this paragraph does not change from <w:outlineLvl w:val="3"/>
		print(paragraph.style.name) # show the style name of the paragraph
		print(paragraph.text) # show the text of the paragraph
		print(p.xml) # show the xml of the paragraph
```
I do not see it under parfmt so this may just be a new feature request ?:
```
from .text.parfmt import (
    CT_Ind, CT_Jc, CT_PPr, CT_Spacing, CT_TabStop, CT_TabStops
)
register_element_cls('w:ind',             CT_Ind)
register_element_cls('w:jc',              CT_Jc)
register_element_cls('w:keepLines',       CT_OnOff)
register_element_cls('w:keepNext',        CT_OnOff)
register_element_cls('w:pageBreakBefore', CT_OnOff)
register_element_cls('w:pPr',             CT_PPr)
register_element_cls('w:pStyle',          CT_String)
register_element_cls('w:spacing',         CT_Spacing)
register_element_cls('w:tab',             CT_TabStop)
register_element_cls('w:tabs',            CT_TabStops)
register_element_cls('w:widowControl',    CT_OnOff)
```

**Comment by scanny** [comment]
Alright, I think the code I'm looking for is this:

```python
document = Document("my_doc.docx")
paragraph = document.paragraphs[42]
print(paragraph._p.xml)
```

Which produces something like:

```xml
<w:p>
  <w:pPr>
    <w:pStyle w:val="TOC9"/>
    <w:outlineLvl w:val="3"/>
    <w:rPr>
      <w:rStyle w:val="Strong"/>
    </w:rPr>
  </w:pPr>
  ...
```

If that's the case, probably the easiest thing is just to drop the `w:outline` element altogether, since it is not needed; that sort of thing is typically provided by the style, but it looks like the author perhaps customized it here by applying it directly to the paragraph.

```python
outlineLvls = paragraph._p.xpath(".//w:outlineLvl")
for outlineLvl in outlineLvls:
    outlineLvl.getparent().remove(outlineLvl)
```

or more compactly:

```python
map(lambda o: o.getparent().remove(o), paragraph._p.xpath(".//w:outlineLvl"))
```

**Comment by cali-hotplate** [comment]
Awesome!  I very appreciate it.  Worked perfect.

**Comment by coder-yzx** [comment]
Thank you!!!
