### ISSUE TITLE
Can't get the content in revision mode in table of docx file

### ISSUE THREAD

**Issue by gagmeng** [python-openxml/python-docx#748]
![image](https://user-images.githubusercontent.com/13564117/69475445-24e90680-0e08-11ea-8927-a4340537402f.png)
As shown in above, I want to get the last non-empty row of data in the table.However, because the last line is in the revision state, the data cannot be obtained normally using the tool.

the python code  is as below:
```python
#coding:utf-8
import os
from docx import Document
  
def parse_docx(f):
  i = 0
  doc = Document(f)
  tables = doc.tables
  t = tables[i]
  for j in range(len(t.rows)):
      index = len(t.rows) - j - 1         
      version = t.cell(index,0).text
      datetime = t.cell(index,1).text
      modifyContent = t.cell(index,2).text
      author = t.cell(index,3).text
      if (len(version) != 0) and (len(datetime) != 0) and (len(modifyContent) != 0) and (len(author) != 0):            
          return f.decode(encoding='gbk') + '\n' + version + '   ' + datetime + '   ' + modifyContent + '   ' + author  + '\n'
          break
  
if __name__ == "__main__":
  PATH = os.path.dirname(os.path.abspath(__file__)) 
  doc_files = os.listdir(PATH)
  for doc in doc_files:
    if os.path.splitext(doc)[1] == '.docx':
      try:
        retstr = parse_docx(PATH+'\\'+doc)
        print retstr
      except Exception as e:
        print e
```

The output obtained after executing the script is “V0.0.3   2014-01-22   Modify 2   Test3”，that's not the data I expected to get.

**Comment by scanny** [comment]
Post the XML of the table and we'll have a look. The solution depends on the tagname of the enclosing element:

```python
print(table._tbl.xml)
```

**Comment by gagmeng** [comment]
Attach the test docx file as belows:
[https://mega.nz/#!3JwD1ABK!TwGOyqXMyFUEfRCTIggbysEnlEVprx-3Xz0TrGdNft8](url)

Thanks.

**Comment by gagmeng** [comment]
Any progress for it? Thanks

**Comment by gagmeng** [comment]
Attach the content of table._tbl.xml

`<w:tbl xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns:cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns:cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns:cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns:cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns:cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns:cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns:cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns:cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cex="http://schemas.microsoft.com/office/word/2018/wordml/cex" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16="http://schemas.microsoft.com/office/word/2018/wordml" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape">
  <w:tblPr>
    <w:tblW w:w="8528" w:type="dxa"/>
    <w:jc w:val="center"/>
    <w:tblBorders>
      <w:top w:val="single" w:sz="12" w:space="0" w:color="auto"/>
      <w:left w:val="single" w:sz="12" w:space="0" w:color="auto"/>
      <w:bottom w:val="single" w:sz="12" w:space="0" w:color="auto"/>
      <w:right w:val="single" w:sz="12" w:space="0" w:color="auto"/>
      <w:insideH w:val="single" w:sz="6" w:space="0" w:color="auto"/>
      <w:insideV w:val="single" w:sz="6" w:space="0" w:color="auto"/>
    </w:tblBorders>
    <w:tblLayout w:type="fixed"/>
    <w:tblLook w:val="0000" w:firstRow="0" w:lastRow="0" w:firstColumn="0" w:lastColumn="0" w:noHBand="0" w:noVBand="0"/>
  </w:tblPr>
  <w:tblGrid>
    <w:gridCol w:w="1027"/>
    <w:gridCol w:w="1985"/>
    <w:gridCol w:w="4284"/>
    <w:gridCol w:w="1232"/>
  </w:tblGrid>
  <w:tr w:rsidR="003F2873" w:rsidRPr="00D320C1" w14:paraId="1C1FA036" w14:textId="77777777" w:rsidTr="00981D03">
    <w:trPr>
      <w:trHeight w:val="624"/>
      <w:jc w:val="center"/>
    </w:trPr>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1027" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="24E47D2A" w14:textId="71C22230" w:rsidR="003F2873" w:rsidRPr="00D320C1" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:tabs>
            <w:tab w:val="center" w:pos="988"/>
          </w:tabs>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
          <w:t>v</w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
          <w:t>ersion</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1985" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="6CA28494" w14:textId="6B0CA801" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
          <w:t>d</w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
          <w:t>ate</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4284" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="31C5172E" w14:textId="6E84AA06" w:rsidR="003F2873" w:rsidRPr="00D320C1" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
        </w:pPr>
        <w:proofErr w:type="spellStart"/>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
          <w:t>m</w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
          <w:t>odifycontent</w:t>
        </w:r>
        <w:proofErr w:type="spellEnd"/>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1232" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="71170B76" w14:textId="2C85BB3A" w:rsidR="003F2873" w:rsidRPr="00D320C1" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
          <w:t>a</w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:sz w:val="28"/>
            <w:szCs w:val="28"/>
          </w:rPr>
          <w:t>uthor</w:t>
        </w:r>
      </w:p>
    </w:tc>
  </w:tr>
  <w:tr w:rsidR="003F2873" w:rsidRPr="00D320C1" w14:paraId="481CA8B7" w14:textId="77777777" w:rsidTr="00981D03">
    <w:trPr>
      <w:trHeight w:val="624"/>
      <w:jc w:val="center"/>
    </w:trPr>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1027" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="0451F24A" w14:textId="77777777" w:rsidR="003F2873" w:rsidRPr="00E03906" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>V0.0.1</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1985" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="56C8BCF9" w14:textId="77777777" w:rsidR="003F2873" w:rsidRPr="00E03906" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>2013-06-19</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4284" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="6E069038" w14:textId="57BFA271" w:rsidR="003F2873" w:rsidRPr="00E84038" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:r>
          <w:rPr>
            <w:rFonts w:hint="eastAsia"/>
            <w:noProof/>
          </w:rPr>
          <w:t>d</w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:noProof/>
          </w:rPr>
          <w:t>raft</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1232" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="0CD7A68A" w14:textId="6DC7BB17" w:rsidR="003F2873" w:rsidRPr="00E03906" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>t</w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>est1</w:t>
        </w:r>
      </w:p>
    </w:tc>
  </w:tr>
  <w:tr w:rsidR="003F2873" w:rsidRPr="00D320C1" w14:paraId="24290D09" w14:textId="77777777" w:rsidTr="00981D03">
    <w:trPr>
      <w:trHeight w:val="624"/>
      <w:jc w:val="center"/>
    </w:trPr>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1027" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="0E81513F" w14:textId="77777777" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>V0.0.2</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1985" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="12168C6C" w14:textId="77777777" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>2014-01-17</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4284" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="0615B6FF" w14:textId="226163BC" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:rPr>
            <w:noProof/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:noProof/>
          </w:rPr>
          <w:t>Modify1</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1232" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="0A1A0B1D" w14:textId="0D3BD8E0" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>Test2</w:t>
        </w:r>
      </w:p>
    </w:tc>
  </w:tr>
  <w:tr w:rsidR="003F2873" w:rsidRPr="00D320C1" w14:paraId="5D474920" w14:textId="77777777" w:rsidTr="00981D03">
    <w:trPr>
      <w:trHeight w:val="624"/>
      <w:jc w:val="center"/>
    </w:trPr>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1027" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="55E5E045" w14:textId="77777777" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>V0.0.3</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1985" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="6ED99446" w14:textId="77777777" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>2014-01-22</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4284" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="2C1A4023" w14:textId="4BFBB7FB" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:rPr>
            <w:noProof/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:noProof/>
          </w:rPr>
          <w:t>Modify 2</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1232" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="061B3830" w14:textId="12CDF147" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="00981D03">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
          <w:t>Test3</w:t>
        </w:r>
      </w:p>
    </w:tc>
  </w:tr>
  <w:tr w:rsidR="003F2873" w:rsidRPr="00D320C1" w14:paraId="05A63802" w14:textId="77777777" w:rsidTr="00981D03">
    <w:trPr>
      <w:trHeight w:val="624"/>
      <w:jc w:val="center"/>
      <w:ins w:id="0" w:author="gagmeng" w:date="2019-11-23T15:37:00Z"/>
    </w:trPr>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1027" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="3948EBC8" w14:textId="1327B972" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="003F2873">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:ins w:id="1" w:author="gagmeng" w:date="2019-11-23T15:37:00Z"/>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:ins w:id="2" w:author="gagmeng" w:date="2019-11-23T15:37:00Z">
          <w:r>
            <w:rPr>
              <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
              <w:bCs/>
              <w:szCs w:val="24"/>
            </w:rPr>
            <w:t>V</w:t>
          </w:r>
          <w:r>
            <w:rPr>
              <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
              <w:bCs/>
              <w:szCs w:val="24"/>
            </w:rPr>
            <w:t>0</w:t>
          </w:r>
        </w:ins>
        <w:ins w:id="3" w:author="gagmeng" w:date="2019-11-23T15:38:00Z">
          <w:r>
            <w:rPr>
              <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
              <w:bCs/>
              <w:szCs w:val="24"/>
            </w:rPr>
            <w:t>.0.4</w:t>
          </w:r>
        </w:ins>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1985" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="3D8A2488" w14:textId="41A841EC" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="003F2873">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:ins w:id="4" w:author="gagmeng" w:date="2019-11-23T15:37:00Z"/>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:ins w:id="5" w:author="gagmeng" w:date="2019-11-23T15:38:00Z">
          <w:r>
            <w:rPr>
              <w:rFonts w:ascii="宋体" w:hAnsi="宋体" w:hint="eastAsia"/>
              <w:bCs/>
              <w:szCs w:val="24"/>
            </w:rPr>
            <w:t>2</w:t>
          </w:r>
          <w:r>
            <w:rPr>
              <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
              <w:bCs/>
              <w:szCs w:val="24"/>
            </w:rPr>
            <w:t>019-11-23</w:t>
          </w:r>
        </w:ins>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4284" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="77A85D2E" w14:textId="1799018A" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="003F2873">
        <w:pPr>
          <w:rPr>
            <w:ins w:id="6" w:author="gagmeng" w:date="2019-11-23T15:37:00Z"/>
            <w:noProof/>
          </w:rPr>
        </w:pPr>
        <w:ins w:id="7" w:author="gagmeng" w:date="2019-11-23T15:38:00Z">
          <w:r>
            <w:rPr>
              <w:noProof/>
            </w:rPr>
            <w:t xml:space="preserve">Modify </w:t>
          </w:r>
          <w:r>
            <w:rPr>
              <w:noProof/>
            </w:rPr>
            <w:t>3</w:t>
          </w:r>
        </w:ins>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="1232" w:type="dxa"/>
        <w:vAlign w:val="center"/>
      </w:tcPr>
      <w:p w14:paraId="110B9D82" w14:textId="34EBA5A5" w:rsidR="003F2873" w:rsidRDefault="003F2873" w:rsidP="003F2873">
        <w:pPr>
          <w:jc w:val="center"/>
          <w:rPr>
            <w:ins w:id="8" w:author="gagmeng" w:date="2019-11-23T15:37:00Z"/>
            <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
            <w:bCs/>
            <w:szCs w:val="24"/>
          </w:rPr>
        </w:pPr>
        <w:ins w:id="9" w:author="gagmeng" w:date="2019-11-23T15:38:00Z">
          <w:r>
            <w:rPr>
              <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
              <w:bCs/>
              <w:szCs w:val="24"/>
            </w:rPr>
            <w:t>Test</w:t>
          </w:r>
          <w:r>
            <w:rPr>
              <w:rFonts w:ascii="宋体" w:hAnsi="宋体"/>
              <w:bCs/>
              <w:szCs w:val="24"/>
            </w:rPr>
            <w:t>4</w:t>
          </w:r>
        </w:ins>
      </w:p>
    </w:tc>
  </w:tr>
</w:tbl>`

**Comment by scanny** [comment]
Something like this should work:

```python
tbl = table._tbl
# ---move each run inside a `w:ins` element up to be a sibling of the `w:ins`---
for r in tbl.xpath("../w:ins/w:r"):
    r.addnext(r.getparent())
# ---then get rid of all the (now empty) `w:ins` elements.
for ins in tbl.xpath("../w:ins"):
    ins.getparent().remove(ins)
```

I expect there are more elegant ways to do this, but this should do the trick.

**Comment by gagmeng** [comment]
Report error "cannot add ancestor as sibling, please break cycle first"

**Comment by scanny** [comment]
k, changed it slightly. But you should work to understand what it's trying to achieve and how, not wait for others to provide you a recipe. Otherwise you will remain helpless. The details you need are in this neighborhood: https://lxml.de/api/lxml.etree._Element-class.html

**Comment by gagmeng** [comment]
The issus has resolved, close.
