### ISSUE TITLE
Why number of page breaks changes when read the same document two times

### ISSUE THREAD

**Issue by unreax** [python-openxml/python-docx#751]
I have python code that generates one .docx file, and I need to check where are soft page breaks and hard page breaks. I use this script:

```python
import docx

document= docx.Document('REPORT.docx')

for p in document.paragraphs:
    for run in p.runs:
        if 'lastRenderedPageBreak' in run._element.xml:
            print 'soft page break found at run:', run.text
        if 'w:br' in run._element.xml and 'type="page"' in run._element.xml:
            print 'hard page break found at run:', run.text
```

The problem is when I read the generated document immediately after it's created, the printed result from the code above is not correct(number of soft page breaks is lower than real soft page breaks in the document). But if I manually open the REPORT.docx, type in one single letter and after that delete it and save the document(Actually there is nothing changed in it), when executing the script again the number of soft page breaks now is correct. I also noticed that file size is getting bigger after this.

Can someone explain why is this happening? I want to check when insert image, is it on the same page or (if it's too large) is automatically moved to the next page when generating REPORT.docx file. So if there is another way to do that, please tell me.

**Comment by DKWoods** [comment]
> I have python code that generates one .docx file, and I need to check 
> where are soft page breaks and hard page breaks. I use this script:
> |import docx document= docx.Document('REPORT.docx') for p in 
> document.paragraphs: for run in p.runs: if 'lastRenderedPageBreak' in 
> run._element.xml: print 'soft page break found at run:', run.text if 
> 'w:br' in run._element.xml and 'type="page"' in run._element.xml: 
> print 'hard page break found at run:', run.text|
>
> The problem is when I read the generated document immediately when it 
> is created, the printed result from the code above is not 
> correct(number of soft page breaks is lower than real soft page breaks 
> in the document). But if I manualy open the REPORT.docx, type in one 
> single letter and after that delete it and save the document(Actually 
> there is nothing changed in it), when executing the script again the 
> number of soft page breaks now is correct.
>
> Can someone explain why is this happening?
>

I think it's because the page breaks don't actually get rendered until 
you load the file in Word, and they don't exist in the file for you to 
find until you've saved the text.  Page breaks are dependent upon many 
factors including your page size, which can be altered by the paper size 
you are using in your printer, so it's really hard to calculate them 
outside of a defined context.   Your code isn't going to find something 
in the XML that hasn't been created yet.

David

-- 
David Woods
Pronouns:  he, him, his

**Comment by unreax** [comment]
Thank you!

My problem is when REPORT.docx is generated on some pages there are images which are mooved to the next page because are too large to fit to the previous one. 
I want to check in real time whether the image, has been moved to the next page to reduce it's size until fit to the current page.

Is there some trick to do this?

**Comment by scanny** [comment]
As David says, you cannot accomplish what you want with `python-docx` alone. It is the Word rendering engine that is adding the `lastRenderedPageBreak` elements when you load (and thereby render) the document in Word.

Perhaps a VBA or COM32 solution would allow something like this.
