### ISSUE TITLE
Question: Is it possible to convert Word shapes/drawings to standard jpeg/png images?

### ISSUE THREAD

**Issue by TheKalpit** [python-openxml/python-docx#752]
I've been looking for a solution which can convert shapes/drawings in docx to standard image formats (jpeg/png). Ideally, I'd like it to have support for Python on Ubuntu, but at this point any solution would work.

An excerpt of w:r from docx xml of a sample shape: https://gist.github.com/TheKalpit/323f220f55d509ede1fda8b032229b17

What are my options?

**Comment by scanny** [comment]
There's no API support for that in `python-docx`. VBA might be a possible route.
