### ISSUE TITLE
Function - Wrap in front of text.

### ISSUE THREAD

**Issue by Gu7z** [python-openxml/python-docx#753]
I'm trying to make something like that. Is there a way to wrap image in front of text??
If exist sorry i didnt found it.

![Capturar](https://user-images.githubusercontent.com/48556195/69986824-869a2680-1514-11ea-91dd-9f021e83e16b.PNG)

**Comment by zflemingg1** [comment]
I'm having the same issue

**Comment by scanny** [comment]
There is currently no API support for floating images.
