### ISSUE TITLE
how to insert float text framebox?

### ISSUE THREAD

**Issue by retsyo** [python-openxml/python-docx#756]
*The short story: *
I need to insert images to make a document, the images take almost all the page area. At the same time I need to add page number information, but I don't know how. If there is only several pages, I can insert text framebox( sorry I don't know what is the real English name of it), then add field ` {page} of {sectionpages} ` in the text framebox; but there is dozens of pages

*The long story:*
You may ask “why not use PDF”. Actually, I made PDF by extracting some pages from some PDF files. Most of the PDF files made by me can be printed on the paper without problem. But I found some pages did not. 
At first, I think if I generate images from those PDF pages with problem, make PDF from them, then the produced PDF will be printed without problem. So I made a PDF from only 74 images, which is about 100MB. However when I try to print the PDF on my win7 64 bits, the printing task  runs a very lone time, uses up more than 1GB hard-disk space, but nothing is actually printed!
Then I insert all the images into DOCX file, which can be printed without problem at a very high speed.

thanks

```python
import glob
import docx

from docx import Document
from docx.shared import Cm

document = Document()

#changing the page margins
sections = document.sections
margin = 0
for section in sections:
    section.top_margin = Cm(margin)
    section.bottom_margin = Cm(margin)
    section.left_margin = Cm(margin)
    section.right_margin = Cm(margin)

lstImg = glob.glob('out/*.png')
lstImg.sort()

for img in lstImg:
    document.add_picture(img, width=Cm(21.0))

for page in document.pages:           # <---this is what I need
    textFrame = addTextFrame(position=somewhere, size=somesize, borderAttribute=some)
    textFrame.addField('page')
    textFrame.addText(' of ')
    textFrame.addField('sectionpages')

document.save('demo.docx')
```

**Comment by scanny** [comment]
There is no API support for this in `python-docx`.

**Comment by DarrenPadraigDV** [comment]
Hey @scanny, is this something that will ever be exposed? Would love this as a feature.
