### ISSUE TITLE
Remove form content control from docx

### ISSUE THREAD

**Issue by johnstile** [python-openxml/python-docx#761]
Using python-docx, I would like to perform what MS Word calls, "Remove Content Controls".
In Word, one must select all, right click, and choose "Remove Content Controls", and save.
The result: populated text remains, and python-docx can now see all of the text.
Before removing content-control form fields, the content text is not easily accessible via python-docx.
Using python-docx==0.8.10

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues
list is for suspected bugs and new feature requests.

There is no API support for this in `python-docx`. You'd need to manipulate the underlying XML. Have a search on "python-docx workaround function" to get an idea how that could be easier starting with `python-docx` to get into the right part of the XML.

**Comment by johnstile** [comment]
This was a feature request, not a bug.
