### ISSUE TITLE
How can I edit font-size... of content control

### ISSUE THREAD

**Issue by vuonghungvinh** [python-openxml/python-docx#762]
I got that element
doc_elm = document._element
                contentControls = doc_elm.xpath('.//w:sdt')
                for contentControl in contentControls:
                    print(contentControl)

Now, how can I edit font-size or line spacing?

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues
list is for suspected bugs and new feature requests.
