### ISSUE TITLE
"not a zip file" in Python 3

### ISSUE THREAD

**Issue by pfuntner** [python-openxml/python-docx#765]
This is more of a question but I don't know where to ask questions.

I have this collection of tools that worked well in Python 2 and one of them used python-docx to look at `*.docx` files.  I'm switching my tools to use Python 3 and found that a script that works with Python 2 does not work with Python 3:

```
$ cat docx
#! /usr/bin/env python3

import os
import sys
from docx import Document # from python-docx

assert len(sys.argv) == 2, 'Specify a filename'
assert os.path.isfile(sys.argv[1]), 'Cannot find {}'.format(sys.arg[1])

print('Python {}'.format(sys.version_info))
with open(sys.argv[1]) as stream:
  doc = Document(stream)
  print('{} paragraphs'.format(len(doc.paragraphs)))
$ ./docx Hello.docx
Python sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "./docx", line 31, in <module>
    doc = Document(stream)
  File "/usr/lib/python3.6/site-packages/docx/api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "/usr/lib/python3.6/site-packages/docx/opc/package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/usr/lib/python3.6/site-packages/docx/opc/pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/usr/lib/python3.6/site-packages/docx/opc/phys_pkg.py", line 101, in __init__
    self._zipf = ZipFile(pkg_file, 'r')
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
$ python2 ./docx Hello.docx
Python sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0)
1 paragraphs
$ pip3 list | grep docx
python-docx 0.8.10
$ 
```

I see the documentation says is supports Python 3.3 and 3.4.  Are there plans to support 3.6?

**Comment by scanny** [comment]
Hi John, StackOverflow is the best place to ask support questions (be sure to use "python-docx" tag), but suspected bugs and feature requests belong here. I'd say this is the right place to start for this one.

I recommend trying a few things to narrow it down:

1. see if you can create a document in Python3.6 from scratch, save it and reopen it. I'm betting this works. If so, it shows this is not a version-specific breakage. Something like:

```python
document = Document()
add_paragraph("something")
document.save("path/something.docx")

document = Document("path/something.docx")
```

2. try opening the Hello.docx file directly with `zip` in Python. It won't be a document of course, but I'm betting you get the same error on that file in Python 3.6, even when `python-docx` is nowhere in sight.

3. Let us know what happens and we'll go from there.

We've been running in Python 3 almost from the beginning and I don't see any reports of them changing ZipFile on version 3.6 (although of course I could have missed something).

Anyway, if you can narrow it down like that then we'll see what's what.

**Comment by reschkek-bpv** [comment]
I get this error too (python 3.6) when I try to open a docx file in "text-mode". To fix, I open the file in "binary-mode" instead, like this:

```
with open(sys.argv[1], 'rb') as stream:
  doc = Document(stream)
```

Or just pass the filename to the constructor, like this:

```
doc = Document(sys.argv[1])
```

**Comment by brasky** [comment]
Opening the file in the default `r` mode decodes the file to text, whereas passing the filename or opening the file in binary mode does not decode the file. Basically even though the variable is named stream, that is not a stream it's a TextIOWrapper which is not a zip file. 

You can either open the file in binary mode or just remove the `with` since I imagine you don't really need the try/finally.
