### ISSUE TITLE
'Document' object has no attribute 'add_paragragh'

### ISSUE THREAD

**Issue by zzll0909** [python-openxml/python-docx#766]
I can use function“add_heading” to add a heading, but function“add_paragragh"has this problem.

> 
![image](https://user-images.githubusercontent.com/54501255/71554690-a2361580-2a5d-11ea-82c6-995945e6b727.png)

**Comment by wjsetzer** [comment]
I think you might have been looking for '`Document.add_paragraph`'.

It looks like you misspelled "paragraph" as "paragragh".

**Comment by zzll0909** [comment]
> I think you might have been looking for 'Document.add_paragraph()'.
> It looks like you misspelled "paragraph" as "paragragh".

OK,I understand,I made this mistake.
