### ISSUE TITLE
How can I justify run objects?

### ISSUE THREAD

**Issue by HASKADOG** [python-openxml/python-docx#767]

**Comment by HASKADOG** [comment]
I need something like that:
Mr.Josh Sins________                                                              2019.1.12

**Comment by scanny** [comment]
Please ask support questions on StackOverflow. If you use the "python-docx" tag we'll see it. This issues list is reserved for suspected bugs and feature requests.

In your case I would look into tabs and tab-stops. There is such a thing as a "right-tab" which should do what you want.
