### ISSUE TITLE
Printing Nested Tables

### ISSUE THREAD

**Issue by richylyq** [python-openxml/python-docx#769]
HI there, I would like to check if it is possible to print nested tables out using this library? I tried to work on it but however, it just prints the nested table as empty.

```
from docx import Document

f = open('a.docx', 'rb')
doc = Document(f)

table = doc.tables[0]
data = []

keys = None
for i, row in enumerate(table.columns):
    text = (cell.text for cell in row.cells)

    if i == 0:
        keys = tuple(text)
        continue
    row_data = dict(zip(keys, text))
    data.append(row_data)
print (data)

x = 0
for i in doc.paragraphs:
    if x < 20:
        print (i.text)
    else:
        break
    x = x + 1

f.close()
```

**Comment by richylyq** [comment]
Sorry for my mistake, just realised that this doesn't support nested table. Keep up the good work tho!

**Comment by scanny** [comment]
@richylyq `python-docx` supports nested tables just fine, you just need to look for them as tables. They are not part of the text of a cell. Something like:

```
for cell in cells:
    for table in cell.tables:
        # do something with the nested table.
```

**Comment by richylyq** [comment]
Alright thanks @scanny I will go ahead and try it out. Thanks for the assistance! 😃

**Comment by richylyq** [comment]
Hey @scanny I can retrieve data in nested tables already! However, I believe the way i am doing right now is not a feasible way, but i cannot think of a better method right now. 
```
def pctnt():
    tables = doc.tables
    for table in tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    print(paragraph.text)
                for table in cell.tables:
                    for row in table.rows:
                        for cell in row.cells:
                            for paragraph in cell.paragraphs:
                                print(paragraph.text)
                            for table in cell.tables:
                                for row in table.rows:
                                    for cell in row.cells:
                                        for paragraph in cell.paragraphs:
                                            print(paragraph.text)
```
I am able to retrieve the data in the nested table within the nested table of this particular document but this is right now due to the fact that i know that there is the nested table within the nested table. Do you have any idea how to retrieve something like this without knowing what or how many nested tables the document have? 

Thanks in advance!

**Comment by scanny** [comment]
I think I would extract the bit about navigating a single table for its paragraphs and make that recursive:

```python
def iter_table_paragraphs(table):
    for row in table.rows:
        for cell in row.cells:
            yield from cell.paragraphs
            for table in cell.tables:
                yield from iter_table_paragraphs(table)       

def print_tables(document):
    for paragraph in iter_table_paragraphs(document):
        print(paragraph.text)
```

That way your specific use for those paragraphs (printing in this case) is up to the caller and the `iter_table_paragraphs()` function is more general purpose. You could use it to inspect each paragraph for example, or maybe inspect each paragraph style or search for a word.

**Comment by richylyq** [comment]
This might do! I actually checked on StackOverflow and someone gave me the similar idea. Just for your reference or to whom that may come across this question.
```def print_paragraphs(doc):
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    print(paragraph.text)
                print_paragraphs(cell)
```

Thanks @scanny anyways!
