### ISSUE TITLE
How can i find the page num of a paragraph?

### ISSUE THREAD

**Issue by ClaudiusGitHub** [python-openxml/python-docx#772]

**Comment by ClaudiusGitHub** [comment]
I want a pragram to check the docx files, if there are  errors in the paragraph, i  should print the errors info of the paragraph, just like the page num of the error, but i didn't find the function of python-docx

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues
list is for suspected bugs and new feature requests. There is no reliable way to determine the page number of a paragraph using `python-docx` https://stackoverflow.com/questions/36193159/page-number-python-docx.
