### ISSUE TITLE
Override __eq__ operator for the Paragraph class

### ISSUE THREAD

**Issue by yks72p** [python-openxml/python-docx#773]
It would be nice to have the ability to check if two paragraphs are equal.
So operator `__eq__` must be overriden for `docx.text.paragraph.Paragraph` class.

**Comment by scanny** [comment]
What do you mean by "equal"?

**Comment by scanny** [comment]
Two `Paragraph` objects are considered equal if they point to the same `<w:p>` XML element. That behavior is already implemented.
