### ISSUE TITLE
Unable to find/parse any elements in docx file

### ISSUE THREAD

**Issue by danielloader** [python-openxml/python-docx#775]
Hey, thanks for the library - looks like it'll be super useful. I'm just running into a bit of a problem with a document and parsing it.
I've uploaded the file to a [repl.it](https://repl.it/@danielloader/DopeyLeafySoftwareagent) and attaching it to this issue.

I confirmed the library is reading/parsing the file with the document attributes being printed but no other element seems accessible. I'd love to give more debug information but I'm basically stuck at step one of trying to return anything from the XML DOM.

Any help would be appreciated.

[200120.docx](https://github.com/python-openxml/python-docx/files/4082906/200120.docx)

**Comment by danielloader** [comment]
As an aside [using lxml and pandas](https://repl.it/@danielloader/GiantYellowGlueware) seems to work, so now more curious why python-docx isn't.

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues
list is for suspected bugs and new feature requests.
