### ISSUE TITLE
ELFCLASS64 ERROR

### ISSUE THREAD

**Issue by shubham101096** [python-openxml/python-docx#776]
![IMG-4580](https://user-images.githubusercontent.com/42842288/73624399-9f36d200-4666-11ea-80bd-f018ecf054a6.jpg)

Please help to resolve the error shown in image.

**Comment by scanny** [comment]
This is a problem installing `lxml` on Windows, not a `python-docx` error. I expect you can reproduce this with a Python file that contains only `from lxml import etree`. Google is your friend on how to resolve the `lxml` install problem.

**Comment by shubham101096** [comment]
Sir the image above is the console of the board. Initially, I had installed the python-docx package using pip on my Ubuntu 64 BIT pc in a folder (and a 64 bit python) . Then I transferred the installed packages to my board which uses  PowerPC e5500 processor. The board has 32BIT python installed on it. So, when I use python-docx on the board it gives ELFCLASS64 ERROR. I cannot directly install the packages on board as it does not have internet access. Please help me to resolve this.

**Comment by scanny** [comment]
Alright, well, whatever the platform is, this is a problem with installing `lxml` on it, not a `python-docx` problem. You can prove that to yourself by running the following code in your python environment there:

```python
from lxml import etree
```

I suggest you Google lxml install and get that working and perhaps how to install 32-bit Python/pip, maybe something like this: https://stackoverflow.com/questions/39015410/windows-python-64-32-bit-versions-and-pip

But other than that, I'm afraid I can't help you.
