### ISSUE TITLE
Adding pictures to the document header

### ISSUE THREAD

**Issue by Escaldor** [python-openxml/python-docx#777]
Hi, I'm developing a proyect for my work where I take data from an excel sheet and pour it into a Word Template. I have everything ready except for the logo on the header, tryed almost everything and still can't manage to do it. 

This is how it's suposed to look like:
![Sin título](https://user-images.githubusercontent.com/58092265/73950320-7e76b280-48da-11ea-8849-6ad7b2418790.png)
 
This is the best i could get so far:
![Sin título2](https://user-images.githubusercontent.com/58092265/73950588-ecbb7500-48da-11ea-8223-cfa5b68db733.png)

I can right-click the image and change from inline to square and manually place it where I want it to be, but that beats the purpose of automating the task. 

Love this lib and really hope I can finish* this little project as it was intended. Thanks so much for reading, I'll be waiting for your reply!

**Comment by scanny** [comment]
Post the code you used to produce this result.

**Comment by Escaldor** [comment]
> Post the code you used to produce this result.

    document = Document()
    sections = document.sections
    for section in sections:
    	section.page_height = Mm(355.6)
    	section.page_width = Mm(215.9)
    	section.top_margin = Cm(1)
    	section.bottom_margin = Cm(1.5)
    	section.left_margin = Cm(3)
    	section.right_margin = Cm(1)
    	header = section.header
	

    
    htable=header.add_table(1, 2, Inches(6))
    htab_cells=htable.rows[0].cells
    ht0=htab_cells[0].add_paragraph()
    



    paragraph = header.paragraphs[0]
    paragraph.text = '''\t\t“2020 – Año del Congreso pedagógico” 	                                                                                                                                                                    Ley Provincial Nº 3114-A\n'''
    original = input('Original? (S/N): ')
    if original.upper() == 'S':
        kh=ht0.add_run()
        kh.add_picture((r'C:\Users\Usuario\PyApps\Resol. Auto\escudo.png'), width=Cm(6), height=Cm(3.5))
    else:
        kh=ht0.add_run()
        kh.add_picture((r'C:\Users\Usuario\PyApps\Resol. Auto\blank.png'), width=Cm(6), height=Cm(3.5))
    style = document.styles['Header']
    paragraph_style = document.styles
    paragraph_font = style.font
    paragraph_font.name = 'Times New Roman'
    paragraph_font.size = Pt(8)

**Comment by scanny** [comment]
When you add the table, it appears _below_ the default first paragraph in the header.

Maybe you can delete the default paragraph with this:

```python
hdr = header._element
hdr.remove(hdr.xpath("w:p")[0])
```
before you add the table, then it should move to the top and you can place the right-side address in the second cell of the table.

Also consider creating the "letterhead" by hand and then using that .docx as your template file with `document = Document("my-letterhead.docx").

**Comment by Escaldor** [comment]
Hi, I was just trying to do what you said but all of the sudden my code stopped working and I have no idea why. 
CMD tells me this: 
![cmd](https://user-images.githubusercontent.com/58092265/74154158-e1c15700-4bf0-11ea-968d-b7fd84396bf6.png)

 I didn't change anything, I even used it a few hours ago and it worked just fine. I use that specific piece of code in four different scripts and it stopped working in all of them. Any idea of what might have happened? 
Here's my code:
![sublime](https://user-images.githubusercontent.com/58092265/74155249-fdc5f800-4bf2-11ea-8bec-dae97637d36b.png)

**Comment by Escaldor** [comment]
> Hi, I was just trying to do what you said but all of the sudden my code stopped working and I have no idea why.
> CMD tells me this:
> ![cmd](https://user-images.githubusercontent.com/58092265/74154158-e1c15700-4bf0-11ea-968d-b7fd84396bf6.png)
> 
> I didn't change anything, I even used it a few hours ago and it worked just fine. I use that specific piece of code in four different scripts and it stopped working in all of them. Any idea of what might have happened?
> Here's my code:
> ![sublime](https://user-images.githubusercontent.com/58092265/74155249-fdc5f800-4bf2-11ea-8bec-dae97637d36b.png)

UPDATE:
 I was trying to figure out what happened when I remembered that I installed the "docxtlp" module and found this: 
![dasdasdadas](https://user-images.githubusercontent.com/58092265/74159433-8eec9d00-4bfa-11ea-8d9e-23f36ec7822e.png)

**Comment by Escaldor** [comment]
> When you add the table, it appears _below_ the default first paragraph in the header.
> 
> Maybe you can delete the default paragraph with this:
> 
> ```python
> hdr = header._element
> hdr.remove(hdr.xpath("w:p")[0])
> ```
> 
> before you add the table, then it should move to the top and you can place the right-side address in the second cell of the table.
> 
> Also consider creating the "letterhead" by hand and then using that .docx as your template file with `document = Document("my-letterhead.docx").

 After solving that minor issue, I changed following your advice and it worked, here are the results:
![Sin título](https://user-images.githubusercontent.com/58092265/74167426-ff99b680-4c06-11ea-8744-5bb99d6377d3.png)

Thanks so much for answering, you did help me a lot!
