### ISSUE TITLE
How to read docx in turn ( eg: paragraph, table, table; paragraph, table )

### ISSUE THREAD

**Issue by liulover5** [python-openxml/python-docx#779]
How to read docx in turn ( eg: paragraph, table, table; paragraph, table )

read in turn ,because paragraph is ralated to table which is under its paragraph... 

eg:
paragraph 1
table 1
table 2 
paragraph 2
table 3

as:
below is a group data 
paragraph 1
table 1
table 2 
...
paragraph 2
table 3

**Comment by scanny** [comment]
Duplicate of #40
