### ISSUE TITLE
feature: add_table() sets cell widths

### ISSUE THREAD

**Issue by scanny** [python-openxml/python-docx#78]
In order to provide the least surprising initial behavior
As a developer using python-docx
I would like a table inserted using `add_table()` to be serviceable in both Word and LibreOffice without further adjustment.

Related to #75. Default table added with `Document.add_table()` runs off the page in LibreOffice, although it's fine in Word. Rendering differences aside, it would be better if it produced consistent results across the two clients.

The solution is to add column widths, e.g. `<w:gridCol w:w="1440"/>` as well as matching cell widths, e.g. `<w:tcW w:w="1440" w:type="dxa"/>` for each cell in each column. This is consistent with what Word does when adding a new table from the ribbon.

Column widths should be evenly distributed across the page width. For example, a 4-column table inserted into a page with 8 inches between the margins should have four columns 2 inches wide each.

**Comment by scanny** [comment]
Added in release v0.8.5, pushed on Feb 21, 2015.

**Comment by louiscremen** [comment]
Hi Scanny,

I've updated to 0.8.5 from 0.7.4 and now all my tables are the same width (and this is the closest issue I've found that might be the cause of it)

This is how I used to format tables (which worked fine in 0.7.4)
table = document.add_table(rows=10,cols=2,style="ColorfulList-Accent5")
table.autofit = False
table.columns[0].width = 13 * emusPerCm
table.columns[1].width = 3 * emusPerCm

However - now it does not appear to accept this. Based on your description, I presume I now need to have for loops everywhere to change all the cell widths? Is it possible that have it fallback on column width and set the cell width if cell width is not specified. There are few circumstances I can think of for varied styled cells within a table.

**Comment by scanny** [comment]
Hi Louis, yes, the behavior you're seeing is an artifact of the change added to address this issue with how new tables appeared in LibreOffice Writer. Now, when a table is created, the columns widths are each set to a proportional fraction of the page width, but also the width of each *cell* in each column is set to match the column width.

What we haven't gotten done yet is to carry this logic through to cell widths on assignment to Column.width. The reason being the logic is not trivial in the general case where one or more cells can be merged. In those cases, the cell width should be the sum of the column width of all the columns it spans.

I've added a new issue for it here #161.

In the meantime, your table creation code can be cleaner with a column width setting function that does the needful, something like this:
```python
def set_column_width(column, width):
    for cell in column:
        cell.width = width

table = document.add_table(rows=10,cols=2,style="ColorfulList-Accent5")
set_column_width(table.columns[0], Cm(13))
```

If you have merged cells, you'll need to do the needful to ensure those cells get the appropriate different width.

By the way, your width setting can be a little simpler using the Cm() constructor:
```python
from docx.shared import Cm

column.width = Cm(13)
```

**Comment by louiscremen** [comment]
Thanks @scanny.

I've written a function that's similar to what you've described (set_table_width rather than set_column_width) which accepts the table and a list argument. I just have to copy and paste it about 40 or 50 times. I was hoping to avoid it.

However, since it is not a trivial change and the functionality is still there - I'm not too concerned, just means I need to change my code. Compatibility with multiple processors is more important and cell merging is something I see people wanting to generate.

Did not know about Cm() function, although multiplying width by 360000 isn't too bad.

Thank you for the feature and for the speedy response - Love your work :)

**Comment by dwapstra** [comment]
```
def set_column_width(column, width):
    for cell in column:
        cell.width = width

set_column_width(table.columns[0], Cm(2.5))
```

gives an error:

TypeError: '_Column' object is not iterable

**Comment by scanny** [comment]
it should be `for cell in column.cells:`.

**Comment by dwapstra** [comment]
thanks. I use the following now:
```
def set_column_width(column, width):
    column.width = width
    for cell in column.cells:
        cell.width = width
```

**Comment by nikosme** [comment]
any idea hot to enable the option "automatically adjust to content" when i create a table on a word docx file using python librarie docx ???

**Comment by tabomics** [comment]
@nikosme  did you figure out how to do this? Thanks.

**Comment by conor909** [comment]
I'm trying to set my table to either "AutoFit to Window" or "preferred width 100 percentage", either way I just want my tables "full width"
