### ISSUE TITLE
How to get the page count of a document

### ISSUE THREAD

**Issue by richylyq** [python-openxml/python-docx#780]
Hi,

I would like to know if it is possible to get the page count of a document in this library. If it is possible, how should I go about doing it. 

Thanks in advance!

**Comment by shashwat-vik** [comment]
Had the same issue. Couldn't find any native approach.
So read from the XML property file present in DOCX using only the standard libraries (python 3.5):

```
import zipfile, re

def getDocxPageCount(docx_fpath):
    docx_object = zipfile.ZipFile(docx_fpath)
    docx_property_file_data = docx_object.read('docProps/app.xml').decode()
    page_count = re.search(r"<Pages>(\d+)</Pages>", docx_property_file_data).group(1)
    return page_count
```

**Comment by shashwat-vik** [comment]
Had the same issue. Couldn't find any native approach.
So read from the XML property file present in DOCX using only the standard libraries (python 3.5):

```
import zipfile, re

def getDocxPageCount(docx_fpath):
    docx_object = zipfile.ZipFile(docx_fpath)
    docx_property_file_data = docx_object.read('docProps/app.xml').decode()
    page_count = re.search(r"<Pages>(\d+)</Pages>", docx_property_file_data).group(1)
    return int(page_count)
```

**Comment by PasaOpasen** [comment]
> import zipfile, re
> 
> def getDocxPageCount(docx_fpath):
>     docx_object = zipfile.ZipFile(docx_fpath)
>     docx_property_file_data = docx_object.read('docProps/app.xml').decode()
>     page_count = re.search(r"<Pages>(\d+)</Pages>", docx_property_file_data).group(1)
>     return int(page_count)

works properly only when there are pagebreaks between each page
