### ISSUE TITLE
run.add_picture() -> "This image cannot currently be displayed"

### ISSUE THREAD

**Issue by jliempt** [python-openxml/python-docx#782]
Hi,

I am trying to replace the contents of an existing cell in an existing table with an image. However, in the saved .docx, I am getting a box inside that cell with the "This image cannot currently be displayed" message.

On the other hand, adding the same image to the document itself works just fine. My code looks like this:

```
from docx import Document

doc = Document('input.docx')
new_doc = Document()

# Read existing table
tbl1 = doc.tables[0]

def delete_paragraph(paragraph):
    p = paragraph._element
    p.getparent().remove(p)
    p._p = p._element = None

# This will result in the box with error message in Word
delete_paragraph(tbl1.rows[50].cells[2].paragraphs[0])
par = tbl1.rows[50].cells[2].add_paragraph()
run = par.add_run()
run.add_picture("screens/pic0.jpg")

# This adds the image on top of the document just fine
new_doc.add_picture("screens/pic0.jpg")

# Add a paragraph to the doc, insert the updated table into it
paragraph = new_doc.add_paragraph()
paragraph._p.addnext(tbl1._tbl)
new_doc.save('output.docx')
```

How the cell looks like in Word:
![error](https://user-images.githubusercontent.com/35920075/74449179-7be8ff80-4e7c-11ea-9519-3f765b701e36.PNG)

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues
list is for suspected bugs and new feature requests. In this case, might be worth trying adding it without deleting the paragraph, just to see if the two are interacting somehow. A cell without a paragraph element is invalid according to the spec and the code may reasonably expect one to be there.
