### ISSUE TITLE
Can't edit, change filename, or insert picture after save

### ISSUE THREAD

**Issue by spencertse122** [python-openxml/python-docx#785]
Hi,

Thank you first for sharing the tool.

So after saving the processed document into docx, the file doesn't allow any duplicates, change of filename, insert pictures, or other operations. It just shows a pop up window showing there's an error or no permission.

Thank you!

**Comment by scanny** [comment]
Please post this question (and other support questions) on StackOverflow using the "python-docx" tag. You'll need to provide more information there, like what platform you're running on and you'll need to produce a minimum reproducing example.
