### ISSUE TITLE
Feature suggestion: a hylang dsl example

### ISSUE THREAD

**Issue by shizhaojingszj** [python-openxml/python-docx#787]
A great library, but a little verbose when writing I think.

https://docs.hylang.org/en/stable/ hylang is totally interoperable with python, and lisp can be great for DSL, so a good idea may be combining these together. May be an example provide a way to use hy to write a document. Does anyone think this is worthy ?

**Comment by scanny** [comment]
By all means feel free, but a blog or something would be the better choice. It wouldn't be something we'd accept into the main documentation.
