### ISSUE TITLE
How to add list number to paragraphs which are in a table

### ISSUE THREAD

**Issue by leopoldwalkure** [python-openxml/python-docx#791]
The style of “List Number” works well in documents but not in tables.

I'm wondering if python-docx can make this or not.

Plz let me know, thank you!

P.S. I've sent an e-mail to the "python-docx@googlegroups.com"  before and it seems the address is unavailable.

**Comment by scanny** [comment]
Cannot reproduce. Works for me. Try it by hand and see if it works.

**Comment by leopoldwalkure** [comment]
Hi, Scanny

It is very kind of you to reply me about this basic question.

Could you draft a small demo with a few lines for me, please? Cz this is really confused to me. I'm not a pro at programming and it drives me crazy......

Please help, thank you!

Wish you health!
