### ISSUE TITLE
Feature: add_paragraph() before and after parameter

### ISSUE THREAD

**Issue by xdml** [python-openxml/python-docx#793]
Hi, I am aware of `insert_paragraph_before()`.

I hope that one simple method is better then different specific methods, so I suggest to define it like:

```python
def add_paragraph(self, text='', style=None, before=None, after=None):
```

If `before` is provided, it will do same as `insert_paragraph_before()`, if `after` is provided, it will add paragraph after existing one, provided in `after` parameter.

If both `before` and `after` are provided some exception will be raised.

**Comment by scanny** [comment]
No, we'd consider changing behavior of a method by "flag" parameters to be poor API design. The idea of `insert_paragraph()` is where we're going with that. But thanks for the suggestion.
