### ISSUE TITLE
Insert a image into a opened word document.

### ISSUE THREAD

**Issue by hot4words** [python-openxml/python-docx#795]
When I try to run my code 

```
from docx import Document
from docx.shared import Inches
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.cos(2*np.pi*t)
plt.plot(t, s)

plt.savefig('test.png')

document = Document('report6.docx')

document.add_picture('test.png', width=Inches(1.25))

document.save('report6.docx')
```
I get this error
**PermissionError: [Errno 13] Permission denied: 'report6.docx'**
To solve the error, I need to close my report6.docx first.
Is there a way I can insert my image without closing the doc and observe the change immediately when I insert the image?

**Comment by scanny** [comment]
No. `python-docx` reads and writes files. If the file you're writing to is open, the `.save()` call will fail.

**Comment by scanny** [comment]
No. `python-docx` reads and writes files. If the file you're writing to is open, the `.save()` call will fail.

If you want "interactive" updating to the Word file (while you have it open) you'll need to use a com32-style solution, such as Visual Basic (VBA) or perhaps via the PyWin32 package. Both of these require running under Windows I believe.
