### ISSUE TITLE
Creating a paragraph with line breaks?

### ISSUE THREAD

**Issue by jnardone** [python-openxml/python-docx#801]
text = "This is a line break\n\nNow there's more\n\nOh god i am not good with computer"
    t_para = doc.add_paragraph(text, style='List')

When I do this, my document output is

    <w:r><w:t>This is a line breakNow there's moreOh god i am not good with computer</w:t></w:r>

Per the documentation, I expected those newlines to be converted to *br* tags.  What do I need to do to convert this?

I've tried multi-escaping the newlines in my substitutions, but the code does appear to be looking for the specific control characters vs. literal "\n" as strings.

**Comment by scanny** [comment]
What version are you running? This works the expected way for me.

```python
>>> document = Document()
>>> paragraph = document.add_paragraph("abc\ndfg\n\nhij", style="List")
>>> print(paragraph._p.xml)
<w:p xmlns:w="...">
  <w:pPr>
    <w:pStyle w:val="List"/>
  </w:pPr>
  <w:r>
    <w:t>abc</w:t>
    <w:br/>
    <w:t>dfg</w:t>
    <w:br/>
    <w:br/>
    <w:t>hij</w:t>
  </w:r>
</w:p>

```

**Comment by jnardone** [comment]
Sorry about this.  You are correct.  There was some middleware processing unbeknownst to me that was modifying the data to be encoded.  Happy to have this library and the support.
