### ISSUE TITLE
Change table border line when useing add_table.

### ISSUE THREAD

**Issue by houzeyu2683** [python-openxml/python-docx#804]
I want to change the border line of table in the document.
Here is my test code following blow.
```
from docx import Document
document = Document()
document.add_table(rows=1, cols=2)
document.save('demo.docx')
```
But the table border line is empty.
![擷取](https://user-images.githubusercontent.com/42731603/77811397-d957a980-70d4-11ea-8f48-78326ae8b6cc.PNG)

After read the document of API, I try to change the style of table.
![擷取](https://user-images.githubusercontent.com/42731603/77811417-01dfa380-70d5-11ea-8ed5-31d1d4b215b1.PNG)

![擷取](https://user-images.githubusercontent.com/42731603/77811430-2471bc80-70d5-11ea-9061-d44395512191.PNG)

It return no style with name. And I try other table style, it the same result.
Does anyone known how to fix the problem?

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues
list is for suspected bugs and new feature requests.
