### ISSUE TITLE
Changing Heading font doesn't work

### ISSUE THREAD

**Issue by akkana** [python-openxml/python-docx#805]
https://python-docx.readthedocs.io/en/latest/user/styles-using.html implies that I should be able to change Heading font styles like this:
```
font = doc.styles['Heading 1'].font
font.name = 'Times New Roman'
font.size = docx.shared.Pt(16)
```
But that doesn't work: the resulting document uses Calibri for all headings. (They're also blue and Heading 1 has an underline, which I also need to eliminate somehow.)

It also doesn't work to change the font on a specific heading, nor to delete the latent_styles for the headings.

Github won't let me attach a .py file, so here's my sample standalone program that tries all three methods, but all of the headings come out as blue Calibri despite all attempts to change them to Times New Roman. 

```
#!/usr/bin/env python3

import docx

doc = docx.Document()

# Deleting heading latent styles seems to do nothing:
latent_styles = doc.styles.latent_styles
latent_styles['Heading 1'].delete()
latent_styles['Heading 2'].delete()

# Setting the Normal font works:
font = doc.styles['Normal'].font
font.name = 'Times New Roman'
font.size = docx.shared.Pt(12)

# Setting heading styles doesn't do anything:
# they all still end up as blue Calibri.
font = doc.styles['Heading 1'].font
font.name = 'Times New Roman'
font.size = docx.shared.Pt(16)

font = doc.styles['Heading 2'].font
font.name = 'Times New Roman'
font.size = docx.shared.Pt(14)

doc.add_heading("Heading 0", 0)
doc.add_paragraph('Here is a paragraph of text.')
doc.add_heading("Heading 1", 1)
doc.add_paragraph('Here is a paragraph of text.')
doc.add_heading("Heading 2", 2)
doc.add_paragraph('Here is a paragraph of text.')

# It also doesn't work to change the style of a specific heading:
heading = doc.add_heading("Another Heading 1", 1)
heading.style.font.name = "Times New Roman"
doc.add_paragraph('Here is a paragraph of text.')

doc.save('/tmp/test.docx')
```

The document produced:
[test.docx](https://github.com/python-openxml/python-docx/files/4399175/test.docx)

https://stackoverflow.com/questions/37220754/cant-change-heading-1-font-name-using-docx mentions this as a known bug, but the only issues I found here were 390 which seems to be dismissed as an Asian font issue, and 366, I'm not sure if that's the same problem or not.

**Comment by scanny** [comment]
Hi Akkana, I think I can help you with this, but I'd prefer to answer on SO where more folks can benefit; a closed issue is going to rank a lot lower than an SO question on search.

Let's start with the "Changing heading style font doesn't work" issue and we can take up any others that are left over as separate questions.

Make sure you tag the question with "python-docx" and it will come through on my feed.

**Comment by akkana** [comment]
I don't have a stackoverflow account. Do I really need to sign up for one? I'd love to get an answer, so I'll sign up if I need to.

**Comment by scanny** [comment]
I think it's worth doing. That's where all the support for `python-docx` happens and it seems like the first search result for every other open-source question I go looking for (which is quite a few :). I'll bet there are some GIMP questions and so forth over there you might be able to weigh in on yourself if you try one or two of the tag feeds (RSS).

Even asking and answering support questions is contributing, so it makes some sense to do that where they will have the widest impact.

If you really don't want to I can get you started here, but I'll be more willing to give it quality time if I know it's contributing to the overall corpus of support resources. I'm sure you won't be the last to come across this one.

**Comment by akkana** [comment]
Okay, done. https://stackoverflow.com/questions/60921603/how-do-i-change-heading-font-face-and-size-in-python-docx

**Comment by akkana** [comment]
Sorry to be a pest, but this still seems like a bug even if there's an workaround, especially since the documentation references heading styles. If heading styles don't work in the normal way, could there at least be a documentation change to remove the reference to heading styles or to warn that headings don't work the normal way and mention the workaround? Are there other styles besides headings that don't support font name or color in the normal way? (I'd offer to update the documentation, but I'm still pretty confused about why headings don't work like other elements and how I'd explain that.)

I do very much appreciate the workaround -- it fixed my problem. Thanks!
