### ISSUE TITLE
Adding text to existing template

### ISSUE THREAD

**Issue by Tayyab-Ilahi12** [python-openxml/python-docx#807]
Hi, i am currently working on a freelance project what i am asked to do is copy data from one CV and paste it into a new .docx template having headings like 
Languages:
Experience:
Now what i am trying to is read the template file and then add Language info after the Languages word. maybe a run or a paragraph. I found  a insert_before function but not a paragraph. I can't find a way out. Also there is no function in Python-docx that does it. I found some articles mentioning addnext but i am not able to find it in Python-docx

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues
list is for suspected bugs and new feature requests.

**Comment by Tayyab-Ilahi12** [comment]
@scanny just did 
kindly check it out: https://stackoverflow.com/questions/61056479/add-after-paragraph-in-python-docx
