### ISSUE TITLE
feature: floating table

### ISSUE THREAD

**Issue by AHoou** [python-openxml/python-docx#808]
### Take pictures as an example: 
![1](https://user-images.githubusercontent.com/46209516/78873066-d23d7d80-7a7c-11ea-9852-f5afb8f927cf.png)

**Comment by scanny** [comment]
There is no API support for floating tables in `python-docx`.

**Comment by GZDXLQH** [comment]
> There is no API support for floating tables in `python-docx`.

OK.But thanks for your replay.
