### ISSUE TITLE
AttributeError: 'Document' object has no attribute 'add_paragragh'

### ISSUE THREAD

**Issue by watalo** [python-openxml/python-docx#809]
Hi,I have been confused by ‘AttributeError’ for several days.  I have tried many ways to solve this problem, but I still failed. I doubt it's because I upgraded Python to version 3.7.7. 
 Here is a simple:
`from docx import Document`
`doc = Document()`
`doc.add_paragragh('i love python-docx')`
`doc.save('test.docx')` 

> AttributeError: 'Document' object has no attribute 'add_paragragh'

**Comment by scanny** [comment]
I think you mean ".add_paragraph()" with a "ph" at the end instead of "gh". :)

**Comment by watalo** [comment]
OMG，I am so foolish. Thank you very much!
