### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by cadilllaclook** [python-openxml/python-docx#812]
Does it support python3.6?

**Comment by mstd0n** [comment]
I'm running it on Python 3.8.2 with no compatibility issues that I can tell.

**Comment by linuxkd** [comment]
Documentation states even older versions of Python.
https://python-docx.readthedocs.io/en/latest/user/install.html

> Dependencies
>    Python 2.6, 2.7, 3.3, or 3.4
>    lxml >= 2.3.2
