### ISSUE TITLE
Writing data to a table without proceeding /n

### ISSUE THREAD

**Issue by mstd0n** [python-openxml/python-docx#813]
Is there anyway to write data to a cell in a table without it adding /n before the text?

I tried doing raw text with: insert_paragraph_before(r'text', style=NONE)

I also cleared the formatting in my table. I can have the table auto scale row height to accommodate for the extra line breaks...but it doesn't looks very nice.

**Comment by mstd0n** [comment]
OK I found a work around.

Word processors appear to add a default paragraph in a field. Instead of inserting a new paragraph behind it, you can append the current one.

doc.tables[X].cell(X,X).paragraphs[X].add_run('text.')

I'm not sure if this is the most elegant solution, but it works...and more importantly **ISN'T AN ISSUE WITH PYTHON-DOCX** its just how word processors work.

**Comment by garvamel** [comment]
You probably saved my hours with this. Thank you very much.

**Comment by garvamel** [comment]
> OK I found a work around.
> 
> Word processors appear to add a default paragraph in a field. Instead of inserting a new paragraph behind it, you can append the current one.
> 
> doc.tables[X].cell(X,X).paragraphs[X].add_run('text.')
> 
> I'm not sure if this is the most elegant solution, but it works...and more importantly **ISN'T AN ISSUE WITH PYTHON-DOCX** its just how word processors work.

You saved me hours with this workaround. Thank you very much!

**Comment by mstd0n** [comment]
Awesome! Glad I could help someone else save some time.
