### ISSUE TITLE
Add bold on specific text after creating table

### ISSUE THREAD

**Issue by sakulachi8** [python-openxml/python-docx#815]
table = document.add_table(rows=1, cols=2)
table.style = document.styles['Table Grid']
row_cells = table.add_row().cells
row_cells[0].text = 'Some Text'
row_cells[1].text = 'This is text with some **BOLD** and some non bold text'

How i will achieve this

**Comment by linuxkd** [comment]
You need to use runs. Something like this:
```
run = paragraph.add_run()
run.text = "This is text with some "
run.font.bold = True
run = paragraph.add_run()
run.text = "BOLD "
run.font.bold = False
run = paragraph.add_run()
run.text = "and some non bold text"

row_cells[1].text = run
```

I didn't test this, but something like this should work. That last line might be off a bit. Check the documentation!
