### ISSUE TITLE
Naviagte insertion point to a particualr point with respect to line number and characterafter?

### ISSUE THREAD

**Issue by chethansai** [python-openxml/python-docx#816]
The whole idea is to insert text at desired location.
Like "_"(if there was no underscore.. I would say to add underscore at 2nd line 7th characterposition

**Comment by linuxkd** [comment]
You can search your document for an anchor and insert data based on that anchor. By that I mean iterate through the document for some text or style etc, then insert whatever it is that you want. The documentation has examples for this sort of thing.
