### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by josephernest** [python-openxml/python-docx#817]
Hi, Congrats for this great project @scanny!

In a .docx file, I need to replace every text `{{name}}` by a variable in Python, and then export the .docx to PDF. This works:

    doc = docx.Document('template.docx')
    for paragraph in doc.paragraphs:
        paragraph.text = paragraph.text.replace('{{name}}', 'john')
    doc.save('temp.docx')  
    # this is very fast until here
    # the next line is very slow (3 or 4 seconds for each iteration):
    subprocess.call(r"C:\Program Files\LibreOffice\program\soffice.exe --headless --convert-to pdf temp.docx --outdir ." % i)

**Is there a faster way, built-in in `python-docx`, or with another python library, to export a DOCX to PDF?**

(I need to do this in batch for thousands of PDF)

**Comment by josephernest** [comment]
PS: is there maybe a way to connect `python-docx` to `reportlab` to produce PDF (instead of having to use `soffice.exe --headless`) @scanny?

**Comment by linuxkd** [comment]
Here is an option that might work for you.

1) Setup the above python code to take a filename parameter, and then call the script with a for loop that sends the filename to be iterated on.
2) Modify the code on the doc.save line to name the file based on the input filename. Like mydocument-clean.docx (or whatever makes sense for your use case)
2) Use a bash for loop to iterate through your files, something like this should probably work
`for i in $(\ls -1 *.docx; do python3 yourscriptname.py $i; done`

**Comment by josephernest** [comment]
@linuxkd Thank you for your answer, but I don't really understand it. The slow part is to start a `C:\Program Files\LibreOffice\program\soffice.exe --headless --convert-to pdf temp.docx --outdir .` process for each file.

I found this solution in the meantime: you can pass multiple .docx in one pass:

    C:\Program Files\LibreOffice\program\swriter.exe --headless --convert-to pdf --outdir temp1.docx temp2.docx ... temp100.docx

**Comment by vonyang** [comment]
Is there a way to convert a ```.docx``` to ```.pdf``` using ```reportlab```?
I have this code but I don't find a way to achieve the addition of each page to ```canvas.Canvas()```, to convert to a pdf without using an external application.
```
documentStream = Document(BytesIO(WordStream.getvalue()))
seccion = documentStream.sections[0]
height = seccion.page_height
width = seccion.page_width

application = BytesIO()
documentStream.save(application)
application.seek(0)
canva = canvas.Canvas(application)
canva.setPageSize((round(width.pt), round(height.pt)))

canva.showPage()
canva.save()
application.seek(0)
```
