### ISSUE TITLE
"Word found unreadable content..." after adding 20 images in the document

### ISSUE THREAD

**Issue by pierrick-libert** [python-openxml/python-docx#820]
Hello,

I'm running into a very particular issue which I'm unable to understand so far.
If I add 20 times the same image (or 20 unique images) my document got an error when I'm trying to open it: "Word found unreadable content..."
However if I do the same things but 19 times, I got no issues.

I checked online and word does not have a limit of images per document and my images sizes are around 20Kb so it shouldn't be a problem.
I checked the XML between the two documents generated and I don't see much differences between them.

I'm running on python 3.8.2 on windows. My Word version is Microsoft 365.

Let me know if you have any questions or suggestions, any help is welcome!

Thank you,

**Comment by pierrick-libert** [comment]
It was coming from complex object in the footer or header
In my case, a drawing line

**Comment by mrsanrise** [comment]
I think it is related to https://github.com/python-openxml/python-docx/issues/455
