### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'output.docx' 

### ISSUE THREAD

**Issue by luvensaitory** [python-openxml/python-docx#821]
I recently run python code on my server which OS is Ubuntu 16.04. And when using 
 `document.save('output.docx')`  happened this error.
I have already set my code using `chmod 777 mycode.py`
How can I deal with it?

**Comment by linuxkd** [comment]
> I recently run python code on my server which OS is Ubuntu 16.04. And when using
> `document.save('output.docx')` happened this error.
> I have already set my code using `chmod 777 mycode.py`
> How can I deal with it?

This is not a python-docx issue, this is a local permissions issue. Make sure your script has write access to the folder that you are trying to save the file in. Also, I'd recommend not explicitly setting read/write/execute for everyone on files as well. 

You may additionally need to specify the full output path depending on your code.
