### ISSUE TITLE
When i use my Microsoft Word to create a template python-docx skips the first line

### ISSUE THREAD

**Issue by wrong1man** [python-openxml/python-docx#822]
So im not sure if this is an issue with the package or somehow me/my Word.

So really simple way to recreate:
first i save the base template somewhere handy
```
doc=docx.Document()
doc.save("_somewhere handy_/originaltemplate.docx")
```
now i open this file in Word, do absolutely no changes, and save (i tried saving in every mode possible) - saved as "originaltemplate-saved.docx"
after i add the paragrph "TEST" in **BOTH** documents
```

doc=docx.Document("originaltemplate.docx")
doc.add_paragraph("TEST")
doc.save("originaltemplate-addedparagraph.docx")


doc=docx.Document("originaltemplate-saved.docx")
doc.add_paragraph("TEST")
doc.save("originaltemplate-saved-addedparagraph.docx")
```
Resulting files:
![image](https://user-images.githubusercontent.com/38586988/81445855-9e37a400-9171-11ea-9d75-36374088e1df.png)

This is especially horrible when adding images as they can get added to the second page!
My quick workaround for this was using google docs to create my template.

**Comment by wrong1man** [comment]
[originaltemplate.docx](https://github.com/python-openxml/python-docx/files/4601395/originaltemplate.docx)
[originaltemplate-saved.docx](https://github.com/python-openxml/python-docx/files/4601396/originaltemplate-saved.docx)

here are the files

**Comment by scanny** [comment]
An empty file contains a single empty paragraph. So you have to populate the first paragraph first, and only then start adding paragraphs.

**Comment by wrong1man** [comment]
> An empty file contains a single empty paragraph. So you have to populate the first paragraph first, and only then start adding paragraphs.

Hey! Thanks for the reply. So how would you add an image?
And why does making a template via google docs yields a different result?

**Comment by wrong1man** [comment]
well just replying to myself now, in case anyone else lands here, scanny's explanation allowed me to find this command - `document._body.clear_content()` which clears the first paragraph (and well anything else on the body so carefull with it).
