### ISSUE TITLE
[question] Can't find page breaks in an existing document

### ISSUE THREAD

**Issue by giuliohome** [python-openxml/python-docx#823]
I've tried to open an existing docx with the following code:

```
from docx import Document
document = Document('Testme.docx')
sections = document.sections
for section in sections:
    print(section.start_type)
paragraphs = document.paragraphs
for paragraph in paragraphs:
    for run in paragraph.runs:
        print(run.text)
        if hasattr(run, 'breaks'):
            for br in run.breaks:
                print(br.type.__name__)
```
The document has 3 pages (and here I mean 2 **manual** page breaks) but I can only see the initial `NEW_PAGE (2)` from the output.
Which is the correct show to find the page breaks?

**Comment by giuliohome** [comment]
I've found [this answer](https://stackoverflow.com/a/55691833/11323942). 
It does the trick. Is it the correct way?

**Comment by giuliohome** [comment]
It's also strange that if I code
```
for paragraph in paragraphs:
    print("paragraph format")
    print(paragraph.paragraph_format.page_break_before)
```
it outputps `None` even for paragraphs after a manual page break! Is it a bug?

**Comment by giuliohome** [comment]
Notice that under the [Breaks documentation](https://python-docx.readthedocs.io/en/latest/dev/analysis/features/text/breaks.html?highlight=run) in readthedoc, under C[andidate protocol – run.add_break() ](https://python-docx.readthedocs.io/en/latest/dev/analysis/features/text/breaks.html?highlight=run#candidate-protocol-run-add-break)
it loooks like one could do 
```
>>> run.breaks
[<docx.text.Break object at 0x10a7c4f50>]
```
while instead it is not an attribute, see the real effect:
```
>>> run.breaks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Run' object has no attribute 'breaks'
```

**Comment by giuliohome** [comment]
Quite amazing that you close it without even writing a word of comment.
Of course this is a software to avoid.
Let me unsubscribe from it immediately

**Comment by scanny** [comment]
@giuliohome didn't mean to be abrupt, just clearing out resolved issues and this one hasn't had any action for several months. Your solution looks fine and looks like it works for you. The document you refer to is a design document and may contain ideas for features that have not yet been added.
