### ISSUE TITLE
</w:smartTag>

### ISSUE THREAD

**Issue by fenccliuhua** [python-openxml/python-docx#825]
def opendocx(files):    #打开文件
    document = Document(files)
    fdata = document.element
    # print(document.paragraphs)
    # print(document.tables)
    # print(document.styles)
    # for i in fdata.xpath('w:body/*'):
    for i in document.paragraphs:
        print(i.text)
[02.docx](https://github.com/python-openxml/python-docx/files/4625962/02.docx)

文档中的w:smartTags标签内容在索取段落文本时，内容丢失。

**Comment by XieXiaofei901210** [comment]
我也遇到同样的情况，怎么解决？

**Comment by gaineleanor** [comment]
你好 可以尝试此方法. 

from docx import Document
files = r'C:\Users\xxx\Desktop\python-docx-lmxl\02.docx'
docx = Document(files)
for k in docx._element.body.xpath('w:p'):
    print(''.join([x.text for x in k.xpath('descendant::w:r')])) # descendant::w:r 选取所有当前节点的子孙元素中包含w:r的节点
    # for x in k.xpath('w:r | w:smartTag/w:r'):    或者指定选取
![捕获](https://user-images.githubusercontent.com/59348227/90852331-bd1d1780-e3a9-11ea-9bfd-698a52e6ca73.JPG)
