### ISSUE TITLE
How can I read the special Special characters in .docx?

### ISSUE THREAD

**Issue by LYU2026** [python-openxml/python-docx#826]
relate to Feature: Add Bookmark [#425](https://github.com/python-openxml/python-docx/issues/425)
such as 
'''
 xxxx   #corss or stick in box
 xxxx   #blank box
'''
the font is "Wingdings 2" 
![image](https://user-images.githubusercontent.com/45093086/82655264-81609d80-9c54-11ea-91e3-c7b80662c5f8.png)

 how can I know which sentence is marked? thanks

**Comment by LYU2026** [comment]
I had try .run .font  .style, but failed

**Comment by LYU2026** [comment]
copy the charater to notepad++, it read as '0'(blank box) and '1'(corss in box).

**Comment by LYU2026** [comment]
Look! It's a  widget like checkbox

**Comment by zhuwansu** [comment]
> Look! It's a widget like checkbox
i have the same problem with you , can you tell me how can i solve it ? thank you very much~!   @LYU2026

**Comment by zhuwansu** [comment]
my characters like this :
þ智联   þ前程无忧  ☐猎聘  ☐拉钩网  BOSS直聘  ☐其它网站       
and i want get the special symbol checkbox that checked or not,  @LYU2026

**Comment by LYU2026** [comment]
> my string like this :
> þ智联 þ前程无忧 ☐猎聘 ☐拉钩网 BOSS直聘 ☐其它网站
> and i want get the special symbol checkbox that checked or not, @LYU2026

**Comment by LYU2026** [comment]
you can copy the character to a new blank .docx, then read the file with python-docx,  convert the paragraph to xml-dict and you will find some good idea. 
such as [https://github.com/python-openxml/python-docx/issues/425](url)
