### ISSUE TITLE
MSOffice detects docx files as corrupted when i used append in Docx

### ISSUE THREAD

**Issue by RkParuchuri1142** [python-openxml/python-docx#829]
Am new to python and trying to merge the two or more files by using the below code.
With this code am able to merge the documents into one and save it as combined_document.docx.
How ever when i tried to open this file, getting error as 
"We're Sorry. We can't open combined_document.docx because we found a problem with its contents."
Can  anyone guide me to overcome this?
My code is:

from docx import Document

files = ['form1.doc']
def combine_doc(files):
      combined_document = Document('Default_Template.docx')

     for index, file in enumerate(files):
               sub_doc = Document(file)
               for element in sub_doc.element.body:
                     combined_document.element.body.append(element)
    combined_document.save('combined_document.docx')
combine_doc(files)

**Comment by scanny** [comment]
Your code does in fact corrupt the files, so this is the expected behavior.

**Comment by thomas-massey** [comment]
Could you elaborate please? I presume changing the raw data would change hashes etc so it doesn't appear safe, what would the fix be?
