### ISSUE TITLE
Cell merging is slow

### ISSUE THREAD

**Issue by Hassan-Akhlaq** [python-openxml/python-docx#830]
i have been merging cells row wise in multiple table and it takes about 1 second to merge a row containing 20 cells using this "row.cells[0].merge(row.cells[-1])". i am merging upto 50 rows in whole doc. which makes it upto 1 min . is there any faster way? 
here are some functions i am using. 
calling text_rows funtion 5 times  with count =10 in whole process. like so

` text_rows(table,10)`

```python
def insert_rows_for_data(table, row_count):
    strt_point = len(table.rows)
    col_count = len(table.columns)
    for i in range(row_count):
        table.add_row()

    table_cells = table._cells
    return strt_point, col_count, table_cells


def text_rows(table, count, text=None, align=True, color=None):
    starting, col_count, table_cells = insert_rows_for_data(table, count)
    for index, x in enumerate(range(count)):
        empty_row = table_cells[starting * col_count : (starting + 1) * col_count]
        empty_row[0].merge(empty_row[-1])
        if text:
            empty_row[0].text = text
        if align == True:
            align_cell(empty_row[0])
        if color:
            add_custom_color(empty_row[0], color)
        starting += 1
```

**Comment by scanny** [comment]
I can't read your code. Can you format it properly? And indicate how many times you're calling what method in your overall process.

**Comment by Hassan-Akhlaq** [comment]
updated!

**Comment by scanny** [comment]
Reduce your calls to `table._cells` to the absolute minimum. Preferably zero, possibly getting the Row object returned by `table.add_row()` and calling `row.cells`, again though the minimum number of times (perhaps once per row).

**Comment by Hassan-Akhlaq** [comment]
thanks this helps.
