### ISSUE TITLE
 Read with special characters

### ISSUE THREAD

**Issue by jrujanodlegal** [python-openxml/python-docx#832]
Trying to read with special characters does not load the lines correctly

line: `En <<city>> a <<date1>>, entre <<company1>>, dni <<dni>> y <<company2>>,`

```
doc = Document(destination_uri)
for p in doc.paragraphs:
    for run in p.runs:
      print(run.text)
```
expected result: `En <<city>> a <<date1>>, entre <<company1>>, dni <<dni>> y <<company2>>,`

current result:

```
En <<city>> a <<date1>>,
 
entre <<company1>
>, 
dni
 <<dni>> y <<company2>>, 

```

**Comment by scanny** [comment]
This is the expected behavior. Runs break on arbitrary boundaries; they do not necessarily hold whole words or phrases.
