### ISSUE TITLE
Bitmap text when fonts may not be embedded

### ISSUE THREAD

**Issue by sgrumel** [python-openxml/python-docx#833]
I'm going to save a docx to pdf file:

doc = word.Documents.Open(input_file)
doc.SaveAs(output_file, FileFormat=17)

If a do the same action by simple using the "File > SaveAs > .pdf" on Microsoft Word i actually have to remove the flag "Bitmap text when fonts may not be embedded" (inside the pdf format option) in order to generate a text-searchable pdf file (See attached image).

![Img1](https://user-images.githubusercontent.com/66800718/84438517-f6613a80-ac36-11ea-873c-55be418424ab.jpg)

Is there a way to do the same operation (removing the flag) by python-docx?

**Comment by scanny** [comment]
No, not currently.
