### ISSUE TITLE
PyPI release incorrect for 0.8.10

### ISSUE THREAD

**Issue by 00willo** [python-openxml/python-docx#834]
Hi @scanny,

Thanks for you open source effort with this package.  As mentioned in #619 the package uploaded to PyPI  doesn't have the code contained with the 0.8.10 tag (11Jun19) )on github. It appears as through when 0.8.9 was tagged and released (09Jan19), another commit on the same day was done in preparation for 0.8.10, and it was accidentally uploaded at that time.  PyPI shows both versions (0.8.9 and 0.8.10) landed on 09Jan19, before the 0.8.10 tag was made on github.

As the other ticket was closed, just raising a new ticket to cover this, and bring it to the forefront. Thanks.

**Comment by scanny** [comment]
Fixed in release v0.8.11 on May 15, 2021.
