### ISSUE TITLE
Issue with accessing the fontname and size

### ISSUE THREAD

**Issue by gayam** [python-openxml/python-docx#837]
Hi,

I was trying to read the font name and size from run and it is inconsistent across fonts. It worked with Arial font but when I changed the font to Times New Roman, the output was None. The font size was always None. Is there any other to read font details from the source document?

```
from docx import Document
src_document = Document('Test.docx')

for paragraph in src_document.paragraphs:
	for run in paragraph.runs:
		print(run.font.name, run.font.size)
```

**Comment by ganguo-li** [comment]
I suggest you refer to the website ——https://python-docx.readthedocs.io/en/latest/api/text.html#run-objects.
The document mentions that none indicates the typeface is inherited from the style hierarchy.

**Comment by gayam** [comment]
> I suggest you refer to the website ——https://python-docx.readthedocs.io/en/latest/api/text.html#run-objects.
> The document mentions that none indicates the typeface is inherited from the style hierarchy.

I tried that option too. The style in both the source and the newly created document are same. But the font are not.
Both the styles are Default Paragraph font and font name are size are set to None.

```
from docx import Document
src_document = Document('Test.docx')
trg_document = Document()

for paragraph in src_document.paragraphs:
	trg_para = trg_document.add_paragraph()
	for run in paragraph.runs:
		run1 = trg_para.add_run(run.text)
		run1.font.name = run.font.name
		run1.font.size = run.font.size
		print(run.style.name, run.font.name, run.font.size)
		print(run1.style.name, run1.font.name, run1.font.size)

trg_document.save('font_result.docx')
```
