### ISSUE TITLE
Understanding insert_element_before

### ISSUE THREAD

**Issue by PyTomE** [python-openxml/python-docx#839]
Without going in all details, I am currently trying to create a template for reporting which contains all the tables, paragraphs, sections, and (empty) pictures which will be read by python-docx. Now, I will - for a start - copy a paragraph from one location to another. Thus, for instance, create a paragraph after (or before) another using all the content and style of the one in action.

So, I read a lot and tried to understand lxml, etree, and of course python-xml.
Where I ended up was this little function

```
def copy_before_paragraph(p,insert):
    """
    Return a newly created paragraph, inserted directly before this
    paragraph using the template from "insert"
    """
    templ = deepcopy(insert)
    newp = p._p.insert_element_before(templ)
    return Paragraph(newp, p._parent)

p13=mydoc.paragraphs[13]
p14=mydoc.paragraphs[14]
copy_before_paragraph(p13,p14._p)
```

which works - somewhat - and not at the same time.
Looking at the result, the content of p14 is added *after* p13 and it is in the same paragraph!
So, looking at the xml of p13 I see:

```
<w:p xmlns:w=....>
  <w:pPr>
    ...
  </w:pPr>
  <w:r>
    ... text of p13
  </w:r>
  <w:p w:rsidR="00FF4FE6" w:rsidRDefault="00FF4FE6" w:rsidP="00FF4FE6">
    ... content of p14
  </w:p>
</w:p>
```

Interestingly this works, but it is obviously wrong.
So, how can I really add before the paragraph p13 in the way I want to do that?

Any help very appreciated.

And of course: great package! Thanks

**Comment by scanny** [comment]
Try something like this:

```python
def copy_paragraph_before(anchor_paragraph, source_paragraph):
    """Return copy of `source_paragraph`, inserted directly before `anchor_paragraph`."""
    new_p = deepcopy(source_paragraph._p)
    anchor_paragraph._p.addprevious(new_p)
    return Paragraph(new_p, anchor_paragraph.parent)

anchor_paragraph = mydoc.paragraphs[13]
source_paragraph = mydoc.paragraphs[14]
copy_paragraph_before(anchor_paragraph, source_paragraph)
```

**Comment by PyTomE** [comment]
Perfect! It is working, just a small typo in the return. It should be
```python
    return Paragraph(new_p, anchor_paragraph._parent)
```
Thanks a lot

**Comment by PyTomE** [comment]
closed
