### ISSUE TITLE
Identifying Table Styles

### ISSUE THREAD

**Issue by gayam** [python-openxml/python-docx#840]
I am trying to replicate tables from source document to a new doc. I had issues with replicating the table styles in the new document. It works if the table style is grid but for other it doesn't.

```
from docx import Document
src_document = Document('Table Test.docx')
trg_document = Document()

for table in src_document.tables:
	print(table.style.name)
	new_table = trg_document.add_table(len(table.rows), len(table.columns), table.style)
	print(new_table.style.name)

trg_document.save('table_result.docx')
```

When I use "Table Grid" style it works as expected, but when I use a different style it doesn't work. For example, if I use "Table Contemporary" in the source document, the output of the first print statement is "Table Contemporary", but the output of the second print statement is "Normal Table", which is the default.

Why does this work with one table type but not with others?

**Comment by ccellado** [comment]
There is a problem with table styles - different office suites show styles that are not only embedded in the doc.

The way to find what styles reside in the file :
```
or item in document.styles:
     print(item)
```
You'll see what styles exactly the document has.
To add a new one I've installed MS Office 2019 , and embedded it inside document.
Other office suites wont allow or wont work with table styles altogether.
