### ISSUE TITLE
Add hyperlink pointing to a heading

### ISSUE THREAD

**Issue by arun-kol** [python-openxml/python-docx#846]
Is there any way a block of text can be hyperlinked to a heading? Similar to the navigation in docx. Clicking the hyperlink will take you to the heading.

**Comment by BayooG** [comment]
you mean like inserting a reference somewhere in the document and clicking on it would take you to some other place in the document?

**Comment by arun-kol** [comment]
Yes, that would be the aim. I am specifically looking to link to a heading that is generated by add_heading() function, but a generic solution would also work.

**Comment by BayooG** [comment]
once I was working on something similar

first, you have to add a bookmark to the paragraph (heading paragraph in your case)
`
def add_bookmarkStart(paragraph, _id):
    name = '_Ref_id_num_' + _id
    start = OxmlElement('w:bookmarkStart')
    start.set(qn('w:name'), name)
    start.set(qn('w:id'), str(_id))
    paragraph._p.append(start)
    return name
`

then you should create another paragraph in a way like this
`
def append_ref_to_paragraph(paragraph, refName, text = ''):
    # run 1
    run = paragraph.add_run(text)
    r = run._r
    fldChar = OxmlElement('w:fldChar')
    fldChar.set(qn('w:fldCharType'), 'begin')
    r.append(fldChar)
    # run 2
    run = paragraph.add_run()
    r = run._r
    instrText = OxmlElement('w:instrText')
    instrText.text = 'REF ' + refName + ' \h'
    r.append(instrText)
    # run 3
    run = paragraph.add_run()
    r = run._r
    fldChar = OxmlElement('w:fldChar')
    fldChar.set(qn('w:fldCharType'), 'end')
    r.append(fldChar)
`
you can give this paragraph any style you like (hyperlink, etc..)
and when you ctr+right click on this paragraph it should take you to the heading paragraph

**Comment by shabbir-zinnox** [comment]
Can i have an example of this? i am creating a document, where on click on heading number the document to should display the the paragrah. I have been looking for this since months
