### ISSUE TITLE
Docx missing line number

### ISSUE THREAD

**Issue by YC-wind** [python-openxml/python-docx#847]
```
document = Document(path)
texts = [paragraph.style.name+paragraph.text for paragraph in document.paragraphs]
```
when text has line number,  but docx can not return.

**Comment by BayooG** [comment]
maybe try getting the text this way
`def get_text(paragraph):
       allRuns = [Run(r, paragraph) for r in paragraph._p.xpath('.//w:r[not(ancestor::w:r)]')]
        return u"".join([r.text for r in allRuns])`
instead of `paragraph.text`

**Comment by YC-wind** [comment]
how can i use `Run(r, paragraph)`

**Comment by BayooG** [comment]
you can import it like this
`from docx.text.run import Run`

**Comment by YC-wind** [comment]
sorry, it not works

**Comment by BayooG** [comment]
try:
`Run(r, paragraph._p)`

**Comment by BayooG** [comment]
@YC-wind 
try:
`Run(r, paragraph._p)`
