### ISSUE TITLE
Apply multiple styles within a single paragraph or sentence

### ISSUE THREAD

**Issue by dgonzo27** [python-openxml/python-docx#851]
I am consuming a word doc as a template, then when a user downloads the document, certain fields in that document are populated with some user data.  The problem is when I am trying to add character styling to specific runs within a paragraph:

    para.add_run(some_value, style='black-char-style')
    para.add_run(next_value, style='red-char-style')

I even tried to insert a paragraph before:

    para.insert_paragraph_before(some_value, style='black-paragraph')
    para.insert_paragraph_before(next_value, style='red-paragraph')
    para.clear()

Another take:

    para.insert_paragraph_before(some_value, style='black-paragraph')
    para.clear # or para.text = ''
    para.add_run(next_value, style='red-char-style')

The result is either all black text or all red text, depending on which is set first.  This is similar to the open issue in regard to splitting runs.  I wrote my own functions to handle parsing out the strings I'm looking to add as a run, and it does so successfully, but the issue comes in styling.

Any suggestions, remediations, or upcoming class-based/api functions that allow for multiple styles to be set within a paragraph or sentence?

**Comment by dgonzo27** [comment]
@aliciaogolla Just so you can reference that we are trying to get this resolved

**Comment by brasky** [comment]
Are "red-char-style", "black-char-style", etc themes?

What has worked for me in the past is the following:
```python
from docx import Document
from docx.shared import RGBColor

document = Document()
document.add_paragraph().add_run("This run will be red").font.color.rgb = RGBColor(100,0,0)
document.add_paragraph("This paragraph will be the default color, so black probably")
document.save("yourdoc.docx")
```

Does this answer your question? From what I understand you're trying to add text with different colors and this should do that. Modifying an existing document to change the color is more complicated since I think that run.font is a read-only object.

**Comment by dgonzo27** [comment]
@brasky Yeah unfortunately my only use case is to modify existing documents to change the color of text.  Essentially, a user should be able to upload a templated word document with empty fields and certain highlights to bring attention to what information needs to be completed upon downloading that template.  I am able to use “{{“ as if it were a django form to dynamically replace data upon downloading, however there are additional fields that don’t correlate to data being pulled from a db model.  In those cases, I wanted the text to be highlighted in red so that the downloader knows where to update the form. 

To achieve this, I used a similar string manipulation method that I was using with the “{{“.  So I would build a template word document with “$$”around the text that should be red”$$”.  Upon a user downloading the document, just as I search and replace curly braces with django data, I updated the character styling of strings to be replaced with red text.  But upon doing so, the entire paragraph is styled in red text, not the specific characters, even when I defined it to be a character style.

I wasn’t able to find a workaround so I built a microservice application to handle smart reporting and export the final result as a PDF opposed to word docs, but the flexibility would still be nice to have in the future if there were an accurate way to modify character styling that didn’t apply to an entire paragraph

**Comment by abubelinha** [comment]
@dgonzo27 a bit late but maybe your `'black-char-style'` and `'red-char-style'` where defined as [paragraph styles](https://python-docx.readthedocs.io/en/latest/api/style.html#docx.styles.style._ParagraphStyle) instead of [character styles](https://python-docx.readthedocs.io/en/latest/api/style.html#docx.styles.style._CharacterStyle)?
