### ISSUE TITLE
table cell text return ‘’ when cell text are hyperlinks

### ISSUE THREAD

**Issue by heartacker** [python-openxml/python-docx#856]
as the picture
![image](https://user-images.githubusercontent.com/1876302/90592511-53b9cf00-e218-11ea-9f72-7227d917472c.png)

cell.text return ''

 (DRS-PLL - 1.1 is ok)

What did I do wrong?
is there any way to read the text `DRS-PLL - 1.2`
THANKS

**Comment by br-rkdrnf** [comment]
https://github.com/python-openxml/python-docx/pull/842
Currently, hyperlinks are not included in `text` property. You should manually inspect child elements of a `paragraph` element to see if there's a hyperlink.
