### ISSUE TITLE
Changing line spacing for one table changes it in all tables

### ISSUE THREAD

**Issue by samrickman** [python-openxml/python-docx#867]
Hi,

Firstly, thanks for creating python-docx. It is really awesome.

I am having some issues with a document that has 13 tables. Specifically, when I change the line spacing for one table, it changes it for all of them. Here is a minimal example:

```python
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_LINE_SPACING
document_path = "../../../Daily Reports/Reports/For MIR CT/15_09_2020_Report_CT/15_09_2020_MIRReport_CT_v5.docx"
doc = Document(document_path)
for index, table in enumerate(doc.tables):
    print(index, table.style.paragraph_format.line_spacing)
```

Output:

```
0 1.0
1 1.0
2 1.0
3 1.0
4 1.0
5 1.0
6 1.0
7 1.0
8 1.0
9 1.0
10 1.0
11 1.0
12 1.0
```

I want to change the line spacing for table 3, and only table 3. However, when I do this:

```python
table = doc.tables[3]
table.style.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
table.style.paragraph_format.line_spacing = Pt(7)

for index, table in enumerate(doc.tables):
    print(index, table.style.paragraph_format.line_spacing)
```

Output:

```

0 88900
1 88900
2 88900
3 88900
4 88900
5 88900
6 88900
7 88900
8 88900
9 88900
10 88900
11 88900
12 88900
```

You can see it has changed the line spacing for all of the tables - they are all now 7 pt (12 point is 152400).

Is this a bug or am I doing something wrong?

**Comment by scanny** [comment]
A _style_ is like a formatting template that you set up once and then apply to as many document objects as you want to get consistent formatting. Every object with that style applied gets that same set of formatting settings. When you adjust the table style (which all the tables appear to be sharing) you get exactly the result you're seeing.

I think what you want to be doing is setting the paragraph line spacing directly on the paragraphs only on the table in question. You could possibly set up a new paragraph style and just apply that to those paragraphs if you wanted.

**Comment by samrickman** [comment]
Aha! This makes total sense. Thank you!
