### ISSUE TITLE
dox c not working

### ISSUE THREAD

**Issue by jamir888** [python-openxml/python-docx#871]
whenever i rung this code
import docx
mydoc = docx.Document()

item = {"Maling":["melon jam 300gram", "34aed"], "nescafe":["3 in 1 coffee", "20 aed"]}

for i in item:
    mydoc.add_paragraph(i)
    for j in item[i]:
        mydoc.add_paragraph(j)

mydoc.save('demo.docx')

it shows issue like show below.
mydoc = docx.Document() AttributeError: module 'docx' has no attribute 'Document'

**Comment by scanny** [comment]
make sure you don't have the `docx` package installed:

```bash
$ pip uninstall docx python-docx
$ pip install python-docx
```

Also make sure there is no Python file named `docx.py` in the directory you're running from or a `docx/` directory with an __init__.py file in it either. Choose a different name for the project.

**Comment by jamir888** [comment]
I installed pip3 install python-docx but still show error 

mydoc = docx.Document() AttributeError: module 'docx' has no attribute 'Document
