### ISSUE TITLE
how can i change the font of result displayed in word and i want to change it writes from right alignment

### ISSUE THREAD

**Issue by jamir888** [python-openxml/python-docx#872]
import docx
mydoc = docx.Document()

price = {"Maling":["Melon Jam 300gram", "34aed"], "Nescafe":["3 in 1 coffee", "20 aed"]}

for i in price:
    mydoc.add_paragraph(i)
    for j in price[i]:
        mydoc.add_paragraph(j)
        mydoc.add_run.bold= True

mydoc.save('demo.docx')

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag
(https://stackoverflow.com/questions/tagged/python-docx). This issues list is reserved
for suspected bugs and feature requests.
