### ISSUE TITLE
inserting math equation, advanced list dealing with python-docx

### ISSUE THREAD

**Issue by evgeny123456** [python-openxml/python-docx#874]
Hi python-docx, python-pptx community, @scanny,

It is not the platform for this, but I would like to ask for help & advice ( nobody replied on stack-exchange on similar questions).

- [ ] Problem:

 I am having issues on making nice script that allows to update results of some research in a 30+pages word file with formulas, figures, tables, etc.. Word file has mostly static text, and some parts of the document where figures, numbers will be updated after the script run.

- [ ] What I ask for:

some advise/mentorship from more experienced users of python-docx on **how to add convenient dealing with mathematical formulas, advanced lists** & **how to architecture big program to do auto-update of the word file** with static and dynamic blocks. 

As a side thing, _I would be happy to add to python-pptx new features along the way to enrich these libraries._ 

Thanks a lot!

**Comment by scanny** [comment]
@evgeny123456 Unfortunately the feature set of `python-docx` represents only a portion of what can be done in the Word format and it's very likely to stay that way. There is no current support for the features you mention and may never be. If you want these capabilities in Python you'll likely have to build them yourself. An alternative would be to use a Microsoft library and VBA or C# or perhaps something in the LibreOffice libraries that may have support for these.
