### ISSUE TITLE
Docx table specific cell has text, but python-docx gets an empty string for it

### ISSUE THREAD

**Issue by rafaelgp23** [python-openxml/python-docx#876]
Hi,

Could you please help me understand why python-docx is unable to return the actual text inside the table cell (#CH2KEY#), from the docx file below?
[Release_Notes.docx](https://github.com/python-openxml/python-docx/files/5329153/Release_Notes.docx)

```
from docx import Document
filepath = r'Release_Notes.docx' 
document = Document(filepath)

for table in document.tables:
...     for row in table.rows:
...         for cell in row.cells:
...             for paragraph in cell.paragraphs:
...                 print(paragraph.text)
```

Output:        

> Tracking #
> Summary
> #CH1KEY#
> #CH1DESC#
> 
> #CH2DESC#
>

**Comment by scanny** [comment]
Print out the XML for that cell and see what is there:

```python
print(cell._tc.xml)
```

Usually this happens because the text is wrapped in some sort of container element, often a pending revision.

**Comment by rafaelgp23** [comment]
Here's the output for #CH2KEY# cell._tc.xml:

> <w:tc xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns:cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns:cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns:cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns:cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns:cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns:cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns:cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns:cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape">
>   <w:tcPr>
>     <w:tcW w:w="3210" w:type="dxa"/>
>     <w:tcBorders>
>       <w:top w:val="single" w:sz="4" w:space="0" w:color="auto"/>
>       <w:left w:val="single" w:sz="4" w:space="0" w:color="auto"/>
>       <w:bottom w:val="single" w:sz="4" w:space="0" w:color="auto"/>
>       <w:right w:val="single" w:sz="4" w:space="0" w:color="auto"/>
>     </w:tcBorders>
>     <w:tcMar>
>       <w:top w:w="40" w:type="dxa"/>
>       <w:left w:w="40" w:type="dxa"/>
>       <w:bottom w:w="40" w:type="dxa"/>
>       <w:right w:w="40" w:type="dxa"/>
>     </w:tcMar>
>     <w:vAlign w:val="bottom"/>
>   </w:tcPr>
>   <w:p w:rsidR="00E929D7" w:rsidRPr="00BA6D15" w:rsidRDefault="00E929D7" w:rsidP="002F0113">
>     <w:pPr>
>       <w:spacing w:before="120" w:after="120"/>
>     </w:pPr>
>     <w:hyperlink r:id="rId4" w:tgtFrame="_blank" w:history="1">
>       <w:r>
>         <w:t>#CH2KEY#</w:t>
>       </w:r>
>     </w:hyperlink>
>   </w:p>
> </w:tc>

**Comment by rafaelgp23** [comment]
It seems there is fragments of hyperlink there, is that what is causing the problem?

**Comment by rafaelgp23** [comment]
Also is there anything simple to add on those for loops to avoid this kind of problem? I need something to at least raise an Exception if this happens again.

**Comment by scanny** [comment]
Yes. Get rid of the hyperlink and you should be good to go.

Something like `if paragraph._p.xpath(".//w:hyperlink"):` might do the trick. You'd have to experiment if that doesn't work as is, perhaps to get the xpath expression right.
