### ISSUE TITLE
memory problems

### ISSUE THREAD

**Issue by Link-Go** [python-openxml/python-docx#880]
Dears:
      when I use docx.Document to open a docx which size is approximately 3mb in linux, and I found about 1.5G memory is used.
      anyway to reduce the memory ? 
      thanks a lot !

**Comment by scanny** [comment]
You'll have to profile further to find out more specifically where the memory is going. A multiple of 500 sounds like a lot. Might be worth starting with an empty file and see how much that takes up. In any case, we haven't heard of any memory consumption problems so you'd have to identify the cause more closely before this would be actionable.
