### ISSUE TITLE
image_part.filename is not fetching correct name of the image name

### ISSUE THREAD

**Issue by sanyoggupta** [python-openxml/python-docx#882]
I would like to fetch the file name of the inline image from word document and use following code: from docx import Document

from docx import Document

doc = Document('sample_DoubleCheck.docx')

rId=[]

for s in doc.inline_shapes:    
 blip = s._inline.graphic.graphicData.pic.blipFill.blip   
 rId.append(blip.embed)
    

document_part = doc.part
image_part = document_part.related_parts[rId[0]]
print(image_part.filename)
However the output coming as 'image.jpeg' but when I check in the media folder of the word file after unzipping the file. The name of the file is 'image1.jpeg'.

**Comment by sanyoggupta** [comment]
Seeking a help here. Please suggest where I am goofing...

**Comment by scanny** [comment]
Partname ("image1.jpeg") and image filename ("image.jpeg") are different things. Partname is always a name of the form `image{n}.{ext}`. The image filename is either the original filename if it's available or the default `image.{ext}`.

The image filename is not always available. If a picture is inserted from a file, PowerPoint will retain that file-name. But if it originates from a copy/paste operation, there is no file involved to get a filename from and the image filename is set to the default `image.{ext}` where `ext` is based on the image type (jpeg, png, etc.).
