### ISSUE TITLE
Enhancement: extending inerface to odt.

### ISSUE THREAD

**Issue by ntala** [python-openxml/python-docx#885]
Your tool is great ! Thann you for all the work done.
I am desperately looking for a module like yours for odt files.

Is there any whil to implement the same interface for opendocumenformat documents ?

**Comment by scanny** [comment]
Sorry @ntala I don't know of any and we don't have any plans to build one.

**Comment by buhtz** [comment]
But isn't "docx" OpenDocument?
Of course Microsoft did modified it to create incompatibility with LibreOffice & Co but theoretically isn't this the same format spec?
