### ISSUE TITLE
Question: Using the BableFish ... German

### ISSUE THREAD

**Issue by 42sol-eu** [python-openxml/python-docx#886]
We do have some troubles with german language and docx.

Is the BableFish class implemented for multi language usage?
Or is it only prepared.

I am thinking about a pull request to add german naming in a way that more languages could be added.

(the german incarnation of Word behaves odd anyway by no german umlauts or even spaces)

If there is already an implementation that might be used.  I am open to go this way

Cheers
 Felix

**Comment by scanny** [comment]
No, that class has no multi-language support. You should be able to set that up for your own purposes by assigning a different tuple of pairs to `BabelFish.style_aliases`, perhaps something like:

```python
BabelFish.style_aliases = (
    ("Heading 1", 'heading 1'),
    ...
)
```

**Comment by 42sol-eu** [comment]
thanks. that sounds good 

we did some experiments on changing formats and had seemingly an effect that could write styles to style.xml without adding and deleting styled pagraphs to the document. I will investigate further on that.
