### ISSUE TITLE
Find a table based on the position of a paragraph

### ISSUE THREAD

**Issue by FredEPr** [python-openxml/python-docx#887]
I have a document with the following format:

Unknown content
Paragraph with unique name
Table
Unknown content
Paragraph with unique name
Table
Unknown content

I know the unique names and would like to get the tables following them. Something like a method: def GetTableFromName(paragraphName: str) -> Table:

Is this possible with python-docx?
I know I can iterate through document.paragraphs to find the paragraphs but I have no idea how to guess a position in document.tables based on this information.

**Comment by scanny** [comment]
have a Google on `python-docx iter_block_items` and you'll see some prior art on accessing document "block" items (paragraphs and tables) in document order. This should give you the ability to detect the right tables.

**Comment by FredEPr** [comment]
Looks like it will do the trick. Thank you!

**Comment by FredEPr** [comment]
I used the method you gave [here](https://stackoverflow.com/questions/43637211/retrieve-document-content-with-document-structure-with-python-docx) and it worked fine.

**Comment by scanny** [comment]
Glad to hear it @FredEPr :)
