### ISSUE TITLE
Detect Corrupt .docx file

### ISSUE THREAD

**Issue by tarun9450** [python-openxml/python-docx#894]
Hi all, 

Can you please help me i figuring this out.
While reading a .docx file from python-docx (docx.Document(file_name)), how can I detect if the docx file is correct or corrupt.

I've seen cases where these input docx files are either empty or corrupt.
How can I flag these cases using this library.

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag
(https://stackoverflow.com/questions/tagged/python-docx). This issues list is reserved
for suspected bugs and feature requests.

There is no current support for this in `python-docx`. The only reliable way I've found to detect this is by opening the file using Word. Also note that a given file may open in say, LibreOffice but not in Word or GoogleDocs. The acceptance/repair criteria is specific to the client and is not described in the .docx file spec.
