### ISSUE TITLE
Converting floating anchored table to an inline table

### ISSUE THREAD

**Issue by alllexx88** [python-openxml/python-docx#896]
Hello! I'm having an issue with an OCRed document produced by FineReader Engine 12 ([SUFER_.docx](https://github.com/python-openxml/python-docx/files/5598802/SUFER_.docx)). FRE created the first table in the docx as some kind of a floating anchored object, hence it's missing from the document `tables`, and I can't properly process it with python-docx. Since I can't find the option for FRE to not behave in this way, I'm wondering if there is a way to do the conversion on python-docx/xml level?

TIA,
Alex

**Comment by scanny** [comment]
@alllexx88 floating objects (tables, images, etc.) are not supported in `python-docx` and there are no current plans to add it.
