### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by TheCrott** [python-openxml/python-docx#897]
Hi maintainers

I would like to integrate the project into [OSS-fuzz](https://github.com/google/oss-fuzz). This is a free service by Google where they perform continuous fuzzing of open-source projects used by industry and with the only expectation that maintainers of the project will patch the bugs found by OSS-Fuzz.

[Atheris](https://github.com/google/atheris) will be used to fuzz this project. [Atheris](https://github.com/google/atheris) is a python-based fuzzer created by Google.
If you are interested in this, could you please provide me with an email address that will be receiving the bug reports that Atheris find?

Aldo

**Comment by scanny** [comment]
@TheCrott, thanks for reaching out, we have no interest in this at present but will keep it in mind :)
