### ISSUE TITLE
Google Docs incorrectly displays table with "Table Grid" style

### ISSUE THREAD

**Issue by kajojify** [python-openxml/python-docx#898]
Hello guys! Thanks for the nice package. 

OS: Ubuntu 18.04
Package version: python_docx-0.8.10

Steps to reproduce:
1. Take the example script from https://python-docx.readthedocs.io/en/latest . 
2. Get rid of `document.add_picture('monty-truth.png', width=Inches(1.25))` line and add
`table.style = "Table Grid"` right under `table = document.add_table(rows=1, cols=3)`. 
Run the script to produce demo.docx. 
3. Open your Google Drive and upload demo.docx.
4. Google drive thumbnail is ok:
![image](https://user-images.githubusercontent.com/20267977/100356310-b67eeb80-2ffb-11eb-97eb-70fb6c55e134.png)

5. But then open the file using Google Docs and see some weird table style set by Google Drive:
![image](https://user-images.githubusercontent.com/20267977/100356551-0d84c080-2ffc-11eb-955f-0e9713518461.png)

In the meanwhile, if I open demo.docx in LibreOffice, everything is displayed ok.
What is wrong with the style? Or maybe this is some bug on Google Docs side? 
Thanks.

**Comment by kajojify** [comment]
Upd: Windows wordpad displays correctly.

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag
(https://stackoverflow.com/questions/tagged/python-docx). This issues list is reserved
for suspected bugs and feature requests.

I expect this is related to Google Docs not having the `TableGrid` table-style in its default document. Make sure you read and understand the documentation on styles on this page and the one following it in the documentation:
https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html
