### ISSUE TITLE
How do i set table style

### ISSUE THREAD

**Issue by keithsun80** [python-openxml/python-docx#9]
Hi scanny.

How do i set table style?

When i using 

```
document.add_table(rows=len(table_data), cols=len(table_data[0]),style="TableGrid")

```

I search the API , but i didn't find method do it, I need set table size and width and height and color and so on.

"Cell class" also didn't find any method support it.

**Comment by aslam-vs** [comment]
I want to change font size of table content. I tried lots.

**Comment by TomTrogh** [comment]
It seems the font of the previous paragraph is reused (which is a problem from Word itself). I used this not-so-beautiful workaround:

- add a paragraph
- set its font size
- remove the paragraph

Then, the next table will have the deleted paragraph's font size.

Code:
```
doc.add_paragraph('')
paragraph = doc.paragraphs[-1]
paragraph.style.font.size = Pt(font_size)
p = paragraph._element
p.getparent().remove(p)
p._p = p._element = None
doc.add_table(...)
```

**Comment by danielmestrez** [comment]
You have to set it using Document object which contains all the styles. https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html
Like this

document = Document()
table.style = document.styles['Table Grid']

**Comment by PovilasKirna** [comment]
> What you need to do is open a document in your Document() call, not just use the default.
> 
> 1. Create a blank document in Word and save it as 'template.docx'.
> 2. Customize one of the table styles in 'template.docx' to look the way you want.
> 3. Create a new table while still in Word, and apply the customized table style to it
> 4. After that you can delete the table and save the file again.
> 
> After that you start a new document in python-docx using `document = Document('template.docx')` and it will use the file you customized. The table style you customized will be available to apply to tables you make with python-pptx. The table style name is the same as it is in Word, with all spaces removed. For example, 'Light Shading - Accent 1' becomes 'LightShading-Accent1'.

It has been too long, I scoured the internet for an answer. Thank you
![16c](https://user-images.githubusercontent.com/53233943/111824176-8632c400-88ee-11eb-9479-90adffc175b2.jpg)

**Comment by sqmch** [comment]
The above solution works fine if you start with the template file, but I find myself in a situation where I'm injecting tables into an existing .docx file (which doesn't stay static and can change, so I can't do my template creation trick there), meaning that I use a separate Document() to create the table and then inject it to the main file. That means that what ever I do with the styles of the table file, all of that gets lost once the table goes to the main file and I'm left with just the standard Table Grid as my choice. Are there any other options for me here or am I doomed? I also need to do things such as color the background of a cell depending on the content, also something that would get lost after injecting the tables to the main file.

Are there any alternatives or longer solutions I could look into, or is this the pinnacle of what python can do for me when it comes to working with .docx files? Many thanks to whoever can provide some insights.
