### ISSUE TITLE
Split single docx to multiple docx

### ISSUE THREAD

**Issue by jaichandrasreeram** [python-openxml/python-docx#900]
How to split the doc with multiple pages to multiple single page  doc
say if I have a doc of 3 pages in a single doc, can we split and get 3 files with single page 
**from**                                                        
doc -> page1                                               
            page2                                                
            page3                                               
 **to**
 doc1->page1
doc2->page2
 doc3->page3

please help me, I tried as in documentation but it's working for the new doc but not for the existing doc

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag
(https://stackoverflow.com/questions/tagged/python-docx). This issues list is reserved
for suspected bugs and feature requests.
