### ISSUE TITLE
Extracted string missing a word only in WindowsOS's

### ISSUE THREAD

**Issue by sbacky** [python-openxml/python-docx#901]
Similar to issue #497, each time I extract some text from a word document, update some text and insert the text back into the same spot that it was extracted from, the formal names in the text extracted would be missing. 
What's weird is that I seem to only encounter this problem on Windows OS's and not on OS X. When testing this script on Windows 7 and Windows 10 version 1909, every instance of the expected date pattern was processed correctly but the formal names in the same paragraphs are missing. When I tested the same script on macOS Big Sur version 11.0.1, I was not able to recreate the problem and every document was processed perfectly. I could add the names in post but there are hundreds of documents that need to be processed plus the script works fine on OS X. I have thought about just running the script on MacOS but the files are in a work drive that my personal laptop cannot connect to.

```
import docx
import re

doc = docx.Document("/path/to/engLetter.docx")
datePattern = r" (20[0-9]+)"
for index, para in enumerate(doc.paragraphs):
    date = re.search(datePattern, para.text)
    if date != None:
        newDate = " {}".format(int(date.group(1)) + 1)
        line = re.sub(datePattern, newDate, para.text)
        doc.paragraphs[index].text = line

doc.save("/path/to/engLetter.docx")
```

The text I am trying to change is: 
**Changes are in bold to make it easier to see but the actually text is not in bold**

Original Text
    "The Firm’s hourly rates for compliance for **2020** are as follows:  Partner hourly rates are:  **John Doe–$250, Jane Doe–
    $250**.  Our Associate hourly rates range from $150–175.  Our bookkeeping rate is $65 per hour."
Updated Text
    "The Firm’s hourly rates for compliance for **2021** are as follows:  Partner hourly rates are:  **–$250, –$250**.  
    Our Associate hourly rates range from $150–175.  Our bookkeeping rate is $65 per hour."

**Comment by scanny** [comment]
you'll need to post the code otherwise we have nothing to go on.

**Comment by sbacky** [comment]
@scanny No problem! Does this help? I have tried to do the changes line by line in the python interpreter after importing the
processing script I wrote. This is the part of the script that is suppose to update the dates paragraph by paragraph.
[proc-eng-letters.txt](https://github.com/python-openxml/python-docx/files/5619430/proc-eng-letters.txt)

**Comment by scanny** [comment]
You need to post the code in your original post (you can edit it to put that in).

**Comment by sbacky** [comment]
@scanny what about now?

**Comment by scanny** [comment]
Okay, much better. This narrows things down quite a bit. I've slightly simplified your code and formatted it as Python, you can see how by editing that original post to see the source.

A couple things I would recommend.

1. Put (temporary) `print()` calls around assigning `new_date` to make sure you're getting the right number and not a blank space or whatever:

```python
    ...
    print("old_date == %r" % match.group(1))
    new_date = " %s" % (int(match.group(1)) + 1)
    print("new_date == %r" % new_date)
    ...
```

2. Don't get a new reference to the paragraph, use the one you have. Getting it again by index just invites errors and is not necessary.

```python
   ...
   para.text = re.sub(datePattern, new_date, para.text)
   ...
```

3. Add in a couple other print statements to track along the process while you're debugging:

```python
import docx
import re

doc = docx.Document("/path/to/engLetter.docx")
datePattern = r" (20[0-9]+)"
for paragraph in doc.paragraphs:
    match = re.search(datePattern, paragraph.text)
    if not match:
        continue
    print("old_date == %r" % match.group(1))
    new_date = " %s" % (int(match.group(1)) + 1)
    print("new_date == %r" % new_date)
    print("paragraph-text before == %r" % paragraph.text)
    line = re.sub(datePattern, new_date, paragraph.text)
    print("line == %r" % line)
    paragraph.text = line
    print("paragraph-text after == %r" % paragraph.text)

doc.save("/path/to/engLetter.docx")
```

Then see what you discover with the benefit of that feedback from the program execution.

**Comment by sbacky** [comment]
@scanny Okay awesome thanks! I'll update the code I have with your suggestions and let you know what happens.

**Comment by sbacky** [comment]
@scanny this is what I got

old_date:
"2020"

new_date:
"2021"

paragraph-text before:
"The Firm’s hourly rates for compliance for 2020 are as follows: Partner hourly rates are: –$250, –$250.
Our Associate hourly rates range from $150–175. Our bookkeeping rate is $65 per hour."

paragraph-text after:
"The Firm’s hourly rates for compliance for 2021 are as follows: Partner hourly rates are: –$250, –$250.
Our Associate hourly rates range from $150–175. Our bookkeeping rate is $65 per hour."

eng_letter.docx text:
"The Firm’s hourly rates for compliance for 2020 are as follows: Partner hourly rates are: John Doe–$250, Jane Doe–
$250. Our Associate hourly rates range from $150–175. Our bookkeeping rate is $65 per hour."

**Comment by scanny** [comment]
Does your problem seeing it on Windows persist? If so, you need to run this code in the Windows environment to see if you get the same results. You are troubleshooting here; don't rely on me for that. It's a skill you need to build for yourself. Reason about what these results tell you and where to go next.

**Comment by sbacky** [comment]
@scanny Okay thanks for the direction. I'll dig in and see what I can find.
