### ISSUE TITLE
_tc.bottom获取异常

### ISSUE THREAD

**Issue by myloe00** [python-openxml/python-docx#903]
The attribute  _tc.bottom  cannot be obtained  if cells in excel like this  
<table>
    <tr>
        <td rowspan="2">颜色</td>
       <td rowspan="2">颜色</td>
        <td>红色</td>
    </tr>
    <tr>
        <td>黄色</td>
    </tr>
    <tr>
        <td colspan="2">姓氏</td>
        <td>公司</td>
    </tr>
    <tr>
        <td>王</td>
        <td>张</td>
        <td>11</td>
    </tr>
</table>

we  count merged cells   by _tc.bottom and _tc.top in vertical direction. And it rasie Exception in above case.
Is  there  any other methods to count merged cells ?

**Comment by myloe00** [comment]
finally we solved it by this way:
```
def solve_bug(row_size, row, col, origin_table, tmp_row=None, tmp_col=None, turns=10):
    """
    ---------------------------------
    -       - cell1 -       -       -
    -       -       -----------------
    -       -       -       -       -
    ---------------------------------
    -               -       -       -
    ---------------------------------
    -       -       -       -       -
    ---------------------------------
    @param row_size: 
    @param tmp_row:
    @param tmp_col:
    @param turns: just for avoid  endless loop in some case 
    @return:
    """
    tmp_row = tmp_row if tmp_row else row
    tmp_col = tmp_col if tmp_col else col
    turns -= 1
    try:
        tmp_row += 1
        row_size += 1
        origin_table.cell(tmp_row, tmp_col)._tc.bottom
    except Exception as e:
        if turns < 1:
            raise e
        return solve_bug(row_size, row=row, col=col, origin_table=origin_table, tmp_row=tmp_row, tmp_col=tmp_col,
                         turns=turns)
    return row_size
```

but it is not Elegant solution

**Comment by scanny** [comment]
@myloe00 thanks for posting your solution :)
