### ISSUE TITLE
How to get type of list in paragraph?

### ISSUE THREAD

**Issue by Always-prog** [python-openxml/python-docx#904]
I ask a question in StackOverflow: https://stackoverflow.com/questions/65250064/how-to-detect-style-of-list-bullet-or-numbering-in-python-docx

And ask here.
I can get a list item in a paragraph by this:
```python
...
from docx.oxml import numbering
...
for paragraph in document.paragraphs:
    if "<w:numId" in paragraph._p.xml:
        pass#this is list item
```
But how to get the type of list item (bullet or numbering)?

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag
(https://stackoverflow.com/questions/tagged/python-docx). This issues list is reserved
for suspected bugs and feature requests.
