### ISSUE TITLE
How to read text from ToC?

### ISSUE THREAD

**Issue by Always-prog** [python-openxml/python-docx#905]
I have a "for" to elements
```python
for paragraph in self.__OXML_DOCUMENT__.elements:
   ...
```
And need to get a text from the paragraph. How to get a text I know, but in python-ooxml package not have support ToC elements, and I can't read text from ToC style element.
```
class TOC(Element):
    """Represents Table Of Contents element.

    We don't do much with this element at the moment."""    
    pass
```
Maybe need to get text by XML?

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag (https://stackoverflow.com/questions/tagged/python-docx). This issues list is reserved for suspected bugs and feature requests.
