### ISSUE TITLE
Find and replace WordArt text in docx.

### ISSUE THREAD

**Issue by johnkaita1997** [python-openxml/python-docx#907]
Hope this finds you well, is it possible to replace WordArt text, I have attempted many approaches but they all seem to only find and replace normal text in the document? 
How can we achieve this? Currently stuck on this issue

**Comment by scanny** [comment]
This issues list is reserved for suspected bugs and feature requests. Please post support questions on StackOverflow using the `python-docx` tag (https://stackoverflow.com/questions/tagged/python-docx). That way many people can benefit from the time invested in answers.

I believe you'll find that WordArt is a separate "linked" part in the DOCX package, basically a separate file in the zip archive that a .docx file is. So the "text" aspect is not going to be found in one of `document.paragraphs`. I don't know the details of the WordArt file format (XML vocabulary I would hope, but could be binary), and I doubt you'll find much in the way of documentation of it, although you should definitely search thoroughly for whatever you can find out there.

I would start by inspecting the XML at the point in the document where the WordArt appears and work from there.
