### ISSUE TITLE
Combine runs of a paragraph

### ISSUE THREAD

**Issue by Talib07** [python-openxml/python-docx#910]
I am trying to modify a docx file without disturbing the layout and format of a file.
There are few words in the docx file which i am trying to replace with other words. In most of the cases it can be successfully achieved as the words can easily be found in some specific runs, however some words are getting split into multiple runs and it is becoming very difficult challenge to search those individual pieces and then combine those words which has been split into multiple runs.
As they have been split into multiple pieces my search algorithm is not able to find those words and i am failing in replacing those words.

**Comment by scanny** [comment]
The algorithm here should work for your case: https://github.com/python-openxml/python-docx/issues/30#issuecomment-879593691
