### ISSUE TITLE
space_before and space_after seems to be overwritten

### ISSUE THREAD

**Issue by AlmostAlex** [python-openxml/python-docx#923]
Hey,

I am trying to add paragraphs after a certain section in an existing document.
Adding those paragraphs works fine, but formatting them has proven to be a challenge.
Following is my rough code:

    for paragraph in document.paragraphs:
    
          if fin == paragraph.text:
  
              for comment in spez:
  
                  new_p = OxmlElement("w:p")
                  paragraph._p.addnext(new_p)
                  new_para = Paragraph(new_p, paragraph._parent)
  
                  new_para.style = "List Bullet"
                  new_para.paragraph_format.keep_together = True
                  new_para.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.LEFT
                  new_para.paragraph_format.first_line_indent = Cm(-0.4)
                  new_para.paragraph_format.right_indent = Cm(3.99)
                  new_para.paragraph_format.left_indent = Cm(0.78)
                  new_para.paragraph_format.space_before = Pt(6.65)
                  new_para.paragraph_format.space_after = Pt(0)
                  new_para.text = comment
                  new_para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.MULTIPLE
                  new_para.paragraph_format.line_spacing = 1.04

**The problem is, that the `new_para.paragraph_format.space_before = Pt(6.65)` is seemingly overwritten by the checkbock:** 
![image](https://user-images.githubusercontent.com/34305685/107008211-cea97e80-6793-11eb-86a0-15c0cd086c48.png)
(This is checked for the newly created paragraph).

I tried to apply the solution provided [here](https://stackoverflow.com/questions/57008834/python-docx-how-to-set-space-after-paragraphs-of-the-same-style/57012175#57012175) but it seems like there is no `w:pPr/w:contextualSpacing` in the xml of my document to be found.
At least I am getting a "list index out of range" error in for the Line:
`cspacing = new_element.xpath(r'w:pPr/w:contextualSpacing')[0]` which is provided in the solution.

Checking the new_para -> paragraph_format -> _element -> xml content i found the following content inside the <w:pPr> Tag:

`<w:pPr>\n    <w:pStyle w:val="Aufzhlungszeichen"/>\n    <w:keepLines/>\n    <w:spacing w:before="133" w:after="0" w:lineRule="auto"/>\n    <w:ind w:hanging="227" w:right="2262" w:left="442"/>\n    <w:jc w:val="left"/>\n  </w:pPr>\n  `

It seems to be such a simple task. Sorry, if I am missing something simple.
Looking forward to replies!

**Comment by AlmostAlex** [comment]
I think the xml, that I've read is not the full representation of what there is in the file. 
- I've unzipped the docx file and in the styles.xml file I found the `<w:contextualSpacing/>`. 

But the fact remains, that I sadly can't seem to get a hold of it in my code --> cannot get rid of it. Any ideas on how I can deactivate the "Don't add space between paragraphs of the same style"-Option?
Thanks!

**Comment by AlmostAlex** [comment]
What I've done now was:

1. In my created file (which had the checkbox ticked) i found in the /word/document.xml, that "contextualSpacing" does not exist.
2. I then opened that docx-file and unchecked it manually on the whole document.
3. looking at the /word/document.xml of the edited docx I now found: `<w:contextualSpacing w:val="0"/>`
in the file.

So i think rather then removing it, i need to set it as being false. Can someone help me with how this can be accomplished?
--> Adding `<w:contextualSpacing w:val="0"/>` into `<w:Ppr>` for each paragraph, that i've created the following way:

    new_p = OxmlElement("w:p") 
    paragraph._p.addnext(new_p)
    new_para = Paragraph(new_p, paragraph._parent)

**Comment by AlmostAlex** [comment]
I did it!

     new_p = OxmlElement("w:p") 
     paragraph._p.addnext(new_p)
     new_para = Paragraph(new_p, paragraph._parent)

     wp = new_para._p
     wPpr = wp.pPr
     w = OxmlElement('w:contextualSpacing')
     w.set(qn('w:val'), '0')
     wPpr.append(w)
     wp.append(wPpr)

With this, the checkbox is finally unchecked. I think other (new) users would definitely appreciate it if the library would set this itself as soon as space_before or space_after hast been set. I'll close this now, but if someone has some questions regarding my problem, I'll gladly reply!

**Comment by Chexiaogeng** [comment]
> I did it!
> 
> ```
>  new_p = OxmlElement("w:p") 
>  paragraph._p.addnext(new_p)
>  new_para = Paragraph(new_p, paragraph._parent)
> 
>  wp = new_para._p
>  wPpr = wp.pPr
>  w = OxmlElement('w:contextualSpacing')
>  w.set(qn('w:val'), '0')
>  wPpr.append(w)
>  wp.append(wPpr)
> ```
> 
> With this, the checkbox is finally unchecked. I think other (new) users would definitely appreciate it if the library would set this itself as soon as space_before or space_after hast been set. I'll close this now, but if someone has some questions regarding my problem, I'll gladly reply!

hi，I have the same problem,Paragraph func ,what is it ? thank you 。Waiting for your reply
