### ISSUE TITLE
Deprcication warning importin ABCs

### ISSUE THREAD

**Issue by palunel** [python-openxml/python-docx#927]
We are receiving the following deprecation warning:

`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated si
nce Python 3.3, and in 3.10 it will stop working`

Please advise if I can go ahead and create a pull request to resolve.  I cannot seem to find a related issue.

**Comment by kdebrab** [comment]
See https://github.com/python-openxml/python-docx/issues/619

**Comment by palunel** [comment]
Thanks @kdebrab So i found it odd that I kept getting this error.  Apparently what was happening is that It did not install via` wheel` and reverted to an older installation. The source files where clearly not the same as the latest build’s files. Once I installed wheel it pulled the latest build and the error disappeared obviously.

**Comment by StevenMapes** [comment]
Is this likely to be fix prior to Python 3.10's full release in October? #834 suggested is was a merge issue when the last PyPi release was made. I see it's on a the shortlist but it's likely to cause more problems as people start moving to 3.10 or running automated builds from pip for 3.10

**Comment by scanny** [comment]
Fixed in release v0.8.11 on May 15, 2021.
