### ISSUE TITLE
Location of the table

### ISSUE THREAD

**Issue by santhoshck** [python-openxml/python-docx#933]
I am looking for an option to locate a table after a heading at a specific level. 
_table_after (Paragaraph)_ should return a table after specified paragraph before the next paragraph of the same style. If there are no tables, return None.

**Comment by scanny** [comment]
You'll need to whip something like that up yourself.

Search Google on `python-docx iter_block_items` to find an algorithm for iterating over document block items (paragraphs and tables) in document order.

Paragraphs will compare equal if they refer to the same paragraph.

You'll have to distinguish paragraph objects from table objects with `isinstance()` or `type(x)`.

**Comment by santhoshck** [comment]
That works. Appreciate your prompt support!! Thank you.
