### ISSUE TITLE
Some footers are not found in certain documents

### ISSUE THREAD

**Issue by Lukasdeloose** [python-openxml/python-docx#934]
I'm trying to automate the changing of footers using python-docx. However, I came across a weird case, where sometimes the footer is not found. In attachment you can find 2 files: _Example1.docx_ and _Example2.docx_. At first site, they seem perfectly identical. However, when iterating over the footers in _Example1.docx_, the footer containing 'Company123' is not found. 

Here is some example code, where document is an instance of the docx.Document class:

```
  for section in document.sections:
      for paragraph in section.even_page_footer.paragraphs:
          logging.info("even page footer")
          print(paragraph.text)
      for paragraph in section.first_page_footer.paragraphs:
          logging.info("first page footer")
          print(paragraph.text)
      for paragraph in section.footer.paragraphs:
          logging.info("Normal footer")
          print(paragraph.text)
```

For both files, three footer objects are found. However, for the file _Example1.docx_, no paragraph is found. The file _Example2.docx_ output the footer 'company123'

Output Example1:

> INFO:root:even page footer
> INFO:root:
> INFO:root:Normal footer
> INFO:root:
> 

Output Example2:

> INFO:root:even page footer
> INFO:root:
> INFO:root:first page footer
> INFO:root:Company 123
> INFO:root:Normal footer
> INFO:root:
> 

When unzipping the .docx files, the same amount of footers are found. Furthermore, in both files, 'different first page' footer is turned on.

Does someone have any idea what could cause this? 

[Example1.docx](https://github.com/python-openxml/python-docx/files/6206586/ChangeMandate-Nl.-.Copy.docx)
[Example2.docx](https://github.com/python-openxml/python-docx/files/6206588/ChangeMandate-EN.-.Copy.docx)

**Comment by Lukasdeloose** [comment]
Update, there is a difference in the XML of both footers:

_Example1.docx_ (footer **not** found):

```
<w:ftr>
<w:sdt>
    <w:sdtPr>
      <w:id w:val="-527020063"/>
      <w:docPartObj>
        <w:docPartGallery w:val="Page Numbers (Bottom of Page)"/>
        <w:docPartUnique/>
      </w:docPartObj>
    </w:sdtPr>
    <w:sdtEndPr/>
    <w:sdtContent>
      <w:sdt>
        <w:sdtPr>
          <w:id w:val="1232039604"/>
          <w:docPartObj>
            <w:docPartGallery w:val="Page Numbers (Bottom of Page)"/>
            <w:docPartUnique/>
          </w:docPartObj>
        </w:sdtPr>
        <w:sdtEndPr/>
        <w:sdtContent>
          <w:p w14:paraId="14BA2137" w14:textId="74E8C901" w:rsidR="00235E99" w:rsidRPr="00C314C5" w:rsidRDefault="00DA7B95" w:rsidP="00DA7B95">
            <w:pPr>
              <w:pStyle w:val="MemberofDTT"/>
              <w:rPr>
                <w:lang w:val="en-US"/>
              </w:rPr>
            </w:pPr>
            <w:r>
              <w:t>Company 123</w:t>
            </w:r>
          </w:p>
        </w:sdtContent>
      </w:sdt>
    </w:sdtContent>
  </w:sdt>
</w:ftr>
```

_Example2.docx_ (footer found):

```
<w:ftr>
<w:p w14:paraId="14BA2137" w14:textId="34174282" w:rsidR="00235E99" w:rsidRPr="0006403A" w:rsidRDefault="0006403A" w:rsidP="006A3E48">
    <w:pPr>
      <w:pStyle w:val="MemberofDTT"/>
      <w:rPr>
        <w:lang w:val="nl-BE"/>
      </w:rPr>
    </w:pPr>
    <w:r>
      <w:rPr>
        <w:lang w:val="nl-BE"/>
      </w:rPr>
      <w:t>Company 123</w:t>
    </w:r>
  </w:p>
</w:ftr>



```

**Comment by scanny** [comment]
The `<w:sdt>` (structured-document tag) element is wrapping the contents of the footer and `python-docx` doesn't know how to interpret it. I believe these arise in documents that originated with some sort of "fill out the form" process.

To get this to work you'd need to remove the SDT "wrapper" elements and raise the contents of the `w:sdtContent` element to be direct children of the `w:ftr` element.

Interestingly, in your example, there are recursively nested `w:sdt` elements, something like a form-field within a form-field sort of situation. Anyway, you need to cut those parts out (perhaps recursively) if you want `python-docx` to be able to read it.

**Comment by Lukasdeloose** [comment]
Thanks for the reply! Is it possible to use `python-docx` to modify the XML directly, or should this be done in a different script before reading the file into `python-docx`?

**Comment by scanny** [comment]
You can use `python-docx` to get a reference to the XML element of interest and then use `lxml` commands to manipulate that element and its contents. Every XML element in `python-docx` is a `lxml.etree._Element` (or subclass) instance https://lxml.de/api/lxml.etree._Element-class.html.

This saves a lot of trouble because `python-docx` takes care of all the packaging concerns and you can focus on a particular area of XML manipulation.

In this case, for example, you can get the `<w:ftr>` element with:

```
footer = section.footer
ftr = footer._element
```

There are extra (and sometimes overridden) so-called "oxml" methods on elements that `python-docx` knows about. For example, since `python-docx` knows the `w:ftr` element you can do:

```
sdts = ftr.xpath(".//w:sdt")
```

To get all `w:sdt` descendents of the `w:ftr` element. The XPath expression works by itself here because this method is overridden by `oxml` elements. On the `w:sdt` elements this returns, you would have to use the base `lxml` version of `.xpath()` which requires an argument to map namespaces. https://lxml.de/xpathxslt.html

**Comment by Lukasdeloose** [comment]
Thanks for the help! I managed to fix the XML (not using python-docx however) and adapt the footers. 

PS: Love this library, thank you for the great work!

**Comment by scanny** [comment]
Glad you got it working @Lukasdeloose :) Out of curiosity, what approach did you use? Others with a similar problem will want to know and if you can mention it here why it's fresh in your mind that will be a help to others in future.

**Comment by Lukasdeloose** [comment]
Certainly not the most reusable and efficient approach because I had to create a quick fix to get it working, but:

* Use the Python zipfile library to extract the docx file
* Iterate over all footer files
  1. Look for the needed footer file
  2. Use Regex to look for the paragraphs
  3. Replace everything between the `w:sdt` elements with the paragraphs
 
Here is a code example:

`tmp_dir = tempfile.mkdtemp(dir=output_path)

    zip = zipfile.ZipFile(input_filepath)
    zip.extractall(tmp_dir)

    for filename in os.listdir(os.path.join(tmp_dir, 'word')):
        if 'footer' in filename:
            footer_filepath = os.path.join(tmp_dir, 'word', filename)
            with open(footer_filepath, 'rb') as f:
                bytes_read = f.read()
                text = bytes_read.decode()
                if "TextToRecognizeFooter" in text.lower():
                    paragraph = re.search('<w:p(.*)</w:p>', text)
                    if paragraph:
                        new_text = re.sub('<w:sdt>(.*)</w:sdt>', paragraph.group(), text)
                    else:
                        continue
                else:
                    continue
            os.remove(footer_filepath)
            with open(footer_filepath, "wb") as f:
                f.write(new_text.encode())

    # Get a list of all the files in the original docx zipfile
    filenames = zip.namelist()

    # Now, create the new zip file and add all the filex into the archive

    # Replace input file
    with zipfile.ZipFile(output_filepath, "w") as docx:
        for filename in filenames:
            docx.write(os.path.join(tmp_dir, filename), filename)

    # Clean up the temp dir
    shutil.rmtree(tmp_dir)
`
