### ISSUE TITLE
Update default bundled template?

### ISSUE THREAD

**Issue by corobin** [python-openxml/python-docx#936]
I just noticed that the default template that is bundled with python-docx is not consistent with the current default styles being used by word

The template file "...\Python39\site-packages\docx\templates\default.docx"

The most obvious difference is the default fonts being Cambria instead of Calibri which MS has used since, IIRC, the introduction of docx as a format. But the rest of the document formatting is also not matching the defaults if you just opened a new word doc from O365.

I tried creating a new blank document and opening that as the base, but I ran into 2 problems:

- documents created using that have an empty line at the top, presumably because the saved document has an empty link and python-docx is appending to it
- the default "List Bullet" didn't exist so i created an unsorted list in a blank word file and checked the styles in that file, it was called "List Paragraph". however, using python-docx to add a style="List Paragraph" paragraph would created an indented paragraph but not a bulleted list

I also noticed that the current default template is not the latest docx format so i tried to create a docx 2007 file but unfortunately the current word version offers no option of creating it.

I would appreciate any workarounds in the meantime,

But i suggest the longer term solution is just to replace the defaults to match current MS Word defaults.

Thanks.

**Comment by corobin** [comment]
Hey thanks for your detailed comment! It was very helpful to point me in the right direction.

I solved my particular issue so i thought i'd report back what I did and how I got there, although it's probably not the intended solution lol.

So the Mac thing makes sense, I'm not familiar with it but it might have come with a different default template.

I was able to manually edit the XML and remove *everything* inside the body and MS Word was able to open it fine, but of course it being able to open it doesn't mean it's valid markup. I didn't end up doing this anyway.

I couldn't reproduce the Bullet list. I opened up a new word document, clicked the bulleted list from the ribbon menu to make a bulleted list, deleted it (actually, makes no difference if i delete it or not), saved the document. then i used python-docx to check document.styles and it only returns a "List Paragraph" style, no "List Bullet" style.

Since I am using this for a very particular purpose, here's how i ended up working around it: I just left the bulleted list in the template file, and used insert_paragraph_before to add text above that. this killed both birds with one stone: I didn't need to figure out an empty word document, and didn't have to create a new bulleted list with python-docx.

**Comment by scanny** [comment]
@corobin note that the bulleted list icon on the toolbar _does not_ use the `ListBullet` style. Rather it applies bullet formatting directly to the paragraph. If you want the `ListBullet` style in your document you just need to add a paragraph, apply that style to it (from the style gallery) and then delete the paragraph and save.
