### ISSUE TITLE
WD_ALIGN_PARAGRAPH.RIGHT not working 

### ISSUE THREAD

**Issue by poxford3** [python-openxml/python-docx#943]
When using the titular command with an image after using "add_run", the image is not right aligned.  I've bolded the section that is in question. Was attempting to recreate something similar to [this](https://stackoverflow.com/questions/53475659/adding-logo-in-header-of-word-document-using-python-docx) but swapping the picture and text section. Unsure if this can be achieved with the library. 

    from docx import Document
    from docx2pdf import convert
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Inches, RGBColor, Pt
    
    header = doc1.sections[0].header
    htable = header.add_table(1,2,Inches(9))
    htab_cells = htable.rows[0].cells
    ht0=htab_cells[1].add_paragraph()
    kh=ht0.add_run()
    kh.add_picture(holder_logo,width=Inches(.75))
    kh.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    header1=htab_cells[0].add_paragraph().add_run("Notice to Zero Dollar Change\nDATA CENTER")
    header1.font.size = Pt(16)
    header1.font.name = 'AvantGarde LT Book'
    header1.font.color.rgb = RGBColor.from_string("0266BB")

**Comment by LordTejas** [comment]
Please use following funtion to get to know purticular attributes, it helps a lot.

```python
object.__dir__()
```
To use Alignment check my code I made to insert reference id at top page. Focus on alignment part you will get to know the solution!

```python
def insert_reference_id(self, reference_id: str,font_size: int, align: str = "left") -> None:
        """
        Inserts the reference Id in the
        :param reference_id: reference data to be inserted <string>
        :param font_size: set font size of the reference data
        :param align: set alignment of the reference data
        :return: None, Inserts the reference id in the docuement
        """

        ref_data = f"Ref. No.: {reference_id}"
        # print(ref_data)

        first_page = self._sections[0]._document_part.document
        p = first_page.paragraphs[0]
        # print(p)
        text = p.text
        p.insert_paragraph_before(ref_data)
        p = first_page.paragraphs[0]

        # Aligning image
        try:
            align_object = eval(f"WD_PARAGRAPH_ALIGNMENT.{align.upper()}")
        except:
            print("WARNING! Invalid alignment found!!! Using default alignment option.")
            align_object = WD_PARAGRAPH_ALIGNMENT.LEFT

        p.alignment = align_object
        p.style.font.size = Pt(font_size)
```

As we see the paragraph object has alignment object but run object doesn't. Use the above code it will resolve the issue or use .__dir__() to know the right attributes.
