### ISSUE TITLE
Could i get the coordinates of objects such as images, tables...?

### ISSUE THREAD

**Issue by benlee73** [python-openxml/python-docx#944]
Actually, I really want to get a document image with the object's coordinates.
When I add a paragraph, image or table, I need roughly those coordinates.

Is this possible? Is there any way?
I would be very grateful if you could respond.

**Comment by scanny** [comment]
No, not with `python-docx`. Positioning is the responsibility of a rendering engine and `python-docx` only edits the persisted document.
