### ISSUE TITLE
Copying the Document Object 

### ISSUE THREAD

**Issue by tlherysr** [python-openxml/python-docx#946]
Hello, 

I want to copy the `Document` object I've created to my clipboard. I am going to use this to keep the styles, fonts everything and paste it to a word document. Example code:

```python
from docx import Document
from docx.shared import Inches

document = Document()

document.add_heading('Document Title', 0)

p = document.add_paragraph('A plain paragraph having some ')
p.add_run('bold').bold = True
p.add_run(' and some ')
p.add_run('italic.').italic = True

document.add_heading('Heading, level 1', level=1)
document.add_paragraph('Intense quote', style='Intense Quote')

document.add_paragraph(
    'first item in unordered list', style='List Bullet'
)
document.add_paragraph(
    'first item in ordered list', style='List Number'
)

document.add_picture('monty-truth.png', width=Inches(1.25))

records = (
    (3, '101', 'Spam'),
    (7, '422', 'Eggs'),
    (4, '631', 'Spam, spam, eggs, and spam')
)

table = document.add_table(rows=1, cols=3)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = 'Qty'
hdr_cells[1].text = 'Id'
hdr_cells[2].text = 'Desc'
for qty, id, desc in records:
    row_cells = table.add_row().cells
    row_cells[0].text = str(qty)
    row_cells[1].text = id
    row_cells[2].text = desc

document.add_page_break()

document.save('demo.docx')
```

What I want to do is copying everything in the demo.docx file so basically the document object itself to my clipboard and paste it directly to another word file by keeping the styles. I want to copy everything in the file as I am copying it from the word file itself. 

I've checked the other issues but generally, they were about copying the elements in the object to another word file. So this is a different case. 

Is there any way to do that?
Thanks.

**Comment by tlherysr** [comment]
Thanks for the answer but my purpose is copying everything to the clipboard. Because I will use it in a web project. And copied text will be pasted manually to the word documents manually by users. Is there any way to do this??

**Comment by LordTejas** [comment]
You have to copy each run with a for loop, The code below runs good for text and with their styles.

```python
from docx import Document


def get_para_data(output_doc_name, paragraph):
    """
    Write the run to the new file and then set its font, bold, alignment, color etc. data.
    """

    output_para = output_doc_name.add_paragraph()
    for run in paragraph.runs:
        output_run = output_para.add_run(run.text)
        # Run's bold data
        output_run.bold = run.bold
        # Run's italic data
        output_run.italic = run.italic
        # Run's underline data
        output_run.underline = run.underline
        # Run's color data
        output_run.font.color.rgb = run.font.color.rgb
        # Run's font data
        output_run.style.name = run.style.name
    # Paragraph's alignment data
    output_para.paragraph_format.alignment = paragraph.paragraph_format.alignment


input = Document('sample3.docx')

paragraphs = []
for para in input.paragraphs:
    p = para.text
    paragraphs.append(p)

output = Document()
for item in paragraphs:
    output.add_paragraph(item)

output.save('demo.docx')
```

For images and other content, we know that they are just runs, So try to iter through them as runs, Use '.__dir__()' to get to know all the possible contents of the document page including sections and runs. Hope it may help.

**Comment by tlherysr** [comment]
As I said, I can copy the content by iterating the paragraphs but the problem is I need to copy the content to the clipboard, not to another word file. Just think that there is some content on a web page and I have a template to apply. I will take the necessary images and texts and finally, I will put them into a Word file by applying the template. After that, I will be able to paste the content directly into any word file easily.

**Comment by scanny** [comment]
@tlherysr there is no API support for anything like this. If you want to do it from Python, you'll need to write it for yourself. You'll need to understand what the clipboard formats are for Word (possibly RTF), convert what you find in `python-docx` to that format, and then manage to get it into the clipboard.

If it were me I would probably find another way. If I really needed to do it I would probably explore win32com and do it in Windows using the Microsoft Office Word API. Otherwise you have a lot of advanced work to do and I don't think we can be of much help to you in getting it done other than to wish you good luck :)
