### ISSUE TITLE
How to get image from python-docx

### ISSUE THREAD

**Issue by sushipan** [python-openxml/python-docx#953]
Hello
       I want to get image from the docx file. 
 Who can tell me hao to do ,
        Thanks

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-docx` tag.

**Comment by sushipan** [comment]
OK. Thank you , I think I have found the solution to my case
https://github.com/python-openxml/python-docx/commit/6be3b23c29df7e297fd6f602ed11bccefb3bae0a
May be can help some one .

**Comment by abubelinha** [comment]
@sushipan so would you mind to share a sample code of how you implemented it?
Thanks

**Comment by Laxmi530** [comment]
> OK. Thank you , I think I have found the solution to my case [6be3b23](https://github.com/python-openxml/python-docx/commit/6be3b23c29df7e297fd6f602ed11bccefb3bae0a) May be can help some one .

can you please provide the link to the solution.
