### ISSUE TITLE
Footer structure

### ISSUE THREAD

**Issue by eskildbr** [python-openxml/python-docx#957]
Hi,

I am working with a project where I want to automate a process at work where we update the footer of every wordfile we have. The problem is that I can't seem to get the wanted structure of the footer. What I want is 

![image](https://user-images.githubusercontent.com/57830302/121306589-56002d80-c8ff-11eb-84de-ef594ef46b26.png)

But when running my code I get:

![image](https://user-images.githubusercontent.com/57830302/121306958-c0b16900-c8ff-11eb-9559-62b081563b9d.png)

What I think is the problem is that I have created one paragraph and putting that whole paragraph's allignment to the right. I have also tried hardcoding in tabs to push the text to the right, but that ain't very dynamic, since it depends on the lenght of the string etc. Is it maybe possible to add several paragraphs, having the seperate paragraphs on the same line? or adding runs and aligning those to their seperate side of footer.

This is the code I run to add the footer text:

![image](https://user-images.githubusercontent.com/57830302/121323149-de86ca00-c90f-11eb-8817-399231f394c8.png)

The add_page_number function is the one from [Add page number using python-docx](https://stackoverflow.com/questions/56658872/add-page-number-using-python-docx)

Is it maybe possible to add two paragraphs, but seperate them in different colums so that the paragraphs appear in the same line?

**Comment by scanny** [comment]
Have you seen this section in the documentation? https://python-docx.readthedocs.io/en/latest/user/hdrftr.html#adding-zoned-header-content

There are such thing as centered and right-aligned tab stops and these can be used to align content like this easily and reliably. These are built into the default styles for header and footer. You can try it out in a new document in Word to see how they work. Just click in the header or footer and type: "left", tab, "ctr", tab, "right" and you'll see those words magically align left, center, and right respectively. If you show the ruler (View > Ruler) then you can see the center tabstop and right tabstop that are doing the work.

You just need to make sure those `Header` and `Footer` styles are defined in your starting document:
https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html
https://python-docx.readthedocs.io/en/latest/user/styles-using.html

**Comment by eskildbr** [comment]
Hey!

I manage to figure it out. So the case is that I did use '\t\t' before for making the text to the right, because it says in the documentation that this is possible. The thing is that it did not work when I was opening a file and editing the content of the footer or when creating a new file.

I will give you an example:

This is the code I use. I ended up creating different paragraphs and runs to those paragraghs to be able to allign the different paragrahps.

[cid:6ce1a3f6-a169-4dc0-95ec-00554448f454]

When using this code to create a NEW file, the footer becomes slighlty misalligned:

[cid:05c07762-2c39-453b-983f-e126c5af0edf]

And when using the code to edit an existing file, the result is the same:

[cid:22e612f8-7b8a-46fc-8588-4cb6a70ca405]

As you can see the document owner is displayed on the right side, but not all the way to the right. Because in the code I insert a new line after 'access' which should put the document owner on a new line, but puts it all the way to the right. Really annoying, so I tried creating new paragraphs for each line, but that did not work either.

Do you have any suggestions?

________________________________
Fra: Steve Canny ***@***.***>
Sendt: onsdag 9. juni 2021 05:45
Til: python-openxml/python-docx ***@***.***>
Kopi: Eskild Brobak ***@***.***>; Author ***@***.***>
Emne: Re: [python-openxml/python-docx] Footer structure (#957)


Have you seen this section in the documentation? https://python-docx.readthedocs.io/en/latest/user/hdrftr.html#adding-zoned-header-content

There are such thing as centered and right-aligned tab stops and these can be used to align content like this easily and reliably. These are built into the default styles for header and footer. You can try it out in a new document in Word to see how they work. Just click in the header or footer and type: "left", tab, "ctr", tab, "right" and you'll see those words magically align left, center, and right respectively. If you show the ruler (View > Ruler) then you can see the center tabstop and right tabstop that are doing the work.

You just need to make sure those Header and Footer styles are defined in your starting document:
https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html
https://python-docx.readthedocs.io/en/latest/user/styles-using.html

**Comment by scanny** [comment]
@eskildbr please use GitHub to respond, not email. I'm not seeing the code you included.

A couple things to check.

1. Is this text actually in the footer of the document or just a paragraph toward the bottom of the page?
2. What is the paragraph-style for the paragraph in question?

Also note that tabs can be set for a paragraph using `paragraph.paragraph_format.tab_stops` and you can use that to create a single right-aligned tab stop in the right place (close to or at the right margin I expect).

**Comment by eskildbr** [comment]
> @eskildbr please use GitHub to respond, not email. I'm not seeing the code you included.
> 
> A couple things to check.
> 
> 1. Is this text actually in the footer of the document or just a paragraph toward the bottom of the page?
> 2. What is the paragraph-style for the paragraph in question?
> 
> Also note that tabs can be set for a paragraph using `paragraph.paragraph_format.tab_stops` and you can use that to create a single right-aligned tab stop in the right place (close to or at the right margin I expect).

I have no clue why I sent it as a mail, but alright! 

For the bulletpoints you mentioned:
1. Yes, the text is in the footer
2. footer_para.style = document.styles['Footer'] is the style I am using currently. This I have set at the bottom of the function.

I can send new images so that you can see the case: 

This is the code I am running:
![image](https://user-images.githubusercontent.com/57830302/121636444-3ba58b80-ca88-11eb-9cac-e71e0c4179b3.png)

And this is the output:
![image](https://user-images.githubusercontent.com/57830302/121637120-38f76600-ca89-11eb-8470-6fe90a0ca4c7.png)

As you can see the, from the image above, "bunntekst" is norwegian for footer.

**Comment by scanny** [comment]
Try adding separate paragraphs (rather than runs) for each of the second and third lines. You can change the space before and space after of each paragraph to keep them tightly spaced together if needed.

**Comment by eskildbr** [comment]
How do I add new paragraphs in the footer? In the document its just to say "document.add_paragraph("some text")" but how is this done in the footer?

**Comment by scanny** [comment]
`paragraph = footer.add_paragraph(...)`

A footer is a block-item container the same as a document object is. A block item is a paragraph or table.

**Comment by eskildbr** [comment]
Oh okey, wouldn't it be possible to say, in my code, footer_para.add_paragraph()?

**Comment by eskildbr** [comment]
> `paragraph = footer.add_paragraph(...)`
> 
> A footer is a block-item container the same as a document object is. A block item is a paragraph or table.

This method worked fine, after removing whitespace. But now there is a problem that it creates a paragraph everytime the code runs, which makes the footer really big. 

I can't seem to find a function that removes a paragraph, is this not implemented or am I just that blind?

**Comment by scanny** [comment]
In general, a block-item container such as a document, footer, or table cell is going to be born containing a single empty paragraph.

This means you have to access the first paragraph differently than you do subsequent paragraphs. So you would use `footer.paragraphs[0]` to access the first paragraph and `footer.add_paragraph()` to add subsequent ones.

You are probably going to want all of the paragraphs to have the `Footer` style because that's where the tabstops come from. Alternatively of course you can add your own tabstops to a paragraph wherever you want.

If you really want to delete a paragraph and it has no hyperlinks or pictures embedded in it then this will do the trick:

```python
def remove_paragraph(paragraph):
    """Remove `paragraph` from the XML.

    `paragraph` reference is invalid after this function executes.
    """
    p = paragraph._p
    p.getparent().remove(p)
```
