### ISSUE TITLE
How to iterate over each Sentence in Word doc

### ISSUE THREAD

**Issue by ilcaa72** [python-openxml/python-docx#961]
i am currently using VBA on Word and would love to switch to pyDocx.  So i had a question. Within VBA it has a paragraph and sentence object and i can iterate over every sentence like this...  Word VBA know what a paragraph, sentence and word and its easy to iterate and make specific changes.....

How can i accomplish this with pyDocx?  is the Word VBA object model available to me in pyDocx?  thanks for any insight.  

```
'//  loop over each sentence and word in a Word document (using VBA IDE in MS Word)
Dim s As Range
For Each s In ActiveDocument.Sentences
              s.Select
             
             for each wrd in s
                      wrd.Select
     next
next
```

**Comment by scanny** [comment]
pyDocx is a different package. This repository is for `python-docx`.

**Comment by ilcaa72** [comment]
sorry it was my mistake, (i didnt know the other package existed) i have the right forum and package (ive updated my question)
