### ISSUE TITLE
Change Style of Header and Footer

### ISSUE THREAD

**Issue by yuktasarode** [python-openxml/python-docx#963]
I am trying to change the style of the header and footer in my word document using pydocx. However, after going through the documentation of section, header and footer objects I noticed there is no style attribute present. However in normal word I am able to change the style manually. Is there anyway to change the header and footer style using pydocx.

**Comment by scanny** [comment]
PyDocx is a different package from `python-docx`. Please direct questions for that project to its support site.

Support questions for `python-docx` are directed to StackOverflow using the `python-docx` tag.
