### ISSUE TITLE
Custom bullet style not showing up

### ISSUE THREAD

**Issue by Jashbaba30** [python-openxml/python-docx#967]
I have defined a new style named

> Bullet List 2

 in the word UI. I want to apply that style through python-docx. The style appears in the styles.xml file. But when I try to apply the style using python-docx, it does not show up.

Here is snippet of my code: 

Before applying the style : 
     
```
        all_paras = document.paragraphs
        p = all_paras[0]
        print(p.style._element.xml)
```

 The output is :

```
<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cex="http://schemas.microsoft.com/office/word/2018/wordml/cex" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16="http://schemas.microsoft.com/office/word/2018/wordml" xmlns:w16sdtdh="http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" w:type="paragraph" w:styleId="ListParagraph">
  <w:name w:val="List Paragraph"/>
  <w:basedOn w:val="Normal"/>
  <w:link w:val="ListParagraphChar"/>
  <w:uiPriority w:val="34"/>
  <w:qFormat/>
  <w:rsid w:val="00FE3826"/>
  <w:pPr>
    <w:ind w:left="720"/>
    <w:contextualSpacing/>
  </w:pPr>
</w:style>
```

Applying custom style : 

```
p.style = "Bullet List 2"
print(p.style._element.xml)
```

The output is : 

```
<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cex="http://schemas.microsoft.com/office/word/2018/wordml/cex" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16="http://schemas.microsoft.com/office/word/2018/wordml" xmlns:w16sdtdh="http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" w:type="paragraph" w:customStyle="1" w:styleId="BulletList2">
  <w:name w:val="Bullet List 2"/>
  <w:basedOn w:val="ListParagraph"/>
  <w:link w:val="BulletList2Char"/>
  <w:qFormat/>
  <w:rsid w:val="000D79E5"/>
  <w:pPr>
    <w:numPr>
      <w:numId w:val="12"/>
    </w:numPr>
  </w:pPr>
</w:style>
```
The style has changed after applying it through python-docx. But when I check the word file, the style appears unchanged. 

My custom style appears in style library. But does not get implemented

**Comment by scanny** [comment]
How do you expect it to appear, specifically, and how does it actually appear? When you select that paragraph, what style does the Word UI say it has?

**Comment by Jashbaba30** [comment]
Here is the screenshot. I hope this helps. 

![image](https://user-images.githubusercontent.com/50791012/123463883-b1bdfc80-d609-11eb-89f2-b9106bdd9be8.png)

This screenshot is after changing the style as mentioned.

**Comment by scanny** [comment]
From the screenshot, it appears that the style is indeed set to Bullet List 2, which is the expected behavior. The style exists, and it is applied to this paragraph.

If the _definition_ of that paragraph-style is not what you want then that's a different problem.

**Comment by Jashbaba30** [comment]
But it appears that when I apply the same style through Word UI, it gets implemented correctly.

**Comment by Flyomega** [comment]
> But it appears that when I apply the same style through Word UI, it gets implemented correctly.

i have the same problem and im still struggling on this after long days of searching.

**Comment by scanny** [comment]
Make sure you understand these two pages from the documentation:
- https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html
- https://python-docx.readthedocs.io/en/latest/user/styles-using.html

In particular, the style has to be defined _in the document you're working on_, which in this case would mean you need to use a custom "starting" file like:
```python
document = Document("blank-docx-with-my-style-in-it.docx")
```

If you're still having trouble, post exactly what steps you're taking to reproduce the unexpected behavior.
