### ISSUE TITLE
Highlights don't show once i make changes to document by hand.

### ISSUE THREAD

**Issue by rcuttriss** [python-openxml/python-docx#977]
So my objective is simple. Highlight certain text yellow. For instance.

```python
for par in document.paragraphs:
    for run in par.runs:
        print(f"before :: {run.font.highlight_color}")
        run.font.highlight_color = WD_COLOR_INDEX.YELLOW
        print(f"after :: {run.font.highlight_color}")
```
So i ran this code on a fresh example text document (i had not touched it up until this point). I run the code and open the text document in wordpad, everything is highlighted as expected. Then I ctrl+a all the text and manually set the highlight to clear in WordPad, to run it again. I run the code again and go to open it in WordPad but this time nothing changes, the text still has no highlight as I changed by hand a moment ago. I add the two print statements above and notice that the highlight color is in fact getting applied. I change the highlight color from Yellow to Black and the print statements show that the Yellow highlight was changed to Black! But when i go to open the docx file there is no highlight!

For some reason the second that I manually change the highlight in WordPad using the UI I can never see highlight changes the code makes. I upload the text files to google drive and can see the highlight changes my code makes in there, but not on my own machine! Why is this? Does something get cached on my local machine that causes WordPad to not see the document as it is?

**Comment by scanny** [comment]
I expect it has to do with how WordPad interacts with the .docx file, probably both with how it interprets those files as well as what it changes to implement "highlighting".

You can inspect the XML for a run with `print(run._r.xml)`. If you do that before and after `python-docx` sets the highlight color you should be able to pretty easily see exactly what XML changes it is making.

Then you can do the same with WordPad and I expect you'll see it makes different changes to "highlight" a run of text.

**Comment by rcuttriss** [comment]
So I followed your advice and upon examining the XML I found the problem.

So the code highlighted the run as Yellow but I manually with WordPad highlighted it Pink and got the following xml
<w:highlight w:val="yellow"/>
<w:shd w:val="clear" w:fill="FF00FF"/>
it seems that this w:shd value takes precedence over the highlight my code applies. Is there a way with python-docx to change this attribute?

**Comment by rcuttriss** [comment]
> I expect it has to do with how WordPad interacts with the .docx file, probably both with how it interprets those files as well as what it changes to implement "highlighting".
> 
> You can inspect the XML for a run with `print(run._r.xml)`. If you do that before and after `python-docx` sets the highlight color you should be able to pretty easily see exactly what XML changes it is making.
> 
> Then you can do the same with WordPad and I expect you'll see it makes different changes to "highlight" a run of text.

So I followed your advice and upon examining the XML I found the problem.

So the code highlighted the run as Yellow but I manually with WordPad highlighted it Pink and got the following xml
<w:highlight w:val="yellow"/>
<w:shd w:val="clear" w:fill="FF00FF"/>
it seems that this w:shd value takes precedence over the highlight my code applies. Is there a way with python-docx to change this attribute?

**Comment by scanny** [comment]
There's currently no API support for that unfortunately.
