### ISSUE TITLE
feature: Paragraph Indentation

### ISSUE THREAD

**Issue by qwindelzorf** [python-openxml/python-docx#98]
I'd like a way to set the indentation for a paragraph. From an initial run through the code, it looks like there's not currently support for such a thing, but it wouldn't be too hard to add. I'm willing to make the needed changes, but want to make sure I go about it correctly.

Most of the needed functionality already exists as a result of having paragraph justification/alignment. The needed xml is pretty simple:

```xml
<w:pPr>
    <w:ind w:left="XX" w:hanging="XX" w:right="XX"/>
</w:pPr>
```

It would mostly just be a matter of adding the necessary fixtures to the API to let the user pass an integer in for the desired indentation values.

**Comment by scanny** [comment]
Added with release v0.8.0 on Feb 8, 2015.
