### ISSUE TITLE
Search and replace text OK, shapes/images KO

### ISSUE THREAD

**Issue by valerianrossigneux** [python-openxml/python-docx#984]
Hi there, I have successfully been able to search and replace paragraph text and also text in table.

Now in my master document, I want people to be able to add "named" placeholders that I will be able to replace wither with a picture or a table (coming from a panda dataframe). 

I tried:
- Add a square shape, this does not appear as an InlineShapes. KO
- Add a Textbox, this does not appear as an InlineShapes. KO
- Add a Table, i couldn't name the table to access it directly. KO.
- Add an image, this DOES appear in the inlineShapes table but somehow, i am struggling to replace it with my pic/table. I can't addnext(), I can't access the parent, I can't access it's position. Any hint here ?

![Uploading image.png…]()

**Comment by scanny** [comment]
An inline shape is embedded in a run, so you could mark the run with text like `"{{pic-goes-here}}"`, find that run, then delete the text and call `run.add_picture()` to place a picture there.

On the table bit, that would be trickier. I suppose you would have to replace a paragraph with a table. That would have to be done at a lower level (like using `lxml`). Perhaps you could create a table at the end of the document and move it to the desired location.

**Comment by valerianrossigneux** [comment]
Thanks @scanny, managed to do something that works.
