### ISSUE TITLE
Adding a table to the middle of an existing document

### ISSUE THREAD

**Issue by davidasboth** [python-openxml/python-docx#985]
I'm trying to figure out how to take an existing Word document template and dynamically insert one or more tables at a certain point somewhere in the middle. I know `add_table` only adds a table right at the end, same with images. I've managed do this with images by leaving some placeholder text where I want the image, finding the right paragraph with python-docx, clearing the text and adding a new run (which supports `add_picture`). So I guess what I want to know is:

- does a <w:r> element support adding a table inside it? (if yes I could somehow copy my approach by adding a table inside a new run)
- or should I try to identify an existing paragraph and add a table inside it? (currently not an explicit option as far as I can tell)
- is there a better/correct way to do what I'm trying to do?

**Comment by scanny** [comment]
A table is a _block_ element, as is a paragraph. This means it spans the space between the margin and has a top and a bottom which can be occupied by no other element. A document is a series of block items (if we neglect floating items for the moment).

A run is an _inline_ element and can only appear inside a paragraph.

Interestingly, like a document, a table-cell is also a block-item container. That means it can contain paragraphs but can also contain "nested" tables.

Applying these concepts to your problem, a table can only be inserted as a sibling to a paragraph or another table. You can mark the paragraph you want it to appear above or below or replace, but that text marking, say "{{table-goes-here}}" will itself be inside one or more runs. So you can't just replace the "placeholder" text with a table.

A simple approach would be to have a placeholder that is the only text in a paragraph, then insert the table before that paragraph and remove the placeholder paragraph. There are other approaches but I think I'd try this one first and see if it didn't work just fine.

The simplest way I can think of to insert a table at a given location would be something like this:

```python
placeholder_paragraph = find_placeholder("{{table-goes-here}}")  # --- you have to write this function yourself ---
table = document.add_table(...)
tbl = table._tbl
p = placeholder_paragraph._p
p.addprevious(tbl)
p.getparent().remove(p)
```

The `.addprevious()` etc. functions are part of the `lxml.etree._Element` interface which all XML elements in `python-docx` have: https://lxml.de/api/lxml.etree._Element-class.html

**Comment by davidasboth** [comment]
Thanks so much for the quick and thorough reply @scanny! I hadn't appreciated that I can take a table object and assign it to sit in another paragraph. That is definitely the workaround I was after, I'll give it a go and report back if I have any follow up questions. Thanks again!

**Comment by davidasboth** [comment]
Works a treat, thanks again @scanny.
