### ISSUE TITLE
Why is Cambria 11pt used as default font?

### ISSUE THREAD

**Issue by AlkisPis** [python-openxml/python-docx#991]
Re: Quickstart, https://python-docx.readthedocs.io/en/latest/user/quickstart.html

In the created docx file, why is **Cambria 11pt** used as default font, and not the default font in Normal.dotm?

**Comment by scanny** [comment]
`python-docx` always _edits_ files. When you call:

```python
document = Document()
```

it is the same as:

```python
document = Document("docx/templates/default.docx")
```

where `default.docx` is the default starting document shipped in the `python-docx` package.

That default document happens to have Cambria 11pt as the font in its Normal style.

If you want something different, you need to create your own template document and load it like this instead:

```python
document = Document("my-default-template.docx")
```

The default template is there for the common case where folks don't care about the details and just want to produce readable output.
