### ISSUE TITLE
'Style' element deprecated!

### ISSUE THREAD

**Issue by AlkisPis** [python-openxml/python-docx#996]
Re: Quickstart - https://python-docx.readthedocs.io/en/latest/user/quickstart.html contains bad code!

Both `document.add_paragraph('Lorem ipsum dolor sit amet.', style='ListBullet')` and `para.style = 'List Bullet'` produce the following:

**UserWarning: style lookup by style_id is deprecated. Use style name as key instead.
return self._get_style_id_from_style(self[style_name], style_type)**

**Comment by scanny** [comment]
Please include the full stack trace with any error report.

**Comment by vahtras** [comment]
Came across a similar message, context jupyter notebook. 

~~~
table.style = 'TableGrid'
...
[/home/olav/.pyenv/versions/3.12.0/envs/lr/lib/python3.12/site-packages/docx/styles/styles.py:130](http://localhost:8888/home/olav/.pyenv/versions/3.12.0/envs/lr/lib/python3.12/site-packages/docx/styles/styles.py#line=129): UserWarning: style lookup by style_id is deprecated. Use style name as key instead.
  return self._get_style_id_from_style(self[style_name], style_type)
~~~

**Comment by scanny** [comment]
Fixed in next release.
